### ISSUE TITLE
Sorry, i have this error is_readable() expects parameter 1 to be a valid path, object given

### ISSUE THREAD

**Issue by RodrigoDiaz99** [abraham/twitteroauth#1000]
These are my functions where I do the publication process: 

    public function twitter_post(Request $request)
    {
        $twitter = Twitter::query()->first();
        $message = $request->input('message');
        $hasFile = $request->hasFile('attachment'); //true or false

        $file = null; //set the file to

        if ($hasFile) {
            $file = $request->file('attachment');
        }

        return $this->postMessageToTwitter($twitter->twitter_oauth_token, $twitter->twitter_oauth_token_secret, $message, $file);
    }
    public function postMessageToTwitter($oauth_token, $oauth_token_secret, $message, $file=null) //file has default as null

    {
        $push = new TwitterOAuth($this->consumerKey, $this->consumerSecret, $oauth_token, $oauth_token_secret); //$file has default as null
        $push->setTimeouts(10, 15);
        $push->ssl_verifypeer = true;

        if (!empty($file)) { //if a file has been
            $media = $push->upload('\xampp\tmp', ['media' =>$file]);

            // dd($media);
            $parameters = [
                'status' => $message,
                'media_ids' => $media->media_id_string,
            ];
            dd($parameters);
            $push->post('statuses/update', $parameters); //push attachment with message to twitter status
        } else {
            $push->post('statuses/update', array('status' => $message)); //message without attachment
        }
        //$push->post('statuses/update', ['status' => $message]);
         return response()->json($push->getLastbody());

**Comment by abraham** [comment]
$push->upload('\xampp\tmp', ['media' =>$file])

The first parameter needs to be the Twitter API endpoint `'media/upload'`. The `media` value needs to be a string pointing to a file on the local filesystem. It looks like you are using an in-memory file.

**Comment by abraham** [comment]
It looks like `$file` still isn't a string. It must be a path to a media file written to the filesystem.

**Comment by abraham** [comment]
What are you using for a value of `$file`?

**Comment by RodrigoDiaz99** [comment]
to be honest, i dont know, this is all my code

public function twitter_post(Request $request)
{
    $twitter = Twitter::query()->first();
    $message = $request->input('message');
    $hasFile = $request->hasFile('attachment'); //true or false

    $file = null; //set the file to

    if ($hasFile) {
        $file = $request->file('attachment');
    }

    return $this->postMessageToTwitter($twitter->twitter_oauth_token, $twitter->twitter_oauth_token_secret, $message, $file);
}
public function postMessageToTwitter($oauth_token, $oauth_token_secret, $message, $file=null) //file has default as null

{
    $push = new TwitterOAuth($this->consumerKey, $this->consumerSecret, $oauth_token, $oauth_token_secret); //$file has default as null
    $push->setTimeouts(10, 15);
    $push->ssl_verifypeer = true;

    if (!empty($file)) { //if a file has been
        $media = $push->upload('\xampp\tmp', ['media' =>$file]);

        // dd($media);
        $parameters = [
            'status' => $message,
            'media_ids' => $media->media_id_string,
        ];
        dd($parameters);
        $push->post('statuses/update', $parameters); //push attachment with message to twitter status
    } else {
        $push->post('statuses/update', array('status' => $message)); //message without attachment
    }
    //$push->post('statuses/update', ['status' => $message]);
     return response()->json($push->getLastbody());

**Comment by RodrigoDiaz99** [comment]
here I declare $ file



public function twitter_post(Request $request)
{
    $twitter = Twitter::query()->first();
    $message = $request->input('message');
    $hasFile = $request->hasFile('attachment'); //true or false

    $file = null; //set the file to

    if ($hasFile) {
        $file = $request->file('attachment');
    }

    return $this->postMessageToTwitter($twitter->twitter_oauth_token, $twitter->twitter_oauth_token_secret, $message, $file);
}

**Comment by RodrigoDiaz99** [comment]
here he passed the parameter

     public function postMessageToTwitter($oauth_token, $oauth_token_secret, $message, $file=null) //file has default as null

     {
    $push = new TwitterOAuth($this->consumerKey, $this->consumerSecret, $oauth_token, $oauth_token_secret); //$file has 
    default as null
    $push->setTimeouts(10, 15);
    $push->ssl_verifypeer = true;

    if (!empty($file)) { //if a file has been
        $media = $push->upload('\xampp\tmp', ['media' =>$file]);

        // dd($media);
        $parameters = [
            'status' => $message,
            'media_ids' => $media->media_id_string,
        ];
        dd($parameters);
        $push->post('statuses/update', $parameters); //push attachment with message to twitter status
    } else {
        $push->post('statuses/update', array('status' => $message)); //message without attachment
    }
    //$push->post('statuses/update', ['status' => $message]);
     return response()->json($push->getLastbody());

**Comment by abraham** [comment]
`$file = $request->file('attachment');` and the error message you are getting suggests you have an in memory handle to the media file. As I said in https://github.com/abraham/twitteroauth/issues/1000#issuecomment-943976132 you probably have to write the file to the filesystem sot that the value of `$file` is a path to the file location like `"/tmp/file.png"`

**Comment by RodrigoDiaz99** [comment]
so, should change  'media/upload' for what?
in my code i change this '\xampp\tmp' for this  'media/upload'and still have the same error.

**Comment by abraham** [comment]
`media/upload` is the Twitter API path and must remain. It is unrelated to where the file is located on your filesystem.

You probably have to take the data in `$request->file('attachment')` and use something like [How to get a temporary file path?](https://stackoverflow.com/questions/12097631/how-to-get-a-temporary-file-path) to write it to a tmp directory.
