### ISSUE TITLE
Can't find media in tweet

### ISSUE THREAD

**Issue by Reuns** [abraham/twitteroauth#1001]
Hello everyone !

I can't get the media in this tweet : https://twitter.com/wanegen47/status/1416333836737204224

doing `print_r ($tweet->entities);` return no media at all.

> object(stdClass)#1302 (4) {
>   ["hashtags"]=>
>   array(2) {
>     [0]=>
>     object(stdClass)#1300 (2) {
>       ["text"]=>
>       string(17) "PlayStationTrophy"
>       ["indices"]=>
>       array(2) {
>         [0]=>
>         int(77)
>         [1]=>
>         int(95)
>       }
>     }
>     [1]=>
>     object(stdClass)#1301 (2) {
>       ["text"]=>
>       string(8) "PS5Share"
>       ["indices"]=>
>       array(2) {
>         [0]=>
>         int(96)
>         [1]=>
>         int(105)
>       }
>     }
>   }
>   ["symbols"]=>
>   array(0) {
>   }
>   ["user_mentions"]=>
>   array(1) {
>     [0]=>
>     object(stdClass)#1303 (5) {
>       ["screen_name"]=>
>       string(11) "HighScorefr"
>       ["name"]=>
>       string(13) "High-score.fr"
>       ["id"]=>
>       int(1162273106766860289)
>       ["id_str"]=>
>       string(19) "1162273106766860289"
>       ["indices"]=>
>       array(2) {
>         [0]=>
>         int(64)
>         [1]=>
>         int(76)
>       }
>     }
>   }
>   ["urls"]=>
>   array(1) {
>     [0]=>
>     object(stdClass)#1304 (4) {
>       ["url"]=>
>       string(23) "https://t.co/qHXDRz2xhN"
>       ["expanded_url"]=>
>       string(52) "https://twitter.com/i/web/status/1416333836737204224"
>       ["display_url"]=>
>       string(29) "twitter.com/i/web/status/1…"
>       ["indices"]=>
>       array(2) {
>         [0]=>
>         int(108)
>         [1]=>
>         int(131)
>       }
>     }
>   }
> }

However it works perfectly on the others tweets I've checked.
Is there something I'm doing wrong or is it some kind of a bug ?

Thanks for your help.

**Comment by Reuns** [comment]
Thanks for your quick answer !
I don't mean to bother you, but how should I set these parameters ?

Right now my script is like :

`$statuses = $connection->get('statuses/mentions_timeline', ['count' => 200, 'exclude_replies' => false]);`
`foreach ($statuses as $tweet) {`
`...`
`}`


> 
> 
> Make sure you include parameters `include_entities=true&tweet_mode=extended`. It shows up then.

**Comment by abraham** [comment]
That looks correct. What do you mean you script stopped working?
