### ISSUE TITLE
PUT function has hardcoded json=false

### ISSUE THREAD

**Issue by salmanalee** [abraham/twitteroauth#1002]
Twitter's new stream publish API uses PUT method and it expects JSON parameters. Looks like there is no way to send PUT with JSON using the existing method. 

API

PUT /users/:user_id/broadcasts/:broadcast_id/state(PUBLISH)

Expects: title, state, should_not_tweet and locale as JSON body params

Current method converts postFields in to query params. 

Thank you for this package and your hard work.

**Comment by abraham** [comment]
Can you link to the API you are talking about? I'm not finding it. This library has not been tested with any streaming API so I don't know how it'll behave until https://github.com/abraham/twitteroauth/issues/295 is implemented.

**Comment by salmanalee** [comment]
Is it possible to not send postFields as query params also? Twitter API is erroring out
https://github.com/abraham/twitteroauth/blob/main/src/TwitterOAuth.php#L725
