### ISSUE TITLE
Unable to tweet

### ISSUE THREAD

**Issue by Dynzels** [abraham/twitteroauth#1004]
Hello,

I just installed the new version of your package and since then I can't tweet.

GET (search for a user) requests work fine, but POST requests do not. The return sent by the request is "null".

Do you have any idea where the problem may be coming from? Thank you

My code :

`// On require l'autoload (pour utiliser l'API de Twitter)
require('vendor/autoload.php');
use Abraham\TwitterOAuth\TwitterOAuth;

define('CONSUMER_KEY', 'FNBy0IO4Cr9FN7OC5OSZ0XGt1');
define('CONSUMER_SECREY', 'P8UYOE7kYikfExOfTAaldd06xNxDLrzzNyeIitnv7bJRtLrKbX');
define('ACCESS_TOKEN', '1444237558783827972-8WM870sr1mMuywOohSru3sFvp8nz8J');
define('ACCESS_SECRET', 'VYVad5yeYNGzcQe20xt7zyzl65Ld09hyYMHXKdKdziIjU');

// On se connecte à l'API de Twitter
$twitter = new TwitterOAuth(CONSUMER_KEY,CONSUMER_SECREY,ACCESS_TOKEN,ACCESS_SECRET);

$twitter->setApiVersion('2');
$twitter->setTimeouts(10, 120);

$parameters = [
    'status' => 'Meow Meow Meow'
];
$result = $twitter->post('status/update', $parameters); 

if ($twitter->getLastHttpCode() == 200) {
		echo 'OK';
} else
{
	echo 'KO';
}`

**Comment by kesavanm** [comment]
What was the fix? Facing the same issue
