### ISSUE TITLE
Fatal error on incorrect callback url

### ISSUE THREAD

**Issue by meta4creations** [abraham/twitteroauth#1006]
Can we get errors like this returned to display to users? I know how to resolve the error, but general user's of my plugin may accidentally not have the correct callback URL and would then get a fatal error instead of being notified about what the issue is.

`PHP Fatal error:  Uncaught Abraham\TwitterOAuth\TwitterOAuthException: {"errors":[{"code":415,"message":"Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings"}]}`

**Comment by abraham** [comment]
You can get that with a try/catch

```php
try {
    $response = $connection->oauth('oauth/request_token', array('oauth_callback' => 'https://example.com'));
} catch (Exception $e) {
    var_dump(json_decode($e->getMessage())->errors[0]->message);
}
```

**Comment by meta4creations** [comment]
Works great, thanks!
