### ISSUE TITLE
That method has been replaced with the `oauth` method. Please read through the sign in flow for the current method names. Https://twitteroauth.com

### ISSUE THREAD

**Issue by AnitaGiani** [abraham/twitteroauth#1011]
That method has been replaced with the `oauth` method. Please read through the sign in flow for the current method names. Https://twitteroauth.com

_Originally posted by @abraham in https://github.com/abraham/twitteroauth/issues/321#issuecomment-78071951_

Can you please explain how to solve the issue. I am getting the same issue and i am a complete beginner.

**Comment by AnitaGiani** [comment]
![Capture](https://user-images.githubusercontent.com/64680167/142357357-8bd00927-756c-4023-ba91-9d6dd7c7010a.PNG)

**Comment by AnitaGiani** [comment]
Fatal error: Uncaught Error: Class "Composer\CaBundle\CaBundle" not found in C:\xampp\htdocs\8-apis\twitteroauth\src\TwitterOAuth.php:609 Stack trace: #0 C:\xampp\htdocs\8-apis\twitteroauth\src\TwitterOAuth.php(657): Abraham\TwitterOAuth\TwitterOAuth->curlOptions() #1 C:\xampp\htdocs\8-apis\twitteroauth\src\TwitterOAuth.php(594): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array, false) #2 C:\xampp\htdocs\8-apis\twitteroauth\src\TwitterOAuth.php(527): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array, false) #3 C:\xampp\htdocs\8-apis\twitteroauth\src\TwitterOAuth.php(479): Abraham\TwitterOAuth\TwitterOAuth->makeRequests('https://api.twi...', 'GET', Array, false) #4 C:\xampp\htdocs\8-apis\twitteroauth\src\TwitterOAuth.php(231): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'account/verify_...', Array, false) #5 C:\xampp\htdocs\8-apis\twitterapi.php(11): Abraham\TwitterOAuth\TwitterOAuth->get('account/verify_...') #6 {main} thrown in C:\xampp\htdocs\8-apis\twitteroauth\src\TwitterOAuth.php on line 609

**Comment by abraham** [comment]
Please use composer to install. https://getcomposer.org/doc/00-intro.md
