### ISSUE TITLE
V2 API use not clear

### ISSUE THREAD

**Issue by HashandSalt** [abraham/twitteroauth#1018]
Sorry if this is a daft question, but it isnt clear from the docs how to do a V2 api request like

`GET /2/users/:id/tweets`

whilst `$twitter->get('users', ['ids' => $myid]);` works fine, i cant figure out were to put `/tweets` or anything that comes after. Can somebody help here please and would like to suggest a few more V2 examples in the documentation.

**Comment by JuanRangel** [comment]
You can use this 

```
public $service;
public function __construct()
{
    $this->service = new TwitterOAuth(
         config('twitter.consumer_key'),
         config('twitter.consumer_secret')
    );
}
public function getTweet($id)
{
   $this->service->get('users/'.$id.'/tweets', [
           'tweet.fields' => 'non_public_metrics,public_metrics',
           'max_results' => $count
     ]);
}
```

**Comment by roboscripts** [comment]
Yes please anyone can put a PHP example on how to do a text tweet and a tweet with an image too with V2.

My code works fine with V1 but not with V2 anymore

Thanks

**Comment by JuanRangel** [comment]
You can set config settings like so 

```
$this->service = new TwitterOAuth(
            config('twitter.consumer_key'),
            config('twitter.consumer_secret')
        );

        $this->service->setApiVersion('2');
        $this->service->setDecodeJsonAsArray(true);
```

**Comment by abraham** [comment]
v2 doesn't support media yet. https://trello.com/c/Zr9zDrJx/109-replacement-of-media-uploads-functionality

**Comment by abraham** [comment]
Here is an example of tweeting with v2 API. https://github.com/abraham/twitteroauth/issues/1019#issuecomment-997224994
