### ISSUE TITLE
API v1, not available to new Twitter dev accounts

### ISSUE THREAD

**Issue by roboscripts** [abraham/twitteroauth#1019]
Hi

Seems that now all new Twitter dev registrations are forced to use the Twitter V2 API

I have updated my library with your API v2 fix and it works fine to login and let's say get a user detail but it cant tweet text or text with image anymore.

Is there a quick fix to be able to tweet text and text with images?

This is the code I use with V1.1

// Post message with no image
$status = $connection->post('statuses/update', array('status' => $tweet_message));

// Post message with image
$status = $connection->upload('statuses/update_with_media', array('status' => $tweet_message, 'media[]' => file_get_contents($image)));

I would appreciate a PHP example code...

I have tried replacing the endpoint with 'tweets' for the text one with now success

Thanks guys

**Comment by abraham** [comment]
As far as I'm aware v2 doesn't support media yet. https://trello.com/c/Zr9zDrJx/109-replacement-of-media-uploads-functionality

How are you currently trying to post tweets with v2?

**Comment by hamzaali4231** [comment]
Does v2 not allow for texts tweets to twitter. I am able to authorize to twitter, but no tweets seem to be actually sending.

This is what my code looks like at the moment:

`public function postTwitterMessage($oauth_token, $oauth_token_secret)
    {
        $push = new TwitterOAuth(env('TWITTER_CONSUMER_KEY'), env('TWITTER_CONSUMER_SECRET'), $oauth_token, $oauth_token_secret);
        $push->setTimeouts(10,15);
        $push->post('statuses/update', ['status' => 'Just a random string']);`

**Comment by abraham** [comment]
Posting tweets with v2 is working for me. Your isn't using the v2 api though.

```php
$connection = new TwitterOAuth(
    // ...
);
$connection->setApiVersion('2');
$status_payload = [
    'text' => 'Hello World ' . time(),
];
$response = $connection->post('tweets', $status_payload, true);
```

**Comment by roboscripts** [comment]
Hi Thanks that worked for text.

For tweets with images, seems that codebird found a way:

Send a tweet with image media attachments
The Twitter API v2 doesn't yet support media uploads, so for the time being we are using the v1.1 media upload endpoint to upload an image and attach it to a tweet. We will match that functionality as it comes online in Twitter API v2

// first, use the tweeets()->upload method to upload your image file
$image = $twitter->tweets()->upload('./img/chris_de_burgh.png');

//pass the returned media id to a media object as an array
$media = (new \Coderjerk\BirdElephant\Compose\Media)->mediaIds([$image->media_id_string]);

//compose the tweet and pass alog the media object
$tweet = (new \Coderjerk\BirdElephant\Compose\Tweet)->text('Thanks @coderjerk')
    ->media($media);

Anyway we can achieve that with twitterauth until they release an endpoint for media?

Thanks again
