### ISSUE TITLE
Tweeting with images

### ISSUE THREAD

**Issue by roboscripts** [abraham/twitteroauth#1024]
Hi Thanks for the other solution for tweets with text Working now...

For tweets with images, seems that another library found a way:

Send a tweet with image media attachments
The Twitter API v2 doesn't yet support media uploads, so for the time being we are using the v1.1 media upload endpoint to upload an image and attach it to a tweet. We will match that functionality as it comes online in Twitter API v2

// first, use the tweeets()->upload method to upload your image file
$image = $twitter->tweets()->upload('./img/chris_de_burgh.png');

//pass the returned media id to a media object as an array
$media = (new \Coderjerk\BirdElephant\Compose\Media)->mediaIds([$image->media_id_string]);

//compose the tweet and pass alog the media object
$tweet = (new \Coderjerk\BirdElephant\Compose\Tweet)->text('Thanks @coderjerk')
->media($media);

Anyway we can achieve that with twitterauth until they release an endpoint for media?

Thanks again

**Comment by abraham** [comment]
It sounds like you can upload media with v1.1 api as documented on https://twitteroauth.com/ and include the media ids with the text tweet. I haven't tried it. Is it not working for you?
