### ISSUE TITLE
Twitter 2.0 API compatibility issue ?

### ISSUE THREAD

**Issue by MetinSAYGIN** [abraham/twitteroauth#1028]
Hello,

i think there is a problem with the format of 2.0 api command
for example : this work good 
$c->setApiVersion('2');
$content = $c -> get("tweets", ['ids' => 1247616214769086465]);

but this does not
$c->setApiVersion('2');
$content = $c->get("tweets/:id", ['id' => 1247616214769086465]);

it return me that 

object(stdClass)#15 (4) { ["errors"]=> array(2) { [0]=> object(stdClass)#12 (2) { ["parameters"]=> object(stdClass)#9 (1) { ["id"]=> array(2) { [0]=> string(3) ":id" [1]=> string(19) "1247616214769086465" } } ["message"]=> string(49) "The `id` query parameter value [:id] is not valid" } [1]=> object(stdClass)#14 (2) { ["parameters"]=> object(stdClass)#13 (1) { ["id"]=> array(2) { [0]=> string(3) ":id" [1]=> string(19) "1247616214769086465" } } ["message"]=> string(62) "Duplicate parameters are not allowed: the `id` query parameter" } } ["title"]=> string(15) "Invalid Request" ["detail"]=> string(51) "One or more parameters to your request was invalid." ["type"]=> string(50) "https://api.twitter.com/2/problems/invalid-request" }

https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets-id

Maybe i miss something ..

**Comment by abraham** [comment]
The `:id` is a placeholder for where the tweet id goes. `tweets/1067094924124872705`

**Comment by MetinSAYGIN** [comment]
Thanks for the fast help.
My bad.
