### ISSUE TITLE
setApiVersion() is not a function

### ISSUE THREAD

**Issue by RelishedChicken** [abraham/twitteroauth#1029]
I've got a simple PHP app that is trying to search tweets in user context, however I'm trying to use the v2 API. https://twitteroauth.com/ says to use setApiVersion() to set it to v2, but each time I call this, I get an error that the function doesn't exist.

```
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token['oauth_token'], $access_token['oauth_token_secret']);
$connection->setApiVersion('2'); <--- This function is not found
$response = $connection->get("tweets/search/recent", ["query" => $q, "max_results" => 100]);
```

**Comment by RelishedChicken** [comment]
also additionally to this, is it possible via your library to even search tweets in the user context (once authed)? I need this opposed to having the developer account context, which wouldn't work.

**Comment by abraham** [comment]
If setApiVersion isn't defined you need to update the version of the library.

Yes you can search tweets. https://github.com/abraham/twitteroauth/blob/main/tests/TwitterOAuthStatusesTest.php#L44

**Comment by RelishedChicken** [comment]
Hi, I believe it's already on the latest version. Looking at my SFTP, the Config.php folder is there with the method, and TwitterOAuth() does extend it. Ah yes I've seen that, but just to double check that tweet search use the authorised user when available? As in the above code, I set the $access_token which is for the authed user.

**Comment by RelishedChicken** [comment]
I think I've worked this out now, 1&1 hosting defaults to php 7.1 (wow) and that means composer won't be able to install the latest version of this! Seems to work fine now and the search is being done on user context too! :)
