### ISSUE TITLE
getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by antsstyle** [abraham/twitteroauth#1032]
Hi all!

I'm getting frequent moments where TwitterOAuth throws an exception upon attempting to post to an endpoint (intermittently - I'm making it do a very high volume of requests in several processes simultaneously).

While I can obviously catch the thrown exception, the main question here is that it doesn't seem to actually initiate any retries (or if it does, there is no function I know of for testing if it is making any retries before failing, and it doesn't log anything in this regard). I have set the TwitterOAuth instance to retry 3 times at 1 second intervals. If it throws exceptions upon connection failure then I can modify my code to deal with that, but I'm unsure whether this is simply some other issue I don't know about.

Stack trace is below. I'm not sure what other information would be useful here, but I certainly can provide any info I have.

```
[20-Jan-2022 22:05:08 America/Chicago] PHP Fatal error:  Uncaught Abraham\TwitterOAuth\TwitterOAuthException: getaddrinfo() thread failed to start in /home1/antssyle/public_html/nftcryptoblocker/vendor/abraham/twitteroauth/src/TwitterOAuth.php:704
Stack trace:
#0 /home1/antssyle/public_html/nftcryptoblocker/vendor/abraham/twitteroauth/src/TwitterOAuth.php(594): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array, false)
#1 /home1/antssyle/public_html/nftcryptoblocker/vendor/abraham/twitteroauth/src/TwitterOAuth.php(527): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array, false)
#2 /home1/antssyle/public_html/nftcryptoblocker/vendor/abraham/twitteroauth/src/TwitterOAuth.php(479): Abraham\TwitterOAuth\TwitterOAuth->makeRequests('https://api.twi...', 'POST', Array, false)
#3 /home1/antssyle/public_html/nftcryptoblocker/vendor/abraham/twitteroauth/src/TwitterOAuth.php(248): Abraham\TwitterOAuth\TwitterOAuth->http('POST', 'https://api.twi...', 'blocks/create', Array, false)
#4 /home1/ants in /home1/antssyle/public_html/nftcryptoblocker/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 704
```

**Comment by mfn** [comment]
I don't think this related to the library, this comes from the system, specifically curl.

I suggest to check out https://github.com/curl/curl/issues/6495#issuecomment-779398725 for pointers.

**Comment by antsstyle** [comment]
You are quite right. While I was doing more investigation, I discovered that I often get fork / resource temporarily unavailable errors at the same time as this one, so it's most likely my shared webhostings' process limit that is the culprit here.

Thank you for pointing me in the right direction!
