### ISSUE TITLE
Is OAuth 2.0 with PKCE flow supported?

### ISSUE THREAD

**Issue by antsstyle** [abraham/twitteroauth#1041]
Hi everyone,

Just wondering in case I've missed it - is Twitter's OAuth 2.0 with PKCE flow supported in TwitterOAuth? I can't find mention of it anywhere in the docs, and the methods I can find only seem to support OAuth 1.0a.

Still figuring out exactly how the PKCE flow works with Twitter, sorry if I missed something obvious somewhere!

**Comment by abraham** [comment]
I believe this will require some work but I haven't had time to look into it yet.

**Comment by antsstyle** [comment]
Alright. I'm looking into it during the month - if I figure it out, if I have time I'll make a pull request, or if not I'll post my findings here.

**Comment by antsstyle** [comment]
Writing an update here, have managed to get OAuth2 with PKCE working and making requests successfully. The main pitfalls were getting the authorize URL correct and putting correct scopes on the access tokens.

The example code here for a Confidential Client app that can keep its client secret secure. I'll try and write a proper explanation if I get time.
[twitteroauth - oauth2 test.zip](https://github.com/abraham/twitteroauth/files/8208853/twitteroauth.-.oauth2.test.zip)

**Comment by ghnp5** [comment]
Hi @abraham . Is this supposed now by any chance? Doesn't seem like, but I'd like to confirm with you 😊
Thank you!

**Comment by abraham** [comment]
TwitterOAuth is in maintenance mode and major improvements are no longer planned. https://github.com/abraham/twitteroauth/issues/1188
