### ISSUE TITLE
setApiVersion does not exist

### ISSUE THREAD

**Issue by sukerman** [abraham/twitteroauth#1042]
// method doesn't exist??? 
$connection->setApiVersion('2');

When I try this it says method does not exist?

**Comment by abraham** [comment]
Update TwitterOAuth.

**Comment by abraham** [comment]
Using `setApiVersion` will require at least PHP 7.3.

**Comment by sukerman** [comment]
Yes I understand thanks, unfortunately, its a massive legacy 5.6 app.
