### ISSUE TITLE
Modernize PHP

### ISSUE THREAD

**Issue by abraham** [abraham/twitteroauth#1055]
Look for PHP language improvements that could cleanup the codebase.

https://dnlytras.com/blog/modern-php/

**Comment by mfn** [comment]
https://github.com/rectorphp/rector/ is quite a well known tool to perform a LOT of those migrations. It even can be used as a "one time thing" so it's not necessary to have as a dependency afterwards.

(OTOH, sometimes an afternoon with PhpStorm, which has built-in refactor mods for many of those, can give equally useful results)
