### ISSUE TITLE
oauth/access_token example fails with "Request token missing"

### ISSUE THREAD

**Issue by mgiuffrida** [abraham/twitteroauth#1071]
**What are you attempting to do**
I'm running the example line in the [docs](https://twitteroauth.com/):

```php
$access_token = $connection->oauth("oauth/access_token", ["oauth_verifier" => "$oauth_verifier"]);
```

This fails with:

```
PHP Fatal error:  Uncaught Abraham\\TwitterOAuth\\TwitterOAuthException: Request token missing in <path>/vendor/abraham/twitteroauth/src/TwitterOAuth.php:183
```

**Solution**

The call needs an `oauth_token` parameter. This should be added to the docs.

**Code example**

```php
$connection = new TwitterOAuth(
  $_ENV['TWITTER_API_KEY'],
  $_ENV['TWITTER_SECRET'],
  $_ENV['TWITTER_ACCESS_TOKEN'],
  $_ENV['TWITTER_ACCESS_TOKEN_SECRET']);
$connection->setApiVersion('2');

$oauth_verifier = $_GET['oauth_verifier'];  // from OAuth2 request_token flow; var_dump shows this a string of len 32

$access_token = $connection->oauth("oauth/access_token", ["oauth_verifier" => "$oauth_verifier"]);  // fails
```

**Versions:**

- TwitterOAuth: (not sure how to find this, but content-hash is b06c7d82390a42fcd56159e9637ed3dd)
- PHP: v8.1.4

**Comment by mgiuffrida** [comment]
When I include the `oauth_token` as a parameter, I receive a different API response: "This feature is temporarily unavailable."

I'm probably calling the API incorrectly somehow, but at the very least, the example in the README should be fixed.

**Comment by mgiuffrida** [comment]
Updated the bug report to indicate the solution I found. The call was simply missing the `oauth_token` parameter.

**Comment by bradstw** [comment]
Thank you for this. Ran into the exact same problem. Adding in the oauth_token parameter solved my problem. 
Working code is now ```$access_token = $connection->oauth("oauth/access_token", ["oauth_token" => $oauth_token, "oauth_verifier" => $oauth_verify]);```

**Comment by abraham** [comment]
twitteroauth.com is currently working without passing `oauth_token` to `oauth/access_token`. You can see it in the source code: https://github.com/abraham/twitteroauth-com/blob/main/src/callback.php#L27

Do your apps have access to API v1.1? Or just v2?

**Comment by abraham** [comment]
When you construct the `TwitterOAuth` instance you are passing the same oauth_token value?
