### ISSUE TITLE
Static function return version of class TwitterOAuth

### ISSUE THREAD

**Issue by diderich** [abraham/twitteroauth#1089]
**Is your feature request related to a problem? Please describe.**
To be able to generate a report including what version of a package is installed, it would be great of **TwitterOAuth** could include a static function, e.g., `TwitterOAuth::getVersion()` that would return the version number of the package (not the Twitter API). This would help identify potential issues, for example, users having an outdated of the package version installed.

**Describe the solution you'd like**
Provide a static function `TwitterOAuth::getVersion()` that returns as a string, the version of the **TwitterOAuth** package.

**Describe alternatives you've considered**
An tedious and error prone alternative, would be to manually take the package's version number from the README.md file and hard-code it into the application showing the version installed.

**Additional context**
The figure below shows how I would use the function's output:
![apis](https://user-images.githubusercontent.com/10230144/172177302-5272a9b2-c8cb-4a6f-af83-44d6435a8743.jpg)

**Comment by abraham** [comment]
Using the composer method would be ideal to avoid having to constantly update the code for each new version.
