### ISSUE TITLE
Requests with bodies must have content-type of application/json.

### ISSUE THREAD

**Issue by RoHodson** [abraham/twitteroauth#1090]
I get this error when trying to make a tweet:  
Requests with bodies must have content-type of application/json.

When I use "statuses/update" instead of "tweets" as the POST URL (and "status" instead of "text" as the key), I get null and no tweet posted
`

	$connection 		= new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $ACCESSTOKEN, $ACCESSTOKENSECRET);
	$connection->setApiVersion('2');
	
	var_dump(PostTweet($connection, "THIS IS A TEST"), "test");
	
	function PostTweet(&$connection, $status, $quote_tweet_id = false, $in_reply_to_tweet_id = false){//returns true on success, or an error message on failure
		if(!$status){
			return 		"Status was empty";
		}
		$status			= ["text" => $status];
		if($quote_tweet_id){
			$status["quote_tweet_id"] = $quote_tweet_id;
		}
		if($in_reply_to_tweet_id){
			$status["in_reply_to_tweet_id"] = $in_reply_to_tweet_id;
		}
		$result 		= $connection->post("tweets", $status);
		if ($connection->getLastHttpCode() == 200) {
			return 		true;
		}
		return 			$result->errors[0]->message;
	}
	
`

**Comment by RoHodson** [comment]
Changing TwitterOAuth.php to have:

`        $options[CURLOPT_HTTPHEADER] = [
            'Accept: application/json',
			'Content-Type: application/json',
            $authorization,
            'Expect:',
        ];`

also results in null..

**Comment by RoHodson** [comment]
That solved the error message, but I'm still getting NULL

`	$connection 		= new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $ACCESSTOKEN, $ACCESSTOKENSECRET);
$status = "TESTING";
var_dump($connection->post("tweets", ["status" => $status], true));
`

**Comment by abraham** [comment]
Here is an example with v1 and v2 of the Twitter API. They both worked in my testing just now.

```php
require 'vendor/autoload.php';

use Abraham\TwitterOAuth\TwitterOAuth;

$connection = new TwitterOAuth(
    'abc',
    'abc',
    '123-abc,
    'abc',
);

$status_payload = [
    'status' => 'Hello World 1' . time(),
];
$response = $connection->post('statuses/update', $status_payload);
var_dump($response);

$connection->setApiVersion('2');

$status_payload = [
    'text' => 'Hello World 2' . time(),
];
$response = $connection->post('tweets', $status_payload, true);
var_dump($response);
```

**Comment by RoHodson** [comment]
First part of the code (before v2) does not work, I get: You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve

Second part does not work, I get: Forbidden

**Comment by abraham** [comment]
1 is expected. You'll have to get access from Twitter if want to use v1 of the API.

For 2 there should be an error code or message in the API response body explaining the forbidden.

**Comment by RoHodson** [comment]
object(stdClass)#6084 (4) { ["title"]=> string(9) "Forbidden" ["detail"]=> string(9) "Forbidden" ["type"]=> string(11) "about:blank" ["status"]=> int(403) }

**Comment by RoHodson** [comment]
App permissions is already set to Read and Write. Why would I have to revoke?

Why is this such a mess on Twitter's side? I know this isn't your fault since you just make the API, but having to jump through so many god damn hoops is infuriating. You have to apply for this, then that, then undo it, then do it again. There's literally 7 bloody API keys you need. WHY NOT ONE? Who the hell designed it like this?

**Comment by abraham** [comment]
Token permission levels don't change so if the app was set to read only, you generated the user's token, upgraded the app to read+write, the user's token is still read only. The easy fix is revoke the app as the user and generate new tokens with the current permissions.
