### ISSUE TITLE
Media upload returning null with OAuth1.0

### ISSUE THREAD

**Issue by joshembling** [abraham/twitteroauth#1101]
As per the exact example in the docs, $media1 returns null when dumping out (quadruple checked file path), and error reads "Attempt to read property "media_id_string" on null"... which means the file won't upload so therefore can't be added to the tweet?

Why is this and what am I doing wrong. This is the example I'm using (Laravel 9)

```
$connection = new TwitterOAuth(...);
$media1 = $connection->upload('media/upload', ['media' => Storage::path($filename)]);
$parameters = [
    'status' => 'Meow Meow Meow',
    'media_ids' => implode(',', [$media1->media_id_string])
];
$result = $connection->post('statuses/update', $parameters);
```

FYI, my Twitter API auth settings are:

**OAuth 1.0a
Can be used with Twitter API v1.1 and v2
Uses broad authorization with coarse scopes
App permissions - read and write**

**Comment by abraham** [comment]
My best guess is it's something to do with your PHP version or configuration. Try some different PHP versions and some different PHP hosts. If it works there than we can rule out a credentials or Twitter app configuration issue.

**Comment by abraham** [comment]
Glad you got it working.

**Comment by compujeramey** [comment]
Ran into the same issue. Appreciate the workaround of moving the setApiVersion @joshembling.

**Comment by larsjanssen6** [comment]
Hmm not working for me :(

**Comment by JaimeObregon** [comment]
Besides moving the `setApiVersion()` call downstream as @joshembling points out, I have had to also change the endpoint name from `statuses/update` to `tweets` and to add a third parameter to the `post()` call and set it to `true`. 

All of this can be seen in his example above. In my opinion, the docs at [twitteroauth.com](https://twitteroauth.com) might better reflect these changes.

**Comment by Meenaachy07** [comment]
In this coding you can modify with choose image from blade file? Please

$connection = new TwitterOAuth(...);
// don't see connection to version 2 yet

        // upload image
        $result = $connection->upload('media/upload', [
            'media' => 'path/to/image',
        ], true);

        // check result (returns media object)
        var_dump($result);

        // if the connection api version isn't set here to v2, the response below will not work, it'll just return null... and you'll be scratching your head 
       // On the contrary, if it's set to v2 before media upload (underneath the $connection init at the top), that will return null and the tweet will post as normal. Vice versa kind of thing.
        $connection->setApiVersion('2');

        $response = $connection->post('tweets', [
            'text' => 'Test',
            'media' => [
                'media_ids' => [$result->media_id_string],
            ]
        ], true);

       // tweet uploaded
        var_dump($response);
