### ISSUE TITLE
Unsupported Authentication

### ISSUE THREAD

**Issue by HackerGaucho** [abraham/twitteroauth#1127]
**What are you attempting to do**
Add rules to [Filtered Stream](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/api-reference/post-tweets-search-stream-rules)

**Expected behavior**
Return a array with the rules

**Actual behavior**

Return a 403

```
object(stdClass)#4 (4) {
  ["title"]=>
  string(26) "Unsupported Authentication"
  ["detail"]=>
  string(141) "Authenticating with OAuth 1.0a User Context is forbidden for this endpoint.  Supported authentication types are [OAuth 2.0 Application-Only]."
  ["type"]=>
  string(61) "https://api.twitter.com/2/problems/unsupported-authentication"
  ["status"]=>
  int(403)
}
```

**Code example**

```php
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$connection->setApiVersion('2');
$rules_arr=[
  'add' => 
  [
      'value' => 'term1',
  ],
  [
      'value' => 'term2',
  ],
];
$result = $connection->post('tweets/search/stream/rules/',$rules_arr,true);
var_dump($result);
```

**Versions:**

- TwitterOAuth: [e.g. v4.0.1]
- PHP: v [e.g. v8.1.11]

**Additional context**

**Comment by abraham** [comment]
I think you need to get app app token like in [the `testOauth2Token` test](https://github.com/abraham/twitteroauth/blob/main/tests/TwitterOAuthOAuthTest.php#L54-L65) and use it like in [the `testOauth2BearerToken` test](https://github.com/abraham/twitteroauth/blob/main/tests/TwitterOAuthOAuthTest.php#L71-L84).
