### ISSUE TITLE
Account details

### ISSUE THREAD

**Issue by bryllequinto23** [abraham/twitteroauth#1130]
How can I get the details of the twitter account (username, userid) etc. after authorizing?

**Comment by brandymedia** [comment]
```
$connection->setApiVersion('2');
$resp = $connection->get("users/:id");
```
Where :id is the actual ID of the user you are looking up.

**Comment by abraham** [comment]
Traditionally this is done with [account/verify_credentials](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials).
