### ISSUE TITLE
Unauthorized 401 when updating list meta data with PUT request

### ISSUE THREAD

**Issue by brandymedia** [abraham/twitteroauth#1133]
**What are you attempting to do**
Trying to update a lists meta data using a PUT request

**Expected behavior**
The list should update

**Actual behavior**
An error is received
```
}
  "title": "Unauthorized"
  "type": "about:blank"
  "status": 401
  "detail": "Unauthorized"
}
```

**Code example**

```php
$resp = $connection->put("lists/1", ["name" => "new name", "description" => "new description, yo!", "private" => false], true);
```

List ID omitted for security reasons/

**Versions:**

- TwitterOAuth: [e.g. v3.3.0]
- PHP: v [e.g. v8.1]

**Additional context**
The same request does work via Postman

**Comment by brandymedia** [comment]
Is it because PUT has not been implemented? I just tried $connection->delete and got the following error:

```
{
  "title": "Method Not Allowed"
  "detail": "Method Not Allowed"
  "type": "about:blank"
  "status": 405
}
```
Is it only GET and POST that work with the package?

**Comment by abraham** [comment]
If it's working with v2 i suspect it's something with Twitters migration from v1 to v2. It's been pretty piecemeal.
