### ISSUE TITLE
How to get tweets with more than 1000 likes?

### ISSUE THREAD

**Issue by ar4min** [abraham/twitteroauth#1134]
Hello . I want to find favstar tweets that have more than 1k likes by region. Any ideas for this? If possible, put a query of the request

**Comment by abraham** [comment]
The best option I can think of is the [search API](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets) using the [`min_faves` search flag](https://www.labnol.org/internet/twitter-search-tricks/13693/) with the [`geocode` parameter](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets). I suspect it will be very inaccurate though as most tweets don't have location info.
