### ISSUE TITLE
Media upload doesn't work using image URL

### ISSUE THREAD

**Issue by neopage** [abraham/twitteroauth#1156]
**Is your feature request related to a problem? Please describe.**
Media upload doesn't work using image URL.

example code:
```
$media1 = $connection->upload('media/upload', ['media' => 'https://hoge/kitten.jpg']);
:
$result = $connection->post('statuses/update', $parameters);
```

result: 
```
PHP Fatal error:  Uncaught InvalidArgumentException: You must supply a readable file in ~/vendor/abraham/twitteroauth/src/TwitterOAuth.php
:
```

**Describe the solution you'd like**
remove the code : !is_readable($parameters['media'])
detail, see pull requiest.

**Describe alternatives you've considered**
I also considered a way to skip "is_readable" if it's image URL.
But, I thought "is_readable" is excessive checking. So, removed "is_readable".

**Additional context**
is_readable function cannnot check URL image is readble or not.

**Comment by abraham** [comment]
Currently you have to download the image into a cache location and upload from there. https://github.com/abraham/twitteroauth/issues/681 is planned add alternative approaches.
