### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by sansur099** [abraham/twitteroauth#1158]
https://pastebin.pl/view/1155bbe0 I'm trying login but checkpoint problem every time. I'm unlock account after try this problem

**Comment by sansur099** [comment]
Sir ı'm solved changed host. problem is I think date time for server. But now I want to send dm with api ı can't.

**Comment by abraham** [comment]
[Here is an example of how to send DMs](https://github.com/abraham/twitteroauth/blob/ee22855c6b59cd31929b61f352af6a27fc55ae14/tests/TwitterOAuthDirectMessagesTest.php#L33-L55).

**Comment by sansur099** [comment]
its possible from xoauth so with id pw.

**Comment by abraham** [comment]
[xauth has been retired](https://twittercommunity.com/t/retirement-of-xauth/88022).

**Comment by sansur099** [comment]
I'm using twitter for ipad api token. Can I send dm with ipad api?

**Comment by abraham** [comment]
I have no idea what the ipad api is and can only help with the twitteroauth php library. For general twitter api questions post to the [developer community](https://twittercommunity.com/).
