### ISSUE TITLE
better examples would be helpful - how do I retrieve timeline to get the last tweet?

### ISSUE THREAD

**Issue by morrow95** [abraham/twitteroauth#1164]
I have been using a much older version of this for years to get the last tweet from my own username.  With the new v2 api I need to redo all of this.  Twitter's own docs aren't the greatest and there are very little examples provided with this.

How would I access the `/2/users/:id/tweets` endpoint with your solution and send optional parameters for this endpoint?

The only example I see provided is : 

```
$connection = new TwitterOAuth(...);
$connection->setApiVersion('2');
$response = $connection->get('users', ['ids' => 12]);
```

**Comment by abraham** [comment]
```
$connection = new TwitterOAuth(...);
$connection->setApiVersion('2');
$response = $connection->get('users/12/tweets');
```

**Comment by alxvallejo** [comment]
@abraham There is no CONSUMER_KEY or CONSUMER_SECRET offered by registering an app with the Twitter Developer Portal. There is only an Api Key, Api Key Secret, Client Key, and Client Secret. Please advise?

**Comment by abraham** [comment]
I believe for OAuth 1:
- CONSUMER_KEY = Api Key
- CONSUMER_SECRET = Api Key Secret
And for OAuth 2:
- CONSUMER_KEY = Client ID
- CONSUMER_SECRET = Client Secret

**Comment by chayaneng** [comment]
@abraham for OAuth 2 those client ID and client secret is not working. Can you instruct me more? or @alxvallejo ?

**Comment by abraham** [comment]
Please open a new issue describing your problem.
