### ISSUE TITLE
This feature is temporarily unavailable, how can I handle this error?

### ISSUE THREAD

**Issue by chayaneng** [abraham/twitteroauth#1168]
$oauth_token = $request['oauth_token'];
     $oauth_verifier = $request['oauth_verifier'];
     $connection = new TwitterOAuth(env('TWITTER_CONSUMER_KEY'), env('TWITTER_CONSUMER_SECRET'), $oauth_token, $oauth_verifier);
     $token = $connection->oauth("oauth/access_token", ["oauth_verifier" => $oauth_verifier]);

On tis point when I am doing second call on TwitterOAuth() with same token and verifier, it is giving me **"This feature is temporarily unavailable"** error. How can I handle this error?

    "message": "This feature is temporarily unavailable",
    "exception": "Abraham\\TwitterOAuth\\TwitterOAuthException",
    "file": "C:\\xampp\\htdocs\\sage-seo\\sage_seo_lambda\\vendor\\abraham\\twitteroauth\\src\\TwitterOAuth.php",
    "line": 183,

**Comment by abraham** [comment]
`$connection` needs to be built with passing the request token `oauth_token` and `oauth_token_secret` to `TwitterOAuth`, not `oauth_token` and `oauth_verifier`.

**Comment by chayaneng** [comment]
$connection = new TwitterOAuth(env('TWITTER_CONSUMER_KEY'), env('TWITTER_CONSUMER_SECRET'), $oauth_token, $oauth_token_secret);
    $token = $connection->oauth("oauth/access_token", ["oauth_verifier" => $oauth_verifier]);

I used this as you said, but same problem occurs. I tested to comment out  "oauth/access_token" endpoint line is causing this problem. So what is solution to handle that error when I am doing subsequent call ?

**Comment by abraham** [comment]
`oauth/access_token` should be called once and only once for each token you get from `oauth/request_token`. Are you trying to call it multiple times with the same request token?
