### ISSUE TITLE
Simple user_timeline request returning error

### ISSUE THREAD

**Issue by RailtonSantos** [abraham/twitteroauth#1174]
This is probably not the right place to ask this question, but I need the answer as soon as possible...

I'm trying to fix a Twitter feed that makes a simple `statuses/user_timeline` request... 
It's returning an access level error:
`You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, OAuth) only. If you need access to this endpoint, you may need a different access level`

I believe this request should be "cheap enough" to be accessible using the free version of the API.
As I'm not really familiar with the latest changes of the Twitter API idk if it is related to the API version (as their documentation doesn't seems so clear to me)... So idk if I advise my client to upgrade to basic or pro...

Thanks in advance!

**Comment by abraham** [comment]
As far as I'm aware the free version of the API only allows access to uploads endpoints.

> Free
> For write-only use cases and testing the Twitter API

https://developer.twitter.com/en

**Comment by RailtonSantos** [comment]
damm, but this is because of the latest changes right? this website I'm working on has implemented a version of your library from 2017 that was working with the free version of the API... (yea, no one touched the website since then -.-)
so you think the only way to get Twitter's latest posts is by upgrading to basic?
