### ISSUE TITLE
Undefined property: stdClass::$media_id_string

### ISSUE THREAD

**Issue by ldunphyAK** [abraham/twitteroauth#1175]
2023/06/05 16:23:39 [warning] [application] StackTrace: #0 =.../src/TwitterOAuth.php(384): 
#1 .../src/TwitterOAuth.php(302): Abraham\TwitterOAuth\TwitterOAuth->uploadMediaChunked('media/upload', Array)

**Comment by abraham** [comment]
You're going to have to provide more details. What is the code you are calling? Don't include any API keys/tokens.
