### ISSUE TITLE
No HTTPS proxy support

### ISSUE THREAD

**Issue by zloj-ru** [abraham/twitteroauth#1178]
Please add the parameter set for the curl option CURLOPT_PROXYTYPE, now CURLPROXY_HTTP is written in the code, but more secure connections have long been preferred, for example, my proxy works via https and I have to track changes and, if necessary, set the value CURLPROXY_HTTPS

**Comment by abraham** [comment]
What is `CURLPROXY_HTTPS`? https://www.php.net/manual/en/function.curl-setopt.php doesn't mention it.

**Comment by abraham** [comment]
TwitterOAuth is in maintenance mode and major improvements are no longer planned. https://github.com/abraham/twitteroauth/issues/1188

**Comment by zloj-ru** [comment]
Unfortunately, there is not a complete description, curl is a separate php module and can be viewed directly from the developer: https://curl.se/libcurl/c/CURLOPT_PROXYTYPE.html
