### ISSUE TITLE
INIT process of the video chunked upload

### ISSUE THREAD

**Issue by tsaneyoshi** [abraham/twitteroauth#1179]
There is an error in the INIT process of the video chunked upload.

<error>
Warning: Undefined array key "media" 〜TwitterOAuth.php on line 340

Fatal error: Uncaught TypeError: is_readable(): Argument #1
 ($filename) must be of type string, null given in 
TwitterOAuth.php:340 Stack trace: #0
TwitterOAuth.php(340): is_readable(NULL) #1
TwitterOAuth.php(304): Abraham\TwitterOAuth\TwitterOAuth->uploadMediaNotChunked('media/upload', Array) #2
Abraham\TwitterOAuth\TwitterOAuth->upload('media/upload', Array) #3

```
$filePath = "/path/to/your/video.mp4";
$video_media_ids = null;
$fileSize = filesize($filePath);
//echo $fileSize = int(9180627)

$response = $connection->upload("media/upload", ["command" => "INIT", "media_type" => "video/mp4", "total_bytes" => $fileSize]);
```

Best Regards,

**Comment by abraham** [comment]
You're not passing the `media` value.

```
$connection->upload('media/upload', ['media' => $filePath]);
```
