### ISSUE TITLE
V2 media upload always null

### ISSUE THREAD

**Issue by larsjanssen6** [abraham/twitteroauth#1180]
Is there no way we can get media uploads working with v2?

When I try this:

```
$connection = new TwitterOAuth(
    env("TWITTER_CLIENT_ID"),
    env("TWITTER_CLIENT_SECRET"),
    null,
    $post->account->bearer_token
);

$media = $connection->upload(
    "media/upload",
    [
        "media" => $path,
        "media_type" => $file["mime_type"],
        "media_category" => $isVideo
            ? "tweet_video"
            : "tweet_image",
    ],
    true
);

dd($media);
```

Media is always `null`. How can we fix this?

**Comment by funxiun** [comment]
I found the solution [over here](https://stackoverflow.com/a/76505243).

Posting tweets in API v2 [is slightly different](https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/api-reference/post-tweets) that it used to be but luckily TwitterOAuth is pretty modular so we can change the API call easily.

Hope this helps.

**Comment by abraham** [comment]
Please let us know if that solution doesn't work for you.

**Comment by larsjanssen6** [comment]
Yes, have it working now. Thanks for helping out :)
