### ISSUE TITLE
I did could tweet before but not anymore "You currently have access to a subset of Twitter API v2 endpoints..."

### ISSUE THREAD

**Issue by chon27** [abraham/twitteroauth#1182]
**What are you attempting to do**
I'm trying post a tweet

**Expected behavior**
I did it sometimes in the past and it was fine

**Actual behavior**
Now I'm getting this error:

_You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product_

**Code example**

```php
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
$result = $connection->post("statuses/update", ["status" => $text]);
```

**Versions:**

- TwitterOAuth: v4.0
- PHP: v8.2.7

**Additional context**

**Comment by abraham** [comment]
Twitter has been changing how their API is available. For support on that you'll have to ask them. https://twittercommunity.com/

You might make it work with using the v2 API

```php
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
$connection->setApiVersion('2');
$result = $connection->post("tweets", ["text" => $text], true);
```

**Comment by axsaucedo** [comment]
Adding further context as it seems there's further clarity, this stackoverflow answer provides a good explanation: https://stackoverflow.com/questions/76528610/403-forbidden-453-you-currently-have-access-to-a-subset-of-twitter-api-v2-endp

> Sorry, my friend, but you cannot use the *Search Tweets* feature using the *Free Level Access* on the Twitter API.
> 
> You can use the *Manage Tweets* and *User Lookup* features on Free Level Access.
> 
> For the *Search Tweets* feature, you have to upgrade to the *Basic Level*.
> 
> For more information:
> 
> https://developer.twitter.com/en/docs/twitter-api

Seems to introduce a 100$ a month barrier for simple usage which seems quite suboptimal for most basic/personal usecases.

**Comment by YoannBuzenet** [comment]
Hello Abraham,
Thank you for this amazing library. 
I recently switched to v2 api and can't find how to upload a media now. Would you by chance know what changed ?
Thank you!
Yoann

**Comment by mpruy** [comment]
I would like to open this topic again. I have set the api version to 2 and the endpoint to "tweets" as recommended above. I have left everything else identical to the call under API version 1.

However, I keep getting a response 401 Unauthorized.

Do I have to switch to a bearer token or does the account have to be activated for API version 2?
