### ISSUE TITLE
Media Not Uploading

### ISSUE THREAD

**Issue by MirShaon** [abraham/twitteroauth#1187]
**What are you attempting to do**
I was trying to do implement twitter v2 api for posting solution i was doing testing with this library it was going smoothly but the problem is when i was trying to upload media from my local environment its not working at all i mean no error messages this is the issue i'm facing.

**Expected behavior**
I expect that it will work smoothly as normal text posting working but its not

**Actual behavior**
A clear and concise description of what is actually happening.

**Code example**

```php
require "vendor/autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;

$connection = new TwitterOAuth('', '', '', '');
$connection->setApiVersion('2');
$image = [];

$media = $connection->upload('media/upload', ['media' => 'C:\xampp\htdocs\twitter_oauth\S3169002871756923800.jpg']);
array_push($image, $media->media_id_string);

$data =  [
    'text' => 'Hello world',
    'media'=> ['media_ids' => $image]
];


$content = $connection->post("tweets", $data, true);

echo "<pre>";
print_r($content);
exit;


After run this i'm getting error 

Notice: Trying to get property 'media_id_string' of non-object in C:\xampp\htdocs\twitter_oauth\index.php on line 28
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [parameters] => stdClass Object
                        (
                            [$.media.media_ids[0]] => Array
                                (
                                    [0] => null
                                )

                        )

                    [message] => $.media.media_ids[0]: null found, string expected
                )

        )

    [title] => Invalid Request
    [detail] => One or more parameters to your request was invalid.
    [type] => https://api.twitter.com/2/problems/invalid-request
)

I know why i'm getting error because of media no upload and i'm getting media id 

I'm using Windows 10 and Xamp
```

**Versions:**

- TwitterOAuth: [e.g. v^4.0]
- PHP: v [e.g. v7.4+]

**Additional context**
Please help anyone or is it bug seems bug to me

**Comment by MirShaon** [comment]
I did figure it out

**Comment by YoannBuzenet** [comment]
Hey, I have the same problem.
How did you solve it ?
Thank you!

**Comment by MirShaon** [comment]
In Twitter API V2 media upload endpoint not working yet.
You need to upload media on V1.1 API after upload you will get media id then post on V2 api.

Thank you.
