### ISSUE TITLE
Getting null on account/verify_credentials

### ISSUE THREAD

**Issue by Sourovahmad** [abraham/twitteroauth#1197]
i have a free account on twitter developer. on the developer portal i got the consumer key and secret. as well as the access token and secret.
but when i call 

    $connection = new TwitterOAuth($consumerKey,$consumerSecret,$access_token,$access_token_secret);
    $content = $connection->get("account/verify_credentials");
    dd($content);

i got null. could anyone please explain me why is that ?

**Comment by Vipin-SBM** [comment]
i have faced same issue too. is there any fix?

**Comment by abraham** [comment]
What do you get from these after you make the request?

```php
$connection->getLastHttpCode();
$connection->getLastBody();
```

**Comment by Vipin-SBM** [comment]
i think we cannot use if we have free version. s, this is not considered as bug as i manage to post a tweet using post. Official websites of twitter says "write-only use cases and testing the Twitter API for v2".

**Comment by Vipin-SBM** [comment]
if ($connection->getLastHttpCode() == 200) {
    echo "API request successful! HTTP response code: " . $connection->getLastHttpCode() . "\n";
    echo "API response:\n";
    print_r($response);
} else {
    echo "API request failed! HTTP response code: " . $connection->getLastHttpCode();
}

**Comment by Vipin-SBM** [comment]
i am getting 403 error code (referes to forbidden in official site) for get method and success for post method and i have free version of twitter. Do want me to test anything if i have 403 code. i assume it's because of free version.

**Comment by abraham** [comment]
Yep. That looks like the reason.

**Comment by Vipin-SBM** [comment]
hi there, 
https://developer.twitter.com/en/support/twitter-api/error-troubleshooting please refer to this. i think you check that you are using valid parameters and the correct URI for the endpoint you’re using.

Thank you !
