### ISSUE TITLE
Sorry, you are not authorized to see this status

### ISSUE THREAD

**Issue by emirkutlu** [abraham/twitteroauth#1203]
Hello everyone,
I am using Twitter oauth v1. I log in with pin based login.
mac unofficial api for cs key and cs secret
Consumer key: 3rJOl1ODzm9yZy63FACdg
Consumer secret: 5jPoQ5kQvMJFDYRNE8bQ4rHuds4xJqhvgNJM4awaE8
I use values.

There is no problem when sending a like or follow, however,
When I try to retweet or tweet it says "Sorry, you are not authorized to see this status." I get an error.

My example code:
     $sendAction = new TwitterOAuth($consumerKey, $consumerSecret, $user->twi_access_token, $user->twi_access_token_secret);
     $response = $sendAction->post('statuses/update', ['status' => "Test Tweet"]);
     var_dump($response);

Can you share any information about why I am getting this error?

**Comment by abraham** [comment]
No idea why you're getting that error. "Sorry, you are not authorized to see this status" suggests that you are authenticated and trying to do something you're user isn't allowed to do. I don't know anything about Twitter's app keys and can't help with them.
