### ISSUE TITLE
Send clickable links to Twitter

### ISSUE THREAD

**Issue by ashley-plott** [abraham/twitteroauth#1205]
I want to send links that are clickable, but it comes through as plain text.

` if ($post->post_status === "publish" && $post->post_date === $post->post_modified) {
		// Get the 'push_to_twitter' custom field value
		$push_to_twitter = get_post_meta($ID, 'push_to_twitter', true);

		// Check if 'push_to_twitter' is set to 'yes'
		if ($push_to_twitter === "yes") {

			$twitter = new TwitterOAuth(
				$GLOBALS['api_key'],
				$GLOBALS['api_secret_key'],
				$GLOBALS['access_token'],
				$GLOBALS['access_token_secret']
			);

			$tweet_text = 'New post: ' . get_the_title($ID) . ' ' . esc_url(get_permalink($ID));

			$response = $twitter->post('tweets', [
				'text' => $tweet_text,
			]);
		}
	}`

any help would be great.

**Comment by abraham** [comment]
Include the full URL in the text is all you should need to do. Maybe it's a weird URL that twitter doesn't parse.
