### ISSUE TITLE
Cannot attach mp4 videos

### ISSUE THREAD

**Issue by Membele** [abraham/twitteroauth#1207]
I have all the configuration fine, images and gifs are sent without problems, but the MP4 videos, which were sent for up to two weeks, are now no longer sent.

**Versions:**
- TwitterOAuth: 6.2

**Comment by abraham** [comment]
> which were sent for up to two weeks

If it used to work and now it doesn't it's probably a Twitter issue. You could try asking on https://twittercommunity.com/

**Comment by larsjanssen6** [comment]
Same problem here

**Comment by Samar-Ali666** [comment]
Facing same problem

**Comment by Samar-Ali666** [comment]
Can anyone find a solution ?

**Comment by Samar-Ali666** [comment]
> I have all the configuration fine, images and gifs are sent without problems, but the MP4 videos, which were sent for up to two weeks, are now no longer sent.
> 
> **Versions:**
> 
> * TwitterOAuth: 6.2

I solve the problem .. The twitter start taking some time to process the video at their end ... so we have to wait some time to hit the tweet endpoint

**Comment by muhammadtiolaksono-alpha** [comment]
was problem is solving ?

**Comment by larsjanssen6** [comment]
> > I have all the configuration fine, images and gifs are sent without problems, but the MP4 videos, which were sent for up to two weeks, are now no longer sent.
> > **Versions:**
> > 
> > * TwitterOAuth: 6.2
> 
> I figure out the problem .. The twitter start taking some time to process the video at their end ... so we have to wait some time to hit the tweet endpoint

yes I had the same

**Comment by abraham** [comment]
There appears to now be an API endpoint for checking on the status of media processing.

https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/get-media-upload-status
