### ISSUE TITLE
Unable to upload media as a string (incorrect hostname used)

### ISSUE THREAD

**Issue by antdickens** [abraham/twitteroauth#1209]
**What are you attempting to do**
Upload a media file to twitter, with just the **contents** of the file, rather than a file on disk.

**Expected behavior**
Expect to use the post method to upload the data to Twitter API

**Actual behavior**
Because Twitter has a different hostname for the media upload endpoint, the post method is failing, as all standard post() requests are going to to main hostname.

**Code example**

```php
// Include code that demonstrates the issue.
$data = array('media_data'=>base64_encode($file_contents));
if ($response = $connection->post('media/upload',$data))) {
...
}
```

**Versions:**

- TwitterOAuth: v6.2.0
- PHP: v8.2.7

**Additional context**

My workaround is to look for the specific method and swap the hostname accordingly, which results in the code behaving as expected. Perhaps a method to decide which hostname to use for which methods would be useful in this instance?

```php
public function post(
        string $path,
        array $parameters = [],
        ?bool $json = null,
    ) {
        if (is_null($json)) {
            $json = $this->useJsonBody();
        }

        return $this->http('POST', $path == 'media/upload' ? self::UPLOAD_HOST : self::API_HOST, $path, $parameters, $json);
    }
```

Thanks for all your work on this package!

**Comment by abraham** [comment]
You'll have to write the media to a temp file on disk and upload that with the `upload` method.

```php
$media1 = $connection->upload('media/upload', ['media' => '/path/to/file/kitten1.jpg']);
```

There are no plans add new upload features.
