### ISSUE TITLE
unexpected bug

### ISSUE THREAD

**Issue by boazn0** [abraham/twitteroauth#1210]
When I try to connect:

```
use Abraham\TwitterOAuth\TwitterOAuth;
$connection = new TwitterOAuth( $consumer_key, $consumer_secret, $oauth_access_token,$oauth_access_token_secret);

```
I get this error:

`Parse error: syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in /public_html/incFiles/twitteroauth/src/TwitterOAuth.php on line 33
`
php ver: 7.2.34
twitteroauth: 6.2.0

**Comment by abraham** [comment]
You're using an old version of PHP that isn't supported. You either need to update PHP or switch to an old version of TwitterOAuth.

**Comment by 125569489** [comment]
maybe you can try  it twitter.utools.me
