### ISSUE TITLE
return NULL

### ISSUE THREAD

**Issue by amerhamdan3** [abraham/twitteroauth#1212]
**What are you attempting to do**
i am trying to do simple api request to twitter 

**Expected behavior**
to return any thing than null

**Actual behavior**
NULL

**Code example**

```php
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
$content = $connection->get("account/verify_credentials");
var_dump($content);
```

i was trying to do more complex api but i was troubleshooting and returning to basics 

**Versions:**

 "abraham/twitteroauth": "^6.2",
 "guzzlehttp/guzzle": "^7.8"
- PHP: v 8.2.12

**Comment by abraham** [comment]
It's probably an issue with the credentials. Though I would expect the response to be an error message.

**Comment by amerhamdan3** [comment]
Yes i expected error or not authorized.. but its returning null .. of you
can assist me i will send the credentials of the app and change them later
is it oky ?

**Comment by hizmarck** [comment]
@amerhamdan3 for me worked as you expected. 
![image](https://github.com/abraham/twitteroauth/assets/4828196/7a7b332b-4ee1-4d4e-991d-d49819220077)

but I'm using version 5 of the library. 🤔

**Comment by hizmarck** [comment]
@amerhamdan3 The problem is that for version 6.x the default version configured is 2, and the endpoint that you are trying to get comes from the 1.1 , so, I tested and this worked:

```
 $connection = new TwitterOAuth($key, $secret);
 $connection->setApiVersion("1.1");
 $content = $connection->get("account/verify_credentials");
```

Regards

**Comment by amerhamdan3** [comment]
@hizmarck Thank you now i am getting the error message ,, you are a saver

**Comment by KarlosFodaoBr** [comment]
> @amerhamdan3 The problem is that for version 6.x the default version configured is 2, and the endpoint that you are trying to get comes from the 1.1 , so, I tested and this worked:
> 
> ```
>  $connection = new TwitterOAuth($key, $secret);
>  $connection->setApiVersion("1.1");
>  $content = $connection->get("account/verify_credentials");
> ```
> 
> Regards

ILOVEYOU
