### ISSUE TITLE
Upload Media always null

### ISSUE THREAD

**Issue by lucaschevalierr** [abraham/twitteroauth#1221]
**What are you attempting to do**
I'm trying to upload a photo, but my result is always null...

I was inspired by what was done here: https://stackoverflow.com/questions/76504748/twitter-api-v2-create-tweet-with-media-php/76505243#76505243

Here's my code:

```php
$connection = new TwitterOAuth($consumerKey, $consumerSecret, $accessToken, $accessTokenSecret);
$connection->setApiVersion(1.1);
$media = $connection->upload('media/upload', [
    'media' => 'imgs/test.jpeg'
]);

dd($media);
```

**Versions:**

- TwitterOAuth: ^7.0
- I'm using PHP 8.2.14 and Symfony 7.0.

**Additional context**
I also tried not specifying the API version, adding parameters like media type, but nothing worked.

**Comment by ProdigyView** [comment]
Same here

**Comment by ProdigyView** [comment]
@lucaschevalierr Solved it! Use the chunk upload.

`$media1 = $connection->upload('media/upload', ['media' => '/code/test.mp4','media_type' => 'video/mp4', 'media_category' => 'tweet_video'], ['chunkedUpload' => true]);`

**Comment by lucaschevalierr** [comment]
@ProdigyView It doesn't work for me...
I try to do this :

```php
$media = $connection->upload(
            'media/upload',
            [
                'media' => 'imgs/test.jpeg',
                'media_type' => 'image/jpeg',
                'media_category' => 'tweet_image'
            ],
            ['chunkedUpload' => true]
        );
```


And i have this error : property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given

**Comment by ProdigyView** [comment]
I would the the absolute page to your image:

 'media' => 'imgs/test.jpeg',

**Comment by lucaschevalierr** [comment]
> I would the the absolute page to your image:
> 
> 'media' => 'imgs/test.jpeg',

it doesn't work either

**Comment by lucaschevalierr** [comment]
<img width="623" alt="image" src="https://github.com/abraham/twitteroauth/assets/62570190/32cf7d0c-3f8f-4d14-8d18-28a7ecc00263">

My Twitter application is an application created on API v2, from what I understand, with API v2, we also have access to API v1...

Should I create an application specifically on API v1?

**Comment by lucaschevalierr** [comment]
Anyone have an idea?

**Comment by abraham** [comment]
> And i have this error : property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given

What's the rest of the error? What method is getting an invalid value?

**Comment by lucaschevalierr** [comment]
> > And i have this error : property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given
> 
> What's the rest of the error? What method is getting an invalid value?

Here is the rest of the error :
![image](https://github.com/abraham/twitteroauth/assets/62570190/8aa0c478-0db4-4a3c-ac38-98312e8095a8)

**Comment by abraham** [comment]
If you are not on the latest version of TwitterOAuth you would need to use the old method of setting `chunkedUpload`

```
$media = $connection->upload(
            'media/upload',
            [
                'media' => 'imgs/test.jpeg',
                'media_type' => 'image/jpeg',
                'media_category' => 'tweet_image'
            ],
            true
        );
```

**Comment by lucaschevalierr** [comment]
> If you are not on the latest version of TwitterOAuth you would need to use the old method of setting `chunkedUpload`
> 
> ```
> $media = $connection->upload(
>             'media/upload',
>             [
>                 'media' => 'imgs/test.jpeg',
>                 'media_type' => 'image/jpeg',
>                 'media_category' => 'tweet_image'
>             ],
>             true
>         );
> ```

So I ran some tests:

- When I use the Client ID and Client Secret in the variables $consumerKey and $consumerSecret WITH ['chunkedUpload' => true], I get this error:
![Correction](https://github.com/abraham/twitteroauth/assets/62570190/26443e0c-6c24-4a6e-a4f3-5765193ff587)

- When I use the Client ID and Client Secret in the variables $consumerKey and $consumerSecret WITHOUT ['chunkedUpload' => true], I get this error: 
![Correction (1)](https://github.com/abraham/twitteroauth/assets/62570190/5bac250d-316d-41d7-9f1f-6c701929c9f5)

- When I use the API Key and API Key secret in the variables $consumerKey and $consumerSecret WITH ['chunkedUpload' => true], I get this error:
![Correction (2)](https://github.com/abraham/twitteroauth/assets/62570190/fa8d0c98-7880-4717-967f-448a9ce56f06)

- When I use the API Key and API Key secret in the variables $consumerKey and $consumerSecret WITHOUT ['chunkedUpload' => true], I get "null":
![Correction (4)](https://github.com/abraham/twitteroauth/assets/62570190/b32919b8-756e-4e52-b0de-bfe011984704)


PS: I think I am using the latest version of TwitterOAuth because when I try your code, I get this error: "Expected type 'array'. Found 'true'.”
![Correction (3)](https://github.com/abraham/twitteroauth/assets/62570190/58928f74-7375-4bd4-95b7-a8c3bf1eed18)

PS2: Thank you very much for the time you spend helping me.

**Comment by abraham** [comment]
I think you have an authentication issue. To use that API you need client credentials and user credentials. You would want to use the the values with the following names. You'd also need to make sure that the user has granted write permissions for that token and if the user had previously granted read only permissions, the app needs to be revoked and authorized again.


```php
$connection = new TwitterOAuth('API Key', 'API Secret', 'Access Token', 'Access Token Secret');
```

**Comment by lucaschevalierr** [comment]
> I think you have an authentication issue. To use that API you need client credentials and user credentials. You would want to use the the values with the following names. You'd also need to make sure that the user has granted write permissions for that token and if the user had previously granted read only permissions, the app needs to be revoked and authorized again.
> 
> ```
> $connection = new TwitterOAuth('API Key', 'API Secret', 'Access Token', 'Access Token Secret');
> ```

OMG, the last time I created the token I didn't have the right permissions, I didn't see that it was here.

<img width="584" alt="image" src="https://github.com/abraham/twitteroauth/assets/62570190/debd68b6-0de7-4497-8691-70b94e456c5f">

Thank you and really sorry...
