### ISSUE TITLE
account/verify_credentials returns NULL

### ISSUE THREAD

**Issue by levanigongadze** [abraham/twitteroauth#1223]
I'm trying to get the user information when the user is redirected to the callback url but it returns NULL. 

I also tried to change the API version but the result is the same.

```
            $oauth_verifier = $_GET['oauth_verifier'];
            $oauth_token = $_GET['oauth_token'];
        
            $twitteroauth = new TwitterOAuth($consumerKey, $consumerSecret, $oauth_token, $_SESSION['oauth_token_secret']);
        
            $twitteroauth->setApiVersion('1.1'); // Specify the version you want to use
        
            $access_token = $twitteroauth->oauth("oauth/access_token", ["oauth_verifier" => $oauth_verifier]);
        
            $twitteroauth = new TwitterOAuth($consumerKey, $consumerSecret, $access_token['oauth_token'], $access_token['oauth_token_secret']);

            $user =  $twitteroauth->get("account/verify_credentials");

            print_r($user);
```

**Comment by levanigongadze** [comment]
Done.

`        // Create a new TwitterOAuth instance
        $twitterOAuth = new TwitterOAuth($consumerKey, $consumerSecret, $accessToken, $accessTokenSecret);

        $twitterOAuth->setApiVersion('1.1');

        // Make a request to the Twitter API to retrieve user information
        $userInfo = $twitterOAuth->get("account/verify_credentials");

        // Check if the request was successful
        if ($twitterOAuth->getLastHttpCode() == 200) {
          print_r($userInfo);
        } else {
            // Print an error message if the request was not successful
            echo "Error: Unable to retrieve user information";
        }`

**Comment by abraham** [comment]
You got it working?

**Comment by maaprofit** [comment]
@abraham @levanigongadze had the same issue and what he commented last, worked for me.
It's important to specify the `setApiVersion`. :)

Just leaving this comment in case someone goes through this.
