### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by vadegangas** [abraham/twitteroauth#1225]
I'm trying to post a tweet on behalf of another user, I always get a 403 Forbidden.

The implemented code is:

$connection = new TwitterOAuth($red->getConsumerKey(), $red->getConsumerSecret(), $red->getAccessToken(), $red->getAccessTokenSecret());

$connection->setApiVersion(2);
$connection->setBearer($red->getAccessTokenBehaif()); //Their Behalf

$parameters = [
      'text' => $this->text
];

$result = $connection->post('tweets', $parameters, ['jsonPayload' => true]);

What could I be doing wrong?

**Versions:**

- TwitterOAuth: v7.0.0
- PHP: v8.1

**Comment by abraham** [comment]
[Bearer tokens](https://developer.twitter.com/en/docs/authentication/oauth-2-0) are listed as not working for user requests.
