### ISSUE TITLE
Can't retweet in PHP

### ISSUE THREAD

**Issue by rckt83520** [abraham/twitteroauth#1226]
I have been using your library for several years to automate tweets in PHP, everything works well. I now want to be able to retweet specific tweets from other users, but I can't find the right method. I do have a developer account with "Basic" access, so I should be able to do it.

Is it possible to have a concrete example in PHP? Thanks for your help !

**Comment by abraham** [comment]
I think you'd want https://developer.twitter.com/en/docs/twitter-api/tweets/retweets/api-reference/post-users-id-retweets which on the latest version of this library would look something like:


```php
// $user_id is the user that creating the retweet
// $tweet_id is the tweet that should be retweeted
$result = $connection->post('users/' . $user_id . '/retweets', ['tweet_id' => $tweet_id], ['jsonPayload' => true]);
```

**Comment by rckt83520** [comment]
It's perfect, fast and efficient. Thank you for your valuable help!
