### ISSUE TITLE
statuses/update

### ISSUE THREAD

**Issue by jazz265** [abraham/twitteroauth#1232]
```php
$connection->setApiVersion('2');
$status_id = '1234567890';
$rep= '@name test';

$result = $connection->post('statuses/update', array('in_reply_to_status_id'=> $status_id , 'status' => $rep ));
var_dump($result);

```

I'm trying this code, but it doesn't work well and the result is returned as null. Tweets and media/upload are working, but only status/update is not working properly. Is there something missing?

**Comment by abraham** [comment]
`'statuses/update'` is API v1.1, you need to use the [v2 version](https://developer.x.com/en/docs/twitter-api/tweets/manage-tweets/api-reference/post-tweets).

**Comment by jazz265** [comment]
thank you so much!solved!
