### ISSUE TITLE
usual "Could not connect to Twitter." issue but your library was working perfectly

### ISSUE THREAD

**Issue by Sarasvati** [abraham/twitteroauth#153]
Hi Abraham, I know that you've answered this question probably more than once. However, I get a weird "could not connet to twitter" error after having used your library (I should have tweaked it correctly it for the  API 1.1 and it worked until a few hours ago) with no issues for more than one month. Of course I changed nothing in the past few hours, twitter shouldn't have changed anything either and the error I get when adding var_dump($request); is "NULL Could not connect to Twitter. Refresh the page or try again later." The server looks slow. I can't sync it in case that's the problem (it's shared). The callback is stated in my app and still something must be wrong.
Sure I am not a programmer but I did nothing to change things around so I wonder if you have a guess and/or have heard of similar problems on the topic.

Thanks so much!

**Comment by sixthlife** [comment]
cannot find the twitter api status at https://dev.twitter.com/status

is it down now? can i have the new status url

**Comment by abraham** [comment]
There is a link at the bottom of https://dev.twitter.com/ under "Tools"

**Comment by sixthlife** [comment]
Hi,

 

Thanks

 

It was resolved.

 

Anu
