### ISSUE TITLE
friendships/create issue

### ISSUE THREAD

**Issue by utpal4job** [abraham/twitteroauth#164]
I am using the below code to create friendships on twitter but it's not creating any friendships. Please let me know where i am wrong.

require_once('twitter/twitteroauth/twitteroauth.php');
require_once('twitter/config.php');
$access_token = $_SESSION['access_token'];
$twitteroauth = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token['oauth_token'], $access_token['oauth_token_secret']);
$content = $twitteroauth->get('account/verify_credentials');

$confirm = $twitteroauth->get('friendships/exists', array('user_a' => 'userA', 'user_b' => 'userB'));  
if(!$confirm)
{  
    $twitteroauth->get('users/show', array('screen_name' => 'userA'));
    $twitteroauth->post('friendships/create', array('screen_name' => 'userB'));  
}  

An early response is always appreciated.

Thanks.

**Comment by balintfarago** [comment]
What are we supposed to use?

**Comment by abraham** [comment]
https://dev.twitter.com/rest/reference/get/friendships/show

**Comment by balintfarago** [comment]
I know I just didn't know how to use it then. For others:
`$following = $twitteroauth->get('friendships/show', array('source_id' => $your_id, 'target_id' => $id_to_follow));
$x = json_encode($following);
$json = json_decode($x, true);
if ($json['relationship']['source']['following']) {
	$connection->post('friendships/destroy', array('user_id' => $id_to_follow));
} else {
	$connection->post('friendships/create', array('user_id' => $id_to_follow));
}`
