### ISSUE TITLE
Undefined index: oauth_token in twitteroauth.php on line 82

### ISSUE THREAD

**Issue by geezee** [abraham/twitteroauth#171]
There's nothing much I did that caused this:

```
session_start();
require "api/twitteroauth.php";

$twitteroauth = new TwitterOAuth(KEY,SECRET);
$requestToken = $twitteroauth->getRequestToken("http://localhost/onlinecollaborative/connect_tw.ph    p");

if($twitteroauth->http_code == 200) {
} else {
   die("Something went wrong!");
}
```

**Comment by prakash143** [comment]
Warning: mysql_connect(): Access denied for user 'username'@'localhost' (using password: YES) in C:\xampp\htdocs\Login\config\dbconfig.php on line 7
Access denied for user 'username'@'localhost' (using password: YES)
