### ISSUE TITLE
Getting error "need a consumer key and secret to test the sample code"

### ISSUE THREAD

**Issue by GeeGirls4** [abraham/twitteroauth#201]
I have a consumer key and secret and still getting this error.  I've even reset it to make sure.

What am I doning wrong?

This is my code:
require_once('config.php');
if (CONSUMER_KEY === '' || CONSUMER_SECRET === '' || CONSUMER_KEY === 'mykeyxxx' || CONSUMER_SECRET === 'mykeysecret') {
  echo 'You need a consumer key and secret to test the sample code. Get one from <a href="https://dev.twitter.com/apps">dev.twitter.com/apps</a>';
  exit;

**Comment by atixeret** [comment]
hola me manda el mismo error pero como debo de pasar la variable en el if

This is my code:
require_once('config.php');
if (CONSUMER_KEY === '' || CONSUMER_SECRET === '' || CONSUMER_KEY === 'mykeyxxx' || CONSUMER_SECRET === 'mykeysecret') {
echo 'You need a consumer key and secret to test the sample code. Get one from dev.twitter.com/apps';
exit;
