### ISSUE TITLE
Undefined index: access_token

### ISSUE THREAD

**Issue by mikespence** [abraham/twitteroauth#209]
It all works fine and calls back fine but I get 'Undefined index: access_token' in the apache logs when I return to my site. Any pointers would be great!

**Comment by magamlag** [comment]
I also have the same issue:

ErrorException in AbstractProvider.php line 221:
Undefined index: access_token

I am trying figure out how to fix this  and what can be a reason of this, but without success.

**Comment by abraham** [comment]
This issue has been closed for a long time. Please open a new issue and provide a lot more details.
