### ISSUE TITLE
Class 'TwitterOAuth' not found

### ISSUE THREAD

**Issue by anoura** [abraham/twitteroauth#239]
I'm using the tutorial below along with your twitteroauth folder( + files) to pull in tweets. Unfortunately I am getting an error. Any help would be appreciated. I am running this script on a VPS.

Tutorial: http://www.sitepoint.com/twitter-1-1-oauth-php/

PHP Error: Fatal error: Class 'TwitterOAuth' not found in ...

**Comment by sofathitesh** [comment]
i am also facing same error 

PHP Fatal error:  Class 'TwitterOAuth' not found in /var/www/html/twitteroauth/index.php on line 5

**Comment by Cinoze** [comment]
I've the same error than sofathitesh, don't know why but if i find it ... 
Thanks for your work :)

**Comment by abraham** [comment]
Make sure you are following the install instructions specified on twitteroauth.com

**Comment by hendratjua** [comment]
the problem is the curl already timeout change abraham/twitteroauth/src/TwitterOAuth.php line 23 and 25
    /** @var int How long to wait for a response from the API */
    private $timeout = 10;
    /** @var int how long to wait while connecting to the API */
    private $connectionTimeout = 10;

**Comment by davidefossacecchi** [comment]
There are errors in the manual installation (for example there is not an autoload.php file but and autoloader.php file). Installing it with composer seems to work.

**Comment by davidefossacecchi** [comment]
Some times tells that the offset is undefined att TwitterOAuth.php at line 403, but just sometimes...

**Comment by abraham** [comment]
@davidefossacecchi I've update the `autoload.php` filename but please don't hijack old issues. Open new ones.

**Comment by NikhilRadadiya7** [comment]
i got this error
Notice: Undefined property: stdClass::$name in C:\xampp\htdocs\twitter\index.php on line 59

**Comment by abraham** [comment]
@NikhilRadadiya open a new issue and fully describe your problem.
