### ISSUE TITLE
Weird follower count bug

### ISSUE THREAD

**Issue by KJThaDon** [abraham/twitteroauth#252]
Not sure why this is happening..

I am using the code below to display a twitter follower count. What's happening is it displays fine here on the script im working on >
http://ngx2gaming.com/kjthadon_social/

Although once I include the file above onto the front page sidebar of the site, twitter is the only one that wont display .. As you can see here
http://ngx2gaming.com/

Anyone have an idea why it wont display on my front page, but will when I access the file directly?

Thanks

```
<?php
require_once ('twitteroauth.php');
require_once ('OAuth.php');

$twitter_id = 'ngx2gaming';
$twitter_access_token = 'xxx';
$twitter_access_token_secret = 'xxx';
$twitter_consumer_key = 'xxx';
$twitter_consumer_secret = 'xxx';

$twitter_api = new TwitterOAuth( $twitter_consumer_key , $twitter_consumer_secret , $twitter_access_token , $twitter_access_token_secret );
$twitter_api_link = $twitter_api->get( 'users/lookup' , array ( 'screen_name' => ( $twitter_id ) ) );
$twitter_count = $twitter_api_link[0]->followers_count;
echo $twitter_count;
?>
```

**Comment by Aljessy** [comment]
Hello. i'm trying to use this code above. I have a fatal error on this line <code>$twitter_count = $twitter_api_link[0]->followers_count;</code>.

This it the error <code>Fatal error: Cannot use object of type stdClass as array</code>

Please how can i solve it.

Best regards.
