### ISSUE TITLE
OAuthToken class never used

### ISSUE THREAD

**Issue by merlosy** [abraham/twitteroauth#262]
Hi,
I noticed a small thing in the code: the OAuthToken class is never used, you use OAuthConsumer instead. Even though they are almost the same and it won't change anything, it doesn't make much sense..
In the constructor of TwitterOAuth, you should have:
```
      $this->token = new OAuthToken($oauth_token, $oauth_token_secret);
```
instead of:
```
      $this->token = new OAuthConsumer($oauth_token, $oauth_token_secret);
```

**Comment by abraham** [comment]
Fixed.
