### ISSUE TITLE
include("TwitterOAuth.php"); doesn't work but copying and pasting the entire file contents do

### ISSUE THREAD

**Issue by rchan2** [abraham/twitteroauth#285]
Dear all,

The link to my question on stackoverflow is: http://stackoverflow.com/questions/27745553/php-include-doesnt-work-for-twitteroauth-php-but-when-i-copy-and-paste-its-con

Basically I have my TwitterOAuth.php, OAuth.php and my twitter.php file in the same directory. My twitter.php file is the one I try to include("TwitterOAuth.php"); in to connect to oauth.

When I try to include(...), I get this error:

Fatal error: Class 'TwitterOAuth' not found in /home/sites/rwmchan.com/public_html/twitteroauth-master/src/twitter.php on line 239

***line 239 is the line where I call
$connection = new TwitterOAuth...

However, when I simply copy and paste the ENTIRE contents of the TwitterOAuth.php file, replacing the include(...) line with the file contents, everything is peachy. I've also tried include_once, require, and require_once, to no avail. Please advise!

**Comment by abraham** [comment]
I don't see anything obviously wrong. I'm going to close this issue though since there are a number of people commenting on SO.
