### ISSUE TITLE
composer.json using dev-master breaks the code

### ISSUE THREAD

**Issue by cagataygurturk** [abraham/twitteroauth#286]
Thanks for this library but I think you should be more responsible about version management. I had this library in the composer.json with dev-master because I thought that you were not using tagging system. (The last tag is from 2010)

Then today our deployment script updated composer dependencies, downloaded the last version (old dev branch) and broke all the software.

I think you should create a version with commit adf6a8ee92b0bac69cae7dded9743d5a7de0057e until everybody updates his code.

Thanks.

**Comment by abraham** [comment]
Master should not be considered stable and composer support has never been official. I have however added tag 0.2.1 to the specified commit.
