### ISSUE TITLE
Follow PSR-2 Guidelines

### ISSUE THREAD

**Issue by 0x46616c6b** [abraham/twitteroauth#287]
I would prefer to use the [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) Guidelines for Code Styles. What do you think?

**Comment by CodingMammoth** [comment]
I'm not liking this style:

    Code MUST use 4 spaces for indenting, not tabs.

Nope, 2 spaces is much nicer to read

```` quote
Opening braces for classes MUST go on the next line, and closing braces MUST go on the next line after the body.

Opening braces for methods MUST go on the next line, and closing braces MUST go on the next line after the body.
````
Nog liking this as well, I prefer

    function abc {
      ...
    }

Just me 2 cents ;)

**Comment by 0x46616c6b** [comment]
I think the argumentation of personal dislike the visual style is not purposeful. My motivation cames from integrate the lib in the Symfony Framework or some Web Application. All the main testing and linting tools following the PSR Guidlines. So I must not configure special code styles.

**Comment by abraham** [comment]
I do plan on switching to 4 spaces. I haven't looked at the rest of PSR-2 yet though.

**Comment by hussani** [comment]
+1

I agree with project following PSR-2.

**Comment by 0x46616c6b** [comment]
I would make a merge request for that, but not until your refactorings and api breaks are finished.

**Comment by abraham** [comment]
Do you having linting tools that you like?

**Comment by 0x46616c6b** [comment]
For the initial reformat of the code I would suggest [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer). When you use an IDE like PHPStorm you can simply configure your project to follow PSR-2 and reformat the code.

**Comment by phillipsnick** [comment]
+1

**Comment by abraham** [comment]
OAuth.php has now been split by classes. other than some needed camelCase updates the codebase should be pretty PSR-2 compliant now.

**Comment by abraham** [comment]
I'm considering PSR-2 compatibility done. Please open pull requests/issues for anything that was missed.
