### ISSUE TITLE
JSON_BIGINT_AS_STRING error with php 5.5.3

### ISSUE THREAD

**Issue by neoPix** [abraham/twitteroauth#288]
Updated the version with composer and got the following issue where JSON_BIGINT_AS_STRING isn't implemented properly:

json_decode(): option JSON_BIGINT_AS_STRING not implemented

I'm using php 5.5.3

**Comment by abraham** [comment]
> It looks like this was introduced to some Linux distributions due to LICENSE concerns and you are using an affected json-c PECL module.

> My suggestion would be to use an newer version of the module.

https://stackoverflow.com/questions/19520487/json-bigint-as-string-removed-in-php-5-5

I'll look at conditionally supporting JSON_BIGINT_AS_STRING as well though.

**Comment by neoPix** [comment]
Thanks for the quick answer :+1: .
The stackoverflow solution corrected it (Damn Ubuntu).
