### ISSUE TITLE
Google App Engine Support 

### ISSUE THREAD

**Issue by SumeetGohil** [abraham/twitteroauth#290]
GAE does not supports CURL.

**Comment by abraham** [comment]
In order to support GAE, (file_get_contents )[https://cloud.google.com/appengine/docs/php/urlfetch/] would have to be supported? Is that correct?

**Comment by SumeetGohil** [comment]
Yup

Facebook Latest API Supports That

function_exists('curl_init') ? new FacebookCurlHttpClient() : new FacebookStreamHttpClient();

**Comment by abraham** [comment]
GAE just announced cURL support so I'm going to close this.

https://groups.google.com/forum/#!msg/google-appengine/y6WX6EMnYO4/DlOIAzbYwbwJ
