### ISSUE TITLE
add uploadHost setter and getter

### ISSUE THREAD

**Issue by Whyounes** [abraham/twitteroauth#296]
THe setter and getter for $uploadHost is missing

**Comment by 0x46616c6b** [comment]
see #297

**Comment by abraham** [comment]
Why does it need a getter/setter?

**Comment by Whyounes** [comment]
I'm trying to use the package for 500pc api, but their seems to be no way to set the upload host, because obviously i need to change it :p

**Comment by Whyounes** [comment]
I think i will fork it and try to adapt it to the 500px API, i think the has all the functionality, i think the license allow that

**Comment by Whyounes** [comment]
Or you can make the fields `protected` so we can manipulate the class using inheritance!

**Comment by 0x46616c6b** [comment]
You should properly use the OAuth Implementation [from Google](https://oauth.googlecode.com/svn/code/php/OAuth.php). All the other stuff around you must implement seperatly.

**Comment by abraham** [comment]
I'd like TwitterOAuth to be specific to Twitter so I'm not supporting more generic features. Feel free to fork if you want though and there are a number of generic OAuth libraries listed on GitHub/Packagist.
