### ISSUE TITLE
Please add installation instructions without composer

### ISSUE THREAD

**Issue by jitbit** [abraham/twitteroauth#299]

**Comment by abraham** [comment]
Just curious but are there specific reasons you don't want to use composer?

**Comment by abraham** [comment]
I've added manual install instructions to http://twitteroauth.com/, keep in mind that there is not yet a release that supports it so downloading master will be required.

**Comment by jitbit** [comment]
Answering your question: I'm only an occasional PHP developer (mostly .NET, ObjC, Ruby) I don't know what "composer" is and I don't want to know. Just doing a 5-minute PHP project without any intention to dive into the PHP world deeps. THANKS!
