### ISSUE TITLE
Fatal error: Class 'TwitterOAuth' not found in

### ISSUE THREAD

**Issue by Dalharukn** [abraham/twitteroauth#300]
Hi,

I'm getting this error when i tried load the TwitterOAuth on my webserver. The require_once path was correct because the path is loaded correct but the class doesn't.

My config:

get-tweets.php >

```
<?php
# Load Twitter class
require_once('TwitterOAuth/TwitterOAuth.php');

# Define constants
define('TWEET_LIMIT', 5);
define('TWITTER_USERNAME', '****');
define('CONSUMER_KEY', '****');
define('CONSUMER_SECRET', '****');
define('ACCESS_TOKEN', '****');
define('ACCESS_TOKEN_SECRET', '****');

# Create the connection
THIS FILE FAIL --> $twitter = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);

# Migrate over to SSL/TLS
$twitter->ssl_verifypeer = true;

# Load the Tweets
$tweets = $twitter->get('statuses/user_timeline', array('screen_name' => TWITTER_USERNAME, 'exclude_replies' => 'true', 'include_rts' => 'false', 'count' => TWEET_LIMIT));

# Example output
if(!empty($tweets)) {
    foreach($tweets as $tweet) {

        # Access as an object
        $tweetText = $tweet['text'];

        # Make links active
        $tweetText = preg_replace("#(http://|(www.))(([^s<]{4,68})[^s<]*)#", '<a href="http://$2$3" target="_blank">$1$2$4</a>', $tweetText);

        # Linkify user mentions
        $tweetText = preg_replace("/@(w+)/", '<a href="http://www.twitter.com/$1" target="_blank">@$1</a>', $tweetText);

        # Linkify tags
        $tweetText = preg_replace("/#(w+)/", '<a href="http://search.twitter.com/search?q=$1" target="_blank">#$1</a>', $tweetText);

        # Output
        echo $tweetText;

    }
}
?>
```

File dir:

****************
Functions
----get-tweets.php
----TwitterOAuth
------TwitterOAuth.php
********************

Thanks in advance. Bye.

**Comment by 0x46616c6b** [comment]
The problem is that you don't use an autoloader. Use Composer ans include the autoload.php from the vendors directory. Times when you include all your dependencies in all files is over!

**Comment by Dalharukn** [comment]
I never user composer, I don't know how works. Any guide?

**Comment by abraham** [comment]
Composer is easy to get started with https://getcomposer.org/doc/00-intro.md

**Comment by abraham** [comment]
Actually the immediate problem is probably that you are not using the proper namespace.

```
<?php
require_once('TwitterOAuth/TwitterOAuth.php');
use Abraham\TwitterOAuth\TwitterOAuth;
...
$twitter = new TwitterOAuth(...);
```

However that does not autoload the other half-dozen classes that will also need to be loaded.

**Comment by abraham** [comment]
I've added some instructions for manual installs: http://twitteroauth.com/

**Comment by Dalharukn** [comment]
Thanks abraham, I appreciate your work and your response.

**Comment by Arsintorabi** [comment]
hi i cant  use this..get this error 215 👍 
 $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $this->T_ACCESS_TOKEN, $this->T_ACCESS_TOKEN_SECRET);
		   $connection->host = 'https://api.twitter.com/1.1/';
		   $connection->content_type = 'application/x-www-form-urlencoded';
		   $connection->ssl_verifypeer = TRUE;

**Comment by abraham** [comment]
Please create new issues instead of commenting on unrelated old ones.
