### ISSUE TITLE
How to send Tweets with the Library

### ISSUE THREAD

**Issue by fbownz** [abraham/twitteroauth#307]
I know this might be a noob question but, am fairly new to PHP and I needed some guidance on how I could send a tweet with the library.
I have been able to implement login with the library, now I wanted to know if there is some guidelines on how I can send tweets out through the logged in users accounts.

**Comment by abraham** [comment]
There is a short example under the POST section on https://twitteroauth.com/.

    $statues = $connection->post("statuses/update", array("status" => "hello world"));

**Comment by fbownz** [comment]
Thanks Abraham,
I didn't see that

Emali Morgan
Team Leader Webonmobi.com
Physical Address: AAYMCA Building 2nd Floor, State House Cresent, Nairobi
Mobile: 0719510136
Website: www.webonmobi.com
Blog: ww.webonmobi.com/blog
Facebook: Facebook.com/webonmobi
Twitter: twitter.com/webonmobiseo
Internet Marketing, Website Development
