### ISSUE TITLE
Call to undefined method Abraham\TwitterOAuth\TwitterOAuth::getRequestToken()

### ISSUE THREAD

**Issue by geolyth** [abraham/twitteroauth#308]
<pre>
require "twitteroauth/autoloader.php";
use Abraham\TwitterOAuth\TwitterOAuth;
</pre>
<pre>
$connection = new TwitterOAuth(TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET);
	$request_token = $connection->getRequestToken(TWITTER_OAUTH_CALLBACK);
	$_SESSION['oauth_token'] = $token = $request_token['oauth_token'];
	$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
	switch ($connection->http_code) {
		case 200:
			$url = $connection->getAuthorizeURL($token);
			break;
		default:
			$error = 'Could not connect to Twitter. Refresh the page or try again later.';
	}
</pre>

**Comment by abraham** [comment]
Follow the new [documentation](https://twitteroauth.com/redirect.php).
