### ISSUE TITLE
 Fatal error: Class 'TwitterOAuth' not found

### ISSUE THREAD

**Issue by PHPism** [abraham/twitteroauth#309]
I understand that Twitter API v1 isn't working right now, but it replies to me with user screen name and user id which are enough for my script to authorize the user login.
I'm trying to use both of your TwitterOAuth for php 5.2 and 5.4 versions.
I made something like (First Code):
```
$php_version = phpversion();
if($php_version >= 5.4)
{
	require($config['basedir']."/twitteroauth/autoload.php");
	use Abraham\TwitterOAuth\TwitterOAuth;
}
else
{
	require($config['basedir']."/twitteroauth/twitteroauth_v1.php"); 
}
```

But due to restriction of php < 5.4, I had to change it to (Second Code)
```
$php_version = phpversion();
if($php_version >= 5.4)
{
	include_once($config['basedir']."/twitteroauth/autoload_include.php");
}
else
{
	require($config['basedir']."/twitteroauth/twitteroauth_v1.php"); 
}
```

And in autoload_include.php

```
require($config['basedir']."/twitteroauth/autoload.php");
use Abraham\TwitterOAuth\TwitterOAuth;
```

But every time I try to start the connection, it gives me error: Fatal error: Class 'TwitterOAuth' not found
```
$tw_connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
```
I tried almost everything. Using include and using require and include_once and require_once. Nothing works. Even I tried the first code and it gave me error:  syntax error, unexpected 'use' (T_USE) 
The only way so that it works again. Is by replacing the first or the second code with:

```
$php_version = phpversion();
require($config['basedir']."/twitteroauth/autoload.php");
use Abraham\TwitterOAuth\TwitterOAuth;
```

Note: I perfectly understand that the differances between your classes versions. I already made something like the following code to ensure that my script will use the correct code according to imported class:

```
if($php_version >= 5.4)
{
	$request_token = $tw_connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
}
else
{
	$request_token = $tw_connection->getRequestToken(OAUTH_CALLBACK);
}
```

It's working absolutely fine on php5.2 and php5.3 but the issue started when I tried to use the new OAuthorize.
Thanks for your time.
Waiting your reply.
Best Regards

**Comment by abraham** [comment]
My recommendation is stop using/supporting non-supported versions of PHP. 5.2 hasn't gotten security updates since 2011 and 5.3 hasn't gotten security updates in a year. Continuing to use them is just going to get you hacked.

That said I think `use` only works in the file it's in. Something like this would probably work:

```
$php_version = phpversion();
if($php_version >= 5.4)
{
    require($config['basedir']."/twitteroauth/autoload.php");
}
else
{
    require($config['basedir']."/twitteroauth/twitteroauth_v1.php"); 
}

if($php_version >= 5.4)
{
    $tw_connection = new Abraham\TwitterOAuth\TwitterOAuth(...);
}
else
{
...
}
```
