### ISSUE TITLE
class TwitterOAuth not found.

### ISSUE THREAD

**Issue by gc1e12** [abraham/twitteroauth#310]
I'm using the tutorial below along with your twitteroauth folder, which i downloaded from github. 
https://www.youtube.com/watch?v=iPnGB7a7dO0 

However, when I tried running the index.php, the following error occurs:
Fatal error: Class 'TwitterOAuth' not found in /var/webhomes/gc1e12/linuxproj_html/test/index.php ...

I am pretty sure that it is not because of the require/require_once. 
require('twitteroauth-master/src/TwitterOAuth.php');

**Comment by gc1e12** [comment]
Attached is my file structure, and the php require/require_once used in index php is as followed.
 ------>require('twitteroauth-master/src/TwitterOAuth.php');

![project file structure](https://cloud.githubusercontent.com/assets/5602657/6141019/73ce5084-b197-11e4-9e94-1a7462e37d6e.jpg)

**Comment by abraham** [comment]
If you look at the [manual install](https://twitteroauth.com/) section you will see that you need require the `autoload.php` file. In your case:

```
require "twitteroauth-master/autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;
```

As a side note you should avoid using master and instead download the latest [release](https://github.com/abraham/twitteroauth/releases)

**Comment by gc1e12** [comment]
Thank you
