### ISSUE TITLE
Environment variable HTTPS_PROXY set cause wrong response

### ISSUE THREAD

**Issue by HongKilDong** [abraham/twitteroauth#311]
CURL employs proxy auto-discovery by means of HTTPS_PROXY environment variable, so HTTPS_PROXY set, provided TwitterOAuth::$proxy value isn't set, cause unexpected presence of headers in response body.

Would be good to provide HTTPS_PROXY checking (line 319) but this will fail where getenv function is disabled
```
private function request($url, $method, $headers, $postfields)
    {
        ...
        if (empty($this->proxy) && !getenv('HTTPS_PROXY')) {
        ...                     ^^^^^^^^^^^^^^^^^^^^^^^^        
    }
```

**Comment by abraham** [comment]
Where is the HTTPS_PROXY auto-discovery documented?

**Comment by HongKilDong** [comment]
Its a convention. Most UNIX tools respect the HTTP_PROXY environment variable, curl included.

**Comment by abraham** [comment]
It's an undocumented convention? There must be references out there somewhere.

**Comment by HongKilDong** [comment]
http://curl.haxx.se/mail/lib-2014-09/0095.html )

**Comment by abraham** [comment]
This should just handle the response regardless of if it's proxied or not.
