### ISSUE TITLE
Use of undefined constant CURLOPT_CAINFO

### ISSUE THREAD

**Issue by gc1e12** [abraham/twitteroauth#312]
Thank you. I followed the documentation on "https://twitteroauth.com/". However, there seems to be errors when I tried calling this line.

--> $content = $connection->get("account/verify_credentials");

![index php shot](https://cloud.githubusercontent.com/assets/5602657/6168405/0346d94a-b2bd-11e4-8541-11c0e0ed9d97.jpg)

**Comment by gc1e12** [comment]
These are the errors caused by line 12, and I could not make sense out of it.
![error](https://cloud.githubusercontent.com/assets/5602657/6168465/68497cf8-b2bd-11e4-974c-3f23a9046876.jpg)

**Comment by HongKilDong** [comment]
It seems you don't have curl module installed
http://php.net/manual/en/curl.installation.php

**Comment by abraham** [comment]
Yep. cURL is required.
