### ISSUE TITLE
Weird follower count bug

### ISSUE THREAD

**Issue by Aljessy** [abraham/twitteroauth#317]
Hello i'm trying to use the result of this issue <code>https://github.com/abraham/twitteroauth/issues/252</code>

But i have this fatal error <code> Fatal error: Cannot use object of type stdClass as array</code>

Please how can i solve this problem

**Comment by abraham** [comment]
That's a basic PHP error that is unrelated to TwitterOAuth. A quick Google search yields many possible solutions to explore such as https://stackoverflow.com/questions/5412924/fatal-error-cannot-use-object-of-type-stdclass-as-array-in

**Comment by Aljessy** [comment]
Please help me to solve it, because i don't know how to did it. I wrote this line code <code>$twitter_api = new TwitterOAuth($twitter_consumer_key, $twitter_consumer_secret, $twitter_access_token, $twitter_access_token_secret);
	$twitter_api_link = $twitter_api->get('users/users' , array ('screen_name'=>($twitter_id)));
	$twitter_count = $twitter_api_link[0]->followers_count;</code>
and the error occur on this line <code>$twitter_count = $twitter_api_link[0]->followers_count;</code>

**Comment by Aljessy** [comment]
When i do <code>echo $twitter_api->http_code;</code> the result is 401. It means that i have another problem. I already fix the fatal error bug.

How can i solve this?

**Comment by abraham** [comment]
401 is an authentication error meaning your access tokens is not valid.

**Comment by Aljessy** [comment]
Thanks for your help, i solve my problem
