### ISSUE TITLE
Update mediawiki extension

### ISSUE THREAD

**Issue by paladox** [abraham/twitteroauth#318]
Hi could you update the mediawiki extension to use these new source code please.

**Comment by abraham** [comment]
Any mediawiki extensions are not maintained by me. You should contact the author of the extension.

**Comment by paladox** [comment]
Oh ok. how can I upgrade to your new code the other code was based on your without any changed ecept it is based in a sub folder. https://git.wikimedia.org/summary/mediawiki%2Fextensions%2FTwitterLogin

**Comment by paladox** [comment]
I doint think it is maintained by original author now.
