### ISSUE TITLE
'incorrect signature' while updating status due to wrong encoding in library

### ISSUE THREAD

**Issue by Balauue** [abraham/twitteroauth#32]
While using your latest library version, i expire the following issue while sending a tweet like this:
<code>
$tweet = "http://bit.ly/123456  Content with Umlaut Ö abc";

$response = $connection->post('statuses/update', array('status' => $tweet, 'in_reply_to_status_id' => ''));		
</code>
$response is:

<pre>stdClass Object
(
    [request] => /1/statuses/update.json
    [error] => Incorrect signature
)</pre>

When i urlencode the whole tweet, it will send without problems, but then the tweet is shown up urlencoded at twitter. So i guess there is an encoding problem in the library. 

The Tweet above is a generated tweet wich is utf-8 encoded.

FYI: The signature and all my tokens are correct!

I assume the german "umlauts" like "ä ö ü ß" are the problem. when i replace "ö" with "oe" everything works fine.  But these Signs should not throw this error, they are utf8 encoded.

**Comment by abraham** [comment]
Unable to reproduce in current codebase.
