### ISSUE TITLE
code is stop after getAccessToken()

### ISSUE THREAD

**Issue by fushang** [abraham/twitteroauth#320]
hi
im using this lib to my customer, in local it work fine.
but when i send it to my customer, redirect page not work, just show response of twitter:
`oauth_token=L80FnyWgtFapMLEWu3bid5LS8btsOvR0&oauth_token_secret=JvMCdW25YOBoVLs5VaHDtwrEc9CpVqM7&oauth_callback_confirmed=true`
i checked in my code but can not see any unexpected.
this is my code (i think it stop before go to switch):

```
/* Build TwitterOAuth object with client credentials. */
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
 
/* Get temporary credentials. */
$request_token = $connection->getRequestToken(OAUTH_CALLBACK);

/* Save temporary credentials to session. */
$_SESSION['oauth_token'] = $token = $request_token['oauth_token'];
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
 
/* If last connection failed don't display authorization link. */
switch ($connection->http_code) {
  case 200:
    /* Build authorize URL and redirect user to Twitter. */
    $url = $connection->getAuthorizeURL($token);
    header('Location: ' . $url); 
    break;
  default:
    /* Show notification if something went wrong. */
    echo 'Could not connect to Twitter. Refresh the page or try again later.';
}
```

pls help

**Comment by abraham** [comment]
Is that the the entire redirect.php page?

**Comment by fushang** [comment]
all in this file here:
<?php
$currentCookieParams = array('lifetime' => 0, 'path' => '/', 'domain' =>'', 'secure' =>'', 'httponly' =>'');
session_set_cookie_params(
                $currentCookieParams["lifetime"],
                $currentCookieParams["path"],
                $currentCookieParams["domain"],
                $currentCookieParams["secure"],
                true
            );
session_name('osclass');
/* Start session and load library. */
if(!isset($_SESSION)){
    session_start();
}
require_once('oc-includes/twitteroauth/twitteroauth.php');
require_once('oc-includes/twitteroauth/config.php');

/* Build TwitterOAuth object with client credentials. */
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
 
/* Get temporary credentials. */
$request_token = $connection->getRequestToken(OAUTH_CALLBACK);

/* Save temporary credentials to session. */
$_SESSION['oauth_token'] = $token = $request_token['oauth_token'];
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
 
/* If last connection failed don't display authorization link. */
switch ($connection->http_code) {
  case 200:
    /* Build authorize URL and redirect user to Twitter. */
    $url = $connection->getAuthorizeURL($token);
    header('Location: ' . $url); 
    break;
  default:
    /* Show notification if something went wrong. */
    echo 'Could not connect to Twitter. Refresh the page or try again later.';
}
and it run fine in my local

**Comment by abraham** [comment]
You said the problem is after `getAccessToken` but all the code you have here is way before `getAccessToken` ever gets called.

**Comment by abraham** [comment]
As a side note `getAccessToken` is from an older version of TwitterOAuth and you should consider upgrading to the latest version.

**Comment by fushang** [comment]
Thank for reply, i found that the problem is from getAccessToken function, there is one "echo" so the script can not be use header function after that.
