### ISSUE TITLE
Call to undefined method Abraham\TwitterOAuth\TwitterOAuth::getRequestToken()

### ISSUE THREAD

**Issue by nallankraj** [abraham/twitteroauth#321]
We are using our Own MVC structure. I am unable to implement 'twitteroauth-0.5.1' for our site. Please find the error below.

PHP Fatal error:  Call to undefined method Abraham\TwitterOAuth\TwitterOAuth::getRequestToken()

Please let me know the solution for the same.

**Comment by abraham** [comment]
That method has been replaced with the `oauth` method. Please read through the sign in flow for the current method names. Https://twitteroauth.com

**Comment by SavasSimsek** [comment]
Shalom Abraham.I have an error "Fatal error: Call to undefined method TwitterOAuth::getAutorizeURL() in /home/..../public_html/.../redirect.php on line 18"


my redirect.php code is;


<?php
session_start();

require 'TwitterOAuth/TwitterOAuth.php';
require 'config.php';


$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);

$request_token = $connection->getRequestToken(OAUTH_CALLBACK);

$token = $request_token['oauth_token'];
$_SESSION['oauth_token'] = $token ;
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];

switch($connection->http_code) {
	case 200:
	     $url = $connection->getAutorizeURL($token);
         header('Location:' . $url);
         break;
	default:
	     echo "someting wrong check this http code" . $connection->http_code;

}


?>

How can i solve...Thank you

**Comment by abraham** [comment]
Read my above comment.

**Comment by SavasSimsek** [comment]
Ok..Thank You.
