### ISSUE TITLE
Redirection to a URL

### ISSUE THREAD

**Issue by dorcu** [abraham/twitteroauth#322]
Hi very good,

I would like to know how can I make the login with the Twitter API redirect me to the last URL where I've been.

Can you do this?

Thank You

**Comment by abraham** [comment]
With `oauth_callback` on https://twitteroauth.com/redirect.php

**Comment by dorcu** [comment]
But my login button is on every page, so that I'd like to login automatically return to the page you were viewing the users.

regards,

**Comment by abraham** [comment]
When a user clicks on the signin button and goes to redirect.php you could include a query parameter that includes the path to return to after auth. Store it in the session and in callback.php send them back if the value is set.
