### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by Jonadabe** [abraham/twitteroauth#323]
How to implement this with language support?

**Comment by abraham** [comment]
What do you mean with language support?

**Comment by Jonadabe** [comment]
I mean using the languages (not only in english): https://api.twitter.com/1.1/help/languages.json
I don't know if I'm saying anything wrong...

Thanks for your quick answer.

**Comment by abraham** [comment]
This works fine for me.

```
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret]);
$langs = $connection->get("help/languages");
```

You need to be specific about what you are trying to do, how you are trying to do it, and what is going wrong.

**Comment by Jonadabe** [comment]
Thank you again! You are right.
