### ISSUE TITLE
Problem with oauth

### ISSUE THREAD

**Issue by GlenCarlier** [abraham/twitteroauth#328]
So I recently tried to move my website from a local environment online.
I updated the twitter url and callback url (so the problem shouldnt be there).

I followed the "sign in with twitter example" and I pinpointed the problem to:
$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));

There is no error and the page just stops loading after that line.
I investiged the oauth function and it seems that here lies the problem:
$result = $this->oAuthRequest($url, 'POST', $parameters);

I tried everything I could think of and the only difference between my local environment and the online one is that local I use PHP 5.4 and online 5.5.9-1ubuntu4.7.
Could the problem lie there?

Also once I remove the oauth line and just fill in a oauth token from twitter (wich expires after a few minutes) it works (as in the page loads and once I click the button it refers me to twitter).

Any help appreciated!

**Comment by abraham** [comment]
There has to be some sort of error. What does your servers logs say?

**Comment by GlenCarlier** [comment]
Thats the problem, im getting no errors and my logs only show one thing: when I forgot to update the database user/password (not relevant) and I already fixed.

**Comment by abraham** [comment]
Make sure to enable all errors: http://stackoverflow.com/a/21429652/26406

**Comment by GlenCarlier** [comment]
Okay now it displays these errors:
```
Notice: Use of undefined constant CURLOPT_CAINFO - assumed 'CURLOPT_CAINFO' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 270

Notice: Use of undefined constant CURLOPT_CAPATH - assumed 'CURLOPT_CAPATH' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 271

Notice: Use of undefined constant CURLOPT_CONNECTTIMEOUT - assumed 'CURLOPT_CONNECTTIMEOUT' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 272

Notice: Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 273

Notice: Use of undefined constant CURLOPT_HTTPHEADER - assumed 'CURLOPT_HTTPHEADER' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 274

Notice: Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 275

Notice: Use of undefined constant CURLOPT_SSL_VERIFYHOST - assumed 'CURLOPT_SSL_VERIFYHOST' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 276

Notice: Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 277

Notice: Use of undefined constant CURLOPT_TIMEOUT - assumed 'CURLOPT_TIMEOUT' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 278

Notice: Use of undefined constant CURLOPT_URL - assumed 'CURLOPT_URL' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 279

Notice: Use of undefined constant CURLOPT_USERAGENT - assumed 'CURLOPT_USERAGENT' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 280

Notice: Use of undefined constant CURLOPT_ENCODING - assumed 'CURLOPT_ENCODING' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 281

Notice: Use of undefined constant CURLOPT_POST - assumed 'CURLOPT_POST' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 299

Notice: Use of undefined constant CURLOPT_POSTFIELDS - assumed 'CURLOPT_POSTFIELDS' in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 300

Fatal error: Call to undefined function Abraham\TwitterOAuth\curl_init() in /var/www/html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 304
```

**Comment by abraham** [comment]
You need to install curl. http://php.net/manual/en/book.curl.php

**Comment by GlenCarlier** [comment]
I already have curl installed.

I used this:
sudo apt-get install php5-curl

And restarted with this:
sudo service apache2 restart

**Comment by abraham** [comment]
If you are getting `Bad Authentication data` for `oauth/request_token` than the consumer key/secret probably isn't set properly.

**Comment by GlenCarlier** [comment]
Ok even though when I ran 
sudo apt-get install php5-curl
And It said it was already installed, for some reason it wasnt using it because now everything works.

Thanks for your fast and helpfull answers!

**Comment by TOMITA-git** [comment]
maybe your php version is 7.x.x. In that version, there is the magical command. Try it out!
sudo apt-get install php-curl.
I hope it will be going on...

**Comment by Aartitops** [comment]
Hi,
I using PHP Version 5.6.8 but it is not working.
It is showing error like :- 
 Notice: Use of undefined constant CUsRLOPT_POSTFIELDS - assumed 'CUsRLOPT_POSTFIELDS' in D:\xampp\htdocs\magento02\api.php on line 7

Warning: curl_setopt() expects parameter 2 to be long, string given in D:\xampp\htdocs\magento02\api.php on line 7

Catchable fatal error: Object of class stdClass could not be converted to string in D:\xampp\htdocs\magento02\api.php on line 16

Can you give me please suggestion for this
Thanks.

**Comment by Aartitops** [comment]
Hi,
I want to use api in magento2 and I using PHP Version 5.6.8 but it is not working.
It is showing error like :- 
Notice: Use of undefined constant CUsRLOPT_POSTFIELDS - assumed 'CUsRLOPT_POSTFIELDS' in D:\xampp\htdocs\magento02\api.php on line 7

Warning: curl_setopt() expects parameter 2 to be long, string given in D:\xampp\htdocs\magento02\api.php on line 7

Catchable fatal error: Object of class stdClass could not be converted to string in D:\xampp\htdocs\magento02\api.php on line 16

Can you give me please suggestion for this
Thanks
