### ISSUE TITLE
How to check if a user follow another user

### ISSUE THREAD

**Issue by d0rcu222** [abraham/twitteroauth#329]
Hello,

I wonder how I can get if the "A" user is following the user "B".

I've tried this but it gives me error:

<code>
$tipo_5 = $connection->get('friendships/show', array('source_screen_name' => 'UserA', 'target_screen_name' => 'UserB'));
        //print_r($tipo_5);

        for($o=0;$o<count($tipo_5);$o++){
          $etr = $tipo_5[$o]->relationship->source->screen_name;
          echo $etr.'<br><br>';
        }
</code>

I think it must be an error parsing the code.

**Comment by abraham** [comment]
Issues like this that say there is an error but don't include the error are pretty much a waste of time. That being said if you look at the example result for [GET friendships/show](https://dev.twitter.com/rest/reference/get/friendships/show), the result is not an array so why are you using a for loop?

**Comment by d0rcu222** [comment]
I'm sorry.

It was loop problem. And works well.

regards,
