### ISSUE TITLE
cURL 51 error "CURLE_PEER_FAILED_VERIFICATION" 

### ISSUE THREAD

**Issue by MozMorris** [abraham/twitteroauth#330]
"The remote servers SSL certificate or SSH md5 fingerprint failed validation"

I'm having trouble with the included certificate bundle.

OS X 10.10.2
Homebrew PHP 5.6.6
System cURL 7.37.1
Twitteroauth 0.5.2

    Type: Abraham\TwitterOAuth\TwitterOAuthException
    Message: The remote servers SSL certificate or SSH md5 fingerprint failed validation.
    File: /Users/Moz/Sites/removed/vendor/abraham/twitteroauth/src/TwitterOAuth.php
    Line: 313

Commenting out lines 270-271 in `TwitterOAuth.php` is a temp fix for me.

    CURLOPT_CAINFO => __DIR__ . DIRECTORY_SEPARATOR . 'cacert.pem',
    CURLOPT_CAPATH => __DIR__,

**Comment by abraham** [comment]
v0.5.3 has been released with an updated cacert.pem that should fix the problem.

**Comment by MozMorris** [comment]
Thanks for the quick response @abraham. Did you test it? The update still fails for me.

**Comment by abraham** [comment]
No issues for me but I never reproduced the issue to begin with. If you trust the OS installed public certs you can stick with those.

Was the code working fine and then suddenly stopped working? Or are you just starting to use this environment and it's been like this from the start?

Are you in some sort of corporate intranet that has an HTTPS proxy to the outside world?

**Comment by MozMorris** [comment]
Okay cool, sorry I thought this might have been a common problem hence the certs update.

It's a fresh install, no proxy.

I've used the library before, the project is still in production and looks like it's working fine. I'm guessing  therefore it's platform/curl version specific.

**Comment by abraham** [comment]
The list of public certs needs to be updated once in a while as certificate authorities rotate through new certs. I had assumed that's what your error was and that updating it would fix it.

Generally that error means that the TLS certificate curl is getting is not trusted by the list of public certs packaged with TwitterOAuth. This means that an application or service is intercepting connections between you and Twitter. The most common causes would be Charles Proxy (or equivalent) and corporate compliance proxy. There is however always the chance that someone is maliciously MITM'ing your connections to api.twitter.com.
