### ISSUE TITLE
Syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING on line 3

### ISSUE THREAD

**Issue by ctjl96** [abraham/twitteroauth#334]
```php
<?php
require "twitteroauth/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$content = $connection->get("account/verify_credentials");
?>
```
What gives?

**Comment by abraham** [comment]
What version of PHP are you using?

**Comment by abraham** [comment]
And don't forget to define the four values getting passed to `TwitterOAuth`.

**Comment by abraham** [comment]
I believe this is caused by `use Abraham\TwitterOAuth\TwitterOAuth;` in PHP 5.2. PHP has not been getting security updates since 2011, you should update your version of PHP.
