### ISSUE TITLE
Trying to fix "Sorry, that page does not exist" error

### ISSUE THREAD

**Issue by KingZing** [abraham/twitteroauth#335]
Hi guys,

```
stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [message] => Sorry, that page does not exist [code] => 34 ) ) )
```
My code is here:

![capture2](https://cloud.githubusercontent.com/assets/11875232/7073269/322fbf02-deea-11e4-8929-4fa5cd0d79cc.JPG)

As you can see I'm trying to get a search request to work, but I get the error shown here:

![capture](https://cloud.githubusercontent.com/assets/11875232/7073230/d8fe0e34-dee9-11e4-92c5-84aa5acee607.JPG)

I'm trying a lot of things but can't get passed this error, I've also tried searching online and as some of the topics are old, the fixes are no longer applicable. Is there anything I'm doing wrong?

**Comment by abraham** [comment]
You should not be using a full URL with TwitterOAuth. See GET on https://twitteroauth.com/ for an example TwitterOAuth request.

**Comment by KingZing** [comment]
Thank you for your reply, I have read that documentation, and have updated my code but the same error happens. 

My new code is as this:

![capture2](https://cloud.githubusercontent.com/assets/11875232/7075339/0fbd2694-def9-11e4-90d5-1f966933b9e5.JPG)

**Comment by abraham** [comment]
Please just copy/paste the code code instead of using screenshots. Are you using the latest release of TwitterOAuth?

**Comment by KingZing** [comment]
Okay, from now n I will post my code via that method. Yes I am using the latest version of TwitterOAuth, I just can't seem to get round this problem.

**Comment by abraham** [comment]
Maybe you need to restart the server? The [TwitterOAuthTest.php](https://github.com/abraham/twitteroauth/blob/master/tests/TwitterOAuthTest.php#L153) is using the exact same syntax and it's working fine.

**Comment by KingZing** [comment]
I have restarted my server and tripled checked all the code, I just get the same error.

**Comment by abraham** [comment]
I just ran the exact same code that is in your screenshot and it worked fine. My assumption is you are somehow not executing the PHP code you think you are.

**Comment by abraham** [comment]
Can't reproduce.
