### ISSUE TITLE
Using <input type="file" name="img1" required/> with update with media

### ISSUE THREAD

**Issue by tatters1979** [abraham/twitteroauth#340]
Hi,

Thanks for the library, I'm using the update status with media code below and it's working great. 

I'm trying to let users upload from their computers, phones, etc so I need to use the images they select with the following inputs from a form in the '/path/to/file/kitten1&2.jpg' part of the code. But I'm having no luck?

    <input type="file" name="img1" required/>
    <input type="file" name="img2" required/>

      $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
      $media1 = $connection->upload('media/upload', array('media' => '/path/to/file/kitten1.jpg'));
      $media2 = $connection->upload('media/upload', array('media' => '/path/to/file/kitten2.jpg'));
      $parameters = array(
       'status' => 'Meow Meow Meow',
       'media_ids' => implode(',', array($media1->media_id_string, $media2->media_id_string)),
      );
      $result = $connection->post('statuses/update', $parameters);

**Comment by abraham** [comment]
You'll probably want the `$_FILES['img1']['tmp_name']` value. 

https://php.net/manual/en/features.file-upload.post-method.php

**Comment by tatters1979** [comment]
Nice one, it worked. Thanks again.
