### ISSUE TITLE
Use clear error message on timeout

### ISSUE THREAD

**Issue by uzanpower** [abraham/twitteroauth#341]
Why Me always get this error ?

```
[12-Apr-2015 23:38:35 UTC] PHP Fatal error:  Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' in /home/xxx/public_html/twitteroauth/src/TwitterOAuth.php:141
Stack trace:
#0 /home/xxx/public_html/view/callback.php(23): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/access_to...', Array)
#1 /home/xxx/public_html/page.php(24): require_once('/home/xxx/...')
#2 {main}
  thrown in /home/xxx/public_html/twitteroauth/src/TwitterOAuth.php on line 141
```

**Comment by abraham** [comment]
What is the exception message?

**Comment by uzanpower** [comment]
No Message , Only get this Error

**Comment by abraham** [comment]
Catch the error and see what the message it.

```
try {
    // Your line that is throwing the exception
    $access_token = $connection->oauth("oauth/access_token", ...);
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}
```

**Comment by uzanpower** [comment]
but... , i dont know how this error show

**Comment by nguyentienlong** [comment]
Try to turn php error_reporting  on

// Report all PHP errors (see changelog)
error_reporting(E_ALL);

http://php.net/manual/en/function.error-reporting.php

On Sun, Apr 19, 2015 at 2:13 PM, uzanpower <notifications@github.com> wrote:

> but... , i dont know how this error show
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abraham/twitteroauth/issues/341#issuecomment-94247699>
> .
>



-- 
Long Nguyen
www.longka.info
0163 88 666 27

**Comment by uzanpower** [comment]
No no , my PHP is always on error_reporting , in this case , i don't know how this error show, and then error show , this error no have message

**Comment by abraham** [comment]
Show the error like in my try/catch example.

**Comment by uzanpower** [comment]
ok will try , but i dont know how this error show :'( , sry for problem

**Comment by uzanpower** [comment]
ok , I've tried it , and result is empty , no message

**Comment by abraham** [comment]
Please post your code.

**Comment by uzanpower** [comment]
This is my original code, but previous , my code don't use try/catch , but no only this code , 
```
<?php
session_start();
require_once('config.php');
require_once(__DIR__.'/../twitteroauth/autoload.php');
use Abraham\TwitterOAuth\TwitterOAuth;

define('CONSUMER_KEY', 'xxx');
define('CONSUMER_SECRET', 'xxx');

$url = explode("oauth_token=", $_SERVER['REQUEST_URI']);
$url = explode("&oauth_verifier=",(empty($url[1]) ? '' : $url[1]));
$token = (empty($url[0]) ? '' : $url[0]);
$verifier = (empty($url[1]) ? '' : $url[1]);

if (strpos($_SERVER['REQUEST_URI'], "denied") !== false || empty($token) || empty($verifier) || $_SESSION['oauth_token'] !== $token) {
  $_SESSION['msg'] = TRUE;
  $_SESSION['error'] = 'Something Wrong';
  header('Location: /login.html');
  exit();
}

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $_SESSION['oauth_token'], $_SESSION['oauth_token_secret']);
try {
  $access_token = $connection->oauth("oauth/access_token", array("oauth_verifier" => $verifier));
} catch (Exception $e) {
  echo 'Caught exception: ',  $e->getMessage(), "\n";
}
if($access_token['user_id']) {
  $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token['oauth_token'], $access_token['oauth_token_secret']);
  $user = $connection->get("account/verify_credentials");
  $id    = $user->id;
  $name  = $user->name;
}

$sth = $conn->prepare("SELECT * FROM xxx WHERE xxx = '$id'");
$sth->execute();

if($sth->rowCount() > 0){
  $_SESSION['username'] = $id;
  $_SESSION['name'] = $name;
} else {
  $_SESSION['msg'] = TRUE;
  $_SESSION['error'] = 'Please check your Account, Use Valid Account or Use Registered Account';
}

$link = (isset($_SESSION['redir']) ? $_SESSION['redir'] : '/index.html');
header("location: $link");
?>
```

**Comment by abraham** [comment]
That code works fine for me other than `$conn` not being defined for database work. Make sure you have properly set the `CONSUMER_KEY` and `CONSUMER_SECRET` and then check again that they accurately match what's on apps.twitter.com.

**Comment by abraham** [comment]
BTW this code is going to be fragile and will easily break.

```
$url = explode("oauth_token=", $_SERVER['REQUEST_URI']);
$url = explode("&oauth_verifier=",(empty($url[1]) ? '' : $url[1]));
$token = (empty($url[0]) ? '' : $url[0]);
$verifier = (empty($url[1]) ? '' : $url[1]);
```
You should use something like this:

```
$token = $_REQUEST['oauth_token'];
$verifier = $_REQUEST['oauth_verifier'];
```

**Comment by uzanpower** [comment]
ok, this code run normally and my CS,CK same with my apps, but i dont know this error always show 

BTW :
my website using URL Clean , $_REQUEST don't catch get data

**Comment by abraham** [comment]
Add `var_dump($responseHeader, $responseBody);` right before `return $responseBody;` in the `request` function in TwitterOAuth.php and post the result here.

**Comment by uzanpower** [comment]
this result is NULL , no data return

**Comment by abraham** [comment]
Please post info about the OS/version and PHP/version you are running in.

**Comment by uzanpower** [comment]
OS : limited for me , (used shared hosting)
PHP : PHP 5.4.39
Library : TwitterOAuth 0.5.3

But i have same problem in issues #353 , i found this error in my localhost
Spec of my localhost
OS : Windows 7
PHP : PHP 5.6 
Library : TwitterOAuth 0.5.3

**Comment by abraham** [comment]
Which shared hosting provider? You get the same issue locally and on shared hosting?

**Comment by uzanpower** [comment]
yes, same issue

**Comment by lshaf** [comment]
try to change
```
} catch (Exception $e) {
```
to
```
} catch (\Abraham\TwitterOAuth\TwitterOAuthException $e) {
```
if there's still no output of error, please open TwitterOAuth.php inside folder 'src' then please go to line `135` and I am sure you will see `if ($this->getLastHttpCode() == 200) {` then, change this code
```
if ($this->getLastHttpCode() == 200) {
    parse_str($result, $response);
    $this->response->setBody($response);
    return $response;
} else {
    throw new TwitterOAuthException($result);
}
```
to
```
if ($this->getLastHttpCode() == 200) {
    parse_str($result, $response);
    $this->response->setBody($response);
    return $response;
} else {
    echo "ERROR : ".PHP_EOL;
    var_dump($result);exit;
}
```

and then please show us the output of error.
hope that will help you.

**Comment by abraham** [comment]
Which shared hosting provider?

**Comment by uzanpower** [comment]
@Ishaf : Ok i will try later
@abraham : what do you means ? , issues on my shared hosting ? , or my provider shared hosting ?

**Comment by eivindvr** [comment]
@lshaf Just tried to change the lines in TwitterOAuth.php and I get ERROR : string(4210)

**Comment by lshaf** [comment]
@eivindvr  can you include the error as well?

**Comment by eivindvr** [comment]
@lshaf Is seems to be empty ERROR : string(4210) " "
If I catch the exception I get "Something is technically wrong" from twitter.

**Comment by lshaf** [comment]
@eivindvr well so there's no problem with this plugin actually.
but there's something wrong from twitter and this plugin didn't show the error somehow and I didn't know why.

**Comment by abraham** [comment]
Was it an HTML response from Twitter?

**Comment by eivindvr** [comment]
@abraham Yes, it renders the Twitter html

**Comment by eivindvr** [comment]
@lshaf @abraham 
I managed to print the missing error message:
{"errors":[{"code":220,"message":"Your credentials do not allow access to this resource."}]}

I didn't use the tokens correctly. 
Everything works now thanks for pointing me in the right direction!

**Comment by lshaf** [comment]
@eivindvr
you're welcome

**Comment by uzanpower** [comment]
sry for late information , but then i set the timeout to zero , i don't get the error , in my opinion the problem is short timeout (just my opinion) .

**Comment by abraham** [comment]
I'll make this a task to verify timeouts provide an useful exception.

**Comment by Rizwankandur** [comment]
iam getting access token and secret but while sending tweet message is shows the error as :
Array ( [oauth_token] => FPNJHwAAAAAAyMzhAAABWQFUZfo [oauth_token_secret] => xOoU9Ywub4Kl6hDy8WWcfEee612FvBZP [oauth_callback_confirmed] => true ) 
casestdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => 220 [message] => Your credentials do not allow access to this resource. ) ) )

**Comment by abraham** [comment]
It looks like a clear timeout exception is already being thrown.

> Abraham\TwitterOAuth\TwitterOAuthException: Connection time-out
