### ISSUE TITLE
Switch to a real framework for example code

### ISSUE THREAD

**Issue by abraham** [abraham/twitteroauth#342]
Possibly http://lumen.laravel.com/

**Comment by m2sh** [comment]
PhalconPHP Micro app (https://docs.phalconphp.com/en/latest/reference/micro.html) is similar to Lumen
it could be an other choice

**Comment by jamesxv7** [comment]
This sounds awesome. **thumbs up**

**Comment by obarlas** [comment]
I've been using your code with Laravel for a while now, how can I help?

**Comment by gunnrryy** [comment]
is there any sample/examples of how to code with using this library?

**Comment by abraham** [comment]
@gunnrryy https://twitteroauth.com/ is a live example site and the source is available https://github.com/abraham/twitteroauth-demo

**Comment by abraham** [comment]
TwitterOAuth is in maintenance mode and major improvements are no longer planned. https://github.com/abraham/twitteroauth/issues/1188
