### ISSUE TITLE
Error when create TwitterOauth instance

### ISSUE THREAD

**Issue by wintronic** [abraham/twitteroauth#345]
![error1](https://cloud.githubusercontent.com/assets/5086102/7199692/d977bef4-e520-11e4-839c-0ee092806e7b.png)
I want build an twitter web application using codeigniter.
So i embed you library in my codeigniter project. But I got error. When I try to call TwitterOauth instance with "$twitteroauth = new TwitterOAuth('zBzFeAJrkUZ8f2RhW3cbVeATb','34Jbinx6846848oVVHmUKrP1efOTKFmiw9yBbms9qhz5e3i');" its successful build. 

But when i Try to call 
$request_token = $twitteroauth->oauth('oauth/request_token', array('oauth_callback' => 'http://127.0.0.1:8080/Twitter/index.php/Testing'));
it return error with the screenshoot above with exception message "Caught exception: Problem with the SSL CA cert (path? access rights?)".
Do you know what the problem is ?

For some information i create new apps in the twiitter dev apps.
with callback url : empty.

I have been searching it, but no solution found. thank you

**Comment by abraham** [comment]
TwitterOAuth is unable to read the location of `cacert.pem`

**Comment by wintronic** [comment]
Yeah thanks. i add it and it's working.
But when i call
$url = $twitteroauth->url($request_token['oauth_token']);
header('Location: '. $url);
it ridirect to https://api.twitter.com/xoZpbX9MTWJfEbrWykWkyYpWCakXEokt?
the url is not working.     What should i do ?
and
setTimeouts is not available now ? if no, which file contain the function ? 
Call to undefined method TwitterOAuth::setTimeouts() 

thank you

**Comment by abraham** [comment]
Please see URL on https://twitteroauth.com/ for the currect `->url` syntax. `setTimeouts` is the correct timeout method, please make sure you are running the latest version of TwitterOAuth.
