### ISSUE TITLE
Attempted to load class "TwitterOAuth" from namespace "Abraham\TwitterOAuth". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by alexloehner** [abraham/twitteroauth#346]
Hi there!

First I want to make a feature request: Create a Symfony Bundle from your library please! Makes things much easier. :)

So, here is my problem:

I'm using Symfony 2.6.6 together with many other bundles and I've now installed this twitteroauth library in order to be able to easily get the last tweets.

This is how my composer.json looks like (the relevant parts):

	"require": {
		"php": ">=5.4.0",
		"symfony/symfony": "2.6.*",
		[.....]
		"abraham/twitteroauth": "dev-master"
	},
	[.....]
	"repositories": [
		{
		  "type": "package",
		  "package": {
			"name": "abraham/twitteroauth",
			"version": "dev-master",
			"dist": {
			  "url": "https://github.com/abraham/twitteroauth/zipball/master",
			  "type": "zip"
			},
			"source": {
			  "url": "git://github.com/abraham/twitteroauth.git",
			  "type": "git",
			  "reference": "master"
			}
		  }
		}
	]

The library is correctly installed in ./vendor/abraham/twitteroauth/src...

Then I've created a new action in my controller:

    use Abraham\TwitterOAuth\TwitterOAuth;
    [.....]
    public function getLastTweetsAction()
    {
        $connection = new TwitterOAuth(
            $this->container->getParameter('twitter_consumer_key'),
            $this->container->getParameter('twitter_consumer_secret'),
            $this->container->getParameter('twitter_oauth_token'),
            $this->container->getParameter('twitter_oauth_token_secret')
        );
        $statues = $connection->get("statuses/home_timeline", array("count" => 10, "exclude_replies" => true));

        return $this->render('SywFrontMainBundle:Common:_tweets.html.twig', array(
            'tweets' => $statues,
        ));
    }

Then I've added this controller action to my _footer template of my application this way:

    <div class="col-sm-5">
        <div class="border">
            {% block tweets %}
                {{ render( controller('SywFrontMainBundle:Base:getLastTweets')) }}
            {% endblock %}
        </div>
    </div>

And then I've created a new template in Common, called _tweets.html.twig with the following content:

    <div class="tweets">
        {{ dump(tweets) }}
    </div>

That is all... everything quiet normal and as usual, not?

But when visiting my application, I get this:

	Attempted to load class "TwitterOAuth" from namespace "Abraham\TwitterOAuth".
	Did you forget a "use" statement for another namespace?
	500 Internal Server Error - ClassNotFoundException

**Comment by abraham** [comment]
Do you have `require "vendor/autoload.php";` for composer? BTW, it's not recommended to use `dev-master` as it can change at anytime.

**Comment by alexloehner** [comment]
Symfony has its own autoloader which of course also includes the vendor/autoload.php, so, yes, sure.

**Comment by abraham** [comment]
I'm guessing it's an issue with using `repositories` and `require` in `composer.json`. AFAIK you should use on or the other. Try removing the `repositories` listing, deleting `composer.lock`, deleting the vendor directory and running composer install again.

**Comment by alexloehner** [comment]
wtf... that has worked... o.O  ...I have no clue what that has to do with not finding the namespace or class in that namespace, but it has worked.

Thanks man.

**Comment by abraham** [comment]
:+1:
