### ISSUE TITLE
Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message...

### ISSUE THREAD

**Issue by vanflicke** [abraham/twitteroauth#348]
I'm getting this error below. I've googled, stackoverflowed, and twittercommunitied (are those words?), sorry in advance if the solution is obvious. Not sure why the code is returning a webpage instead of a code. Any help is appreciated.

```
Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message '<!DOCTYPE html> <html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"> <head> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> <meta http-equiv="Content-Language" content="en-us"> <meta name="robots" content="noindex, nofollow"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>Twitter / ?</title> <link href="https://abs.twimg.com/favicons/favicon.ico" rel="shortcut icon" type="image/x-icon"> <link rel="stylesheet" href="https://abs.twimg.com/errors/fullscreen_errors-91ecc652e4fafac52ce8a1a8a181ad24.css"> </head> <body> <div class="topbar js-topbar"> <div class="global-nav" data-section-term="top_nav"> <div class="global-nav-inner"> <div class="container"> <ul class="nav js-global-actions"> <li class="home"> <a class="nav-logo-link" href="https://twitter.com"><img class=" in C:\Users\Owner\marcomcalendar\twitteroauth\src\TwitterOAuth.php on line 141
```

**Comment by abraham** [comment]
Please include the code that is causing the error.

**Comment by vanflicke** [comment]
It hangs on the call to oauth in $connection. $ck and $cs are the key and secret. Thanks again
    
    // if valid....
	//create new connection obj
	$connection = new TwitterOAuth($ck, $cs, $request_token['oauth_token'], $request_token['oauth_token_secret']);
	//get authentication tokens from twitter
	$access_token = $connection->oauth("oauth_token", array("oauth_verifier" => $_REQUEST['oauth_verifier']));

**Comment by vanflicke** [comment]
I think it's similar to this issue, but I couldn't see the resolution https://github.com/abraham/twitteroauth/issues/314

**Comment by abraham** [comment]
Please see https://twitteroauth.com/redirect.php, you are not calling `->oauth` with the correct paht.

**Comment by vanflicke** [comment]
Isn't the redirect BEFORE the twitter authorization? This is happening after the authorization.

**Comment by abraham** [comment]
Then the path is double wrong, continue through authorization on that page and you'll see how to get an access_token.

**Comment by vanflicke** [comment]
ah, I see, the problem is way upstream. So I'm back to the other issue of how to do this on localhost. Thanks for your work on this, it's very cool.

**Comment by vanflicke** [comment]
Fixed. I had to go into host file and fiddle with the localhost settings, re-checked that all the header calls had http://localhost/ before all calls, and verified the session ids were passing through correctly. I wrote up a little function that I could save variable values into the php log for troubleshooting. And I learned what sprintf was from your source code. So it all worked out. Thank you!

**Comment by abraham** [comment]
:+1:

**Comment by raj2kumar2** [comment]
i got a problem in accessing twitter authentication `PHP Fatal error:  Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Failed to connect to api.twitter.com port 443: Connection timed out' in /home/itbusine/public_html/twitee/app/twitteroauth-0.6.2/src/TwitterOAuth.php:400
Stack trace:
#0 /home/itbusine/public_html/twitee/app/twitteroauth-0.6.2/src/TwitterOAuth.php(334): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array)
#1 /home/itbusine/public_html/twitee/app/twitteroauth-0.6.2/src/TwitterOAuth.php(305): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array)
#2 /home/itbusine/public_html/twitee/app/twitteroauth-0.6.2/src/TwitterOAuth.php(179): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'search/tweets', Array)
#3 /home/itbusine/public_html/twitee/app/lib/TwiteeClass.php(34): Abraham\TwitterOAuth\TwitterOAuth->get('search/tweets', Array)`

**Comment by FedgeNo** [comment]
Please open a new issue. This issue is closed.

**Comment by elhardoum** [comment]
Add a callback URL in the app settings in Twitter apps dashboard. That worked for me.
