### ISSUE TITLE
Request time out

### ISSUE THREAD

**Issue by wintronic** [abraham/twitteroauth#349]
Sir may i ask.. I got error Request time out.
I use your code as default so timeout and connection timeout is 5

there is 2 question here :
1. When the request timeout happened ? Because i have tried for waiting for 5 minutes wiithout action. the error is not showing.
2. What should i do next if I got error "Request time out" ? Should I start the code from oauth ?
Really need your explanation

thanks.

**Comment by abraham** [comment]
The timeout occurs if it takes too long to connect to api.twitter.com or if Twitter takes too long responding with content. In general Twitter runs a very fast API and timeouts won't happen.

If a timeout happens you should either surface an error to the user to try again or automatically retry with [exponential backoffs](https://en.wikipedia.org/wiki/Exponential_backoff).
