### ISSUE TITLE
Can't post 140 char status with attached media

### ISSUE THREAD

**Issue by timgavin** [abraham/twitteroauth#351]
When posting media the `status` string can't be longer than 117 chars.

Here's a `print_r()` of the `$parameters` array

```
[status] => Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor 
incididunt ut labore et dolore magna aliqua. Ut enim ad mini
[media_ids] => 594936553887117313
```

Here's the error message from Twitter

```
[code] => 186
[message] => Status is over 140 characters.
```

As you can see in the `$parameters` array `status` is definitely 140 characters, so the API *should* accept it, right?

This only happens when posting media. If I don't attach a file the post is sent to Twitter and all is good. Is this a Twitter issue? I haven't been able to find anything on this.

Thanks!

**Comment by abraham** [comment]
Media is attached by adding a URL at the end of the status text. That URL will take 23 characters away from 140.
