### ISSUE TITLE
Is the library incomplete? I got this error

### ISSUE THREAD

**Issue by appshop** [abraham/twitteroauth#353]
When I want creat a URL for the "login with twitter" I get this error

Fatal error:  Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' in /home/u155633994/public_html/vendor/abraham/twitteroauth/src/TwitterOAuth.php:141
Stack trace:
#0 /home/u155633994/public_html/twitter.php(24): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array)
#1 {main}
  thrown in /home/u155633994/public_html/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 141

So, I checked the code and this line in this file it seems like incomplete because the method $this->getLastHttpCode() aim to a empty code (getHttpCode() is empty) and the TwitterOAuthException() class have not __construct, so it's impossible that it can accept any parameter.

Abraham, can you solve this errors?

Thank you so much.

P.D.: sorry for my bad level of English, it's not my native language.

**Comment by abraham** [comment]
Please describe exactly how you are calling the `oauth` method.

**Comment by appshop** [comment]
This is the code that I use in my twitter.php

<?php
require 'vendor/autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;
define('CONSUMER_KEY', "97lmBWViXz5hrWoPDXJmgvt5g");
define('CONSUMER_SECRET', "12ooDeqh6bDoV85dp3KkwzzmSiv6In1pLm80LZpsdplygYtH1B");
define('OauthToken', "2910356392-qqrLqtxlJ6QvcZVmR3kdpK3w6Z6U7WL2hRcvSD7");
define ('OauthTokenSecret', "Ww5sg0TcM1iR67ZpR4qql6qpZzFERej0qeTECpIFTHHBV");
define('OAUTH_CALLBACK', 'http://joniprobandoapis.esy.es/landingtwitter.php');

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);

$url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
var_dump($url);
?>
<a href="<?php echo $url;?>">Login with Twitter</a>

**Comment by yozaira** [comment]
Im having the same issue.

**Comment by abraham** [comment]
Closing in favor of #353 as it looks like the same issue. Please post PHP/OS details there.

**Comment by appshop** [comment]
I'm using PHP 5.5.21 in remote server, it use LAMP and I was installed Twitter Oauth with Composer require using a json file and composer update command.

In localhost it works, but in remote not. And all uploads/transaccions with FTP succeded.

My host is Hostinger.es

**Comment by abraham** [comment]
Does the remote server have [cURL](https://php.net/manual/en/book.curl.php) and [OpenSSL](https://php.net/manual/en/book.openssl.php) installed?

**Comment by abraham** [comment]
I accidentally linked this issue to itself so we'll just run with both.

**Comment by appshop** [comment]
yes, cURL and OpenSSL are enabled

**Comment by abraham** [comment]
What's the OS/version?

**Comment by appshop** [comment]
do you mean my TwitterOauth version or my Operative System version?

TwitterOauth is the last version aim in the guide install.
Operative System is Windows 8 (but I don't think that is outstanding).

If you mean about my cURL version, is 7.40.0
If you mean about my OpenSSL version, is 1.0.1l

If you need more information just ask me.

I think that the problem is in the composer repository, because it's not normal that the class TwitterOauthException is empty. And, review the library, and trying write code, I can't find the getAccessToken method of TwitterOauth to use with the oauth_verifier when my app catch the response of Twitter after the user login. (new TwitterOauth(consumer_key, consumer_secret, oauth_token_oauth_token_secret)->getAccessToken($_REQUEST['oauth_verifier']))

Thank you so much for your response.

**Comment by abraham** [comment]
Yes OS/version means the operating system version the code is being run under. Are running windows 8 on the server too?

`getAccessToken` is an old method from TwitterOAuth v2 or so. On current version (v5) it's replaced by `oauth`.

There is nothing wrong with the composer version, it's running on https://twitteroauth.com/ just fine.
