### ISSUE TITLE
The access_token method must be called with a request_token

### ISSUE THREAD

**Issue by davidbrooks** [abraham/twitteroauth#354]
I'm a bit stuck on something, and I can't for the life of me figure it out. The user has already been directed away from the app for authentication, and it returns them on the callback page. I see the two $_GET values for oauth_verifier and oauth_token, and so I'm calling:

```
$access_token = $connection->oauth("oauth/access_token", array("oauth_verifier" => $oauth_verifier));
```

$connection is created in the same exact way as I did to get the user authenticating in the first place, yet for some reason I get this error:

```
Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message '{"error":"The access_token method must be called with a request_token","request":"\/oauth\/access_token"}' in /home/gearhead/public_html/write/twitteroauth/src/TwitterOAuth.php:141 Stack trace: #0 /home/gearhead/public_html/write/twitter_callback.php(15): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/access_to...', Array) #1 {main} thrown in /home/gearhead/public_html/write/twitteroauth/src/TwitterOAuth.php on line 141
```

The error itself doesn't make sense to me, except that I know there are similarities between the request_token and access_token pages. Have you seen this before, or is there something I'm just completely missing?

Thanks!

**Comment by abraham** [comment]
Make sure you are creating a new `TwitterOAuth` object with a the request_token and secret

**Comment by davidbrooks** [comment]
Using the code:

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);

I'm having a bit of trouble wrapping my head around which of these values it ought to be. I'm guessing that the $access_token, and $access_token_secret are from the app's credentials, and the consumer_key is the request_token, the consumer_secret is the token that comes back with the oauth_verifier. The oauth_verifier is just shipped over in the request. Would all of that be correct, or am I still not understanding? Thanks!

**Comment by abraham** [comment]
In simplified form the flow goes like this
 - Get a temporary request token/secret with `oauth/request_token`
 - redirect user to oauth/authorize with request token
 - user returns and you request token/secret for `oauth/access_token`

This is spelled out step by step, live on twitteroauth.com.

**Comment by davidbrooks** [comment]
Right, and that part three is where I have the issue mentioned above. If I throw the request_token into > $access_token = $connection->oauth("oauth/access_token", array("oauth_verifier" => $oauth_verifier)); I still get the error message above, so I assume it has to be in the TwitterOAuth function. I just can't figure out which variable maps to which value since neither request_token or the other value returned from Twitter (oauth_token) match the variables in the TwitterOAuth documentation. Sorry to be dense here.

**Comment by abraham** [comment]
Which is why I recommend you look at https://twitteroauth.com/redirect.php because it has exacly how to implemnt the code.
