### ISSUE TITLE
Interaction between num chars in tweet and uploading media

### ISSUE THREAD

**Issue by es314159** [abraham/twitteroauth#355]
Using the sample code for uploading an image with a status...
If I upload the image alone it works.  
If I upload the status alone it works. 
If I upload the status and the image together it fails.  
If the status is 140 chars + the image it fails
If the status is 101 chars + the image it succeeds

Any idea why this would happen?

**Comment by abraham** [comment]
Media uploads work by adding a URL to the tweet so you are adding media you have to choun the characters differently.

**Comment by lshaf** [comment]
you can get media url length in here
`https://dev.twitter.com/rest/reference/get/help/configuration`
with variable `characters_reserved_per_media` and this also work when you put url on your status because twitter automatically short your url.
