### ISSUE TITLE
Add ability to add Scheduled Tweets

### ISSUE THREAD

**Issue by jamesond** [abraham/twitteroauth#358]
I looked around and couldn't find out if this capability is already in the API? If not would be awesome to have.

Thanks for building the API (FYI)

**Comment by abraham** [comment]
Scheduled tweets is not supported by the Twitter API and is outside the scope of this library.

**Comment by jamesond** [comment]
Thanks Abraham. I saw scheduled posts when reading a few articles but I believe it was more for advertising. Thanks for the reply!

- Jameson Strocsher
