### ISSUE TITLE
Fatal error: Class 'TwitterOAuth' not found

### ISSUE THREAD

**Issue by snortatu** [abraham/twitteroauth#360]
I am just trying to add a twitter login btn for my site using your twitter api libary...i have been flowing your tutorial https://twitteroauth.com/ ...i seem to be getting this error   Fatal error: Class 'TwitterOAuth' not found ....

I have used composer to install the library ..

This is my code

```
require "vendor/autoload.php"; 

use Abraham\TwitterOAuth\TwitterOAuth;

define('CONSUMER_KEY', getenv('xxxxxxxxx'));

define('CONSUMER_SECRET', getenv('xxxxxxxx'));

define('OAUTH_CALLBACK', getenv('xxxxxxxxxxx'));

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);

$content = $connection->get("account/verify_credentials");
```

I dont know why i am getting this error ...any help would be good thank you :)

**Comment by abraham** [comment]
It sounds like you didn't install in the right place of installing with composer didn't work.

**Comment by snortatu** [comment]
It looks like it installed the library in the vendor/abraham folder??

**Comment by abraham** [comment]
I put your code in a file `index.php` and ran `composer require abraham/twitteroauth` from the same directory and the class was found just fine. You might try deleting the `composer.json`/ `composer.lock`, files and `vendor` directory and trying to install again.

**Comment by snortatu** [comment]
I deleted the composer.json/ composer.lock file  and uninstalled all the packages in the vendor folder and then deleted the vendor folder...i then reinstalled the twitter libary and i am still getting the same error :( ...i just dont understand why it isnt working :(

**Comment by snortatu** [comment]
My web host is hostmonster.com ... to run composer i have to run php-cli composer.phar ...would it have something to do with my web host and composer?? :P

**Comment by abraham** [comment]
I have no experience with hostmonster. I would guess that the class is getting installed to the wrong location or the autoloader isn't configured properly or something similar. Maybe contact hostmonster support or post to user forums if they have any.

**Comment by snortatu** [comment]
I think the autoloader is working because it is working for yhe facebook/google api libary fine....i guess it would be the class getting install in the wrong location :/ .....i will have a play and see if i can get it working...thanks for your help

**Comment by abraham** [comment]
So something like 

```
{
  "require" : {
    "facebook/php-sdk-v4" : "4.0.*"
  }
}
```

works but something like 

```
{
  "require" : {
    "abraha/twitteroauth" : "0.5.3"
  }
}
```

does not work?

**Comment by snortatu** [comment]
Yes when i require the facebook api libary and add a login to the website it works fine ...when i require the twitter api it seems to add the library fine ...but when i try to add a login/make a call to twitter it gives me the error ...it looks like it just cant fine the class...i will play around with it some more...if i cant get it working i will try a different twitter libary and see if i can get it to work....thank you for your time :)

**Comment by abraham** [comment]
What is the hosting provider/server OS you are using?

**Comment by snortatu** [comment]
Hosting with hostmonster.com ....a linux os .....Apache version 2.2.29.....PHP version 5.4.40

**Comment by snortatu** [comment]
The parth to the class is vendor/abraham/twitteroath/src/TwitterOAuth.php   ???

**Comment by abraham** [comment]
That looks correct.
