### ISSUE TITLE
I get no results when select 'result_type' => 'popular'

### ISSUE THREAD

**Issue by qasimzee** [abraham/twitteroauth#362]
I am trying to filter out the results by "popular" but when I add "'result_type' => 'popular',", I usually get no results. Secondly, I selected "count => 50", that is also not working. API always returns 15 results. Please help
EDIT: I use multiple tags in the search query like "#obama #health".
Thanks

**Comment by abraham** [comment]
Please provide the exact code you are using to query the Twitter API without application secrets.

**Comment by qasimzee** [comment]
Thanks for quick reply. Here it is:
```php
$query = array(
        'q' => 'travel+blog',
        'count' => 50,
        'lang' => 'en',
        'result_type' => 'popular',
    );
```

**Comment by abraham** [comment]
I think that's just the results that Twitter is has. E.g. if I switch your example to be `result_type=recent` than 50 tweets are returned. Perhaps you should instead use `mixed` or `recent`.
