### ISSUE TITLE
Remove last TODO from code

### ISSUE THREAD

**Issue by abraham** [abraham/twitteroauth#369]
```
    private function encodeAppAuthorization($consumer)
    {
        // TODO: key and secret should be rfc 1738 encoded
        ...
    }
```

**Comment by HolaSoyCara** [comment]
Hello, I was looking up possible solutions to your issues that didn't require that much coding, since I'm still learning, and I noticed the [rawurlencode](http://php.net/manual/en/function.rawurlencode.php) function could do what you need, since [rfc 3986](http://tools.ietf.org/html/rfc3986) just updates 1738, right ?

**Comment by abraham** [comment]
Reading through the comments of `rawurlencode` it seems like it has is not an exact match to rfc 1738. I haven't bothered to finish vetting it yet though as the Twitter docs say the values do not currently contain values that would get encoded.

**Comment by yudaishimanaka** [comment]
127.0.0.1:41096 [500]: /login.php - Uncaught Error: Call to undefined function Abraham\TwitterOAuth\curl_init() in /home/yudai/Twitter/twitteroauth/src/TwitterOAuth.php:397
Stack trace:
#0 /home/yudai/Twitter/twitteroauth/src/TwitterOAuth.php(334): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array)
#1 /home/yudai/Twitter/twitteroauth/src/TwitterOAuth.php(135): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array)
#2 /home/yudai/Twitter/login.php(12): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array)
#3 {main}
  thrown in /home/yudai/Twitter/twitteroauth/src/TwitterOAuth.php on line 397

このようなエラーが出ますのですが解決方法がわかりません・・・
ご教授して欲しいです・・・
初心者です
