### ISSUE TITLE
no authorization

### ISSUE THREAD

**Issue by 2s2d** [abraham/twitteroauth#372]
This is my code:

```
<?php
require "twitteroauth/autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;

$connection = new TwitterOAuth('here_my_c_key', 'here_my_c_secret');
$content = $connection->get("account/verify_credentials");
$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => 'http://here_my_call_back_url.php'));
$_SESSION['oauth_token'] = $request_token['oauth_token'];
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
$url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
header('Location: '. $url);

?>
```
and after this i have no authorization apps in twitter account. Why? I have no one error.

**Comment by 2s2d** [comment]
I have not used Composer

**Comment by abraham** [comment]
Apps won't show as authorized on your Twitter settings page until `$connection->oauth('oauth/request_token', ...);` gets run during the callback.

**Comment by 2s2d** [comment]
in http://here_my_call_back_url.php code:

**<?php**
require "twitteroauth/autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;

$request_token = [];
$request_token['oauth_token'] = $_SESSION['oauth_token'];
$request_token['oauth_token_secret'] = $_SESSION['oauth_token_secret'];

if (isset($_REQUEST['oauth_token']) && $request_token['oauth_token'] !== $_REQUEST['oauth_token']) {
    // Abort! Something is wrong.	
}
$connection = new TwitterOAuth('here_my_c_key', 'here_my_c_secret', $request_token['oauth_token'], $request_token['oauth_token_secret']);

$access_token = $connection->oauth("oauth/access_token", array("oauth_verifier" => $_REQUEST['oauth_verifier']));
$_SESSION['access_token'] = $access_token;
$user = $connection->get("account/verify_credentials");
print_r($user);

**?>**

Am I doing something wrong? what is missing?

**Comment by abraham** [comment]
And that prints the user details as expected?

**Comment by 2s2d** [comment]
i have a white list, and Apps don't show as authorized

**Comment by 2s2d** [comment]
here my result
![auth](https://cloud.githubusercontent.com/assets/13050565/8357828/8c4c8a94-1b65-11e5-972a-545acbea09fd.jpg)

**Comment by abraham** [comment]
One thing that needs to change is you need to create a new TwitterOAuth object with the access_token.

**Comment by 2s2d** [comment]
but in this example https://twitteroauth.com/redirect.php we have only one TwitterOAuth object. Where i need to create a new object?

**Comment by 2s2d** [comment]
or i need to chance this code?
$connection = new TwitterOAuth('c_key', 'c_secret', $request_token['oauth_token'], $request_token['oauth_token_secret']);

**Comment by abraham** [comment]
You need to create a new TwitterOAuth object for redirect.php, callback.php and for profile.php. Each one uses different types of tokens.

**Comment by 2s2d** [comment]
sorry, but i don't get it. we have example redirect.php:
<?php
require 'vendor/autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;
define('CONSUMER_KEY', getenv('CONSUMER_KEY'));
define('CONSUMER_SECRET', getenv('CONSUMER_SECRET'));
define('OAUTH_CALLBACK', getenv('OAUTH_CALLBACK'));
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
$_SESSION['oauth_token'] = $request_token['oauth_token'];
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
$url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
?>

and we need after that to create a new object? why it is missing in the example?

**Comment by abraham** [comment]
the app wont show up on your list of authorized apps just by doing redirect.php. You have to successfully do redirect.php and callback.php before an app will be authorized for your account and before the app will show in the account settings list.

**Comment by 2s2d** [comment]
now i create a new TwitterOAuth object in redirect.php:

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
$_SESSION['oauth_token'] = $request_token['oauth_token'];
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
**$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $request_token['oauth_token'], $request_token['oauth_token_secret']);**
$url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
header('Location: '. $url);

but i have no changes http://formyjob.ru/demo/
