### ISSUE TITLE
Name lookup timed out

### ISSUE THREAD

**Issue by jm-factorin** [abraham/twitteroauth#374]
Im using the API for a registration system using twitter data and I encountered this error
```sh
[29-Jun-2015 14:01:22 Asia/Tokyo] exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'name lookup timed out' in /vagrant/prj/web/vendor/abraham/twitteroauth/src/TwitterOAuth.php:345
Stack trace:
#0 /vagrant/prj/web/vendor/abraham/twitteroauth/src/TwitterOAuth.php(278): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array)
#1 /vagrant/prj/web/vendor/abraham/twitteroauth/src/TwitterOAuth.php(134): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array)
```
Im always experiencing this from getting request token, thats why I can't proceed to the authentication page to get access token. Please help

**Comment by abraham** [comment]
That means that whatever DNS your server is using is taking too long to tell you where the Twitter API is. You should try telling your server to use a faster one.

**Comment by jm-factorin** [comment]
Oh :fearful: I also tried to use the setTimeouts function and it works as usual but the response has some delay. Anyways, thanks :blush: :+1:
