### ISSUE TITLE
Fatal error: Class 'Abraham\TwitterOAuth\TwitterOAuth' not found

### ISSUE THREAD

**Issue by Xilax** [abraham/twitteroauth#375]
I am getting this error why trying to use twitteroauth without declaring the namespace.
Is it possible to use TwitterOAuth directly?
Please advise...

**Comment by Enchiridion** [comment]
Try \Abraham\TwitterOAuth\TwitterOAuth()

**Comment by Xilax** [comment]
Thanks for your effort.
My bad, I probably caused the issued by move all file from ./src/ to the root and changed 
$base_dir = __DIR__ . '/src/'; 
to 
$base_dir = __DIR__;
I tried \Abraham\TwitterOAuth\TwitterOAuth() before and didn't due to the change I made.
It's working now it all file in ./src/
Thanks.
Warm regards.
