### ISSUE TITLE
Uploading Image

### ISSUE THREAD

**Issue by Xilax** [abraham/twitteroauth#376]
@abraham I want to know which profile the upload will appear in.
I currently use one developer account to generate ConsumerKey,Secret,Token e.t.c
Using the code below, with no twitter handle specified, How can I upload to a specific account?

<pre>
 $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
  $media1 = $connection->upload('media/upload', array('media' => '/path/to/file/kitten1.jpg'));
  $parameters = array(
   'status' => 'Meow Meow Meow',
   'media_ids' => implode(',', [$media1->media_id_string]),
  );
  $result = $connection->post('statuses/update', $parameters);
</pre>

**Comment by abraham** [comment]
The tweet will appear on whoevers timeline the access_token and access_token_secret belongs to.
