### ISSUE TITLE
Dont work. Help please

### ISSUE THREAD

**Issue by snatural100** [abraham/twitteroauth#377]
I have this code 
he does not work.
just a white screen. not even about the error messages.
what am I doing wrong?

	require_once ("TwitterOAuth/autoload.php");
	require_once("TwitterOAuth/src/TwitterOAuth.php"); 
	use Abraham\TwitterOAuth\TwitterOAuth;
	$connection = new TwitterOAuth('XXXXXXXXXXXXXXXX', 'YYYYYYYYYYYYYYYY', 'GGGGGGGGGGGGGG', 'JJJJJJJJJJJJJJJJJJJJ');

	$media1 = $connection->upload('media/upload', array('media' => 'http://my.site/forum/gallery/5591_02_07_15_8_54_47.jpeg'));

	$parameters = array(
		'status' => 'Meow Meow Meow',
		'media_ids' => implode(',', array($media1->media_id_string, $media2->media_id_string)),
	);
	$result = $connection->post('statuses/update', $parameters);

**Comment by abraham** [comment]
The image has to be on your server as a file. It can't be a URL.
