### ISSUE TITLE
everything seems ok why im getting this error Sorry, that page does not exist","code":34

### ISSUE THREAD

**Issue by shahidbasheer** [abraham/twitteroauth#379]
<?php
	
	require_once("twitteroauth-master/autoload.php");
	use Abraham\TwitterOAuth\TwitterOAuth;

	$twitteruser = "username"; //user name you want to reference
	$notweets = 5; //how many tweets you want to retrieve
	$consumerkey = "********************"; //Noted keys from step 2
	$consumersecret = "********************"; //Noted keys from step 2
	$accesstoken = "********************"; //Noted keys from step 2
	$accesstokensecret = "********************"; //Noted keys from step 2
	
	function getConnectionWithAccessToken($cons_key, $cons_secret, $oauth_token, $oauth_token_secret) {
	  $connection = new TwitterOAuth($cons_key, $cons_secret, $oauth_token, $oauth_token_secret);
	  return $connection;
	}

	$connection = getConnectionWithAccessToken($consumerkey, $consumersecret, $accesstoken, $accesstokensecret);

	$tweets = $connection->get("https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=".$twitteruser."&count=".$notweets);

	echo json_encode($tweets);
	
?>

**Comment by abraham** [comment]
1) You should not be using master, it is not guaranteed stable. Pick a [specific release](https://github.com/abraham/twitteroauth/releases).

2) That's not how the library specifies you should build requests. Instead you should do something like this:

    $tweets = $connection->get("statuses/user_timeline", array("screen_name" => $twitteruser, "count" => $notweets));

**Comment by shahidbasheer** [comment]
Wao grt it worked! **thanks a lot** for your reply i'm using api first time and i ruined my whole day searching and removing this error thanks agian abraham
