### ISSUE TITLE
Private classes do not allow extension

### ISSUE THREAD

**Issue by xtinagodwin** [abraham/twitteroauth#381]
My project requires integration with the Twitter Ads API and the Twitter TON API, which I have accomplished by extending TwitterOauth and writing a tiny bit of code. Is it possible to make the oAuthRequest function and $response member variables protected instead of private? The affected file is src/TwitterOauth.php on lines 265 and 23.

I made these changes locally, however I would love it if these changes could be integrated into the project so a composer update doesn't break things for me.

Thanks for reading!

**Comment by miguelmora76** [comment]
That would be very useful! This would really help with something similar that we're doing on our project.

**Comment by abraham** [comment]
Release 3.1.0 allows overriding `apiUrl` and setting custom API hosts. It should work until #684 is implemented.
