### ISSUE TITLE
TwitterOAuth library broken when running on localhost

### ISSUE THREAD

**Issue by php-oauth** [abraham/twitteroauth#386]
On OSX 10.10.5, I created a clean install of Twitter OAuth using composer and ran the following

     php -S localhost:1234

with a valid CONSUMER_KEY, CONSUMER_SECRET (validated using the Twitter OAuth tool that returns the expected result).

    <?php 

    require "vendor/autoload.php";
    use Abraham\TwitterOAuth\TwitterOAuth;

    define('CONSUMER_KEY', '...');
    define('CONSUMER_SECRET', '..');
    define('OAUTH_CALLBACK', 'test2.php');

    $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
    $request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));

    ?>

which results in

    /test.php - Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' in      /Users/username/Dev/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php:141
Stack trace:
#0 /Users/username/Dev/twitter/test.php(12): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array)
#1 {main}
  thrown in /Users/username/Dev/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 141

        $curlErrno = curl_errno($curlHandle);
        var_dump($curlErrno);

results in int(3), which from http://php.net/manual/en/function.curl-errno.php is [3] => 'CURLE_URL_MALFORMAT', 

PHP version is PHP 5.5.27 (cli) (built: Jul 23 2015 00:21:59)

**Comment by abraham** [comment]
Running `PHP 5.6.12 (cli) (built: Aug  7 2015 11:29:31)` I can't replicate your error. It shouldn't be causing your issue but `OAUTH_CALLBACK` should be set to a complete URL like `http://localhost:1234/test2.php`.

**Comment by php-oauth** [comment]
I've now verified that all works as intended in PHP 5.6.11, but due to using AppEngine, we cannot yet move to 5.6. Is there an issue with cURL in PHP 5.5.27 that we can work around?

**Comment by php-oauth** [comment]
Going deeper, the issue seems to be with CURL 7.43.0 - CURL 7.42.0 works as intended.

**Comment by php-oauth** [comment]
Commenting out CURLOPT_CAPATH => __DIR__ within request function within TwitterOAuth.php resolves this issue.

**Comment by abraham** [comment]
Interesting. That curl_opt should probably be removed since there is not actually a directory with multiple certificate files.

**Comment by fightbulc** [comment]
Running into the exact same issue on my localhost with CURL 7.44.0 and PHP 5.6.12

For now I commented it ```CURLOPT_CAPATH```.

**Comment by abraham** [comment]
[v0.5.4](https://github.com/abraham/twitteroauth/releases/tag/0.5.4) has been released.
