### ISSUE TITLE
media_ids parameter is invalid

### ISSUE THREAD

**Issue by nrileykc** [abraham/twitteroauth#387]
I've used your example on the documentation site, but when trying to post a status update with a single image I keep receiving the error: media_ids parameter is invalid.

**Comment by abraham** [comment]
Please show the code you are using.

**Comment by nrileykc** [comment]
$media = $connection->upload('media/upload', array('media' => '../upload/'.$orgID.'/'.$filename));
        $parameters = array(
            'status' => $tweet,
            'media_ids' => implode(',', array($media->media_id_string)),
        );
        $statues = $connection->post('statuses/update', $parameters);
        echo '<pre>';
        var_dump($statues);
        echo '</pre>';

**Comment by abraham** [comment]
What's the value of `$media`?

    var_dump($media);

**Comment by nrileykc** [comment]
Aha, that was it, had to tweak path.  Thanks for the help.
