### ISSUE TITLE
Error "Esta funcionalidad no está disponible temporalmente"

### ISSUE THREAD

**Issue by leandro2219** [abraham/twitteroauth#388]
Hi,

I am trying to use your API to post a tweet like a user and I am getting this error: 

> Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Esta funcionalidad no estÃ¡ disponible temporalmente' in \sdk\twitteroauth\src\TwitterOAuth.php on line 137 

This is my code for that section:

		//GETTING ALL THE TOKEN NEEDED
		$oauth_verifier = $_GET['oauth_verifier'];
		$token_secret = $_COOKIE['token_secret'];
		$oauth_token = $_GET['oauth_token'];
		
		//EXCHANGING THE TOKENS FOR OAUTH TOKEN AND TOKEN SECRET
		$connection = new TwitterOAuth(TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, $oauth_token, $token_secret);
		$url = $connection->url("oauth/authorize", array("oauth_token" => $oauth_token));
		
		$access_token = $connection->oauth("oauth/access_token", array("oauth_verifier" => $oauth_verifier));
		
		$accessToken=$access_token['oauth_token'];
		$secretToken=$access_token['oauth_token_secret'];
		
		//$media1 = $connection->upload('media/upload', array('media' => '/path/to/file/kitten1.jpg'));
		//$media2 = $connection->upload('media/upload', array('media' => '/path/to/file/kitten2.jpg'));
		$parameters = array(
				'status' => 'AAAAA',
		);
		$result = $connection->post('statuses/update', $parameters);
		print_r($result);

I am getting that error on this step: `$access_token = $connection->oauth("oauth/access_token", array("oauth_verifier" => $oauth_verifier));`

Do you know which could be the problem?

Thanks,
Leandro.

**Comment by abraham** [comment]
You need to create a new `$connection` object with the accessToken/accessToken secret before trying to post the status.

**Comment by leandro2219** [comment]
The problem is that I am not reaching that step, I am getting an error here:

$access_token = $connection->oauth("oauth/access_token", array("oauth_verifier" => $oauth_verifier));

After call that method I am getting this: 

Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Esta funcionalidad no estÃ¡ disponible temporalmente' in \sdk\twitteroauth\src\TwitterOAuth.php on line 137

Thanks.

**Comment by leandro2219** [comment]
So sorry, I found the error. Thanks for all.

**Comment by abraham** [comment]
What was the problem? Incase other people run into similar issues.

**Comment by leandro2219** [comment]
I have only one page to check if is the access was granted (if not was granted I redirect to twitter) and the back url for the autorization, so my error was refresh the page with an old token instead of enter directly to the initial page.

Thanks.
