### ISSUE TITLE
Abraham\TwitterOAuth\TwitterOAuthException  public_html/vendor/abraham/twitteroauth/src/TwitterOAuth.php :141

### ISSUE THREAD

**Issue by ilhanbayram89** [abraham/twitteroauth#390]
I'm getting this error when logging to app after SSL certificate added to my website. I reviewed TwitterOAuth.php on curl options CURLOPT_SSL_VERIFYPEER => true but I'm still getting this error.

**Comment by abraham** [comment]
What is the rest of the error message?

**Comment by ilhanbayram89** [comment]
Empty message returned

Additional information:
Abraham\TwitterOAuth\TwitterOAuthException
File:
/public_html/vendor/abraham/twitteroauth/src/TwitterOAuth.php                    :141
Message:
Stack trace:
#0 /public_html/module/Application/src/Application/Controller/AdminController.php(21541): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array)
#1 /public_html/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): Application\Controller\AdminController->twitterRedirectAction()
#2 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#3 /public_html/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#4 /public_html/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#5 /public_html/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(116): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 
/public_html/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(113): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#7 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 
/public_html/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 /public_html/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 
/public_html/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /public_html/web/index.php(26): Zend\Mvc\Application->run()
#12 {main}


AdminController on line 21541 
$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));

**Comment by message-dimke** [comment]
Hi, how did you fix it? I am getting this too from time to time. Very annoying.
