### ISSUE TITLE
Script working on localhost but not on server. Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'couldn't connect to host' in /home/xxxxxx/public_html/vendor/src/TwitterOAuth.php:401 

### ISSUE THREAD

**Issue by gopalkildoliya** [abraham/twitteroauth#392]
The script works on my localhost xampp server but when i upload this on my server it shows error.
<?php
require "vendor/autoload.php";
define('CONSUMER_KEY', 'xxxxxxxxxxxxxxxxxxxxxxxxxx');
	define('CONSUMER_SECRET', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
	define('OAUTH_CALLBACK', 'xxxxxxxxxxxxxxxxxxxxxxxxxxx;

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
$_SESSION['oauth_token'] = $request_token['oauth_token'];
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
$url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
?>
<html>
	<head>
		<link type="text/css" rel="stylesheet" href="css/bootstrap.css">
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-2 col-md-offset-5" style="position:fixed; top:45%">
					<a href="<?php echo $url;?>" class="btn btn-primary">Start with Twitter</a>
				</div>
			</div>
		</div>
	</body>
</html>

Error On Server:
Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'couldn't connect to host' in /home/xxxxxxxx/public_html/vendor/src/TwitterOAuth.php:401 Stack trace: #0 /home/xxxxxxxx/public_html/vendor/src/TwitterOAuth.php(334): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array) #1 /home/xxxxxxxx/public_html/vendor/src/TwitterOAuth.php(135): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array) #2 /home/xxxxxxxx/public_html/default.php(7): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array) #3 {main} thrown in /home/xxxxxxxx/public_html/vendor/src/TwitterOAuth.php on line 401

**Comment by abraham** [comment]
`couldn't connect to host` sounds like something is blocking connections to the twitter API. Check for firewalls
