### ISSUE TITLE
Getting null everywhere but Linux

### ISSUE THREAD

**Issue by KoolDude79** [abraham/twitteroauth#396]
Is there any dependency I am not aware of? I can't get this library work anywhere but on Linux: 

```
date_default_timezone_set("America/New_York"); 

require_once('lib/twitteroauth/autoload.php');
use Abraham\TwitterOAuth\TwitterOAuth;

define('CONSUMER_KEY', '11111111111111111111111111');
define('CONSUMER_SECRET', '2222222222222222222');
define ('ACCESS_TOKEN', '333333-333333333333333');
define ('ACCESS_TOKEN_SECRET', '4444444444444444444');

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
$tweets = $connection->get('trends/place', array("id" => 1));

$query = ($tweets[0]->trends);
```

And I get:

```
Notice: Trying to get property of non-object in test.php on line 27

NULL
```

I previously had CURL issues on Windows but I managed to fix them. Is there any requirement apart from CURL? I'm also having the same issues in Mac.

**Comment by abraham** [comment]
Curl, and openssl are requirements. Plus PHP > 5.4. There should be some additional errors beyond null though. What is the value of `$tweets`?

**Comment by KoolDude79** [comment]
Null :(

**Comment by KoolDude79** [comment]
So I did this:

require_once('lib/twitteroauth/autoload.php');
use Abraham\TwitterOAuth\TwitterOAuth;

$consumer_key = 'www';
$consumer_secret = 'xxx';
$access_token = 'yyy';
$access_token_secret = 'zzz';

$connection = new TwitterOAuth($consumer_key, $consumer_secret, $access_token, $access_token_secret);
$tweets = $connection->get('trends/place', array("id" => 1));

$query = ($tweets[0]->trends);

var_dump($connection);
var_dump($tweets);
var_dump($query);

$connection:

object(Abraham\TwitterOAuth\TwitterOAuth)[2]
  private 'response' => 
    object(Abraham\TwitterOAuth\Response)[7]
      private 'apiPath' => string 'trends/place' (length=12)
      private 'httpCode' => int 200
      private 'headers' => 
        array (size=24)
          'cache_control' => string 'no-cache, no-store, must-revalidate, pre-check=0, post-check=0' (length=62)
          'content_disposition' => string 'attachment; filename=json.json' (length=30)
          'content_encoding' => string 'gzip' (length=4)
          'content_length' => string '425' (length=3)
          'content_type' => string 'application/json;charset=utf-8' (length=30)
          'date' => string 'Sat, 29 Aug 2015 04:23:11 GMT' (length=29)
          'expires' => string 'Tue, 31 Mar 1981 05:00:00 GMT' (length=29)
          'last_modified' => string 'Sat, 29 Aug 2015 04:23:11 GMT' (length=29)
          'pragma' => string 'no-cache' (length=8)
          'server' => string 'tsa_b' (length=5)
          'set_cookie' => string 'guest_id=v1%3A144082219197015084; Domain=.twitter.com; Path=/; Expires=Mon, 28-Aug-2017 04:23:11 UTC' (length=100)
          'status' => string '200 OK' (length=6)
          'strict_transport_security' => string 'max-age=631138519' (length=17)
          'x_access_level' => string 'read-write' (length=10)
          'x_connection_hash' => string 'edited' (length=32)
          'x_content_type_options' => string 'nosniff' (length=7)
          'x_frame_options' => string 'SAMEORIGIN' (length=10)
          'x_rate_limit_limit' => string '15' (length=2)
          'x_rate_limit_remaining' => string '11' (length=2)
          'x_rate_limit_reset' => string '1440822880' (length=10)
          'x_response_time' => string '16' (length=2)
          'x_transaction' => string '8338c419f7b7b489' (length=16)
          'x_twitter_response_tags' => string 'BouncerCompliant' (length=16)
          'x_xss_protection' => string '1; mode=block' (length=13)
      private 'body' => null
      private 'xHeaders' => 
        array (size=11)
          'x_access_level' => string 'read-write' (length=10)
          'x_connection_hash' => string 'edited' (length=32)
          'x_content_type_options' => string 'nosniff' (length=7)
          'x_frame_options' => string 'SAMEORIGIN' (length=10)
          'x_rate_limit_limit' => string '15' (length=2)
          'x_rate_limit_remaining' => string '11' (length=2)
          'x_rate_limit_reset' => string '1440822880' (length=10)
          'x_response_time' => string '16' (length=2)
          'x_transaction' => string '8338c419f7b7b489' (length=16)
          'x_twitter_response_tags' => string 'BouncerCompliant' (length=16)
          'x_xss_protection' => string '1; mode=block' (length=13)
  private 'bearer' => null
  private 'consumer' => 
    object(Abraham\TwitterOAuth\Consumer)[5]
      public 'key' => string 'www' (length=25)
      public 'secret' => string 'xxx' (length=50)
      public 'callbackUrl' => null
  private 'token' => 
    object(Abraham\TwitterOAuth\Token)[6]
      public 'key' => string 'yyy' (length=50)
      public 'secret' => string 'zzz' (length=45)
  private 'signatureMethod' => 
    object(Abraham\TwitterOAuth\HmacSha1)[4]
  protected 'timeout' => int 5
  protected 'connectionTimeout' => int 5
  protected 'decodeJsonAsArray' => boolean false
  protected 'userAgent' => string 'TwitterOAuth (+https://twitteroauth.com)' (length=40)
  protected 'proxy' => 
    array (size=0)

Both $tweets and $query get null. I have no idea how to interpret this. It works on my linux machine, but I need to make it work on windows and mac.

**Comment by abraham** [comment]
Interesting. 200 response means that Twitter should be successfully returning a response. I'm wondering if something might be failing while trying to parse the JSON response.

**Comment by KoolDude79** [comment]
Is there any way to test it?

**Comment by abraham** [comment]
In the `vendor/abraham/twitteroauth/src/TwitterOAuth.php` file line 306ish var_dump the response. This should be pretty much unprocessed response text from Twitter.

    $response = curl_exec($curlHandle);
    var_dump($response);
    $curlErrno = curl_errno($curlHandle);

**Comment by abraham** [comment]
Reopen if you get additional details.
