### ISSUE TITLE
"code":32 "message":"Could not authenticate you"

### ISSUE THREAD

**Issue by dongchuant** [abraham/twitteroauth#401]
Api auth/access_token returns code 32, so that i encoded double quotes...and then it returns code 215 Bad Authentication data...
Am I using the api in a wrong way?

```
$connection = new TwitterOAuth(self::CONSUMER_KEY, self::CONSUMER_SECRET);
$response = $connection->oauth('oauth/request_token', array('oauth_callback' => $callback));
var_dump($response);
```

**Comment by abraham** [comment]
Please include more details about what you are trying to do, what you expect to be happening and what the actual result is.

**Comment by dongchuant** [comment]
Thanks. I just want to test "sign in with twitter"...
I updated this project to v0.5.4 and  the error above doesn's appear any more.
But I run into some error else that I think I can sovle it...
I am in China and there is some inconvenience.

**Comment by abraham** [comment]
OK. If you run into other problems please open a new issue.
