### ISSUE TITLE
Always this error when uploading a media with chuncked mode: "Over Capacity"

### ISSUE THREAD

**Issue by GMaxera** [abraham/twitteroauth#404]
I'm trying to upload a media with chunk media but I get always this error from Twitter:
message : "Over capacity"
code : 130

I'm doing something wrong ?
This is my code:

```
		$connection = new TwitterOAuth($consumerKey,$consumerSecret,$accessTokenKey,$accessTokenSecret);
		$connection->setTimeouts(60, 30);

		// save video locally to then upload to twitter
		$temp_file = tempnam(sys_get_temp_dir(), 'Video_');
		Cloud::downloadClipTo( $this->jobRefName, "mp4", $temp_file );

		$result = $connection->upload('media/upload', array('media' => $temp_file, 'media_type' => 'video/mp4'), true);

		if ( $connection->getLastHttpCode() != 201 ) {
			// error failed job
			// throw something
			echo "FAILED TO UPLOAD THE VIDEO\n";
			var_dump( $result );
			return;
		}
		if ( !property_exists($result, 'media_id_string') ) {
			// error failed job
			// throw something
			echo "FAILED TO UPLOAD NO MEDIA STRING\n";
			var_dump( $result );
			return;
		}
		$parameters = array('status' => $this->messageToPost, 'media_ids' => $result->media_id_string);
		$result = $connection->post('statuses/update', $parameters);
		echo "POSTING\n";
		var_dump( $result );
		if ( $connection->getLastHttpCode() != 200 ) {
			// error failed job
			// throw something
			return;
		}
		return;
```

**Comment by abraham** [comment]
It looks correct. It might be that Twitter is temporary having capacity issues. Twitter did post some service issues recently. http://twitterstatus.tumblr.com/post/129089856308/twittercom-service-impact

Also make sure the media you are uploading has valid specifications: https://dev.twitter.com/rest/public/uploading-media#videorecs

**Comment by GMaxera** [comment]
I’m replacing a python script that do the upload with your PHP in order to integrate into a more bigger website.

If I run at the same time with the same data to post to the same account …
… the python script post correctly, your upload give the error “Over capacity”
So, it seems more a bug related to your code.

If you want, please, tell me how can I investigate more.

Ciao,
Gianluca.

**Comment by abraham** [comment]
Does it happen for all videos you've tried or just a specific couple? Can you upload an example video somewhere that demonstrates the behaviour?

**Comment by abraham** [comment]
Please comment if you have a way to reproduce consistantly.

**Comment by GMaxera** [comment]
I posted a working code on the first post.
Did you tried it ?

**Comment by abraham** [comment]
Please answer the questions in my [previous comment](https://github.com/abraham/twitteroauth/issues/404#issuecomment-141475763).

**Comment by GMaxera** [comment]
Does it happen for all videos you've tried or just a specific couple?
Yes. As I said, my python script upload to twitter fine while your code fails. My test was to run exactly at the same time from the same computer the same video to the same twitter account. So, I suspect there is something wrong in your code.
If you can guide me, I can investigate.

Can you upload an example video somewhere that demonstrates the behavior?
http://32e506a6aea3853b929e-0b1385a62d762ade5ff0a8631476a6a0.r92.cf3.rackcdn.com/render.mp4
