### ISSUE TITLE
SSL Connect Error with PHP cURL support version NSS/3.19.1 Basic ECC

### ISSUE THREAD

**Issue by renowijoyo** [abraham/twitteroauth#409]
the example doesn't work in my Centos 6.5 server with php cURL using NSS. it shows SSL Connect Error message.
but on xampp on win32 with cURL version using openssl it works.

has the library been known to work on NSS curl?

**Comment by renowijoyo** [comment]
it magically started to work today without any change. maybe twitter is experiencing problem with their oaut

**Comment by renowijoyo** [comment]
UPDATE:
I found out the culprit. I'm using it with Yii2, and it worked before with

$access_token = $connection->oauth("oauth/access_token", array("oauth_verifier" => $_REQUEST['oauth_verifier']));

suddenly it's generating SSL CONNECT ERROR. then worked for a half day and again the error returned.

reviewing my code I realised I'm using the older array syntax. so I changed it to

**Comment by abraham** [comment]
Changing `array()` to `[]` should have zero impact on SSL issues. The most important next step would be identifying the type and cause of the SSL connection error. E.g. Is server sending invalid certificates, are you being MITM'd, etc.

I recommend enabling [curl verbose](https://github.com/abraham/twitteroauth/blob/master/src/TwitterOAuth.php#L352) mode and looking at the logs for the exact errors.

    // CURLOPT_VERBOSE => true,
