### ISSUE TITLE
Bug in request() – $options for curl

### ISSUE THREAD

**Issue by dusterio** [abraham/twitteroauth#419]
I'm not sure if this is related to my environment or not, but I couldn't reproduce it on Ubuntu

I'm running OS X El Capitan, tried PHP 5.5.30 and PHP 5.6.x. Tried both CLI and FPM.

Line 271 of TwitterOAuth.php (request() method) breaks all curl requests for me:
CURLOPT_CAPATH => __DIR__

If I comment this line – TwitterOAuth begins to work, if I leave it as it is – curl will return error code 3 for all request (empty URL). For some reason, URL from $options magically 'disappears' when this line is present (FYI, I'm testing using an https URL). 

I know it doesn't make much sense, but I've got empirical results. 

The reason that comes in mind is that on OS X the second line somehow overrides the first option:
            CURLOPT_CAINFO => __DIR__ . DIRECTORY_SEPARATOR . 'cacert.pem',
            CURLOPT_CAPATH => __DIR__ . DIRECTORY_SEPARATOR,

And on Ubuntu (and maybe other OS) it wouldn't. 

While, probably, you wouldn't care about compatibility of your package with OS X since nobody runs web applications in OS X, I'm sure there are many developers who use their Macs in development environment :)

**Comment by abraham** [comment]
Please update, `CURLOPT_CAPATH` was removed in v0.5.4.
