### ISSUE TITLE
Composer or manual install?

### ISSUE THREAD

**Issue by ANSB** [abraham/twitteroauth#420]
I just installed the lib with composer, write the example with:
require "vendor/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;
at top of code and.... get the famous:
Class 'TwitterOAuth' not found

After having a look at the vendor (and really don't understand the need of 'vomiting' so many pieces of code) I decided to simply use the manual method: unzip in a twitteroauth folder, put at top of code:

equire "twitteroauth/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;

And, know, that's OK. Maybe there is a problem in the composer installation?

Regards
PL

**Comment by abraham** [comment]
Can you provide more details of how you installed with composer and what your directory structure is? I just ran through a quick try without issue.

**Comment by nguyentienlong** [comment]
@abraham might be he config the `psr-4` loader is not correct in `composer.json`

**Comment by nguyentienlong** [comment]
@ANSB can you upload your composer.json here

**Comment by ANSB** [comment]
I don't have it anymore and I migrated to another lib. Sorry.
