### ISSUE TITLE
Problem with quotes encoding

### ISSUE THREAD

**Issue by ericrkl** [abraham/twitteroauth#421]
When sending DM with single or double quotes the message shows up like this:
Trouble with &#34;quotes&#34;, &#39;singles&#39; too!

Have tried mb_convert_encoding, addslashes, urlencode prior to sending text, to no avail.

I include 2 screenshots from twitter web interface (safari) and twitter for iPhone
![twitter_web](https://cloud.githubusercontent.com/assets/6992820/11236104/8546a564-8d9c-11e5-837e-6e16b4642c9a.png)
![twitter_iphone](https://cloud.githubusercontent.com/assets/6992820/11236108/8b111240-8d9c-11e5-9ba5-255d9931e67b.png)

**Comment by abraham** [comment]
You shouldn't need to do any encoding. The following worked for me.

    $dm = $connection->post('direct_messages/new', ['user_id' => $id_str, 'text' => 'Test with "double"']);
    $dm = $connection->post('direct_messages/new', ['user_id' => $id_str, 'text' => "Test with 'single'"]);

<img width="202" alt="screen shot 2015-11-18 at 09 58 00" src="https://cloud.githubusercontent.com/assets/3341/11245951/1c69acd2-8ddb-11e5-9680-cb4b7a990893.png">

**Comment by abraham** [comment]
Please reopen if you have a consistent method of reproducing this.
