### ISSUE TITLE
Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message '{"errors":[{"code":89,"message":"Invalid or expired token."}]}'

### ISSUE THREAD

**Issue by NikhilRadadiya** [abraham/twitteroauth#423]
i'm getting this  error after clicking on the "authorize app" button untill it everything is working fine.please help me solve this.
here is the code which causing the error.
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET,$_SESSION['request_token'] , $_SESSION['request_token_secret']);
  $access_token = $connection->oauth("oauth/request_token", array("oauth_verifier" => $_REQUEST['oauth_verifier'] ));

**Comment by ChelseaStats** [comment]
see solution here: 
http://stackoverflow.com/questions/28646829/twitter-oauth-invalid-or-expired-access-token
