### ISSUE TITLE
Fatal error: Class 'Abraham\TwitterOAuth\TwitterOAuth' not found 

### ISSUE THREAD

**Issue by MenocGit** [abraham/twitteroauth#424]
Hello,

I am getting this error when I try to execute my twitter search program. I am not sure if the require is wrong or I am missing a file required.

Code from TwitterSearch.php:

<?php
require_once("vendor/autoload.php");
use Abraham\TwitterOAuth\TwitterOAuth;

 
define('CONSUMER_KEY', xxxxx);
define('CONSUMER_SECRET', xxxxx);
define('ACCESS_TOKEN',xxxxx);
define('ACCESS_TOKEN_SECRET',xxxxx);
 
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);

Files:
Index.php
composer.json
TwitterSearch.php
vendor Directory:
     autoload.php
     composer Directory:
            Classloader.php
            autoload_classmap.php
            autoload_namespaces.php
            autoload_psr4.php
            autoload_real.php
            installed.json

**Comment by abraham** [comment]
Based on your list of files twitteroauth isn't installed. What install instructions did you follow?

**Comment by MenocGit** [comment]
I am using linux.

For initial install: https://twitteroauth.com/

After I was looking at: https://getcomposer.org/doc/00-intro.md

**Comment by abraham** [comment]
You probably need to install TwitterOAuth again from with the project directory. `vendor` should have a directory `abrahm` that contains the source of TwitterOAuth.

**Comment by wooge** [comment]
I'm having a similar issue — I'm using the Manual Install procedure, I downloaded the latest source zip and there is no `abraham` folder contained within the decompressed structure:

autoload.php
composer.json
LICENSE.md
phpmd.xml
phpunit.xml
README.md
src
tests

**Comment by abraham** [comment]
The manual install doesn't use an `abraham` directory.

```
require "twitteroauth/autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;
```

**Comment by wooge** [comment]
Darnit, my bad... I was using the `use Abraham\TwitterOAuth\TwitterOAuth;` call inside of a function.
