### ISSUE TITLE
Error while processing content unencoding: invalid block type

### ISSUE THREAD

**Issue by acrozes** [abraham/twitteroauth#425]
I have more error like this:

```
Abraham\TwitterOAuth\TwitterOAuthException: 
Error while processing content unencoding: invalid block type (uncaught exception) 
at ./vendor/abraham/twitteroauth/src/TwitterOAuth.php line 400
```

With no more information, I don't understand how to fix this ?

**Comment by abraham** [comment]
This seems like an error in curl processing the response from twitter. What OS/platform are you run this on? Do you have zlib installed?

**Comment by acrozes** [comment]
Centos / Zlib: Running latest 1.2.7-13.el7
I have only a small percentage of requests with this error, the other requests are ok.
I cannot determine if it is an update by me that introduce this (and which one) or an API twitter update ...

**Comment by FedgeNo** [comment]
I looked it up and apparently there is no default cURL options for PHP, which means you're probably not overriding them somewhere else in your code unless you're accessing the handler used by TwitterOAuth for some reason. 

As for this specific error, it appears to be related to Accept-Encoding, which you can set to gzip or deflate. I didn't look at the code in TwitterOAuth to see which one it's currently using but some of Twitter's servers may only be supporting one of these options while most are supporting both. Add in a load balancer and you'd have a situation like this where you only see the error once in a while. 

Also, I could just be completely wrong LOL

**Comment by FedgeNo** [comment]
Another possibility is that Twitter's servers can only use one of these encodings while returning a specific error state.

**Comment by abraham** [comment]
TwitterOAuth is configured with `Accept-Encoding: gzip`. My guess is @FedgeNo is correct, either some Twitter servers are configured incorrectly, or some errors are not encoded correctly.

@acrozes which API methods were you seeing the exception from? Roughly what % of requests do you think caused this exception? 1 in 1000? I'd like to dig further but it'll be hard without being able to actively trigger the cause.

**Comment by acrozes** [comment]
Now I have no more "invalid block type" error but timeout error (after 20s) in Get or Post query.
I catch the error and I resend the request once and it is ok in 99% of cases

In both cases, 1 in 1000 seems to be the right frequency ...

**Comment by abraham** [comment]
Which API methods are you generally seeing the issue with?

**Comment by acrozes** [comment]
Also very rarely I have: "TwitterOAuthException: 35: TCP connection reset by peer"
I don't know if there is a link with this differents errors.

I didn't find any link between errors and request.
In last 30  minutes:
- get user/lookup (2*)
- get friends/ids (3*)
- get followers/ids (2*)
- get favorites/list (1*)
- upload media/upload (1*)
- post friendships/destroy (1*)

**Comment by FedgeNo** [comment]
One other thing is that your server or an upstream switch/router may just be under heavy load and dropping some packets or something. Check out your server's load average if possible. If it's really high that might be your issue. If not, try pinging another server a bunch of times with some large packets and see if you get them all back.

**Comment by abraham** [comment]
Likely an issue on Twitter's side
