### ISSUE TITLE
Error Code: 215 Bad Authentication Data

### ISSUE THREAD

**Issue by honradokarl** [abraham/twitteroauth#426]
Hi it works perfectly on my localhost. But it is not working on live. 
![error](https://cloud.githubusercontent.com/assets/15603443/11648511/477c4b20-9db0-11e5-81d4-d7ce132c372e.jpg)
![error](https://cloud.githubusercontent.com/assets/15603443/11648514/5536bae8-9db0-11e5-858c-403a6a372317.jpg)

**Comment by abraham** [comment]
Common issues when it works in one location but not another are:

- consumer key/secret incorrectly set
- clock is not properly synced using [NTP](https://en.wikipedia.org/wiki/Network_Time_Protocol)
- firewall/network restrictions are blocking requests to `https://api.twitter.com`
