### ISSUE TITLE
How retweet?

### ISSUE THREAD

**Issue by adamziaja** [abraham/twitteroauth#428]
How can I retweet https://dev.twitter.com/rest/reference/post/statuses/retweet/%3Aid ?

`$connection->post("statuses/retweet/$id");`

return

`Sorry, that page does not exist`

**Comment by acrozes** [comment]
The post prototype is: 
```post($path, array $parameters = [])```
So try:
```post("statuses/retwee", ['id'=>$id])```

**Comment by abraham** [comment]
The documentation specifies that the tweet ID is part of the path and not a parameter so the following is correct:

    $connection->post("statuses/retweet/$id");

Make sure the value of `$id` is a valid status ID and make sure that you are using a recent version of TwitterOAuth.

**Comment by adamziaja** [comment]
I use recent version (just done git clone) and still http://pastebin.com/raw/KByi5ex4 looks like something is wrong :(

**Comment by adamziaja** [comment]
When I try RT for example https://twitter.com/MalwareMustDie/status/673810480520007684

```
$connection = @new TwitterOAuth($CONSUMER_KEY, $CONSUMER_SECRET, $access_token, $access_token_secret);

echo "<pre>";
$retweet = $connection->post("statuses/retweet/673810480520007684");
var_dump($retweet);

$statuses = $connection->get("search/tweets", array("q" => "test", "result_type" => "recent", "count" => "100"));
var_dump($statuses);
echo "</pre>";
```

```
object(stdClass)#4 (1) {
  ["errors"]=>
  array(1) {
    [0]=>
    object(stdClass)#8 (2) {
      ["code"]=>
      int(220)
      ["message"]=>
      string(54) "Your credentials do not allow access to this resource."
    }
  }
}
object(stdClass)#7 (2) {
  ["statuses"]=>
  array(100) {
    [0]=>
    object(stdClass)#10 (25) {
      ["metadata"]=>
      object(stdClass)#11 (2) {
        ["iso_language_code"]=>
        string(2) "fr"
        ["result_type"]=>
        string(6) "recent"
      }
      ["created_at"]=>
      string(30) "Sun Dec 20 11:23:12 +0000 2015"
      ["id"]=>
      int(678536120162996224)
      ["id_str"]=>
      string(18) "678536120162996224"
      ["text"]=>
      string(75) "RT @stenmava: @Inesslut maillot de l'AlgĂŠrie floquĂŠ "93 tu peux pas test""
      ["source"]=>
      string(82) "Twitter for iPhone"
      ["truncated"]=>
[...]
```

**Comment by adamziaja** [comment]
My fault, there was PHP_EOL in $id... :-1:
