### ISSUE TITLE
Can someone help me..

### ISSUE THREAD

**Issue by AucT** [abraham/twitteroauth#429]
I just need login users via twitter.
I need following
twitter nickname, twitter user id, and optionally email, optionally avatar.

The docs are hard for me to understand :(
can someone post an example?

**Comment by abraham** [comment]
https://twitteroauth.com/ is a live example. Click on "sign in with Twitter" to see step one.

**Comment by AucT** [comment]
thx for pointing out
very weird documentation style for me though.

**Comment by FedgeNo** [comment]
I found that almost right away but what I did find hard to figure out from the documentation was pulling public data without logging in a user, just using the application credentials.

**Comment by abraham** [comment]
@AucT once authentication is completed TwitterOAuth is just a simple wrapper around the Twitter API. 

The `GET` section of https://twitteroauth.com/ shows an example of converting a Twitter API request to a TwitterOAuth implementation. Getting profile data is just changing out the API path and parameters.

**Comment by abraham** [comment]
@FedgeNo I don't currently have any custom docs for app auth but [testOauth2Token](https://github.com/abraham/twitteroauth/blob/master/tests/TwitterOAuthTest.php#L35) shows how to get an app access token and [testBearerToken](https://github.com/abraham/twitteroauth/blob/master/tests/TwitterOAuthTest.php#L49) shows how to use the bearer token.

**Comment by AucT** [comment]
everything's fine. Your library is awesome!
I found on stackoverflow the solution. And even saved it on github if I forgot.
