### ISSUE TITLE
Bearer Token

### ISSUE THREAD

**Issue by mbarwick83** [abraham/twitteroauth#431]
Do you have an example for using setting/using an application-only bearer token? I looked at your test php file, but couldn't get a full grasp of it. Or maybe this is not possible with this library?

**Comment by abraham** [comment]
There are two steps. 

1) [get a bearer token](https://github.com/abraham/twitteroauth/blob/master/tests/TwitterOAuthTest.php#L35)

```
$twitter = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
$accessToken = $twitter->oauth2('oauth2/token', array('grant_type' => 'client_credentials'));
```

2) [using a bearer token](https://github.com/abraham/twitteroauth/blob/master/tests/TwitterOAuthTest.php#L49)

```
$twitter = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, null, $accessToken->access_token);
$result = $twitter->get('statuses/user_timeline', array('screen_name' => 'twitterapi'));
```
