### ISSUE TITLE
Operation timed out after 15001

### ISSUE THREAD

**Issue by toleabivol** [abraham/twitteroauth#433]
Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Operation timed out after 15001 milliseconds with 0 bytes received'

Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Operation timed out after 5000 milliseconds with 0 bytes received' in /home/virtual/teslathemes.com/public/demo/wp/sevenfold/wp-content/themes/sevenfold/tesla_framework/extensions/twitteroauth/src/TwitterOAuth.php:329 Stack trace: #0 /home/virtual/teslathemes.com/public/demo/wp/sevenfold/wp-content/themes/sevenfold/tesla_framework/extensions/twitteroauth/src/TwitterOAuth.php(263): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array) #1 /home/virtual/teslathemes.com/public/demo/wp/sevenfold/wp-content/themes/sevenfold/tesla_framework/extensions/twitteroauth/src/TwitterOAuth.php(234): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array) #2 /home/virtual/teslathemes.com/public/demo/wp/sevenfold/wp-content/themes/sevenfold/tesla_framework/extensions/twitteroauth/src/TwitterOAuth.php(179): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 's in /home/virtual/teslathemes.com/public/demo/wp/sevenfold/wp-content/themes/sevenfold/tesla_framework/extensions/twitteroauth/src/TwitterOAuth.php on line 329

**Comment by toleabivol** [comment]
Possible twitter api down :

https://dev.twitter.com/overview/status

**Comment by abraham** [comment]
The Twitter API has had a number of issues over the last couple of days. It's likely because of that.

**Comment by triusdeeepak** [comment]
Is there is not any way to remove or skip this error?

**Comment by abraham** [comment]
Generally you should not run into timeout issues. Twitter server's are fast. If there are issues it's usually temporary. If you want to reduce the chance of timeouts you can look at "changing timeout settings" as documented on https://twitteroauth.com/.
