### ISSUE TITLE
Unable to generate request token.

### ISSUE THREAD

**Issue by pranshuagrawal** [abraham/twitteroauth#434]
```
require ('twitteroauth-master/autoload.php');
use Abraham\TwitterOAuth\TwitterOAuth;
include('twitter-config.php');

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);

$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
```

This code was working fine until the last hour, suddenly it stopped working. Till `$connection` i am able to do `var_dum()` after that it is giving me internal server error, that means there is some issue with request token genration. ?

**Comment by abraham** [comment]
Is the server error from your server or from Twitter's server?

**Comment by abraham** [comment]
BTW it's not recommended to use master. You should pick a specific [release ](https://github.com/abraham/twitteroauth/releases).

**Comment by champsupertramp** [comment]
I'm encountering the same issue. It was working 3 weeks ago.

**Comment by abraham** [comment]
Please provide specific errors and stacktraces (without consumer secrets/ user access tokens).
