### ISSUE TITLE
while creating authenticated account in drupal site using Twitter module getting error.

### ISSUE THREAD

**Issue by swatichouksey4u** [abraham/twitteroauth#437]
Hello friends, 
I wanted to add tiwtter comments  functionality in my drupal site. while adding Autheticated account getting "
    Notice: Undefined index: oauth_token in Twitter->get_request_token() (line 59 of C:\wamp\www\www_carepathhealthyengagements_com\sites\all\modules\twitter\twitter.lib.php).
    Notice: Undefined index: oauth_token_secret in Twitter->get_request_token() (line 59 of C:\wamp\www\www_carepathhealthyengagements_com\sites\all\modules\twitter\twitter.lib.php).
    Could not obtain a valid token from the Twitter API. Please review the configuration.
" notice error. 

steps done :-1. enabled twitter-7.x-5.11 and outh 7.x-3.2 modules . 
2. Twitter application created in https://dev.twitter.com and got Website and Callback URL. copied OAuth keys and secret key in Twitter module settings. All the steps followed mentioned in (https://www.drupal.org/node/1346824). 

now when i am trying to add authenticated account geeting error screenshot attached . 

Please provide your solutions . 
![error](https://cloud.githubusercontent.com/assets/16723612/12512665/8afc66ee-c111-11e5-8277-237b38712287.png)

**Comment by abraham** [comment]
This issue tracker is not for the Drupal module. You should post your issue to their discussion area.
