### ISSUE TITLE
How to debug oauth

### ISSUE THREAD

**Issue by champsupertramp** [abraham/twitteroauth#438]
We've created a wordpress plugin with twitteroauth. One of our client sites fails to retrieve `request_token` and generate authentication url. Here's the code:

```PHP
$connection = new TwitterOAuth( $this->consumer_key, $this->consumer_secret );
$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => urlencode($this->oauth_callback) ));
			

$_SESSION['tw_oauth_token'] = $request_token['oauth_token'];
$_SESSION['tw_oauth_token_secret'] = $request_token['oauth_token_secret'];

$this->login_url = $connection->url('oauth/authenticate', array('oauth_token' => $request_token['oauth_token']));

// $this->login_url returns 'https://api.twitter.com/oauth/authenticate?' without 'request_token'
			
```

I've set the right callback url and API credentials but still fails to get the request token. The callback url format is something like this: http://www.example.com.abcd.efg.hij.de/ 

Do you think there's an issue with the callback url format? The callback url is the homepage. How do you debug this kind of issue? I'd like to find out if this is a server-side issue or other?

**Comment by abraham** [comment]
A good way to debug is to enable [curl's verbose mode](https://github.com/abraham/twitteroauth/blob/master/src/TwitterOAuth.php#L352). This will log the HTTPS requests/responses.

You're `urlencode` of the callback URL might be the issue. Encoding is automatically handled.

**Comment by champsupertramp** [comment]
Thank you @abraham !
