### ISSUE TITLE
Cannot redeclare class Abraham\TwitterOAuth\SignatureMethod

### ISSUE THREAD

**Issue by koffisani** [abraham/twitteroauth#439]
I'm trying to use TwitterOAuth on my site (currently testing in local) and I'm facing an error : 
`Cannot redeclare class Abraham\TwitterOAuth\SignatureMethod in /opt/lampp/htdocs/.../twitteroauth/src/SignatureMethod.php on line 13`
Previously, I've used `require` instead of `use` to solve some import errors. Can somebody help me fix this ?

**Comment by abraham** [comment]
Make sure you are using the autoloader as [documented](https://twitteroauth.com/).
