### ISSUE TITLE
Syntax Error with JSON

### ISSUE THREAD

**Issue by theBear** [abraham/twitteroauth#440]
Hi, thx for this awesome library! 

When I try to get [followers/ids](https://dev.twitter.com/rest/reference/get/followers/ids) I receive the correct IDs from the username I've chosen, but I cannot parse the code via _json_. Via `var_dump($statuses)` everything seems fine:

```
object(stdClass) #3 (5) { ["ids"]= > array(4973) {
	[0] => string(10)
	"1234567890" [1] => string(10)
	"1234567891" [2] => string(9)
	"1234567892" [3] => string(10)
	etc.
```

 but when I use `json_decode($statuses)` or `json_decode($statuses,true)` the output is **NULL** and `json_last_error_msg` tells me, that there is a **syntax error**. But which error exactly I don't know. I used the sample codes from [https://twitteroauth.com](https://twitteroauth.com), so I think everything is normal and what is has to be. I pasted the `var_dump`-output into [JSONLinter](http://jsonlint.com/) and it says:

![linter](https://cloud.githubusercontent.com/assets/7254827/12876826/63ff9d28-ce08-11e5-9304-668859d967ba.png)

I also tried some snippets I've found at [stackoverflow](https://stackoverflow.com/questions/689185/json-decode-returns-null-after-webservice-call/689364#689364) to avoid BOM, but no success so far. Btw: I'm using PHP v5.5. Hopefully somebody can help me. Thank you!

**Comment by abraham** [comment]
TwitterOAuth automatically `json_decodes` responses. Just use response as it is.

**Comment by theBear** [comment]
Facepalm deluxe :-D thx!
