### ISSUE TITLE
Application-only authentication: how to get and use?

### ISSUE THREAD

**Issue by theBear** [abraham/twitteroauth#441]
With the user authentification everything works fine, but for some scripts I need the[ Application-only authentication](https://dev.twitter.com/oauth/application-only) to get more requests/15mins (e.g. [search/tweets](https://dev.twitter.com/rest/reference/get/search/tweet)). I read something about [Base64 encoding](https://dev.twitter.com/oauth/application-only), but actually I didn't understand it correctly. Is there a simple command to get **and** to use a _bearer token_ for and with your library?

**Comment by abraham** [comment]
[testOauth2Token](https://github.com/abraham/twitteroauth/blob/master/tests/TwitterOAuthTest.php#L35) shows how to get an app access token and [testBearerToken](https://github.com/abraham/twitteroauth/blob/master/tests/TwitterOAuthTest.php#L49) shows how to use the bearer token
