### ISSUE TITLE
Delete method not supported anymore

### ISSUE THREAD

**Issue by FerdiAgrio** [abraham/twitteroauth#444]
Hi there,
First of all many thanks for developing this library, really helpful.

When developing my custom implementation, I also tested removing a tweet with the delete function which results in the the URL;
https://api.twitter.com/1.1/statuses/destroy/{id}.json
Sadly Twitter responded "HTTP/1.1 400 Bad Request", code "86", message "This method requires a POST.".
Testing was also done at https://dev.twitter.com/rest/tools/console.

When changing the function method from 'DELETE' to 'POST' it will work again.
Maybe it can be changed with the upcoming update?

Best regards!

**Comment by abraham** [comment]
That's interesting. I don't remember Twitter deprecating DELETE but I guess most developers always used POST.
