### ISSUE TITLE
Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Failed to connect to api.twitter.com port 443:

### ISSUE THREAD

**Issue by JulianaDeMoraes** [abraham/twitteroauth#445]
Hello! Please can help solve this problem ? the application to automatically post to twitter is returning these errors :
Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Failed to connect to api.twitter.com port 443: Connection refused' in /home/u511806508/public_html/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php:400 Stack trace: #0 /home/u511806508/public_html/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(334): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array) #1 /home/u511806508/public_html/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(305): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array) #2 /home/u511806508/public_html/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(179): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'account/verify_...', Array) #3 /home/u511806508/public_html/twitter/index.php(43): Abraham\TwitterOAuth\TwitterOAuth->get('account/verify_...') #4 {main} thrown in /home/u511806508/public_html/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 400

**Comment by abraham** [comment]
That sounds to me like there is a firewall blocking connections or something similar. Maybe your IP address is blocked by Twitter.

**Comment by JulianaDeMoraes** [comment]
Mr. Abraham could see if there are any problems in the code ?
https://github.com/JulianaDeMoraes/twikiss.git
My website is hosted in Brazil Hostinger who answered be no restriction on Twitter and that there could be error in the script. I asked Twitter to evaluate whether my site is blacklisted and await response.So thank you

**Comment by abraham** [comment]
It would be much easier for me to look at the code if it wasn't zipped.

**Comment by JulianaDeMoraes** [comment]
Please excuse me . It is the same installation described in https://github.com/pinceladasdaweb/Twitterbot.git . 
- The keys were created and copied as described in https://dev.twitter.com/apps
- The database was created with success and some phrases inserted to script test
 <?php
                    require "inc/twitter_credentials.php";
                    require "inc/Database.php";
                    require "vendor/autoload.php";
                    use Abraham\TwitterOAuth\TwitterOAuth;
                    $pdo = Database::connect();
                    $getTweets = $pdo->prepare("SELECT *, RAND() as rand FROM tweets ORDER BY rand LIMIT 1");
                    $getTweets->execute();
                    if($getTweets->rowCount() > 0) {
                        while ($row = $getTweets->fetch()) {
                            $tweet = $row['tweet'];
                        }
                        $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
                        $content = $connection->get('account/verify_credentials');
                        $connection->post('statuses/update', array('status' => $tweet));
                        if ($connection->getLastHttpCode() === 200) {
                            echo '<p><strong>Your latest tweet:</strong> '. $tweet .'</p>'.PHP_EOL;
                        } else {
                            echo '<p><strong>Error:</strong> A problem ocurred. You filled your Twitter credentials correctly? Or walk abusing the Twitter API?</p>'.PHP_EOL;
                        }
                    } else {
                        echo '<p><strong>Error:</strong> You have no tweets registered in the database or not filled data connection properly.</p>'.PHP_EOL;
                    }
                    Database::disconnect();
                ?>

**Comment by abraham** [comment]
That code looks like it should work fine.

`Failed to connect to api.twitter.com port 443: Connection refused` shouldn't be caused by anything in the  TwitterOAuth library. Usually that's caused by a firewall on your server, in the datacenter, or Twitter blocking you. I would recommend continuing to work with your host and Twitter to try and identify the issue.

**Comment by JulianaDeMoraes** [comment]
Thank you! While awaiting the response from Twitter will install it at another address ok ? Thanks

**Comment by JulianaDeMoraes** [comment]
Mr. Abraham, i changed hosting provider.and created another application and the error message has changed. First, however, the title bar appears an animation and the word connecting remains for about 5 seconds.
Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'connect() timed out!' in /home/vol4_6/freecluster.eu/fceu_17619922/htdocs/vendor/abraham/twitteroauth/src/TwitterOAuth.php:400 Stack trace: #0 /home/vol4_6/freecluster.eu/fceu_17619922/htdocs/vendor/abraham/twitteroauth/src/TwitterOAuth.php(334): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array) #1 /home/vol4_6/freecluster.eu/fceu_17619922/htdocs/vendor/abraham/twitteroauth/src/TwitterOAuth.php(305): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array) #2 /home/vol4_6/freecluster.eu/fceu_17619922/htdocs/vendor/abraham/twitteroauth/src/TwitterOAuth.php(179): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'account/verify_...', Array) #3 /home/vol4_6/freecluster.eu/fceu_17619922/htdocs/index.php(42): Abraham\TwitterOAuth\TwitterOAuth->get('account/verify_...') #4 {main} thrown in /home/vol4_6/freecluster.eu/fceu_17619922/htdocs/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 400

**Comment by Firzenizer** [comment]
I am also getting SSL connection timeout exception and I can't catch it.
> PHP Fatal error:  Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'SSL connection timeout' in /vendor/abraham/twitteroauth/src/TwitterOAuth.php:400
> Stack trace:
> #0 /var/www/vendor/abraham/twitteroauth/src/TwitterOAuth.php(334): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array)
> #1 /var/www/vendor/abraham/twitteroauth/src/TwitterOAuth.php(305): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array)
> #2 /var/www/vendor/abraham/twitteroauth/src/TwitterOAuth.php(179): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'search/tweets', Array)
> #3 /var/www/app/controllers/SocialController.php(378): Abraham\TwitterOAuth\TwitterOAuth->get('search/tweets', Array)

**Comment by JulianaDeMoraes** [comment]
Thank you Mr. Williams. It worked perfectly in both host paid as a free host. Excelent!
