### ISSUE TITLE
error code 215  Bad Authentication data

### ISSUE THREAD

**Issue by archish1989** [abraham/twitteroauth#446]
I've download new library and was trying to implement "account/verify_credentials". but i am getting error code 215  Bad Authentication data. i am doing just described in documentation. then also i ma getting this error this is my code.

```
<?php
	require_once('twitteroauth/autoload.php');
	use Abraham\TwitterOAuth\TwitterOAuth;
	session_start();
	define('oauth_token', 'my oauth_token');
	define('oauth_token_secret', 'my secret');
	define('CONSUMER_KEY', my key');
	define('CONSUMER_SECRET', '	my secret');

	$twitterDetailOauth= new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET,oauth_token,oauth_token_secret);
	$detail = $twitterDetailOauth->get("account/verify_credentials");

	print_r($detail);
?>  
```

**Comment by abraham** [comment]
How are you getting oauth_token and oauth_token_secret?

**Comment by archish1989** [comment]
i've copy paste them form twitter app setting

**Comment by noluong** [comment]
I get same error. Please help

**Comment by abraham** [comment]
I just copied and pasted your exact code, entered my own consumer key/secret and user access_token/secret and got a successful request without issue. Maybe double check the values you are using in the four `define`s match character for character what's on apps.twitter.com.

**Comment by saiterio** [comment]
I just copied and pasted your exact code, entered my own consumer key/secret and user access_token/secret but got error code 215 Bad Authentication data. I have the same issue on my website, but it worked last month. I triple checked my key values... I tested on other website (I created a new application on twitter apps), but same issue.... Can you help me?

**Comment by saiterio** [comment]
I tested also with the sample below (generated via https://dev.twitter.com/oauth/tools/signature-generator/12110475) :
$pageurl = "https://api.twitter.com/1.1/account/verify_credentials.json";
$ch      = curl_init($pageurl);
curl_setopt($ch, CURLOPT_POST, false);
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Authorization: OAuth oauth_consumer_key="XXXXXXXXXXXXXXX"', 'oauth_nonce="YYYYYYYYYYYYYYYYYYYYYYYY"', 'oauth_signature="KSSKLLLLLLLLLLLLL"', 'oauth_signature_method="HMAC-SHA1"', 'oauth_timestamp="1458307679"]', 'oauth_token="111111111111-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"', 'oauth_version="1.0"']);
curl_exec($ch);

The result is the same: bad authentication data

**Comment by abraham** [comment]
Curl will probably not work directly. the `oauth_*` parameters need to be custom generated for every request and is only valid for a couple of minutes.

If you are still having issues make sure you are running an updated version of TwitterOAuth, an updated version of PHP, and that you have exactly copy/pasted the consumer key/secret and you have a valid access token/secret for a user.

**Comment by saiterio** [comment]
Thank you for your answer.
I'm using PHP 5.5.12, I did the test this afternoon with the TwitterOauth library downloaded just before and after having checked consumer key/secret and access token/secret.  But the result was the same.

**Comment by saiterio** [comment]
I created a new twitter account with a new application to check, but same result again.... 
I used the following code, I'm passing the values as URL parameters and I print them, by this way I can check easily the values:

```
<?php
require_once 'twitter/TwitterOAuth.php';
require_once 'twitter/Config.php';

session_start();

echo nl2br("consumer key: " . $_REQUEST["consumer_key"] . "\n");
echo nl2br("consumer_secret: " . $_REQUEST["consumer_secret"] . "\n");
echo nl2br("access_token: " . $_REQUEST["access_token"] . "\n");
echo nl2br("access_token_secret: " . $_REQUEST["access_token_secret"] . "\n");
$twitterDetailOauth = new TwitterOAuth($_REQUEST["consumer_key"], $_REQUEST["consumer_secret"], $_REQUEST["access_token"], $_REQUEST["access_token_secret"]);
try {
    $detail = $twitterDetailOauth->get("account/verify_credentials");
} catch (Exception $ex) {
    var_dump($ex);
}
var_dump($detail);
```

**Comment by saiterio** [comment]
OK, it's working now. As I have to remove namespace for my platform integration, I made probably a mistake, the line  CURLOPT_HTTPHEADER     => ['Accept: application/json', $authorization, 'Expect:'], was become  CURLOPT_HTTPHEADER     => ['Accept: application/json']
