### ISSUE TITLE
Strange behavior in parsing response in oauth

### ISSUE THREAD

**Issue by asobolevsky** [abraham/twitteroauth#448]
I receive a response as a string:

`{"created_at":"Tue Mar 15 12:11:06 +0000 2016","id":709713532246495232,"id_str":"709713532246495232","text":"\u041f\u0440\u043e\u0442\u0438\u0432 \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u0438\u0432\u043d\u043e\u0439 \u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0441\u0442\u0438 \u0437\u0430 \"\u043f\u0440\u043e\u043f\u0430\u0433\u0430\u043d\u0434\u0443... https:\/\/t.co\/HzYV5F06GH","truncated":false,"source":"\u003ca href=\"https:\/\/democrator.ru\" rel=\"nofollow\"\u003eDemocrator Share \u003c\/a\u003e","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":2497457392,"id_str":"2497457392","name":"\u0421\u043e\u0431\u043e\u043b\u0435\u0432\u0441\u043a\u0438\u0439 \u0410\u043b\u0435\u043a\u0441\u0435\u0439","screen_name":"chebarasha","location":"","description":"","url":null,"entities":{"description":{"urls":[]}},"protected":false,"followers_count":2,"friends_count":6,"listed_count":0,"created_at":"Sun Apr 20 15:14:25 +0000 2014","favourites_count":0,"utc_offset":null,"time_zone":null,"geo_enabled":false,"verified":false,"statuses_count":15,"lang":"ru","contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"C0DEED","profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_tile":false,"profile_image_url":"http:\/\/abs.twimg.com\/sticky\/default_profile_images\/default_profile_3_normal.png","profile_image_url_https":"https:\/\/abs.twimg.com\/sticky\/default_profile_images\/default_profile_3_normal.png","profile_link_color":"0084B4","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"has_extended_profile":false,"default_profile":true,"default_profile_image":true,"following":false,"follow_request_sent":false,"notifications":false},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"https:\/\/t.co\/HzYV5F06GH","expanded_url":"http:\/\/loc.democrator.ru\/petition\/protiv-administrativnoj-otvetstvennosti-za-propaga\/","display_url":"loc.democrator.ru\/petition\/proti\u2026","indices":[58,81]}]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"ru"}
`

and then it is parsed in TwitterOAuth::oauth (141 line) with parse_str function.

After that line I have an associative array with one element with key: 

`{"created_at":"Tue_Mar_15_12:11:06__0000_2016","id":709713532246495232,"id_str":"709713532246495232","text":"\u041f\u0440\u043e\u0442\u0438\u0432_\u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u0438\u0432\u043d\u043e\u0439_\u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0441\u0442\u0438_\u0437\u0430_\"\u043f\u0440\u043e\u043f\u0430\u0433\u0430\u043d\u0434\u0443____https:\/\/t_co\/HzYV5F06GH","truncated":false,"source":"\u003ca_href`

and value: 

`\"https:\/\/democrator.ru\" rel=\"nofollow\"\u003eDemocrator Share \u003c\/a\u003e","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":2497457392,"id_str":"2497457392","name":"\u0421\u043e\u0431\u043e\u043b\u0435\u0432\u0441\u043a\u0438\u0439 \u0410\u043b\u0435\u043a\u0441\u0435\u0439","screen_name":"chebarasha","location":"","description":"","url":null,"entities":{"description":{"urls":[]}},"protected":false,"followers_count":2,"friends_count":6,"listed_count":0,"created_at":"Sun Apr 20 15:14:25  0000 2014","favourites_count":0,"utc_offset":null,"time_zone":null,"geo_enabled":false,"verified":false,"statuses_count":15,"lang":"ru","contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"C0DEED","profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_tile":false,"profile_image_url":"http:\/\/abs.twimg.com\/sticky\/default_profile_images\/default_profile_3_normal.png","profile_image_url_https":"https:\/\/abs.twimg.com\/sticky\/default_profile_images\/default_profile_3_normal.png","profile_link_color":"0084B4","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"has_extended_profile":false,"default_profile":true,"default_profile_image":true,"following":false,"follow_request_sent":false,"notifications":false},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"https:\/\/t.co\/HzYV5F06GH","expanded_url":"http:\/\/loc.democrator.ru\/petition\/protiv-administrativnoj-otvetstvennosti-za-propaga\/","display_url":"loc.democrator.ru\/petition\/proti\u2026","indices":[58,81]}]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"ru"}`.

May be there should be an option whether to get a string response or not?

**Comment by abraham** [comment]
I think this was likely caused by issues on Twitter's servers?
