### ISSUE TITLE
Accessing "x_rate_limit_remaining" value...?

### ISSUE THREAD

**Issue by mbarwick83** [abraham/twitteroauth#449]
I can't seem to get this working. I want to check the remaining rate limit value...as below. But I'm getting an error that `$headers` is a undefined property. Help?

```
$twitter = new TwitterApi($oauth->oauth_token, $oauth->oauth_token_secret);
$results = $twitter->get("followers/ids", ["user_id" => $page_id, "cursor" => $results->next_cursor]);

if ($twitter->headers["x_rate_limit_remaining"] == 0)
```

**Comment by abraham** [comment]
You'll want to use `$twitter->getLastXHeaders()`.

**Comment by mbarwick83** [comment]
That get's a list if I var_dump...but I still can't echo out "x_rate_limit_remaining". How would I call rate_limit using getLastXHeaders?

**Comment by abraham** [comment]
It returns an array so you then access it just like you were initially trying.

    $twitter->getLastXHeaders()["x_rate_limit_remaining"]

Note that the response is a string `"0"` not an integer.

**Comment by mbarwick83** [comment]
Hmm, I tried that last night. Let me revisit it with a fresh mind. Thanks for your help. This library is :100: :+1:

**Comment by adiospeds** [comment]
doesn't work for me as well
