### ISSUE TITLE
Timeout Exception

### ISSUE THREAD

**Issue by jetsynthesys** [abraham/twitteroauth#450]
Hi,

On Friday 25th, the code was working fine but today when am trying to search for something. It giving me this fatal error 

`Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Resolving timed out after 5516 milliseconds' `

Any  help on  this

**Comment by abraham** [comment]
That sounds like an issue with your DNS server/provider. My library just relies on curl and the OS to manage that. Make sure your server is updated and your server is using a stable DNS server
