### ISSUE TITLE
Automatic detection of gzip encoding

### ISSUE THREAD

**Issue by QuingKhaos** [abraham/twitteroauth#453]
Although #408 will provide the possibility to turn of gzip encoding an automatic detection would be nice too, so the user doesn't take care about it (especially when deploying on different systems).

The automatic detection should have lower priority, which means, setting the encoding through the config (with #408 merged) overrules (disables) the automatic detection.

Automatic detection should be lazy, so it is only performed when performing the first real curl request and it should be cached (static variable, etc) for all latter curl calls in the same php request.

**Comment by abraham** [comment]
TwitterOAuth is in maintenance mode and major improvements are no longer planned. https://github.com/abraham/twitteroauth/issues/1188
