### ISSUE TITLE
CA cert problem

### ISSUE THREAD

**Issue by iamhappycoder** [abraham/twitteroauth#454]
Using PHP 5.3.28 under Macports/PHPBrew, this doesn't work:

```
CURLOPT_CAINFO => 'cacert.pem',
CURLOPT_CAPATH => __DIR__,
```

This does (CURLOPT_CAPATH omitted):

```
CURLOPT_CAINFO => __DIR__ . '/cacert.pem',
```

**Comment by abraham** [comment]
Update TwitterOAuth, this was fixed a couple releases ago.
