### ISSUE TITLE
Passing objects as parameters

### ISSUE THREAD

**Issue by johnholtripley** [abraham/twitteroauth#456]
Hi,
Firstly, thanks for creating this - it's been incredibly simple to use.
However, I'm having difficulty in passing an object as a parameter for the new alt text support Twitter has introduced.
According to https://blog.twitter.com/2016/alt-text-support-for-twitter-cards-and-the-rest-api they want the alt text to be in this format:
`{
  "media_id": "650011250680795136",
  "alt_text": {
    "text": "dancing cat"
  }
}`
I've tried passing objects, arrays, using json_decode with their example string to get the right format and all sorts, and every time I get `object(stdClass)#7 (2) { ["request"]=> string(31) "/1.1/media/metadata/create.json" ["error"]=> string(21) "Invalid json payload." }` back.

Currently I'm trying:
`$altText = (object) ['text' => 'An image generated in the style of a medieval Herbarium'];
$parameters = [
         'alt_text' => $altText, 
        'media_id' => $media->media_id_string
    ];
$result = $connection->post('media/metadata/create', $parameters);`
but, as with my other attempts, getting that `invalid json payload` error.

Is there a way to do this? Am I just doing something wrong?

Many thanks for any help.

**Comment by abraham** [comment]
That's probably going to need some changes to the library to work in order to support sending a JSON body.

**Comment by johnholtripley** [comment]
Great - Thanks for looking in to it

**Comment by ashur** [comment]
I would also appreciate the ability to send JSON bodies for setting alt text

**Comment by barredo** [comment]
Came looking for this. 

A small note @johnholtripley. Shouldn't you be using the 'upload' endpoint?

> Note: The domain for this endpoint is upload.twitter.com

**Comment by johnholtripley** [comment]
@barredo I genuinely don't know - has that worked for you? Thanks

**Comment by barredo** [comment]
@johnholtripley no, sorry to report. It seems the library should be updated to allow a JSON body. 

@abraham maybe a silly question, but what if we encode the data as JSON and then send it?

**Comment by agaleski** [comment]
The desired result:
```
{"media_id":"123456789","alt_text":{"text":"dancing cat"}}`
```
equals:
```
json_encode(array(
    'media_id' => '123456789', 
    'alt_text' => array(
        'text' => 'dancing cat'
    )
))
```

So your example should look like:
```
$altText = (object) ['text' => 'An image generated in the style of a medieval Herbarium']; 
$parameters = [
    'media_id' => $media->media_id_string,
    'alt_text' => [
        'text' => 'An image generated in the style of a medieval Herbarium'
    ]
];
$result = $connection->post('media/metadata/create', $parameters);
```

Have not had the time to try it so far. Hope it helps.

**Comment by agaleski** [comment]
If that does not work, it should be:
```
$text = json_encode(array(
    'text' => 'An image generated in the style of a medieval Herbarium'
));
$parameters = [
    'media_id' => $media->media_id_string,
    'alt_text' => "$text"
];
$result = $connection->post('media/metadata/create', $parameters);
```
I will test it tomorrow if no one else did till then ;-)

**Comment by abraham** [comment]
Currently `request` doesn't have any special handling for POSTing JSON data. It doesn't know to set `Content-Type: application/json; charset=UTF-8` and expects the `$parameters` value to be an array that by default gets form encoded (`foo=bar&baz=quz`). I think changes need to be made to the API for this to work.

**Comment by abraham** [comment]
I started taking a stab at this with the https://github.com/abraham/twitteroauth/tree/json-post branch. It's a little messy right now and needs test but please give it a try and see if it works for you.

```
$connection = new TwitterOAuth(TEST_CONSUMER_KEY, TEST_CONSUMER_SECRET, TEST_ACCESS_TOKEN, TEST_ACCESS_TOKEN_SECRET);
$connection->setTimeouts(60, 30);

$file_path = __DIR__ . '/tests/kitten.jpg';
$media = $connection->upload('media/upload', ['media' => $file_path]);

$data = [
  'media_id' => $media->media_id_string,
  'alt_text' => [
    'text' => 'dancing cat'
  ]
];
$metadata = $connection->upload('media/metadata/create', $data, null, true);

$status = $connection->post('statuses/update', ['status' => 'kitten', 'media_ids' => $media->media_id_string]);
var_dump($status);
```

You can also use JSON through the `post` method.

```
$connection = new TwitterOAuth(TEST_CONSUMER_KEY, TEST_CONSUMER_SECRET, TEST_ACCESS_TOKEN, TEST_ACCESS_TOKEN_SECRET);

$data = [
  'id' => 'custom-791105004937490432',
  'changes' => [
    [ "op" => "add", "tweet_id" => "791039488252272641"],
    [ "op" => "add", "tweet_id" => "790691297040347137"]
  ]
];
$result = $connection->post('collections/entries/curate', $data, true);
```

**Comment by johnholtripley** [comment]
Ah, wonderful, thanks for looking at it - I'll give it a go as soon as I can

**Comment by johnholtripley** [comment]
Hi @abraham, I've just tried that and it's worked perfectly first time. Thank you so much for adding this feature in.

**Comment by abraham** [comment]
I'll see about getting some tests added soon and releasing it to stable.

**Comment by abuisine** [comment]
Hi there :)
The lib is super easy to use, congrats :)
Is there any chance to this being released prior to 1.0 ?

**Comment by abraham** [comment]
Very likely.

**Comment by abraham** [comment]
Planning on addressing this in #685

**Comment by junaidshad** [comment]
Hey, This helped. I managed to upload a media image via alt-text. 

If you can update the docs, it'll be easy for others to figure it out quickly.

**Comment by BilalTariq01** [comment]
> Hey, This helped. I managed to upload a media image via alt-text.
> 
> If you can update the docs, it'll be easy for others to figure it out quickly.

Hi Junaidshad,

In the latest version, the third parameter must be passed as an array. To handle this correctly, you can set the jsonPayload option to true, as shown below:

`$twitter->post('media/metadata/create', $alt_text_payload, ['jsonPayload' => true]);`

Your juggar is no longer working :joy: 
<img width="1334" height="55" alt="Image" src="https://github.com/user-attachments/assets/42f47224-9daf-475b-9545-744b152935b7" />
