### ISSUE TITLE
An uncaught Exception was encountered - Message: Connection timed out after 5001 milliseconds

### ISSUE THREAD

**Issue by blackbulldog** [abraham/twitteroauth#457]
Getting timeout message each time I try to get a list of followers - in this example for userid BBCRadio2 - here's the code (it's in codeigniter)

      $twit = new TwitterOAuth($data->consumer_key, $data->consumer_secret, $data->access_token, $data->access_secret);
      dump($twit);
      $cursor=-1;
      $options = array(
		  'cursor'=>$cursor,
		  'count'=>200,
		  'user_id'=>$target->targetacc
		  );
      dump($target);
      $proxy_array=explode(":",$data->proxyid);	
      dump($proxy_array);
      $twit->setProxy([
		'CURLOPT_PROXY' => $proxy_array[0],
		'CURLOPT_PROXYUSERPWD' => '',
		'CURLOPT_PROXYPORT' => $proxy_array[1]
		      ]);
      dump($options);
		      
      $followers = $twit->get('followers/list', $options);
      echo "<HR>";
      dump($followers);

here's the dump of $twit - the result of the new TwitterOauth line:

```
Dump => object(Abraham\TwitterOAuth\TwitterOAuth)#23 (11) {
  ["response":"Abraham\TwitterOAuth\TwitterOAuth":private] => object(Abraham\TwitterOAuth\Response)#27 (5) {
    ["apiPath":"Abraham\TwitterOAuth\Response":private] => NULL
    ["httpCode":"Abraham\TwitterOAuth\Response":private] => int(0)
    ["headers":"Abraham\TwitterOAuth\Response":private] => array(0) {
    }
    ["body":"Abraham\TwitterOAuth\Response":private] => array(0) {
    }
    ["xHeaders":"Abraham\TwitterOAuth\Response":private] => array(0) {
    }
  }
  ["bearer":"Abraham\TwitterOAuth\TwitterOAuth":private] => NULL
  ["consumer":"Abraham\TwitterOAuth\TwitterOAuth":private] => object(Abraham\TwitterOAuth\Consumer)#29 (3) {
    ["key"] => string(25) "1UaAS1j95nHPWAXTvjdZ5uz8B"
    ["secret"] => string(50) "0J2Co17vAwOaGG9iAIhPBwFtwW4YeB40GPsYybPNkIozYpSDR6"
    ["callbackUrl"] => NULL
  }
  ["token":"Abraham\TwitterOAuth\TwitterOAuth":private] => object(Abraham\TwitterOAuth\Token)#30 (2) {
    ["key"] => string(50) "4740004281-VmmM5C6cIsa8QtKHwkfQAtajd3XungZl7R9HvOY"
    ["secret"] => string(45) "UozJGVlpPDxh6U9R7ArN17DCYmLjOy1hj3eLYbMNnN7vX"
  }
  ["signatureMethod":"Abraham\TwitterOAuth\TwitterOAuth":private] => object(Abraham\TwitterOAuth\HmacSha1)#28 (0) {
  }
  ["timeout":protected] => int(5)
  ["connectionTimeout":protected] => int(5)
  ["decodeJsonAsArray":protected] => bool(false)
  ["userAgent":protected] => string(40) "TwitterOAuth (+https://twitteroauth.com)"
  ["proxy":protected] => array(0) {
  }
  ["gzipEncoding":protected] => bool(true)
}
```

I've checked access keys and tokens and all are correct.
Here's the full error message:
```
An uncaught Exception was encountered

Type: Abraham\TwitterOAuth\TwitterOAuthException

Message: Connection timed out after 5001 milliseconds

Filename: /var/www/html/ci/application/vendor/abraham/twitteroauth/src/TwitterOAuth.php

Line Number: 403

Backtrace:

File: /var/www/html/ci/application/vendor/abraham/twitteroauth/src/TwitterOAuth.php
Line: 334
Function: request

File: /var/www/html/ci/application/vendor/abraham/twitteroauth/src/TwitterOAuth.php
Line: 305
Function: oAuthRequest

File: /var/www/html/ci/application/vendor/abraham/twitteroauth/src/TwitterOAuth.php
Line: 179
Function: http

File: /var/www/html/ci/application/controllers/Twitter.php
Line: 46
Function: get

File: /var/www/html/ci/index.php
Line: 315
Function: require_once
```

**Comment by abraham** [comment]
The default 5 seconds is usually more than enough for Twitter's fast responses. Since you are using a proxy that is probably the what is slowing down the connection. You can configure the timeout with `$twit->setTimeouts(10, 15);` where the first number is how long to allow connecting to the server, and the second number is the total amount of seconds to allow.


You will also want to go to https://apps.twitter.com/ and "regenerate consumer key and secret" for your app since you pasted it here in the issue.

**Comment by blackbulldog** [comment]
I changed the proxy and all seems to be fine now. Thanks for the reply ... and pointing out I'd pasted the live keys.

Cheers.
