### ISSUE TITLE
Invalid request token

### ISSUE THREAD

**Issue by digitalisons** [abraham/twitteroauth#458]
Hello @abraham 
I'm getiing really anoyed as a really cannot request a token with your library...
I'm doing PHP "The old fashioned way" as you say and i can't do the begining.
I need to gain access on user to post, read, tweet for them as an autorized app...

I've checked and re-checked and test everying so this post is pretty much my last chance of getting this works and start working on my projet ...

Everything is from https://twitteroauth.com/redirect.php and https://github.com/abraham/twitteroauth/archive/0.6.3.zip

This is the very basic, but it's not working for me ...

**sign.php (working good, redirecting to twitter, then to callback.php)**

```
<?php
session_start();
require "twitteroauth/autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;

	define('CONSUMER_KEY',"***************************");
	define('CONSUMER_SECRET',"***************************");
	define('OAUTH_CALLBACK',"http://127.0.0.1/twitter/callback.php");
	
  $connection  = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
  $request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
  if( $request_token)
	{
		$_SESSION['oauth_token'] = $request_token['oauth_token'];
		$_SESSION['oauth_secret'] = $request_token['oauth_token_secret'];
		$url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
		header('Location: '.$url);
	}
	else //error receiving request token
	{
		echo "Problème de token, veuillez nous contacter";
	}

?>
```

**callback.php**

> Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Invalid request token.' in C:\wamp64\www\twitter\twitteroauth\src\TwitterOAuth.php on line  138

>  Abraham\TwitterOAuth\TwitterOAuthException: Invalid request token. in C:\wamp64\www\twitter\twitteroauth\src\TwitterOAuth.php on line 138

```
<?php
session_start();
require "twitteroauth/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;

define('CONSUMER_KEY', getenv('CONSUMER_KEY'));
define('CONSUMER_SECRET', getenv('CONSUMER_SECRET'));
define('OAUTH_CALLBACK', getenv('OAUTH_CALLBACK'));

$request_token = [];
$request_token['oauth_token'] = $_SESSION['oauth_token'];
$request_token['oauth_token_secret'] = $_SESSION['oauth_token_secret'];

if (isset($_REQUEST['oauth_token']) && $request_token['oauth_token'] !== $_REQUEST['oauth_token']) {
    // Abort! Something is wrong.
}
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $request_token['oauth_token'], $request_token['oauth_token_secret']);
$access_token = $connection->oauth("oauth/access_token", ["oauth_verifier" => $_REQUEST['oauth_verifier']]);
print_r($access_token);
?>
```

Thanks for you time managing this tool since years... i hope i could try it soon !

Regards

Olivier @ [Digitalisons.com](http://www.digitalisons.com)

**Comment by abraham** [comment]
`sign.php` has `$_SESSION['oauth_secret']` but `callback.php` has `$_SESSION['oauth_token_secret']`

**Comment by digitalisons** [comment]
Thank you very much @abraham , i feel a bit silly on this one since i try to make it works for days ...

Have a good week end

Olivier @ [Digitalisons.com](https://twitter.com/digitalisons)
