### ISSUE TITLE
Code working on xampp server but not on Linux Ubuntu server?

### ISSUE THREAD

**Issue by santerinogelainen** [abraham/twitteroauth#459]
Hi!

Great job with the API! Loving it so far but I ran into a problem. I have three files: script.php, index.php and config.php. Script.php contains the following:

`require "twitteroauth/autoload.php";`
`use Abraham\TwitterOAuth\TwitterOAuth;`
`$connection = new TwitterOAuth($consumerkey, $consumersecret, $token, $tokensecret);`

Variables $consumerkey, $consumersecret, $token, and $tokensecret are declared in config.php and config.php is included in script.php. Script.php is inlcuded in index.php. Then there is the code in index.php:

`<?php 
$user = $connection->get("users/show", ["user_id" => "111111111"]);
// after this it just echoes a bunch of stuff from $user`

Now this worked perfectly when I was trying it out on my windows workspace (xampp server), but when I moved the script to my linux server the browser loaded the page but stopped loading the script after
`$user = $connection->get("users/show", ["user_id" => "111111111"]);`
I tried moving $user declaration to script.php and browser returned error code 500. I can't even print_r or var_dump $user. Xampp is running PHP 5.6.15 and linux is running PHP 5.5.9. I do have firewall running on the linux, but ports 80 and 443 are allowed. Any idea what might be going on here?

**Comment by AnthonyCiulla** [comment]
Are your server configuration the same on xammp and the host server?
On Apr 9, 2016 9:22 AM, Santeri Nogelainen <notifications@github.com> wrote:Hi!

Great job with the API! Loving it so far but I ran into a problem. I have three files: script.php, index.php and config.php. Script.php contains the following:

require "twitteroauth/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;
$connection = new TwitterOAuth($consumerkey, $consumersecret, $token, $tokensecret);

Variables $consumerkey, $consumersecret, $token, and $tokensecret are declared in config.php and config.php is included in script.php. Script.php is inlcuded in index.php. Then there is the code in index.php:

<?php 
$user = $connection->get("users/show", ["user_id" => "111111111"]);
// after this it just echoes a bunch of stuff from $user

Now this worked perfectly when I was trying it out on my windows workspace (xampp server), but when I moved the script to my linux server the browser loaded the page but stopped loading the script after
$user = $connection->get("users/show", ["user_id" => "111111111"]);
I tried moving $user declaration to script.php and browser returned error code 500. I can't even print_r or var_dump $user. Xampp is running PHP 5.6.15 and linux is running PHP 5.5.9. I do have firewall running on the linux, but ports 80 and 443 are allowed. Any idea what might be going on here?

**Comment by santerinogelainen** [comment]
Thank you! I checked both php.ini files and from there figured out that on linux php-curl extension was not installed! I was using the default configuration for both and assumed both have curl installed. I feel kinda dumb but glad it got fixed!

**Comment by AnthonyCiulla** [comment]
:) glad to help!
On Apr 9, 2016 1:50 PM, Santeri Nogelainen <notifications@github.com> wrote:Thank you! I checked both php.ini files and from there figured out that on linux php-curl extension was not installed! I was using the default configuration for both and assumed both have curl installed. I feel kinda dumb but glad it got fixed!
