### ISSUE TITLE
CURLOPT_CAINFO error on Google App Engine

### ISSUE THREAD

**Issue by yclaes** [abraham/twitteroauth#460]
Hello

I'm receiving this error on Google App Engine:
ErrorException in TwitterOAuth.php line 353:
Use of undefined constant CURLOPT_CAINFO - assumed 'CURLOPT_CAINFO'

We can only enable curl lite on Google App Engine.

Do you know how we can fix this?

Thanks

**Comment by abraham** [comment]
You could probably get it to work by commenting out that line in `TwitterOAuth.php`.

**Comment by abraham** [comment]
I don't think this is an issue anymore with the switch to https://github.com/composer/ca-bundle
