### ISSUE TITLE
a simple example for non oop developer?

### ISSUE THREAD

**Issue by vespino** [abraham/twitteroauth#464]
Hi,

Is there a simple example of how to implement this project? I'm coming from an older version which only has to be included and away we go but simply including the files "Config.php" and "TwitterOAuth.php" results in classes that can't be found and all kinds of errors that go above my head :(

Sorry for not beeing an OOP developer, but I simply are not getting around to it and I'm sticking to WordPress :)

**Comment by angelxmoreno** [comment]
none OOP as in PHP4 ?

**Comment by vespino** [comment]
Like in functions instead of classes.

**Comment by angelxmoreno** [comment]
Pretty sure that would require a different library altogether.

**Comment by vespino** [comment]
Like I said, I know how to implement classes, but not how to write them. This however seems to require another approach, not?

**Comment by vespino** [comment]
What I'm looking for is an (working) example like this:

`<?php
include 'Config.php';
include 'include 'src/TwitterOAuth.php';

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$statuses = $connection->get("search/tweets", ["q" => "twitterapi"]);
?>`

Now this results in something like the following error:

 Fatal error: Uncaught Error: Class 'TwitterOAuth' not found in C:\server\www\opolo.nl\_emt2\index.php:18 Stack trace: #0 {main} thrown in C:\server\www\opolo.nl\_emt2\index.php on line 18

Hope someone can help me.

**Comment by vespino** [comment]
Think I found the solution:

`require "config.php";
require "twitteroauth/autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;

$connection=new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $_COOKIE['oauth_token'], $_COOKIE['oauth_token_secret']);
$content = $connection->get("account/verify_credentials");`

Now only to fix this:

stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [message] => Your credentials do not allow access to this resource [code] => 220 ) ) )

**Comment by angelxmoreno** [comment]
find me on Twitter. Let's make this happen.

**Comment by vespino** [comment]
I already did :)
