### ISSUE TITLE
Error when uploading .webm file - am I doing it wrong?

### ISSUE THREAD

**Issue by blackbulldog** [abraham/twitteroauth#466]
Hi,

Anyone help?
Trying to upload a .webm file using the following code:

      $media1 = $twit->upload('media/upload', ['media' => $image_url]);
      $parameters = [
	  'status' => "It's so cold this bubble freezes instantly",
	  'media_ids' => implode(',', [$media1->media_id_string]),
	  ];
      $result = $twit->post('statuses/update', $parameters); 

$image_url contains the correct path to the .webm fie.

Keep getting this error:

```
Dump => object(stdClass)#37 (1) {
  ["errors"] => array(1) {
    [0] => object(stdClass)#40 (2) {
      ["code"] => int(44)
      ["message"] => string(31) "media_ids parameter is invalid."
    }
  }
}
```

Thanks in advance.

**Comment by abraham** [comment]
If `$media1` has valid content that it's an issue on Twitter's side. You might try waiting 30 seconds to see if the media_id has to propagate servers or something.

**Comment by blackbulldog** [comment]
I can see the problem is with $media1.
a dump of that object after the upload attempt looks like this:
`Dump => object(stdClass)#33 (2) {
  ["request"] => string(22) "/1.1/media/upload.json"
  ["error"] => string(24) "media type unrecognized."
}
` 
any ideas as to whats going wrong?
Thanks

**Comment by abraham** [comment]
> media type unrecognized

Looks like they don't support uploading webm video. Try uploading a different format.

**Comment by blackbulldog** [comment]
Thanks ... if only jellyhead could read ... I misread 'webp' for 'webm' in the allowed types.
