### ISSUE TITLE
"media type unrecognized" uploading mp4 video

### ISSUE THREAD

**Issue by dacastro4** [abraham/twitteroauth#467]
I'm trying to upload a mp4 video and always returns ` { ["request"]=> string(22) "/1.1/media/upload.json" ["error"]=> string(24) "media type unrecognized." }`.

Here is my code
<pre>
<code>
$connection = new TwitterOAuth($consumer_key, $consumer_secret, $access_token, $access_token_secret);
$content = $connection->get("account/verify_credentials");
$status = "Uploading a video with Twitter API";
$media1 = $connection->upload('media/upload', array('media' => __DIR__.'/../videos/video.mp4', 'media_type' => 'video/mp4'), true);
$connection->post('statuses/update', array(
	'status' => $status,
	'media_ids' => implode(',', array($media1->media_id_string))
));
</code>
</pre>

**Comment by abraham** [comment]
Are you sure Twitter supports that media file? Have you successfully uploaded it through the twitter.com UI? Have you successfully uploaded other media files using this same code?

**Comment by dacastro4** [comment]
@abraham I'm so sorry.
Yes yes and yes.
But I solved the problem.
Add one line to the array in the uploadMediaChuncked function in TwitterOAuth.php

It was:
```
// Init
$init = $this->http('POST', self::UPLOAD_HOST, $path, [
    'command' => 'INIT',
    'media_type' => $parameters['media_type'],
    'total_bytes' => filesize($parameters['media'])
]);
```
Changed to:

```
// Init
$file = file_get_contents($parameters['media']);
$data = base64_encode($file);
$init = $this->http('POST', self::UPLOAD_HOST, $path, [
    'command' => 'INIT',
    'media_data' => $data,
    'media_type' => $parameters['media_type'],
    'total_bytes' => filesize($parameters['media'])
]);
```

I was reading the Twitter documentation and it says that the request needs a madie_data to upload the video.
[Twitter Documentarion - Media Upload](https://dev.twitter.com/rest/reference/post/media/upload)
