### ISSUE TITLE
Twitteroauth class doesn't work in a separate file

### ISSUE THREAD

**Issue by toxpal** [abraham/twitteroauth#470]
Searched all the issues here, didn't find a solution. 

Used old version of Twitteroauth  for ages, worked great. Upgraded to the latest version, and get "Class 'TwitterOAuth' not found" error every time my app uses 2 or more files (the only way to get it working is to copy/paste everything into a single file).

For example, this code works perfectly:

```
<?php
require "twitteroauth/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;

function do_something_with_twitter()
{
$connection = new TwitterOAuth("aaaa", "bbbb");
$content = $connection->get("account/verify_credentials");
print_r($content);
}

do_something_with_twitter();
?>
```

However, this one displays "Class 'TwitterOAuth' not found" error, even if the code is exactly the same (except that function is stored in a separate file and loaded using require())

```
<?php
require "twitteroauth/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;
require "functions.php";
do_something_with_twitter();
?>
```

And here's functions.php code:

```
<?php
function do_something_with_twitter()
{
$connection = new TwitterOAuth("aaaa", "bbbb");
$content = $connection->get("account/verify_credentials");
print_r($content);
}
?>
```

How can I get it working again with multiple files, like it used to in Twitteroauth old version (which didn't use autoloader and had just a few files)? I don't really like to store all my functions, settings, and other data in a single file just to get it working.

P.S. Like I said, everything worked great for years with old version, so I don't think there's some error in my code.

**Comment by abraham** [comment]
Move `use Abraham\TwitterOAuth\TwitterOAuth;` to within the `functions.php` file.

**Comment by toxpal** [comment]
Here's the catch - $connection = new TwitterOAuth... line (and some extra code as well) also is used in MANY files (app contains 50+ PHP files). Does it mean I need to manually review every single file and add "use Abraham\TwitterOAuth\TwitterOAuth;" to each file where TwitterOAuth is used. Isn't there a way to get it working by requiring TwitterOAuth library ONCE (like in old versions)?

**Comment by abraham** [comment]
You are only requiring TwitterOAuth once with `require "twitteroauth/autoload.php";`. [use](https://secure.php.net/manual/en/language.namespaces.importing.php) is a way of having more control over namespacing when requiring addional packages and only takes effect within the file it's used in. You can get rid of `use` but you will have to switch to:

```
$connection = new Abraham\TwitterOAuth\TwitterOAuth("aaaa", "bbbb");
```

**Comment by toxpal** [comment]
Thanks for the explanation. And even more thanks for such a great library.

**Comment by Bhupendrasinha** [comment]
Sir, This library is working finr when I deploy on local Xamp server. But it is not working on godaddy. This particular line is causing this.
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET); Please help us.

**Comment by abraham** [comment]
Please don't comment on old issues. Create a new one with the full details of the problem you are having.
