### ISSUE TITLE
statuses/oembed with protected tweet ? 

### ISSUE THREAD

**Issue by symac** [abraham/twitteroauth#472]
Hello,
I am using twitteroauth and I encountered an issue while trying to use statuses/oembed on tweets that have been posted by a user with a protected account. 

If I get "account/verify_credentials" from my connection object, I see that the user is ok, but when I try to get a tweet from the favourites of this user, using "statuses/oembed", if the tweet is protected, I gert a result with an error message saying "Sorry, you are not authorized to see this status."

I can't understand why as according to account/verify_credentials I am correctly authenticated and I can see the tweet on twitter.com with this account. Any thought on this ?

**Comment by abraham** [comment]
Using the OAuth Signature Generator on [GET statuses/oembed](https://dev.twitter.com/rest/reference/get/statuses/oembed) I get the following error so I think that endpoint doesn't support auth.

```
{"error":"Sorry, you are not authorized to see this status.","request":"\/oembed?url=https%3A%2F%2Ftwitter.com%2F{{user}}%2Fstatus%2F{{id}}"}
```
