### ISSUE TITLE
Connection timed out after 5008 milliseconds

### ISSUE THREAD

**Issue by ParagBansod** [abraham/twitteroauth#474]
After doing all the required modifications I got the following error.
Kindly guide to resolve this.

Fatal error:  Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Connection timed out after 5008 milliseconds' in D:\xampp\htdocs\twitteroauth\twitteroauth\src\TwitterOAuth.php:419
Stack trace:
#0 D:\xampp\htdocs\twitteroauth\twitteroauth\src\TwitterOAuth.php(344): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array)
#1 D:\xampp\htdocs\twitteroauth\twitteroauth\src\TwitterOAuth.php(309): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array)
#2 D:\xampp\htdocs\twitteroauth\twitteroauth\src\TwitterOAuth.php(183): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'statuses/retwee...', Array)
#3 D:\xampp\htdocs\twitteroauth\index.php(35): Abraham\TwitterOAuth\TwitterOAuth->get('statuses/retwee...')
#4 {main}
  thrown in D:\xampp\htdocs\twitteroauth\twitteroauth\src\TwitterOAuth.php on line 419

**Comment by abraham** [comment]
I have no idea what the "required modifications" are but https://twitteroauth.com/ shows you how to increase the default timeout at the bottom of the page.
