### ISSUE TITLE
Failed to connect to api.twitter.com port 443: Timed out

### ISSUE THREAD

**Issue by ParagBansod** [abraham/twitteroauth#475]
Dear Abraham,
Thanks for your response and suggestion for my earlier issue https://github.com/abraham/twitteroauth/issues/474 which is closed.

I followed your suggestion but I got the following error.

$connection = new TwitterOAuth($consumer_key, $consumer_secret, $access_token, $access_token_secret);
$connection->setTimeouts(10, 15);
$connection->get("statuses/retweets/748452817724022784");

Please suggest me to correct this.
Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Failed to connect to api.twitter.com port 443: Timed out' in D:\xampp\htdocs\twitteroauth\twitteroauth\src\TwitterOAuth.php:401 Stack trace: #0 D:\xampp\htdocs\twitteroauth\twitteroauth\src\TwitterOAuth.php(333): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array) #1 D:\xampp\htdocs\twitteroauth\twitteroauth\src\TwitterOAuth.php(304): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array) #2 D:\xampp\htdocs\twitteroauth\twitteroauth\src\TwitterOAuth.php(178): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'statuses/retwee...', Array) #3 D:\xampp\htdocs\twitteroauth\index.php(36): Abraham\TwitterOAuth\TwitterOAuth->get('statuses/retwee...') #4 {main} thrown in D:\xampp\htdocs\twitteroauth\twitteroauth\src\TwitterOAuth.php on line 401

**Comment by abraham** [comment]
It's probably a network issue on your side. Twitter servers generally respond under a second. I would suggest looking into firewalls and network filters that could be blocking requests.

**Comment by ParagBansod** [comment]
Dear Abraham
Thanks for your reply.
Things are working fine as it was server issue.
