### ISSUE TITLE
FR: ability to get results as an array

### ISSUE THREAD

**Issue by edalzell** [abraham/twitteroauth#476]
I'm working on an extension for a CMS, and it requires the data returned to be in an array, not an object.

Would be great if there was a way on the `get` call to return an array. After all it's already JSON somewhere so just need a `decode` in there to get the array.

Thanks.

**Comment by abraham** [comment]
You can already do that.

```
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$connection->setDecodeJsonAsArray(false);
```

**Comment by edalzell** [comment]
Ya I just found that. Sorry. This should really be a docs FR as I couldn't see it listed one the one page of readme docs.
