### ISSUE TITLE
Resolving timed out 

### ISSUE THREAD

**Issue by RAKW** [abraham/twitteroauth#478]
hi,
i am using ubuntu server 16.04 and having this error

PHP Fatal error:  Uncaught Abraham\\TwitterOAuth\\TwitterOAuthException: Resolving timed out after 5515 milliseconds in /var/www/html/twitteroauth/src/TwitterOAuth.php:403\nStack trace:\n#0 
/var/www/html/twitteroauth/src/TwitterOAuth.php(334): Abraham\\TwitterOAuth\\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array)\n#1 
/var/www/html/twitteroauth/src/TwitterOAuth.php(305): Abraham\\TwitterOAuth\\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array)\n#2 /var/www/html/twitteroaut$eroauth/src/TwitterOAuth.php(179): 
Abraham\\TwitterOAuth\\TwitterOAuth->http('GET', 'https://api.twi...', 'account/verify_...', Array)\n#3 /var/www/html/functions.php(16): Abraham\\TwitterOAuth\\TwitterOAu$terOAuth->get('account/verify_...')\n#4 /var/www/html/index.php(2):
 require('/var/www/html/f...')\n#5 {main}\n  thrown in /var/www/html/twitteroauth/src/TwitterOAuth.php on line 403

any help please

**Comment by RAKW** [comment]
i increase the curl_setopt($ch, CURLOPT_TIMEOUT,500);
the error now 


[Mon Jul 11 08:23:41.445412 2016] [:error] [pid 1559] [client 192.168.102.76:58132] PHP Notice:  Trying to get property of non-object in /var/www/html/functions.php on line 30, referer: http://192.168.102.4$
[Mon Jul 11 08:23:41.445455 2016] [:error] [pid 1559] [client 192.168.102.76:58132] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/functions.php on line 30, referer: http://192.168.1$
[Mon Jul 11 08:23:41.445468 2016] [:error] [pid 1559] [client 192.168.102.76:58132] PHP Notice:  Undefined variable: urls in /var/www/html/functions.php on line 52, referer: http://192.168.102.40/index.php
[Mon Jul 11 08:23:41.445484 2016] [:error] [pid 1559] [client 192.168.102.76:58132] PHP Notice:  Undefined variable: urls in /var/www/html/functions.php on line 53, referer: http://192.168.102.40/index.php
[Mon Jul 11 08:23:41.445493 2016] [:error] [pid 1559] [client 192.168.102.76:58132] PHP Notice:  Undefined variable: names in /var/www/html/functions.php on line 54, referer: http://192.168.102.40/index.php
[Mon Jul 11 08:23:41.445507 2016] [:error] [pid 1559] [client 192.168.102.76:58132] PHP Notice:  Undefined variable: rnames in /var/www/html/functions.php on line 55, referer: http://192.168.102.40/index.php
[Mon Jul 11 08:23:41.445525 2016] [:error] [pid 1559] [client 192.168.102.76:58132] PHP Notice:  Undefined index: raum in /var/www/html/index.php on line 4, referer: http://192.168.102.40/index.php
 what is the problem.
i try the code in online server it works.

**Comment by hborras** [comment]
You don't need to modify curl_setopt.

You can modify the timeout when you create the TwitterOauth object. 

If you don't share your request and your params is impossible to determine what's the problem.
