### ISSUE TITLE
Accessing library through class file

### ISSUE THREAD

**Issue by ParagBansod** [abraham/twitteroauth#479]
My requirement is to use the library through class file which in
**ROOT**/modules/Twitter/models/Module.php
Code which I am trying is,

```
class Twitter_Module_Model
{
    public function getAllTweets($consumer_key, $consumer_secret,$access_token,$access_token_secret){
		require "twitteroauth/autoload.php";
		use Abraham\TwitterOAuth\TwitterOAuth;
		$connection = new TwitterOAuth($consumer_key, $consumer_secret,$access_token,$access_token_secret);
		
	}
}
```

I have placed the library files in,
**ROOT**/modules/Twitter/models/twitteroauth/autoload.php
**ROOT**/modules/Twitter/models/twitteroauth/src/

$allTweets = $moduleModel->getAllTweets($consumer_key, $consumer_secret,$access_token,$access_token_secret);
getAllTweets() this method is called through test.php

When I use **use Abraham\TwitterOAuth\TwitterOAuth;**  I got blank screen.
And when I comment **use Abraham\TwitterOAuth\TwitterOAuth;** I am able to process things other than **Twitter**.
Please suggest me what to do...

**Comment by abraham** [comment]
Look at the server error logs and see why it's throwing an error.

**Comment by ParagBansod** [comment]
It worked when I changed code referring your reply to some query.
 use Abraham\TwitterOAuth\TwitterOAuth;
 $connection = new TwitterOAuth($consumer_key, $consumer_secret,$access_token,$access_token_secret);

I replace above code with,
 $connection = new Abraham\TwitterOAuth\TwitterOAuth($consumer_key, $consumer_secret,$access_token,$access_token_secret);

Above modification worked for me.
Thank you.
