### ISSUE TITLE
Code Snippet for the verify-credentials to fetch mail address in Android

### ISSUE THREAD

**Issue by AbdulRehmanNazar** [abraham/twitteroauth#483]
Hey I have successfully logged in and get oauth token and everything is fine, but as per your policy to get the mail Address we have to whitelist and do something extra like whitelist the app and some other.
Now I am here to ask that can Twitter team help me to provide the code snippet for the android to fetch the mail address using the verify-credentials GET request, the confusing point is what are the parameters that we have to send in Resource URL like token, secret etc
Looking for your response.
Thanks in advance

**Comment by abraham** [comment]
This seems to be about Android not PHP.
