### ISSUE TITLE
SSL Error?

### ISSUE THREAD

**Issue by prandam** [abraham/twitteroauth#486]
Suddenly all my scripts are saying this:

> Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed' in /home/gramaco/public_html/random/twitteroauth/src/TwitterOAuth.php:403 Stack trace: #0 /home/gramaco/public_html/random/twitteroauth/src/TwitterOAuth.php(334): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array) #1 /home/gramaco/public_html/random/twitteroauth/src/TwitterOAuth.php(305): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array) #2 /home/gramaco/public_html/random/twitteroauth/src/TwitterOAuth.php(179): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'account/verify_...', Array) #3 /home/gramaco/public_html/random/rilkbaudtweet.php(76): Abraham\TwitterOAuth\TwitterOAuth->get('account/verify_...') #4 {main} thrown in /home/gramaco/public_html/random/twitteroauth/src/TwitterOAuth.php on line 403

I thought that maybe was a server ssl problem but no, they say everything is OK with their certificates. I'm missing something?

**Comment by prandam** [comment]
btw, I already uploaded the new version of the library --and the most recent cacert.pem. 
No changes, same error. Thanks for any help!

**Comment by abraham** [comment]
According to GitHub (https://help.github.com/articles/error-ssl-certificate-problem-verify-that-the-ca-cert-is-ok/) that indicates that the public certificates used by the server are out of date. However TwitterOAuth has the latest versions (https://curl.haxx.se/ca/cacert.pem) included so it shouldn't be an issue. Maybe make sure the server config honors the `CURLOPT_CAINFO` setting for curl.

**Comment by prandam** [comment]
My server provider says -after checking their configs--:
"It looks like the issues you're experiencing are due to the configuration of the software you're using. Unfortunately, we are unable to provide support for third-party or custom scripts, so if you would like further assistance with this, I would advise getting in contact with a developer to investigate this further."
What could be the problem?

**Comment by prandam** [comment]
They say that if I could tell them *where* the problem is they could actually change something. Is possible to know this? some test script? --thanks a lot, and excuse the bother

**Comment by abraham** [comment]
The [cacert.pem](https://github.com/abraham/twitteroauth/blob/master/src/cacert.pem) is a whitelist of valid TLS certificates that [TwitterOAuth.php](https://github.com/abraham/twitteroauth/blob/master/src/TwitterOAuth.php#L353) uses to validate your HTTP requests to api.twitter.com are not being maliciously man-in-the-middled. In general the list works as [tests passed fine yesterday](https://travis-ci.org/abraham/twitteroauth). My guess is that the server configuration your server provider has disables the use of `CURLOPT_CAINFO` and isn't providing a default list of valid TLS certificates.

**Comment by abraham** [comment]
I just verified that the cacert.mep file included in TwitterOAuth is enough to the Twitter API certificate. Running the following command will succeed but if you switch `src/cacert.pem` for an empty file it'll fail.

```
curl -1 --cacert src/cacert.pem --ssl https://api.twitter.com
```

I'm not sure what could be causing it to fail. Maybe there is an intermediary proxy server in between your server and api.twitter.com that is terminating their TLS and switching it out for a self-signed cert.

**Comment by prandam** [comment]
They say:
"Your server is making a direct connection to the internet and there is no intermediary proxy server that it would be going through. Did the developer make any changes to the API recently? These operations should continue to work as there have been no changes to the server other than the CA certs i imported into the system. "

Thanks a lot for your time, Abraham.

**Comment by abraham** [comment]
This is a potential solution https://raymii.org/s/snippets/CentOS_5_CA_Certificate_Bundle_Update.html

**Comment by prandam** [comment]
thanks Abraham. Another comment (I haven't modified anything in the source):

"I attempted to replace the cacert.pem file in your script with the default one as outlined in the link you shared with us. Unfortunately that did not solve the problem. It appears the issue is due to en error in syntax in the following file:

/home/gramaco/public_html/random/twitteroauth/src/TwitterOAuth.php

For example, there are some lines in the top of the file that appear to be extraneous, and have invalid file paths:

root@linkko [/home/gramaco/public_html/random/twitteroauth/src]# sed -n '7,9p' TwitterOAuth.php
namespace Abraham\TwitterOAuth;

use Abraham\TwitterOAuth\Util\JsonDecoder;

Since we are not developers, I suggest you cross reference this file with the default version of it as supplied by the script's developer and correct any mistakes. Please let us know if you have any questions."

**Comment by prandam** [comment]
Sorry for this. I just told them that the syntax is OK and check the server's public certificates.
These bots are for my Master's Thesis and I don't know what to do now :-/
Thanks for your help.

**Comment by prandam** [comment]
They say this --it's possible to do it? I'm desperate now--:

"Greetings,

Several days ago I had already updated the CA certificates that the server operating system was using with the one directly from cURL's website. I have also placed the same CA chain within PHP 5.6's directory that it reads from for the CA cert it references as well. The problem is still occurring. So far, from everything I have read, you can try disable peer verification as described here:

http://php.net/manual/en/migration56.openssl.php

http://stackoverflow.com/questions/26148701/file-get-contents-ssl-operation-failed-with-code-1-and-more


Doing the above will side-step extra security but should help fix the issue and retrieve the data. Please let us know if you need further assistance."

**Comment by abraham** [comment]
Try updating to [v0.6.6](https://github.com/abraham/twitteroauth/releases/tag/0.6.6)

**Comment by prandam** [comment]
I did. It didn't work. My provider says:
"You will need to open a line of communication with Twitter's API support and the developer who made the library. Your server has not had any changes made to it however the script and Twitter's API are under development at a steady rate. Your server is functioning as it should and I do not see a reason as to why it would be causing the issue you are seeing. I have ensured the server is using the latest CA chains within the operating system."

It's possible to disable any security measure in SSL that could trigger the error? Even if that defeat the function of it in the first place. I can live with that for now.

Thanks for any help. 5 bots are dead since July 7th.

**Comment by IcyApril** [comment]
@prandam Can you please post the following information:

* PHP Version (running ````php -v````)
* OpenSSL version (running ````openssl version````)

Can you also post the output of the following commands:

* ````curl -v https://api.twitter.com/1.1/help/tos.json````
* ````openssl s_client -connect api.twitter.com:443````

In your case, I suspect it's likely your OpenSSL version being outdated instead of a bug in the codebase itself.

**Comment by prandam** [comment]
The following PHP versions are on the server:

root@linkko [~]# php -v
PHP 5.2.17 (cli) (built: Jul 25 2012 07:41:05) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.2.0, Copyright (c) 1998-2010 Zend Technologies
with the ionCube PHP Loader v4.2.2, Copyright (c) 2002-2012, by ionCube Ltd., and
with Zend Optimizer v3.3.9, Copyright (c) 1998-2009, by Zend Technologies

root@linkko [~]# /opt/php56/bin/php -v
PHP 5.6.18 (cli) (built: Feb 15 2016 22:34:05) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.0.19, Copyright (c) 2002-2015, by ionCube Ltd.
with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies

root@linkko [~]# openssl version
OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

Please note that this version of OpenSSL is backported with updates, pursuant to Centos' release chain so it was not last updated at the above date:

root@linkko [~]# rpm -qi openssl-0.9.8e-40.el5_11
Name : openssl Relocations: (not relocatable)
Version : 0.9.8e Vendor: CentOS
Release : 40.el5_11 Build Date: Tue 31 May 2016 06:51:07 AM CDT
Install Date: Wed 01 Jun 2016 01:12:20 AM CDT Build Host: sclbuild-c5.centos.org
Group : System Environment/Libraries Source RPM: openssl-0.9.8e-40.el5_11.src.rpm
Size : 4061754 License: BSDish
Signature : DSA/SHA1, Tue 31 May 2016 07:09:04 AM CDT, Key ID a8a447dce8562897
Packager : CentOS BuildSystem <http://bugs.centos.org>
URL : http://www.openssl.org/
Summary : The OpenSSL toolkit
Description :
The OpenSSL toolkit provides support for secure communications between
machines. OpenSSL includes a certificate management tool and shared
libraries which provide various cryptographic algorithms and
protocols.

root@linkko [~]# curl -v https://api.twitter.com/1.1/help/tos.json
* About to connect() to api.twitter.com port 443
* Trying 199.59.149.232... connected
* Connected to api.twitter.com (199.59.149.232) port 443
* successfully set certificate verify locations:
* CAfile: /etc/pki/tls/certs/ca-bundle.crt
CApath: none
* SSLv3, TLS handshake, Client hello (1):
SSLv3, TLS handshake, Server hello (2):
SSLv3, TLS handshake, CERT (11):
SSLv3, TLS handshake, Server finished (14):
SSLv3, TLS handshake, Client key exchange (16):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSL connection using AES128-SHA
* Server certificate:
* subject: /C=US/ST=California/L=San Francisco/O=Twitter, Inc./OU=Twitter Security/CN=api.twitter.com
* start date: 2016-06-29 00:00:00 GMT
* expire date: 2019-09-19 12:00:00 GMT
* subjectAltName: api.twitter.com matched
* issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
* SSL certificate verify ok.
> GET /1.1/help/tos.json HTTP/1.1
> User-Agent: curl/7.15.5 (i386-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
> Host: api.twitter.com
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< content-length: 62
< content-type: application/json; charset=utf-8
< date: Sat, 15 Oct 2016 22:27:38 GMT
< server: tsa_a
< set-cookie: guest_id=v1%3A1**CC-Redacted**7; Domain=.twitter.com; Path=/; Expires=Mon, 15-Oct-2018 22:27:38 UTC
< strict-transport-security: max-age=631138519
< x-connection-hash: d3f5d94684d9bc94fbb9d2465965feee
< x-response-time: 3
Connection #0 to host api.twitter.com left intact
* Closing connection #0
* SSLv3, TLS alert, Client hello (1):
{"errors":[{"code":215,"message":"Bad Authentication data."}]}



root@linkko [~]# openssl s_client -connect api.twitter.com:443
CONNECTED(00000003)
depth=2 /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
verify return:1
depth=1 /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
verify return:1
depth=0 /C=US/ST=California/L=San Francisco/O=Twitter, Inc./OU=Twitter Security/CN=api.twitter.com
verify return:1
---
Certificate chain
0 s:/C=US/ST=California/L=San Francisco/O=Twitter, Inc./OU=Twitter Security/CN=api.twitter.com
i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIG7TCCBdWgAwIBAgIQAjuhPSkAdiueJFb7i9EUpTANBgkqhkiG9w0BAQsFADBw
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMS8wLQYDVQQDEyZEaWdpQ2VydCBTSEEyIEhpZ2ggQXNz
dXJhbmNlIFNlcnZlciBDQTAeFw0xNjA2MjkwMDAwMDBaFw0xOTA5MTkxMjAwMDBa
MIGHMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
U2FuIEZyYW5jaXNjbzEWMBQGA1UEChMNVHdpdHRlciwgSW5jLjEZMBcGA1UECxMQ
VHdpdHRlciBTZWN1cml0eTEYMBYGA1UEAxMPYXBpLnR3aXR0ZXIuY29tMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy3yNPYx3dWavH537Rqj+rx8nHCuc
/cKUvco6JpyMkRdW065Qbu8cUVdb6sVaWfu6AJRM1LPf9ZYVCPL7fnHL5lbbbcO3
AevUtzas2569RN0i2KTjauAXzXpxMAxOZVxAD0Rlkolztl/2rhoOHQ6SHPS6XuaP
Bq2q0V5uk9mSiSMw1tf8NUjnRfBjQx0iBmK5+UK1xgg1PcOdWJLaBFMppTQQJ+CR
5VIbSqk6tbnIir7TA23r1FGhsTzuuqFAnfv73qiRAZIJVeWlp9TnUo9xv3r1048Y
4UO2gX7viJhTVM5mBs+uUFO1njYx36A/3E4x9j+kaNb3/JklPrHrUng/EwIDAQAB
o4IDaTCCA2UwHwYDVR0jBBgwFoAUUWj/kK8CB3U8zNllZGKiErhZcjswHQYDVR0O
BBYEFAHDlorNvVeuffr/lVIxFgjPI6n5MBoGA1UdEQQTMBGCD2FwaS50d2l0dGVy
LmNvbTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
BwMCMHUGA1UdHwRuMGwwNKAyoDCGLmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9z
aGEyLWhhLXNlcnZlci1nNS5jcmwwNKAyoDCGLmh0dHA6Ly9jcmw0LmRpZ2ljZXJ0
LmNvbS9zaGEyLWhhLXNlcnZlci1nNS5jcmwwTAYDVR0gBEUwQzA3BglghkgBhv1s
AQEwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAI
BgZngQwBAgIwgYMGCCsGAQUFBwEBBHcwdTAkBggrBgEFBQcwAYYYaHR0cDovL29j
c3AuZGlnaWNlcnQuY29tME0GCCsGAQUFBzAChkFodHRwOi8vY2FjZXJ0cy5kaWdp
Y2VydC5jb20vRGlnaUNlcnRTSEEySGlnaEFzc3VyYW5jZVNlcnZlckNBLmNydDAM
BgNVHRMBAf8EAjAAMIIBfQYKKwYBBAHWeQIEAgSCAW0EggFpAWcAdgCkuQmQtBhY
FIe7E6LMZ3AKPDWYBPkb37jjd80OyA3cEAAAAVWdmMr4AAAEAwBHMEUCIQCQUvhG
NG7+N1Xo9f3E25SlJ/8usQcdCRE5u1p0VJ//rAIgf3nlBm7rfQpgMZL38+B3pRR9
IxXyVbuQEniK8PjBSLEAdgBo9pj4H2SCvjqM7rkoHUz8cVFdZ5PURNEKZ6y7T0/7
xAAAAVWdmMrBAAAEAwBHMEUCIBCNwVKGM8jDZs7O6hGlONYxaOLejyoThlpAgmv3
9eMIAiEA2cVpcpKd2/yH56tC4hCaDmM5b6jt6370I6QFxp9N7IYAdQBWFAaaL9fC
7NP14b1Esj7HRna5vJkRXMDvlJhV1onQ3QAAAVWdmMsZAAAEAwBGMEQCICAGREvt
7MRtTWlc0zZ08iXkamIG4Yfxd8+XwUc4lG03AiAAyVG+izt54YWq5hac+rMM6lWB
Qh7Aitqhx96/0RpSazANBgkqhkiG9w0BAQsFAAOCAQEALVcWzgKiGIFkLpkg4V8d
9GadO++rbhfnElaQDT5gloMIz0x2e5HZ5uLBNgPDmh9thZj3UL5g12bgGxrk4atf
3hQlAEsR1t+JgvlFTMqqSfbxl9rk6L3QpHd0AVNfPgbKVnY0FCQhVPoeJx/4S+MY
qrLdjeTOPnr2OaF+BQtJ4hfjWE8cK7xpXh9yJMoIoCuBv6SlA7uYujPBpzdtlCxZ
HyrIuv+BoKG1s/IsTWl70A916W04fC2tCL+clkYZipWOK2RxVL5cDBA2vQr1WAxQ
8rnHj2pfI4Q9A3RYiwiEa7T4hFjN685UL0LUfJQGDJZqTFbrXDanJhPnfCL5FuOA
yA==
-----END CERTIFICATE-----
subject=/C=US/ST=California/L=San Francisco/O=Twitter, Inc./OU=Twitter Security/CN=api.twitter.com
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
---
No client certificate CA names sent
---
SSL handshake has read 3122 bytes and written 414 bytes
---
New, TLSv1/SSLv3, Cipher is AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
Protocol : TLSv1
Cipher : AES128-SHA
Session-ID: 
Session-ID-ctx: 
Master-Key: C9A019D53EDCA4802DE78DE7F74778AC0AA2D8AAF964A242ADACB5FD27A33AECB7AD099ED5B2B1B9797BD027105799C8
Key-Arg : None
Krb5 Principal: None
Start Time: 1476570486
Timeout : 300 (sec)
Verify return code: 0 (ok)
---

**Comment by prandam** [comment]
The following PHP versions are on the server:

root@linkko [~]# php -v
PHP 5.2.17 (cli) (built: Jul 25 2012 07:41:05) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.2.0, Copyright (c) 1998-2010 Zend Technologies
with the ionCube PHP Loader v4.2.2, Copyright (c) 2002-2012, by ionCube Ltd., and
with Zend Optimizer v3.3.9, Copyright (c) 1998-2009, by Zend Technologies

root@linkko [~]# /opt/php56/bin/php -v
PHP 5.6.18 (cli) (built: Feb 15 2016 22:34:05) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.0.19, Copyright (c) 2002-2015, by ionCube Ltd.
with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies

root@linkko [~]# openssl version
OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

Please note that this version of OpenSSL is backported with updates, pursuant to Centos' release chain so it was not last updated at the above date:

root@linkko [~]# rpm -qi openssl-0.9.8e-40.el5_11
Name : openssl Relocations: (not relocatable)
Version : 0.9.8e Vendor: CentOS
Release : 40.el5_11 Build Date: Tue 31 May 2016 06:51:07 AM CDT
Install Date: Wed 01 Jun 2016 01:12:20 AM CDT Build Host: sclbuild-c5.centos.org
Group : System Environment/Libraries Source RPM: openssl-0.9.8e-40.el5_11.src.rpm
Size : 4061754 License: BSDish
Signature : DSA/SHA1, Tue 31 May 2016 07:09:04 AM CDT, Key ID a8a447dce8562897
Packager : CentOS BuildSystem <http://bugs.centos.org>
URL : http://www.openssl.org/
Summary : The OpenSSL toolkit
Description :
The OpenSSL toolkit provides support for secure communications between
machines. OpenSSL includes a certificate management tool and shared
libraries which provide various cryptographic algorithms and
protocols.

root@linkko [~]# curl -v https://api.twitter.com/1.1/help/tos.json
* About to connect() to api.twitter.com port 443
* Trying 199.59.149.232... connected
* Connected to api.twitter.com (199.59.149.232) port 443
* successfully set certificate verify locations:
* CAfile: /etc/pki/tls/certs/ca-bundle.crt
CApath: none
* SSLv3, TLS handshake, Client hello (1):
SSLv3, TLS handshake, Server hello (2):
SSLv3, TLS handshake, CERT (11):
SSLv3, TLS handshake, Server finished (14):
SSLv3, TLS handshake, Client key exchange (16):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSL connection using AES128-SHA
* Server certificate:
* subject: /C=US/ST=California/L=San Francisco/O=Twitter, Inc./OU=Twitter Security/CN=api.twitter.com
* start date: 2016-06-29 00:00:00 GMT
* expire date: 2019-09-19 12:00:00 GMT
* subjectAltName: api.twitter.com matched
* issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
* SSL certificate verify ok.
> GET /1.1/help/tos.json HTTP/1.1
> User-Agent: curl/7.15.5 (i386-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
> Host: api.twitter.com
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< content-length: 62
< content-type: application/json; charset=utf-8
< date: Sat, 15 Oct 2016 22:27:38 GMT
< server: tsa_a
< set-cookie: guest_id=v1%3A1**CC-Redacted**7; Domain=.twitter.com; Path=/; Expires=Mon, 15-Oct-2018 22:27:38 UTC
< strict-transport-security: max-age=631138519
< x-connection-hash: d3f5d94684d9bc94fbb9d2465965feee
< x-response-time: 3
Connection #0 to host api.twitter.com left intact
* Closing connection #0
* SSLv3, TLS alert, Client hello (1):
{"errors":[{"code":215,"message":"Bad Authentication data."}]}



root@linkko [~]# openssl s_client -connect api.twitter.com:443
CONNECTED(00000003)
depth=2 /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
verify return:1
depth=1 /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
verify return:1
depth=0 /C=US/ST=California/L=San Francisco/O=Twitter, Inc./OU=Twitter Security/CN=api.twitter.com
verify return:1
---
Certificate chain
0 s:/C=US/ST=California/L=San Francisco/O=Twitter, Inc./OU=Twitter Security/CN=api.twitter.com
i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIG7TCCBdWgAwIBAgIQAjuhPSkAdiueJFb7i9EUpTANBgkqhkiG9w0BAQsFADBw
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMS8wLQYDVQQDEyZEaWdpQ2VydCBTSEEyIEhpZ2ggQXNz
dXJhbmNlIFNlcnZlciBDQTAeFw0xNjA2MjkwMDAwMDBaFw0xOTA5MTkxMjAwMDBa
MIGHMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
U2FuIEZyYW5jaXNjbzEWMBQGA1UEChMNVHdpdHRlciwgSW5jLjEZMBcGA1UECxMQ
VHdpdHRlciBTZWN1cml0eTEYMBYGA1UEAxMPYXBpLnR3aXR0ZXIuY29tMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy3yNPYx3dWavH537Rqj+rx8nHCuc
/cKUvco6JpyMkRdW065Qbu8cUVdb6sVaWfu6AJRM1LPf9ZYVCPL7fnHL5lbbbcO3
AevUtzas2569RN0i2KTjauAXzXpxMAxOZVxAD0Rlkolztl/2rhoOHQ6SHPS6XuaP
Bq2q0V5uk9mSiSMw1tf8NUjnRfBjQx0iBmK5+UK1xgg1PcOdWJLaBFMppTQQJ+CR
5VIbSqk6tbnIir7TA23r1FGhsTzuuqFAnfv73qiRAZIJVeWlp9TnUo9xv3r1048Y
4UO2gX7viJhTVM5mBs+uUFO1njYx36A/3E4x9j+kaNb3/JklPrHrUng/EwIDAQAB
o4IDaTCCA2UwHwYDVR0jBBgwFoAUUWj/kK8CB3U8zNllZGKiErhZcjswHQYDVR0O
BBYEFAHDlorNvVeuffr/lVIxFgjPI6n5MBoGA1UdEQQTMBGCD2FwaS50d2l0dGVy
LmNvbTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
BwMCMHUGA1UdHwRuMGwwNKAyoDCGLmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9z
aGEyLWhhLXNlcnZlci1nNS5jcmwwNKAyoDCGLmh0dHA6Ly9jcmw0LmRpZ2ljZXJ0
LmNvbS9zaGEyLWhhLXNlcnZlci1nNS5jcmwwTAYDVR0gBEUwQzA3BglghkgBhv1s
AQEwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAI
BgZngQwBAgIwgYMGCCsGAQUFBwEBBHcwdTAkBggrBgEFBQcwAYYYaHR0cDovL29j
c3AuZGlnaWNlcnQuY29tME0GCCsGAQUFBzAChkFodHRwOi8vY2FjZXJ0cy5kaWdp
Y2VydC5jb20vRGlnaUNlcnRTSEEySGlnaEFzc3VyYW5jZVNlcnZlckNBLmNydDAM
BgNVHRMBAf8EAjAAMIIBfQYKKwYBBAHWeQIEAgSCAW0EggFpAWcAdgCkuQmQtBhY
FIe7E6LMZ3AKPDWYBPkb37jjd80OyA3cEAAAAVWdmMr4AAAEAwBHMEUCIQCQUvhG
NG7+N1Xo9f3E25SlJ/8usQcdCRE5u1p0VJ//rAIgf3nlBm7rfQpgMZL38+B3pRR9
IxXyVbuQEniK8PjBSLEAdgBo9pj4H2SCvjqM7rkoHUz8cVFdZ5PURNEKZ6y7T0/7
xAAAAVWdmMrBAAAEAwBHMEUCIBCNwVKGM8jDZs7O6hGlONYxaOLejyoThlpAgmv3
9eMIAiEA2cVpcpKd2/yH56tC4hCaDmM5b6jt6370I6QFxp9N7IYAdQBWFAaaL9fC
7NP14b1Esj7HRna5vJkRXMDvlJhV1onQ3QAAAVWdmMsZAAAEAwBGMEQCICAGREvt
7MRtTWlc0zZ08iXkamIG4Yfxd8+XwUc4lG03AiAAyVG+izt54YWq5hac+rMM6lWB
Qh7Aitqhx96/0RpSazANBgkqhkiG9w0BAQsFAAOCAQEALVcWzgKiGIFkLpkg4V8d
9GadO++rbhfnElaQDT5gloMIz0x2e5HZ5uLBNgPDmh9thZj3UL5g12bgGxrk4atf
3hQlAEsR1t+JgvlFTMqqSfbxl9rk6L3QpHd0AVNfPgbKVnY0FCQhVPoeJx/4S+MY
qrLdjeTOPnr2OaF+BQtJ4hfjWE8cK7xpXh9yJMoIoCuBv6SlA7uYujPBpzdtlCxZ
HyrIuv+BoKG1s/IsTWl70A916W04fC2tCL+clkYZipWOK2RxVL5cDBA2vQr1WAxQ
8rnHj2pfI4Q9A3RYiwiEa7T4hFjN685UL0LUfJQGDJZqTFbrXDanJhPnfCL5FuOA
yA==
-----END CERTIFICATE-----
subject=/C=US/ST=California/L=San Francisco/O=Twitter, Inc./OU=Twitter Security/CN=api.twitter.com
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
---
No client certificate CA names sent
---
SSL handshake has read 3122 bytes and written 414 bytes
---
New, TLSv1/SSLv3, Cipher is AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
Protocol : TLSv1
Cipher : AES128-SHA
Session-ID: 
Session-ID-ctx: 
Master-Key: C9A019D53EDCA4802DE78DE7F74778AC0AA2D8AAF964A242ADACB5FD27A33AECB7AD099ED5B2B1B9797BD027105799C8
Key-Arg : None
Krb5 Principal: None
Start Time: 1476570486
Timeout : 300 (sec)
Verify return code: 0 (ok)
---

**Comment by abraham** [comment]
Did you get this figured out?

**Comment by emmanuelr20** [comment]
You just need to append your site SSL certificate to the cacert.pem file so twitter can get confirm the certificate.
