### ISSUE TITLE
Can not display data from twitter!!!!

### ISSUE THREAD

**Issue by yifeilyf** [abraham/twitteroauth#488]
The following images are the operations that I did.
![1](https://cloud.githubusercontent.com/assets/12167107/17426652/7b7cc34a-5b0c-11e6-926d-d41d32f9efed.png)
The following is what the console shows:
![2](https://cloud.githubusercontent.com/assets/12167107/17426659/8c0c2e4e-5b0c-11e6-826f-90861947e761.png)
Then I use get method based on your instruction below
![3](https://cloud.githubusercontent.com/assets/12167107/17426671/b0f3f1ba-5b0c-11e6-95d1-bf1d329a9c40.png)
That is my details:
![4](https://cloud.githubusercontent.com/assets/12167107/17426685/d4027852-5b0c-11e6-8a8a-29de034b2bb7.png)
Then I put everything together
![5](https://cloud.githubusercontent.com/assets/12167107/17426783/bc6f1be0-5b0d-11e6-8a9f-533994324be5.png)

The code is: 
$tweets = $connection->get("https://api.twitter.com/1.1/search/tweets.json", ["q" => "%23freebandnames", "since_id"=>24012619984051000,"max_id" =>250126199840518145, "result_type"=>"mixed", "count"=>4]);

After print $tweets display like this rather than any data:
![7](https://cloud.githubusercontent.com/assets/12167107/17426863/8b47e4e2-5b0e-11e6-980a-c8e562497659.png)

What do I miss? 

Many thanks

**Comment by yifeilyf** [comment]
I use localhost. Is that problem caused by localhost?

**Comment by yifeilyf** [comment]
I try another way:
![8](https://cloud.githubusercontent.com/assets/12167107/17427904/d87f8d48-5b16-11e6-8877-1735f8734c7e.png)

![9](https://cloud.githubusercontent.com/assets/12167107/17427910/dfa35bc2-5b16-11e6-8f78-3ef46bd78421.png)

Then still same problem.

**Comment by hborras** [comment]
As you can see here : https://twitteroauth.com/

You should use the methods in this way: 

$statuses = $connection->get("statuses/home_timeline", ["count" => 25, "exclude_replies" => true]);

**Comment by yifeilyf** [comment]
I tried that one. According to the details about mine.
![11](https://cloud.githubusercontent.com/assets/12167107/17428447/05430ca2-5b1b-11e6-9225-a419206506c5.png)

There is no anything request query after statuses/home_timeline.
So i type: $tweets = $connection->get("https://api.twitter.com/1.1/statuses/home_timeline.json");
But still not working.

Thanks for your help

**Comment by abraham** [comment]
You need to use the TwitterOAuth API as defined on https://twitteroauth.com. It does not support full URLs, only the Twitter API *paths*. The URL and `.json` will automatically be added by they library.

    $tweets = $connection->get("statuses/home_timeline");

**Comment by yifeilyf** [comment]
Thanks so much. I think I totally understand.
