### ISSUE TITLE
Bad Authentication Data

### ISSUE THREAD

**Issue by GuardianMajor** [abraham/twitteroauth#491]
I have just started working with this wrapper and I am sorry if my question has been asked, answered, or is wrong; but I would appreciate a bit of assistance getting it ironed out.

Now, I KNOW my `cosumer_key`, `consumer_key_secret`, `access_token` and `access_token_secret` are correct, valid and functioning just fine using the "signature generator" tool on Twitter's dev site.

So short of me doing something wrong on the coding end, it should work but I am getting:

> object(stdClass)# 132 (1) { ["errors"]=> array(1) { [0]=> object(stdClass)# 127 (2) { ["code"]=> int(215) ["message"]=> string(24) "Bad Authentication data." } } }

I have a very simple skeleton code to test the library and make sure it works before doing too much on it, so here is the code:

```
<?php

require "twitteroauth/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;

$c_key = "...REMOVED...IS-VALID...";
$c_sec = "...REMOVED...IS-VALID...";
$a_tok = "...REMOVED...IS-VALID...";
$a_tos = "...REMOVED...IS-VALID...";

function getConnectionWithAccessToken($oauth_token, $oauth_token_secret) {
	$connection = new TwitterOAuth($c_key, $c_sec, $oauth_token, $oauth_token_secret);
	return $connection;
}

$connection = getConnectionWithAccessToken($a_tok, $a_tos);
$statuses = $connection->get("statuses/home_timeline", ["count" => 200, "exclude_replies" => false, "contributor_details" => true, "include_entities" => true]);
var_dump($statuses);

?>
```
So am I doing some completely brain dead noobie stupid? I can't imagine why it won't work, although using this library is new to me, shouldn't really change the underlying principle of using a PHP class, which I have done and do all the time and I suspect will do until I die :)

Any assist on this would be greatly appreciated. All I am doing BTW, is simply pulling my `HOME_TIMELINE` which includes my posts, replies, reposts, and basically any post by only those that I follow, just a bit of context of what I am doing, in fact I am doing this JUST FOR ME, and so the app is set to read-only because I am just PULLING, not pushing anything back.

**Comment by k1sul1** [comment]
Your variables are out of scope. You're referring to $c_key and $c_sec in your connection function, but you're never passing them into the function scope. 

If you'd add `global $c_key, $c_sec;` as the first line in your connection function, this particular example should work. 

http://php.net/manual/en/language.variables.scope.php

**Comment by GuardianMajor** [comment]
@k1sul1 thank you for the reply, in the code as presented you are right it would be like that. Unfortunately more than two months have passed and when I didn't hear back, I already worked out another solution to it and moved on. 

Scope wasn't the issue and I would have loved to discuss it but since there is/was such delayed responses, yet followed by quick closures without knowing if it was even right, I won't waste anyone's time explaining it here since no one seems to actually be interested. 

But thanks none the less.

**Comment by abraham** [comment]
@GuardianMajor Sorry you didn't get a timely response. Most of the support on this project is provided by me, in my spare time, with no monetary compensation when I'm not busy with my job or other responsibilities. Issues are closed quickly with the expectation that if issues persist they can be reopened.

**Comment by GuardianMajor** [comment]
@abraham I understand and its fine - same boat for me and I suspect most of us. Although I have never found the "I am doing it for free" to be a good motto for any developer to make excuses; being one myself I do it because I want to and I don't complain when its free and makes no money. After all, you are welcome to stop but until then we are responsible for what we create. That's all. Thanks for your work and good luck with everything.
