### ISSUE TITLE
oauth_body_hash missing

### ISSUE THREAD

**Issue by archonkulis** [abraham/twitteroauth#493]
For some Twitter requests ( e.g. uploading to TON Api - "/1.1/ton/bucket/ta_partner" ) there is required 'oauth_body_hash' variable in "Authorization" header. Would be good if this library could include it as well.

**Comment by abraham** [comment]
TwitterOAuth is in maintenance mode and major improvements are no longer planned. https://github.com/abraham/twitteroauth/issues/1188
