### ISSUE TITLE
Fatal error: Class 'Abraham\TwitterOAuth\Config' not found home/sites/saidomainnamewillwork.com/public_html/twitter/src/TwitterOAuth.php on line 19

### ISSUE THREAD

**Issue by jaydurga** [abraham/twitteroauth#494]
Dear Mr.Abraham,
                            I am getting the error mentioned above, when I run twitter.php.

This is my twitter.php file.
<?php

 session_start();

include("twitter/autoload.php"); 
include("src/TwitterOAuth.php"); 
use Abraham\TwitterOAuth\TwitterOAuth;

$apikey = "";
$apisecret = "";
$accesstoken = "";
$accesssecret = "";

$connection = new TwitterOAuth($apikey,$apisecret,$accesstoken,$accesssecret);  

$tweets = $connection->get("https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=twitterapi&count=2");

print_r($tweets);

?>

This is TwitterOAuth.php (stored in folder twitter/src/TwitterOAuth.php).

https://jsbin.com/seceyogihe/edit?html

I am using version PHP version 5.5.  I need your help. 

url link :http://176.32.230.251/saidomainnamewillwork.com/twitter/twitter.php
Thanks,
jay

**Comment by abraham** [comment]
Make sure you follow the install instructions on https://twitteroauth.com/
