### ISSUE TITLE
Retrieve user's email upon oauth sign up

### ISSUE THREAD

**Issue by gutibs** [abraham/twitteroauth#495]
Hey, have your class installed and works like a charm, but i'd like to retrieve the user's email address in order to save it into my database for login purposes of my app.
Added this bit of code to the request user's info, but getting an error
$user = $connection->get("account/verify_credentials", ['include_email' => 'true']);

And this is the error i'm getting: This feature is temporarily unavailable 

Can you help me on this?
Thanks!

**Comment by abraham** [comment]
> This feature is temporarily unavailable

Sounds like Twitter temporarily disabled something. Hopefully they'll bring it back soon.

**Comment by gutibs** [comment]
Wow, that was fast, will keep checking from time to time, thanks

**Comment by NitinPrakash** [comment]
This is working fine 
$user = $connection->get("account/verify_credentials", ['include_email' => 'true']);

I am able to fetch user email address. Thanks
