### ISSUE TITLE
User and its behaviors do not have a method or closure named "notsafe".

### ISSUE THREAD

**Issue by sugumarv** [abraham/twitteroauth#496]
in the call back url (http://mysite.com/index.php/site/TwitterCallBack?oauth_token=yfXRagAAAAAAwl8jh4urytjdheDU&oauth_verifier=r6Ga9X87vM2Nchduj3ndkoehdBuhltjZ) it shows the error 

User and its behaviors do not have a method or closure named "notsafe".
update  I removed notsafe() from the following line
$olduser=User::model()->notsafe()->findByAttributes(array('twid'=>$twuser->id));
so the line becomes 
$olduser=User::model()->findByAttributes(array('twid'=>$twuser->id));

after that it showed tbl_user doesn't have a column named twig
so I added twig column in tbl_user

Now it shows the following error 

include(Profile.php): failed to open stream: No such file or directory
I am not using yii user what should I do now
please help me

**Comment by abraham** [comment]
`User::model()->notsafe()` is not related to this library. I suggest you try posting to a Yii developer community or wherever you originally got that code.
