### ISSUE TITLE
count give me wrong tweets

### ISSUE THREAD

**Issue by PouriaParhami** [abraham/twitteroauth#497]
Hello dear abraham
i use this code to get user tweets and show them .
$tweets = $connection->get("statuses/user_timeline", ["count" => $tweet_count, "exclude_replies" => true, "screen_name" => $username]);
        foreach ($tweets as $tweet) {
            echo "<p> $tweet->text </p></br>";
        }
i set $tweet_count = 5 , but i get 2 tweet not 5 tweet , what is wrong in my code ???

**Comment by agaleski** [comment]
Quoted from https://dev.twitter.com/rest/reference/get/statuses/user_timeline

> **count**
> Specifies the number of tweets to try and retrieve, up to a maximum of 200 per distinct request. The value of count is best thought of as a limit to the number of tweets to return because suspended or deleted content is removed after the count has been applied. We include retweets in the count, even if include_rts is not supplied. It is recommended you always send include_rts=1 when using this API method.

So the Retweets included in your received tweet object are counted as well. So you actually got 2 entire tweets with retweets wich equals a limit/count of 4.

Reading the documentation of an api you want to use, often helps to solve issues quickly.

**Comment by abraham** [comment]
Yep, think of of `count` as the max that will be returned, not the exact number.
