### ISSUE TITLE
page doesn't exist

### ISSUE THREAD

**Issue by jxks** [abraham/twitteroauth#498]
Hi, Mr. Abraham,

I'm getting this error to my page:
{"errors":[{"message":"Sorry, that page does not exist","code":34}]}

i followed the instructions from this site:
https://webdevdoor.com/php/authenticating-twitter-feed-timeline-oauth

but i'm still getting an error.

Folder structure:
-twitter
--index.php
-- twitteroauth (folder)
   --- src (folder)
   --- tests (folder)
   --- autoload.php
   --- composter.json
   --- ( & etc)

Here's my code:

<?php
session_start();
  require "twitteroauth/autoload.php";
        use Abraham\TwitterOAuth\TwitterOAuth;
 
$twitteruser = "xxx";
$notweets = 30;
$consumerkey = "xxx";
$consumersecret = "xxx";
$accesstoken = "xxx";
$accesstokensecret = "xxx";
 
function getConnectionWithAccessToken($cons_key, $cons_secret, $oauth_token, $oauth_token_secret) {
  $connection = new TwitterOAuth($cons_key, $cons_secret, $oauth_token, $oauth_token_secret);
  return $connection;
}
 
$connection = getConnectionWithAccessToken($consumerkey, $consumersecret, $accesstoken, $accesstokensecret);
 
$tweets = $connection->get("https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=".$twitteruser."&count=".$notweets);
 
echo json_encode($tweets);
?>

**Comment by abraham** [comment]
This isn't the correct use of the TwitterOAuth API:
```
$connection->get("https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=".$twitteruser."&count=".$notweets);
```
It should conform the the examples listed on https://twitteroauth.com which would look like this:
```
$connection->get("statuses/user_timeline", ["screen_name" => $twitteruser, "count" => $notweets');
```
