### ISSUE TITLE
Resolving timed out after 5515 milliseconds 

### ISSUE THREAD

**Issue by fatihjy** [abraham/twitteroauth#502]
When using users/lookup method for around 5000 - 6000  user ids everything works fine, but when using the same method for more user ids I receive the following error followed by 500 internal server error. 

[Thu Oct 13 09:02:52.417310 2016] [:error] [pid 1286] PHP Fatal error:  Uncaught Abraham\\TwitterOAuth\\TwitterOAuthException: Resolving timed out after 5515 milliseconds in /home/admin/web /public_html/extract/vendor/abraham/twitteroauth/src/TwitterOAuth.php:409\nStack trace:\n#0 /home/admin/web /public_html/extract/vendor/abraham/twitteroauth/src/TwitterOAuth.php(334): Abraham\\TwitterOAuth\\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array)\n#1 /home/admin/web /public_html/extract/vendor/abraham/twitteroauth/src/TwitterOAuth.php(305): Abraham\\TwitterOAuth\\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array)\n#2 /home/admin/web /public_html/extract/vendor/abraham/twitteroauth/src/TwitterOAuth.php(192): Abraham\\TwitterOAuth\\TwitterOAuth->http('POST', 'https://api.twi...', 'users/lookup', Array)\n#3 /home/admin/web/public_html/extract/extractor.php(38): Abraham\\TwitterOAuth\\TwitterOAuth->post('users/lookup', Array)\n#4 {main}\n  thrown in /home/admin/web /public_html/extract/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 409

**Comment by abraham** [comment]
Check out Changing timeout settings on https://twitteroauth.com/
