### ISSUE TITLE
Explore switching to Hack

### ISSUE THREAD

**Issue by abraham** [abraham/twitteroauth#503]
https://code.facebook.com/posts/398235553660954/announcing-the-hack-transpiler/

**Comment by abraham** [comment]
PHP7 seems to be showing a lot of the benefits of HHVM with a more stable runtime so it might be better to look into a more standard PHP type enforcement instead of Hack.

https://slack.engineering/taking-php-seriously-cf7a60065329

**Comment by FedgeNo** [comment]
I would personally avoid any machine generated code in my own projects for debugging reasons. I'm not sure what the output of the transpiler looks like but I generally do better debugging my own code than something someone (or something) else wrote.
