### ISSUE TITLE
Fatal error after forwarding domain name

### ISSUE THREAD

**Issue by chengLA** [abraham/twitteroauth#506]
Hello,

I forwarded our a new domain name to the old website domain name both are working. But When I am try to go to our website, this fatal error come out: 

Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Could not resolve host: api.twitter.com; Name or service not known' in /var/www/html/wp-content/themes/leaderaviation/includes/vendor/twitteroauth-master/src/TwitterOAuth.php:403 Stack trace: #0 /var/www/html/wp-content/themes/leaderaviation/includes/vendor/twitteroauth-master/src/TwitterOAuth.php(163): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array) #1 /var/www/html/wp-content/themes/leaderaviation/pages-templates/front-page.php(15): Abraham\TwitterOAuth\TwitterOAuth->oauth2('oauth2/token', Array) #2 /var/www/html/wp-includes/template-loader.php(75): include('/var/www/html/w...') #3 /var/www/html/wp-blog-header.php(19): require_once('/var/www/html/w...') #4 /var/www/html/index.php(17): require('/var/www/html/w...') #5 {main} thrown in /var/www/html/wp-content/themes/leaderaviation/includes/vendor/twitteroauth-master/src/TwitterOAuth.php on line 403

Can you please help me as soon as possible? Thank you very much !!

**Comment by agaleski** [comment]
https://news.ycombinator.com/item?id=12759520 - DYN failed, taking twitter, github and more with it :stuck_out_tongue:

**Comment by chengLA** [comment]
Thank you very much!!
