### ISSUE TITLE
require(): Failed opening required 'twitteroauth/autoload.php'

### ISSUE THREAD

**Issue by Anitha84** [abraham/twitteroauth#510]
Hi,
I am getting error in twitterapi.
fatal error: require(): Failed opening required 'twitteroauth/autoload.php'.
using php version:5.5

my code:

```
<?php

require "twitteroauth/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;

$apikey = "****";
$apisecret = "*****";
$accesstoken = "*****";
$accesstokensecret = "****";

$connection= new TwitterOAuth($apikey,$apisecret,$accesstoken,$accesstokensecret);
$content = $connection->get("account/verify_credentials");

print_r($content);
 
?>
```

**Comment by abraham** [comment]
Sounds like the `twitteroauth/autoload.php` file isn't there. How did you install TwitterOAuth?

**Comment by Anitha84** [comment]
No, the files are actually there in the server. i couldn't find an option to attach a screenshot here!
downloaded the zip file from https://github.com/abraham/twitteroauth, unzipped and uploaded to server.

**Comment by abraham** [comment]
Is it downloaded to the correct place? Did you rename the folder? By default it unzips to `twitteroauth-0.7.0` (or the current version number.)

**Comment by Anitha84** [comment]
It unzipped as twitteroauth-master. And yes, i renamed the folder as twitteroauth & placed it under public_html folder.

**Comment by abraham** [comment]
I took the exact code you included and put it in `index.php` in a folder `test`.

```
test
|-- index.php
```

Ran it and got the same `Fatal error: require(): Failed opening required 'twitteroauth/autoload.php'`.

I downloaded `twitteroauth-master.zip` to within the `test` folder, unzipped it and renamed the `twitteroauth-master` folder to `twitteroauth`.

```
test
|-- index.php
|-- twitteroauth-master.zip
|-- twitteroath
|    |-- autoload.php
|    |-- src
|    |-- etc...

```

Ran `index.php` again and the error was gone.

**Comment by Anitha84** [comment]
It works! Thanks a lot.

**Comment by robinbhatt4** [comment]
Fatal error: Uncaught Error: Class "Composer\CaBundle\CaBundle" not found in C:\xampp\htdocs\twitteroauth\src\TwitterOAuth.php:

I have installed the composer but still the code is not working

**Comment by abraham** [comment]
Maybe this will help: https://stackoverflow.com/a/64259837/26406. If not please open a new issues.

**Comment by robinbhatt4** [comment]
already done.....
not working ....
group of 5 software  engineers have also reported the same problem

**Comment by ho77iday** [comment]
Was a fix found? I've had this problem since the change on April 30th.

**Comment by robinbhatt4** [comment]
Nope, it wasn't fixed...

**Comment by abraham** [comment]
This is a very old issue. If you hare having problems please open a new one.
