### ISSUE TITLE
Desktop applications only support the oauth_callback value oob

### ISSUE THREAD

**Issue by GlauberF** [abraham/twitteroauth#512]
![erro t](https://cloud.githubusercontent.com/assets/11314585/20110358/3a3970d6-a5cb-11e6-993d-582a1949caf8.png)

**Comment by abraham** [comment]
Make sure you have a default callback URL configured on https://apps.twitter.com.

<img width="1040" alt="screen shot 2016-11-08 at 12 12 00" src="https://cloud.githubusercontent.com/assets/3341/20111103/a6d73fbc-a5ac-11e6-835e-65d7cad74d62.png">
