### ISSUE TITLE
Failed to connect to api.twitter.com port 443: Connection refused

### ISSUE THREAD

**Issue by yesimerden** [abraham/twitteroauth#513]
hello, I get this error code, can you help me?

> Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Failed to connect to api.twitter.com port 443: Connection refused' in /home/u409875123/public_html/twapp/src/TwitterOAuth.php:408 Stack trace: #0 /home/u409875123/public_html/twapp/src/TwitterOAuth.php(334): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array) #1 /home/u409875123/public_html/twapp/src/TwitterOAuth.php(135): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array) #2 /home/u409875123/public_html/twapp/index.php(11): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array) #3 {main} thrown in /home/u409875123/public_html/twapp/src/TwitterOAuth.php on line 408

**Comment by yesimerden** [comment]
**and this is my code:** 


<?php
session_start();
require 'autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;
define('CONSUMER_KEY', " "); 
define('CONSUMER_SECRET', " "); 
define('OAUTH_CALLBACK'," "); 
if (!isset($_SESSION['access_token'])) {
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
	$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
	$_SESSION['oauth_token'] = $request_token['oauth_token'];
	$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
	$url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
	echo $url;
} else {
	$access_token = $_SESSION['access_token'];
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token['oauth_token'], $access_token['oauth_token_secret']);
	$user = $connection->get("account/verify_credentials");
	echo $user->screen_name;
}

**Comment by abraham** [comment]
The error `Failed to connect to api.twitter.com port 443: Connection refused` generally means that your server can't connect to api.twitter.com. Sometimes that's caused by a firewall blocking connections, sometimes that's caused by your IP being blocked by Twitter, sometimes there is an ISP between your server and Twitter that is broken.

It's pretty much always not an issue with the TwitterOAuth library however.

**Comment by CangWriteCode** [comment]
I have the same wrong with you ,i'm from China , My English is poor , I'm not how to solve .

**Comment by abraham** [comment]
You will probably have to configure a proxy.

```
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$connection->setProxy([
    'CURLOPT_PROXY' => '127.0.0.0',
    'CURLOPT_PROXYUSERPWD' => 'secret',
    'CURLOPT_PROXYPORT' => 8080,
]);

// Make requests after this
```

**Comment by motyar** [comment]
Another reason I found is *curl* not enabled.

**Comment by mostafaznv** [comment]
> You will probably have to configure a proxy.
> 
> ```
> $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
> $connection->setProxy([
>     'CURLOPT_PROXY' => '127.0.0.0',
>     'CURLOPT_PROXYUSERPWD' => 'secret',
>     'CURLOPT_PROXYPORT' => 8080,
> ]);
> 
> // Make requests after this
> ```

why proxy type is not configurable?
I want to use socks5 proxy but package uses http proxy by default

**Comment by abraham** [comment]
Pull requests are welcome.

**Comment by jayarya588** [comment]
What will we do if we use OAuth 2.0 Bearer Token method and getting the same error ?

**Comment by abraham** [comment]
This issue is not related to the type of authentication. It's that your server can't make connections to Twitter's servers.
