### ISSUE TITLE
Unable to load the library

### ISSUE THREAD

**Issue by mayurvanza** [abraham/twitteroauth#514]
Hello,

Unable to load the library.

require "vendor/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);

$content = $connection->get("account/verify_credentials");

get 500 error, i also given permission to appropriate file but still display 500 error.

**Comment by abraham** [comment]
You need to look at your server logs and see what the error is.
