### ISSUE TITLE
Can't use function return value in write context

### ISSUE THREAD

**Issue by hdr105** [abraham/twitteroauth#515]
I am facing this error

> Fatal error: Can't use function return value in write context in /home/sajjonli/public_html/user_registration/src/TwitterOAuth.php on line 367

can you please help??

**Comment by abraham** [comment]
Please include more details about the error.

**Comment by Harinka** [comment]
I'm facing the same error : 

>  Fatal error: Can't use function return value in write context in ***/twitteroauth-master/src/TwitterOAuth.php on line 366

this is my test.php : 

`<?php
require_once 'autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;

define('CONSUMER_KEY', 'xxxxxxxxxxxxxxx'); // add your app consumer key between single quotes
define('CONSUMER_SECRET', 'xxxxxxxxxxxxxxxxxxxxxxxx'); // add your app consumer secret key between single quotes
define('OAUTH_CALLBACK', 'xxxxxxxxxxxxxxxx'); // your app callback URL

if (!isset($_SESSION['emetteur']['e_tokenTwitter']) || $_SESSION['emetteur']['e_tokenTwitter'] == '') {
    
    
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET,  "746349335982538752-h4FMNcXSYb8oskokoWUIoRV6jYaoxH4" , "qtaXYN993kTJLH62N91YJristWcTeHWIOL1dRhyxe5TQD"); //Throw the error
    
	$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
	$_SESSION['oauth_token'] = $request_token['oauth_token'];
	$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
	$url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
	echo $url;
    
} else {
    
	$access_token = $_SESSION['emetteur']['e_tokenTwitter'];
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET,  "xxxxxxxxxx" , "xxxxxxxxxxxxxxxxxxx");
	
	// getting basic user info
	$user = $connection->get("account/verify_credentials");
	
	// printing username on screen
	echo $user->screen_name;
	// posting tweet on user profile
	$post = $connection->post('statuses/update', array('status' => 'Test tweet'));
	// displaying response of $post object
	print_r($post);
    
}

?>`

Need some help

**Comment by abraham** [comment]
What OS and OS version are you running on? What PHP version?

**Comment by Harinka** [comment]
PHP v5.4.16
OS : Linux 3.14.32

**Comment by abraham** [comment]
PHP v5.4 is no longer supported and hasn't gotten any security updates in over a year. Upgrade to a current, secure version (v5.6+) and that should fix the issue.

https://secure.php.net/supported-versions.php
