### ISSUE TITLE
Fatal error: Class 'Phar' not found in [...]/abraham/twitteroauth/src/TwitterOAuth.php on line 366

### ISSUE THREAD

**Issue by solo14000** [abraham/twitteroauth#518]
Hello,

My host is One.com that does not support 'Phar' module. I have checked it with technical support.
I'm not using Phar but I get class not found exception mentionned in title.
Could it be possible to make a check on Phar availibility on TwitterOAuth.php line 366 before calling Phar to avoid exception?

Thanks.

Rodolphe

**Comment by abraham** [comment]
I'm thinking something along the lines of this should work.

```
private function pharRunning() {
  return class_exists('Phar') && !empty(\Phar::running(false));
}

```

@IcyApril you did the initial Phar change, does this seem reasonable?

**Comment by IcyApril** [comment]
@abraham That seems very sensible.

**Comment by abraham** [comment]
Deployed as 0.7.2
