### ISSUE TITLE
Tweets truncated/garbled

### ISSUE THREAD

**Issue by jjfster** [abraham/twitteroauth#527]
posted this in a couple of places, but no responses yet, so thought I would try here too:

When I try to grab tweets from a public timeline, many get truncated with garbage characters and I can't seem to grab the whole text.

I tried both the old and the new versions of twitteroauth that I could find.

This was running fine for a long time, so I'm sure it is something new to the API that I can't seem to identify.

I've tried adding extended mode with no luck (still garbaged out):

$res = $connection->get("https://api.twitter.com/1.1/statuses/user_timeline.json?user_id=".$id."&count=".$numTweets."&tweet_mode=extended");
Tried adding a curl-encoding option to twitteroauth, still truncated.

Tried using the new twitteroauth:

$res = $connection->get('statuses/user_timeline', array('screen_name' => $screenName));
Truncated, garbage.

PHP 5.6.8 (cli) (built: Apr 15 2015 15:07:09) Copyright (c) 1997-2015 The PHP Group Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

Here is an example. Could this be some memory issue? Any help would be greatly appreciated:

$res->fulltext DIRECTLY FROM RESPONSE GIVEN BY twitteroauth: "RT @GeoscienceAus: #PicOfTheDay of the #AliceSprings #satellite antenn a taken by the Chief of our #CommunitySafety & Earth Monitoring Div DΓÇª"

ACTUAL TWEET FROM twitter.com: "#PicOfTheDay of the #AliceSprings #satellite antenna taken by the Chief of our #CommunitySafety & Earth Monitoring Div Dr Andy Barnicoat!"

**Comment by abraham** [comment]
I'm not seeing this using TwitterOAuth or https://apigee.com/console/twitter. `tweet_mode=extended` or normal mode. My thoughts would be to make sure everything you are working with is using a consistent character encoding.

**Comment by jjfster** [comment]
It ended up being a Retweet issue.  I was using the tweet full_text field, but you are supposed to use the original, retweet_status full_text field, even though the tweet truncated field is incorrectly set to false.

Here is my post in the Twitter forum:

Sorry, this appears to be the solution. I was thrown at first when the truncated field was set to false, hadn't seen the ellipses before, and too lazy to actually count the characters:

"full_text": "RT @geomatlab: #Oceanography JGR: Using Landsat 8 data to estimate suspended particulate matter in the Yellow River estuary https://t.co/uI…",
"truncated": false,

I regret causing anyone any unnecessary work on this topic.
