### ISSUE TITLE
can't use function return value in write context

### ISSUE THREAD

**Issue by abunoor16** [abraham/twitteroauth#528]
hey
i try to login to twitter the problem is when i run files on localhost server it's work but when i upload it on the host server it's not work , 
[21-Dec-2016 04:31:24 America/Detroit] PHP Fatal error:  Can't use function return value in write context in /home/sarra76j/public_html/sec-app/src/TwitterOAuth.php on line 423

please i need for help

**Comment by abraham** [comment]
Are you on an outdated version of PHP like #515?

**Comment by mohamadou** [comment]
You can resolve the issue with this example below. Because in some version of php 5.5 empty() only supports variables
   private function pharRunning()
    {
        $phar_running = Phar::running(false);
        return class_exists('Phar') && !empty($phar_running);
    }

**Comment by abraham** [comment]
PHP 5.5 is no longer supported.

http://php.net/supported-versions.php
