### ISSUE TITLE
Your credentials do not allow access to this resource

### ISSUE THREAD

**Issue by Arsintorabi** [abraham/twitteroauth#531]
hi i cant use this..get this error  👍
 $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);		  
		   $connection->host = 'https://api.twitter.com/1.1/';
		   $connection->content_type = 'application/x-www-form-urlencoded';
		   $connection->ssl_verifypeer = TRUE;
		   $parameters = [
			    'status' => 'Meow Meow Meow' 
			];			 
		   $detail = $connection->post('statuses/update', $parameters);
			 var_dump($detail);

**Comment by abraham** [comment]
You have to be authenticating as a specific user in order to tweet.

**Comment by Arsintorabi** [comment]
i use this code : dont working get Bad Authentication data.
 $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $this->T_ACCESS_TOKEN, $this->T_ACCESS_TOKEN_SECRET);
$parameters = [
			    'status' => 'Meow Meow Meow' 
	];
			
			    $detail = $connection->post('statuses/update', $parameters);
			
			 var_dump($detail);

**Comment by Arsintorabi** [comment]
please help me to connect

**Comment by abraham** [comment]
There is live documentation that walks you through authentication step by step https://twitteroauth.com/redirect.php

**Comment by Arsintorabi** [comment]
Solved 👍 

enter bad token
