### ISSUE TITLE
get time out err - upload video

### ISSUE THREAD

**Issue by Arsintorabi** [abraham/twitteroauth#532]
code 👎 
$media1 = $connection->upload('media/upload', array('media' => $video_path,'media_type' => 'video/mp4'),TRUE);

**Comment by abraham** [comment]
As documented on https://twitteroauth.com/ you can customise the timeout with the following where the first number is seconds to allow connecting to the server and the second number is the total number of seconds to allow.

```
$connection->setTimeouts(10, 15);
```

**Comment by Arsintorabi** [comment]
not working.. :( 

image type successfully uploaded but video not working

**Comment by abraham** [comment]
If it's still timing out you need to increase the it will wait even longer.
