### ISSUE TITLE
Not able to fetch data using statuses/mentions_timeline 

### ISSUE THREAD

**Issue by sachinwng** [abraham/twitteroauth#533]
I am not able to fetch tweets containing a users’s @screen_name for the authenticating user. What are the possible reasons?

**Comment by oussaki** [comment]
Can you write what you get instead ?
Error Message or Exception .

paste it here and maybe we could help you

**Comment by abraham** [comment]
Also include a snippet of code showing what you are trying to do.

**Comment by sachinwng** [comment]
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$connection->setTimeouts(20, 30);
$mentions = $connection->get("statuses/mentions_timeline", ['screen_name'=>'xxxx',"count" => 200, "exclude_replies" => false]);
echo '<pre>'; print_r($mentions); die;

I am not getting any error message or exception, i am getting an empty array.

**Comment by oussaki** [comment]
Did you tried to call for example another API End Point ?
Like for example : "application/rate_limit_status"
Try with that if it works or not 

Make sure you have the correct $access_token and $access_token_secret

Did you called "oauth/access_token" to get 'oauth_verifier' before calling any API end point ?

**Comment by abraham** [comment]
One thing is that statuses/mentions_timeline does not support the sreen_name parameter.

https://dev.twitter.com/rest/reference/get/statuses/mentions_timeline

**Comment by abraham** [comment]
BTW I just tried you included code and it worked fine for me. `screen_name` was just ignored. I guessing your authentication details are incorrect or have a firewall blocking connections to api.twitter.com.

**Comment by sachinwng** [comment]
@oussaki and @abraham thank you very much. It was problem with access_token.
