### ISSUE TITLE
modify callbackurl when redirect and get oauth_token_secret

### ISSUE THREAD

**Issue by Chathula** [abraham/twitteroauth#534]
i want to pass token_secret as a GET Param with callback url. because it only returns oauth_token and oauth_verifier..

Explanation: 

```php
// Get access_token and access_secret || $twitterCallbackUrl = 'some url for redirect';
$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => $twitterCallbackUrl));
```

this will only generate oauth_token and oauth_verifier as a GET Param on a callback url. how to get access_secret too as a GET param...

because i can't use SESSION in a Laravel API routes! i have to store both token and secret somehow!

**Comment by abraham** [comment]
It's not recommended to do that. You should store it in a database somewhere.
