### ISSUE TITLE
Add requirements

### ISSUE THREAD

**Issue by kraxarn** [abraham/twitteroauth#535]
The php7-curl package seems to be required in order for this to work, but it isn't mentioned anywhere.

**Comment by abraham** [comment]
What change would you recommend? [composer.json](https://github.com/abraham/twitteroauth/blob/master/composer.json) has always specified `ext-curl` as a requirement but AFAIK that's not enforced by anything.

**Comment by KraXarN** [comment]
Maybe point out that the curl module is needed under the manual installation section on the website.

**Comment by abraham** [comment]
Clearer requirements will be deployed to the documentation site soon.
