### ISSUE TITLE
TwitterOAuth is not working

### ISSUE THREAD

**Issue by kaleemullah1** [abraham/twitteroauth#536]
here is my code.
require_once (__DIR__.'/../libraries/twitteroauth-0.7.2/autoload.php');

use Abraham\TwitterOAuth\TwitterOAuth;
echo 'yes';
$connection = new TwitterOAuth('xxxxxxxxxx', 'xxxxxxxxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxxxxxx');
echo 'yes2';
//other code

working fine on windows. but on linux server it is not giving any output after 
$connection = new TwitterOAuth('xxxxxxxxxx', 'xxxxxxxxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxxxxxx');

but in windows working fine
I also tried using including TwitterOAuth.php class but it is not giving any response. it seems some issue is occurred when object is initializing.

**Comment by abraham** [comment]
Make sure you have curl installed on the server.

**Comment by kaleemullah1** [comment]
@abraham thanks fpr quick reply

i have checked curl is installed like this

if  (in_array  ('curl', get_loaded_extensions())) {
        echo "CURL is available on your web server";
    }  else {
        echo "CURL is not available on your web server";
    }

**Comment by AlphaUnitDeveloper** [comment]
I have the same problem. CURL is also installed, can't find the reason for the errors.
