### ISSUE TITLE
how show errors?

### ISSUE THREAD

**Issue by Arsintorabi** [abraham/twitteroauth#539]
$detail=$connection->post('statuses/update', array(
	'status' =>  $key['title']."\n".$link_on 
));
if ($connection->getLastHttpCode() == 200) {
	//success
} else {
	   self::shb_save_log($key['title'],$err_message);
}

i want get text message of error and put in $err_message!

**Comment by abraham** [comment]
Errors from Twitter will be returned from `$connection->` requests.

```
$result = $connection->post('404');
echo $result->errors[0]->message;
// Sorry, that page does not exist
```

**Comment by Arsintorabi** [comment]
thank you Abraham
