### ISSUE TITLE
"code":32,"message":"Could not authenticate you."

### ISSUE THREAD

**Issue by JustinNicholls** [abraham/twitteroauth#540]
I have the following code that was working until yesterday

$SQL = $wpdb->prepare(QUERY);
				$accessToken = $wpdb->get_row($SQL);
				$decryptAccessToken = decryptValue($accessToken->accesscode,$encryptionKey);
				$decryptAccessTokenSecret = decryptValue($accessToken->accesscodesecret,$encryptionKey);

				$connection = new \Abraham\TwitterOAuth\TwitterOAuth(CONSUMER_KEY,CONSUMER_SECRET,$decryptAccessToken,$decryptAccessTokenSecret);
				$credentials = $connection->get('account/verify_credentials');

I have tried regenerating keys, revoking access then granting access again and nothing seems to work. I am posting on another page than the oauth_callback url.

**Comment by JustinNicholls** [comment]
seems to work only if the page is the same as the oauth_callback url

**Comment by abraham** [comment]
Check your https://apps.twitter.com/ settings for "Enable Callback Locking (It is recommended to enable callback locking to ensure apps cannot overwrite the callback url)"

**Comment by JustinNicholls** [comment]
I have tried this and it still does not work if the callback url is different than the one being used

ex authenticating at localhost/twitter and posting on localhost/twitter/posting

**Comment by JustinNicholls** [comment]
ok i think i found out the issue, since I am using wordpress and defining constants there is some issues with the constants messing up.
