### ISSUE TITLE
autoload.php spl_autoload_register not supported on php 5.2.17

### ISSUE THREAD

**Issue by SoftwebNarendra** [abraham/twitteroauth#541]
Hi Mr.Abraham,

I got 500 internal server error when i try to share my data on twitter using your code.
Now i have an issue with php version my current PHP version is 5.2.17 and your code working fine with PHP version 5.5.38 because of "spl_autoload_register" this code i can't go forward, i have try with php 5.5.38 version and code is working fine.

Now i need help for this "I want to remove autoload and include all files on index.php or any other way to include that files or any other solution for spl_autoload_register", so what i have to do for this.

Thanks in Advance.

**Comment by abraham** [comment]
I would recommend that you DO NOT use PHP versions less than 5.6. There are a large number of known, unpatched security issues with 5.2.17.

https://www.cvedetails.com/vulnerability-list/vendor_id-74/product_id-128/version_id-106044/PHP-PHP-5.2.17.html
