### ISSUE TITLE
Doesn't works with advanced searchs

### ISSUE THREAD

**Issue by alebak** [abraham/twitteroauth#546]
Hello, I'm trying this:

```
$search = "from:@user1 @user2";
$statuses = $connection->get("search/tweets", ["q" => $search]);
```

But doesn't works. How to use the Library and Twitter API for advanced searchs?

Thank you for help.

**Comment by abraham** [comment]
The API request is successful but the results are wrong?

**Comment by alebak** [comment]
No shows results. If you use the same query in https://twitter.com/search does works but using the API doesn't.

Also I'm trying to test using the Twitter API console https://dev.twitter.com/rest/tools/console but doesn't works.

So, how to make an search advanced using query operators (https://dev.twitter.com/rest/public/search) and the twitteroauth?

Thanks.

**Comment by abraham** [comment]
Seems to be working for me. Searching for `"from:@twitter @nba"` shows two tweets from `@twitter` that both mention `@nba`

```
Twitter: Going through all these #NBAGIFParty Tweets like… 

@NBA https://t.co/ihJ0jf0Wcw

Twitter: RT @NBA: #NBAGIFparty! 

What are your favorite #NBAAllStar Weekend memories? https://t.co/J5xz4Hg0rU
```

**Comment by alebak** [comment]
Ok, now, you try using other twitter accounts, accounts that are not popular. Does not works.

In addition, if you compare your search `"from:@twitter @nba" `with the result of search.twitter.com should yield more tweets.

**Comment by abraham** [comment]
The Search API doesn't provide the same results as the web search does.

https://twittercommunity.com/t/search-api-and-twitter-search-both-return-different-results/11739/6

**Comment by alebak** [comment]
How to get the same results of Twitter Search? Other API?

**Comment by abraham** [comment]
https://gnip.com/ is probably your best bet.

**Comment by alebak** [comment]
Thanks for help.
