### ISSUE TITLE
Add video STATUS call

### ISSUE THREAD

**Issue by gezadezsi** [abraham/twitteroauth#554]
Hi,

I had a challenge last time which may be easy to fix.

Scenario: upload a video file with chunked upload and post a Tweet to the user's timeline with the new video.

I used the native video upload function which did the work perfectly but it took a couple of seconds (15 - 20s) for Twitter to process my file and I failed to post as my video wasn't ready.

I had to do a do{}while() with the GET call to the UPLOAD endpoint / media/upload path with the  STATUS command. Unfortunately the get function in the class uses the API endpoint and there is no way to modify this without changing your code.

It would be useful to have a function which can handle the GET request to the UPLOAD endpoint too.

My code in case you wish to see:

            $video_result = $conn->upload('media/upload', ['media' => $file_path, 'media_type' => 'video/mp4','media_category'=>'tweet_video'], true);

            $count = 0;
            do
            {
                $statusResponse = $personal_connection->get(
                    'media/upload',
                    array(
                        "command" => "STATUS",
                        "media_id" => $video_result->media_id_string
                    ),
                    true  //I added a boolean variable to override the endpoint, if true, get use the UPLOAD endpoint, not the API 
                );

                if ($statusResponse->processing_info->state != 'succeeded')
                { sleep(5); }
                $videoCount++;
            }
            while ($statusResponse->processing_info->state != 'succeeded' && $count < 5);

            //send the tweet here...

**Comment by s-low** [comment]
Would be great to support this - how about writing this status check into uploadMediaChunked itself? 

```
private function uploadMediaChunked($path, array $parameters) {
       
       $init = $this->http('POST', self::UPLOAD_HOST, $path, $this->mediaInitParameters($parameters));
       
       // Append
        $segment_index = 0;
        $media = fopen($parameters['media'], 'rb');
        while (!feof($media))
        {
            $this->http('POST', self::UPLOAD_HOST, 'media/upload', [
                'command' => 'APPEND',
                'media_id' => $init->media_id_string,
                'segment_index' => $segment_index++,
                'media_data' => base64_encode(fread($media, self::UPLOAD_CHUNK))
            ]);
        }
        fclose($media);
        // Finalize
        $finalize = $this->http('POST', self::UPLOAD_HOST, 'media/upload', [
            'command' => 'FINALIZE',
            'media_id' => $init->media_id_string
        ]);
                
        if (isset($finalize->processing_info)) {
            // perform the status check using UPLOAD_HOST
        }

        return $finalize;
    }
```

**Comment by Aubron** [comment]
Is there still a need to do this? I cannot find information about the STATUS requirement in current API docs:

https://developer.twitter.com/en/docs/media/upload-media/uploading-media/chunked-media-upload

**Comment by abraham** [comment]
It's got it's own docs page. https://developer.twitter.com/en/docs/media/upload-media/api-reference/get-media-upload-status

**Comment by huglester** [comment]
@abraham did you understood what the problem was described and what sollutions do you see?

when you want to check status:
like so:
```php
->get('media/upload', [
                'command' => 'STATUS',
                'media_id' => $uploadedMedia->media_id_string,
            ]);
```

the actual URL should be not the API_HOST but UPLOAD_HOST.

maybe we could have something like:
setUrl() public method, so we cna change URL on the fly... 
and then when we use ->get('media/upload') - it would work flawesly?

Thank you

**Comment by abraham** [comment]
@huglester yes I understand the problem. `STATUS` is an API method Twitter provides to check if they have finished processing media before posting a tweet.

Users of this library shouldn't have to manually set the API host used. It should be automatic based on what they are trying to do. This is both simpler for developers and keeps the number of API methods on this library lower. Keeping the API methods on this library lower are key to better testing and keeping technical debt manageable.

I've got some ideas on how to approach this in a backwards incompatible way but I haven't decided how I want to proceed yet.

**Comment by abraham** [comment]
There are typically four hosts the Twitter API uses:

- `https://api.twitter.com/`
- `https://ads-api.twitter.com/`
- `https://upload.twitter.com/`
- `https://stream.twitter.com/`

There used to be `https://search.twitter.com` but that has been retired.

**Comment by huglester** [comment]
This is pseudo code which is working.
Just need a way to get the 'STATUS' of actual chunk upload.

```php

$uploadedMedia = $this->getConnection()
            ->upload('media/upload', [
                'media' => $media->getPath(),
                'media_type' => 'video/mp4',
                'media_category' => 'tweet_video', // this is needed
            ], true);

        if (isset($uploadedMedia->error)) {
            throw new \Exception(sprintf(
                'Video ID: %s could not be uploaded. %s',
                $video->id,
                $uploadedMedia->error
            ));
        }

        // Check video upload status after X seconds
        $check_after_secs = $uploadedMedia->processing_info->check_after_secs;

        $recheck_upload_status = true;
        $response = null;

        // Check so we know Video is in_progress, failed or succeeded and ready to be used in a status update
        while ($recheck_upload_status === true) {
            sleep($check_after_secs);

            $response = $this->getConnection()
                ->get('media/upload', [
                    'command' => 'STATUS',
                    'media_id' => $uploadedMedia->media_id_string,
                ], true); // I've added this true parameter so I be able to override URL.

            if ($response->processing_info->state !== 'in_progress') {
                $recheck_upload_status = false;
            } else {
                $check_after_secs = $response->processing_info->check_after_secs;
            }
        }

        if ($response->processing_info->state !== 'succeeded') {
            throw new \Exception(sprintf(
                'Video ID: %s could not be processed. State: %s, Message: %s',
                $video->id,
                $response->processing_info->state,
                $response->processing_info->error->message
            ));
        }

       return $response->media_id_string;
```

**Comment by albertleao** [comment]
+1

In my humble opinion, I agree with huglester that a simple check for a get to upload/media is the easiest way to get around, but for forward compatibility a setUrl method would be awesome.

**Comment by milosnovi** [comment]
Hi guys,

any news on this one?

**Comment by nortronthered** [comment]
For anyone else experiencing this issue, I forked and added the following method, additionally creating a pull request in the process (https://github.com/abraham/twitteroauth/pull/631):

```
public function getUpload($path, array $parameters = [])
{
    return $this->http('GET', self::UPLOAD_HOST, $path, $parameters);
}
```

Which can be used like this:
```
...         
$tries = 0;
$maxTries = 5;
$pending = true;
while ($tries < $maxTries && $pending) {
    $statusResponse = $twitter->getUpload('media/upload', [
        'media_id' => $mediaId,
        'command' => 'STATUS',
    ]);
    $processingInfo = $statusResponse->processing_info;

    if (!$processingInfo) {
        throw new \Exception('Could not get status of uploaded video');
    }
    switch ($processingInfo->state) {
        case 'pending':
            $tries++;
            $checkAfterSecs = $processingInfo->check_after_secs ?: 5;
            sleep($checkAfterSecs);
            break;
        case 'succeeded':
            $pending = false;
            break;
        case 'failed':
            throw new \Exception('Could not upload video: ' . $processingInfo->error->message);
            break;
    }
}
if ($pending) {
    throw new \Exception('Video upload timed out');
}
```

**Comment by abraham** [comment]
Fixed with https://github.com/abraham/twitteroauth/pull/634
