### ISSUE TITLE
Where's media_category?

### ISSUE THREAD

**Issue by richellyitalo** [abraham/twitteroauth#555]
I can't find media_category to upload video up 30s in code, how can I do this with current branch?

**Comment by abraham** [comment]
It's part of [`mediaInitParameters`](https://github.com/abraham/twitteroauth/blob/a3df9759a3fc56b496b4d7c4318ea8fdd8a4985b/src/TwitterOAuth.php#L305) which is called by [`uploadMediaChunked `](https://github.com/abraham/twitteroauth/blob/a3df9759a3fc56b496b4d7c4318ea8fdd8a4985b/src/TwitterOAuth.php#L263). You can pass that with as a key=value pair in the $parameters position.
