### ISSUE TITLE
Invalid media_id error while uploading video

### ISSUE THREAD

**Issue by efat33** [abraham/twitteroauth#556]
Hi, I succeeded uploading images, but can't seem to upload video. I came across this issue https://github.com/abraham/twitteroauth/issues/467 posted by @dacastro4 and applied everything from there, but still having this error:  `  stdClass Object( [request] => /1.1/media/upload.json [error] => Invalid media_id: Some().)  `

Here is my code;

```
$tweet_video = 'http://play1.ch/efat/video.mp4';
$media1 = $connection->upload('media/upload', array('media' => $tweet_video, 'media_type' => 'video/mp4'), true);
 $parameters = [
		'status' => $tweet_msg,
		'media_ids' => implode(',', [$media1->media_id_string])
	];
$connection->post('statuses/update', $parameters);
```
Can you please let me know what I'm doing wrong? Any help will greatly be appreciated.

**Comment by gezadezsi** [comment]
Twitter needs time to process the video, you should add some code.

Check my previous Issue report for an example code:
https://github.com/abraham/twitteroauth/issues/554

**Comment by efat33** [comment]
thanks for the reply @gezadezsi. But I don't quite get which code I need to add. You mentioned video takes 15-20s to process, and that's why I increased the time by adding this code` $connection->setTimeouts(60, 30);` can you please explain?

**Comment by gezadezsi** [comment]
setTimeouts unfortunately doesn't solve the problem, that just increase the availbe time for the upload action to finish the process. The upload call will return with success once the video file itself uploaded to Twitter, then you need to wait before you send the status update call. You can try a basic PHP sleep at this point but it's not a nice solution.

It would be good to able to send a GET call to the Uploads endpoint with media/upload path and STATUS command. At the moment it's not possible with this library, that's why I posted my feature request.

I manually modified the library code on here: 
TwitterOAuth.php; line: 178:
public function get($path, array $parameters = [],$override_with_uploadhost = false)
    {
        if($override_with_uploadhost)
            return $this->http('GET', self::UPLOAD_HOST, $path, $parameters);
        else
            return $this->http('GET', self::API_HOST, $path, $parameters);
    }
Note the fact if you set the bool true, it'll send the request to a different endpoint.

After this modification, I used this code:
$video_result = $conn->upload('media/upload', ['media' => $file_path, 'media_type' => 'video/mp4','media_category'=>'tweet_video'], true);

        $count = 0;
        do
        {
            $statusResponse = $conn->get(
                'media/upload',
                array(
                    "command" => "STATUS",
                    "media_id" => $video_result->media_id_string
                ),
                true  //I added a boolean variable to override the endpoint, if true, get use the UPLOAD endpoint, not the API 
            );

            if ($statusResponse->processing_info->state != 'succeeded')
            { sleep(5); }
            $videoCount++;
        }
        while ($statusResponse->processing_info->state != 'succeeded' && $count < 5);

Hope it helps, I know it's bad to modify the library code but I had to start my campaign, also I know that I could solve this in a more elegant way but it works.

**Comment by efat33** [comment]
I've added the code like you said; first modified the get function in TwitterOAuth.php  and then use the following code 
```
        $tweet_msg = 'video tweet';
	$tweet_video = 'http://play1.ch/efat/video.mp4';
	$media1 = $connection->upload('media/upload', array('media' => $tweet_video, 'media_type' => 'video/mp4'), true);
	
	$count = 0;
    do
    {
        $statusResponse = $connection->get(
            'media/upload',
            array(
                "command" => $tweet_msg,
                "media_id" => $media1->media_id_string
            ),
            true  //I added a boolean variable to override the endpoint, if true, get use the UPLOAD endpoint, not the API 
        );

        if ($statusResponse->processing_info->state != 'succeeded')
        { sleep(5); }
        $videoCount++;
    }
    while ($statusResponse->processing_info->state != 'succeeded' && $count < 5);
```
it gives me the timeout error. ` Error 524: A timeout occurred`
have any idea?

**Comment by gezadezsi** [comment]
Inside the Do - While, you have to send the STATUS command, to ask Twitter about your video status:
$statusResponse = $connection->get(
                'media/upload',
                array(
                    "command" => "STATUS",
                    "media_id" => $media1->media_id_string
                ),
                true  //I added a boolean variable to override the endpoint, if true, get use the UPLOAD endpoint, not the API 
            );

and once the while finish, you can send the normal status update call.

So my code is like:
A: Hey Twitter, here is my video
B: Twitter ...uploading...
C: Twitter: your upload is uploaded
D: Hey Twitter, is my video processed yet?
D: Twitter: not yet
D: Hey Twitter, is my video processed yet?
D: Twitter: not yet
D: Hey Twitter, is my video processed yet?
E: Twitter: YES
F: Hey Twitter, take this status update with this media ID

A,B and C is managed by the original library function, D needs the modified GET function from the library and it is inside the Do - While. F is not in my example, you can use your original call.

**Comment by efat33** [comment]
Thanks for your outstanding explanation. I appreciate your effort.  I think timeout error occurred for I didn't increase $count variable. I replaced the $videoCount++;  with $count++;  so there's no timeout error any longer. tweet is posted to twitter, but no video. my code is below:
```
$tweet_msg = 'video tweet';
	$tweet_video = 'http://play1.ch/efat/video.mp4';
	$media1 = $connection->upload('media/upload', array('media' => $tweet_video, 'media_type' => 'video/mp4'), true);
	
	$count = 0;
    do
    {
        $statusResponse = $connection->get(
            'media/upload',
            array(
                "command" => 'STATUS',
                "media_id" => $media1->media_id_string
            ),
            true  //I added a boolean variable to override the endpoint, if true, get use the UPLOAD endpoint, not the API 
        );

        if ($statusResponse->processing_info->state != 'succeeded')
        { sleep(5); }
        $count++;
    }
    while ($statusResponse->processing_info->state != 'succeeded' && $count < 5);
	
	$parameters = [
		'status' => $tweet_msg,
		'media_ids' => implode(',', [$media1->media_id_string])
	];
	$connection->post('statuses/update', $parameters);
	
	if ($connection->getLastHttpCode() == 200) {
		echo 'Tweet posted succesfully'; 
	} else {
		echo 'Handle error case'; 
	} 
```
can you please take the time to see what I'm still missing?

**Comment by gezadezsi** [comment]
My working code looks almost the same as yours, two differences:
 $video_result = $conn->upload('media/upload', ['media' => $file_path, 'media_type' => 'video/mp4','media_category'=>'tweet_video'], true);

I set the media_category => tweet_video tag, I read somewhere that this is essential if you like to upload larger video files with chunked upload. Maybe, as your video is small, you can try to set the last param to false, so use normal (non-chunked) upload or try to set the media_category param.

My other difference is the status post:
$parameters = ['status' => 'My message', 'media_ids' => $video_result->media_id_string];
$result = $personal_connection->post('statuses/update', $parameters);

I don't use any implode call, maybe it's not necessary.
Try these changes, maybe they help :)

**Comment by efat33** [comment]
still no luck. I changed the code as you said but still no video is posted. can you let me know if I put the following code in the right place
```
$parameters = [
		'status' => $tweet_msg,
		'media_ids' => implode(',', [$media1->media_id_string])
	];
	$connection->post('statuses/update', $parameters);
```
I'm just wondering if that would be inside the curly braces of do-while. 
I just don't understand why the same code worked for you isn't working for me.  I even tried what said in issue https://github.com/abraham/twitteroauth/issues/467 but no luck either.

**Comment by abraham** [comment]
I think this should be handled with the new media status check method. https://github.com/abraham/twitteroauth/pull/634
