### ISSUE TITLE
i have a error !!!! 

### ISSUE THREAD

**Issue by spyritu** [abraham/twitteroauth#558]
**hello Abraham, sorry for my english, i have a script**
<?php
      require_once('twitteroauth.php');
      require_once('OAuth.php');
      error_reporting(E_ALL);
      $consumerK = 'xxxxxxx';
      $consumerS = 'xxxxxxx';
      $oAuthT    = 'xxxxxxxx';
      $oAuthS    = 'xxxxxxxxxx';
      $conexion = new TwitterOAuth($consumerK, $consumerS, $oAuthT, $oAuthS);
      var_dump($conexion);
    $response = $conexion->get("account/verify_credentials");
    var_dump($response);
    ?>
****and the result is ...****
var/www/html/info.php:12:
object(TwitterOAuth)[1]
  public 'http_code' => null
  public 'url' => null
  public 'host' => string 'https://api.twitter.com/1.1/' (length=28)
  public 'timeout' => int 30
  public 'connecttimeout' => int 30
  public 'ssl_verifypeer' => boolean false
  public 'format' => string 'json' (length=4)
  public 'decode_json' => boolean false
  public 'http_info' => null
  public 'useragent' => string 'TwitterOAuth v0.2.0-beta2' (length=25)
  public 'sha1_method' => 
    object(OAuthSignatureMethod_HMAC_SHA1)[2]
  public 'consumer' => 
    object(OAuthConsumer)[3]
      public 'key' => string 'xxxxxxxxYoDnQUQTZ1GqZxk1ZBJR' (length=25)
      public 'secret' => string 'xxxxxxxx58ukvmzmf1WBkMzJfhmBgEzfYbBQ1sRgKSPfVjInNZM' (length=50)
      public 'callback_url' => null
  public 'token' => 
    object(OAuthConsumer)[4]
      public 'key' => string 'xxxxxxxxx9385477-LLfK40xb4QfrAHBfq7nLMKgv5L7mkih' (length=50)
      public 'secret' => string 'xxxxxxxV4IaQj26TRUEjVGKax1VCZ2dd3wPBdmbtYlo' (length=45)
      public 'callback_url' => null

but i cant see the the result in account/verify_credentials, i use this script in ubuntu 16.04 and work, but i use other virtual machine with the same operating system, and dont work!, mmmm requirements ? php version? something idea?

Please help me Abraham... Regards ... sorry for my english again...

**Comment by spyritu** [comment]
my code is 
 require_once('twitteroauth.php');
      require_once('OAuth.php');
      error_reporting(E_ALL);
      $consumerK = 'xxxxxxx';
      $consumerS = 'xxxxxxx';
      $oAuthT    = 'xxxxxxxx';
      $oAuthS    = 'xxxxxxxxxx';
      $conexion = new TwitterOAuth($consumerK, $consumerS, $oAuthT, $oAuthS);
      var_dump($conexion);
    $response = $conexion->get("account/verify_credentials");
    var_dump($response);

**Comment by spyritu** [comment]
but i cant see the the result in account/verify_credentials, i use this script in ubuntu 16.04 and work, but i use other virtual machine with the same operating system, and dont work!, mmmm requirements ? php version? something idea?

**Comment by spyritu** [comment]
[twitteroauth.txt](https://github.com/abraham/twitteroauth/files/895200/twitteroauth.txt)
[OAuth.txt](https://github.com/abraham/twitteroauth/files/895201/OAuth.txt)

those are my oauth files

**Comment by abraham** [comment]
Make sure you have CURL installed on the machine that's not working.

**Comment by spyritu** [comment]
hello abraham, :D i dont installed CURL. I install CURL follow, but working, something idea?
thanks a lot for your help and comments.

thanks...

**Comment by spyritu** [comment]
the script dont work in my new virtual machine.   :(

**Comment by abraham** [comment]
> i dont installed CURL. I install CURL follow, but working, something idea?

I don't understand what you are saying. What errors are you getting?

**Comment by spyritu** [comment]
i want to get profile picture and twitter account with 

$response = $conexion->get("account/verify_credentials");

but i print dump_var($response) is empty null!!!!    :(

thanks, abraham

**Comment by abraham** [comment]
Maybe check your server logs for errors?`$response` shouldn't be null.

**Comment by spyritu** [comment]
ok, thanks Abraham
