### ISSUE TITLE
How can I pin up the tweet?

### ISSUE THREAD

**Issue by dorcu** [abraham/twitteroauth#559]
Hi!!

I'm using the statuses/update for to send tweets but i need pin up this same tweet.

How I can make this?

Thanks

**Comment by mrbellek** [comment]
That functionality isn't available in the Twitter REST API right now, and isn't planned: https://twittercommunity.com/t/pin-a-tweet-with-the-twitter-api/13048/8

**Comment by dorcu** [comment]
Thanks you!! ;)
