### ISSUE TITLE
Simple example - keep getting 403 errors

### ISSUE THREAD

**Issue by michaelslange** [abraham/twitteroauth#560]
I am new to PHP (but not new to coding), so I made a very simplistic example. But for some reason I keep getting 403 errors. I've checked and re-checked the consumer and access key/secrets. Any idea why this keeps failing?

[indexTEST.pdf](https://github.com/abraham/twitteroauth/files/923722/indexTEST.pdf)

**Comment by abraham** [comment]
Essentially the exact same code works fine for me. It's almost certainly an issue with the credentials. How are you generating the the access key/secret? Please don't use PDFs anymore. Put code samples in code blocks in the comment/issue.


```
$connection = new TwitterOAuth(TEST_CONSUMER_KEY, TEST_CONSUMER_SECRET, TEST_ACCESS_TOKEN, TEST_ACCESS_TOKEN_SECRET);
$content = $connection->get("account/verify_credentials");
$response = $connection->getLastHttpCode();
echo 'creds ' . $response;
```

**Comment by michaelslange** [comment]
Sorry about that. It wasn't formatting well. Now I see why. 

I setup an app on Twitter at apps.twitter.com. Then I generated an Access Token. For this initial testing, I am copying the consumer key, consumer secret, access token, and access token secret right into this PHP file. 

`<?php

echo 'Begin Test';

// Include twitteroauth
require "twitteroauth/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;

// Set keys
define('CONSUMER_KEY', 'hardcodeMyConsumerKey');
define('CONSUMER_SECRET', 'hardcodeMyConsumerSecret');
$accessToken = 'hardcodeMyAccessToken';
$accessTokenSecret = 'hardcodeMyAccessTokenSecret';

// Create object
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$content = $connection->get("account/verify_credentials");
$response = $connection->getLastHttpCode();
echo '<br />creds '.$response;


// Set status message
$tweetMessage = 'This is a tweet to my Twitter account v4';

// Check for 140 characters
if(strlen($tweetMessage) <= 140)
{
    // Post the status message

	$statues = $connection->post("statuses/update", ["status" => "hello world"]);
	$response = $connection->getLastHttpCode();
	if ($response == 200) {
	    // Tweet posted succesfully
	    echo '<br />Tweeted ok';
	} else {
	    // Handle error case
	    echo '<br />Tweet failed'.$response;
	}
}

echo '<br />End Test';

?>`

**Comment by michaelslange** [comment]
Well putting that in made me think of something. Why am I defining the consumer and access fields differently? So I defined the access fields the same as the consumer fields and it worked.  Thanks for your patience...

`
define('ACCESS_TOKEN', 'hardcodeMyAccessToken');
define('ACCESS_TOKEN_SECRET', 'hardcodeMyAccessTokenSecret');
`
