### ISSUE TITLE
error not tweet

### ISSUE THREAD

**Issue by Gilangbsi** [abraham/twitteroauth#561]
hello Abraham, sorry for my english.

I tried doing the storage to the database oauth_token and oauth_token_secret.  When I try to run the script to do a Tweet with the oauth_token and oauth_token_secret. Why not run a tweet? 

thanks

**Comment by abraham** [comment]
You get an a user's access token and you can use it to tweet from their account but after you save it to the database and then get it back from the database you can no longer use the access token to tweet?
