### ISSUE TITLE
Getting error code 34 while uploading media on twitter

### ISSUE THREAD

**Issue by syedumairahmed** [abraham/twitteroauth#562]
Hi, I am updating the status with media but images is not uploading only text content are sharing. when I degud the image upload I getting error code 34

```
stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [message] => Sorry, that page does not exist [code] => 34 ) ) )
```

here is my code:

```
$post_media = $connection->upload('media/upload', [
    'media' => 'https://microvisioncorp.com/clients/teamnj/img/blog/femaleavatar.png'
]); 
$parameters = [
    'status' => "$post_heading #teamnjmedia #nj",
    'media_ids' => $post_media->media_id_string
];
$connection->post('statuses/update', $parameters);
```

My status is updating without image, screenshot is attached: 
![tweet1](https://cloud.githubusercontent.com/assets/22678502/25131690/20a7e5f8-2460-11e7-8b23-eb68ed8834bf.png)

**Comment by abraham** [comment]
The [documented](https://twitteroauth.com/) way of using `media/upload` is with a file path, not a URL.

```
$media1 = $connection->upload('media/upload', ['media' => '/path/to/file/kitten1.jpg']);
```

Also you should validate that uploading the image is a 200 OK before posting the tweet.

**Comment by syedumairahmed** [comment]
Thanks for the comment brother abraham, let me check and will update to you if face any issue.

**Comment by syedumairahmed** [comment]
image path just like this is correct?: 

../../img/blog/avatar.gif

**Comment by abraham** [comment]
It should look something like that.

**Comment by syedumairahmed** [comment]
but I am getting the same error again, screenshot attached
![tweet12](https://cloud.githubusercontent.com/assets/22678502/25136523/b20bb976-246e-11e7-9b94-1e2c95d0f3fa.png)

**Comment by abraham** [comment]
The second error about HTML encoding is unrelated. You could do some HTML tags/server config to fix that.

The page does not exist error is coming from this?

```
$post_media = $connection->upload('media/upload', [
    'media' => '../../img/blog/avatar.gif'
]); 
```

**Comment by syedumairahmed** [comment]
Hello abraham good morning from pakistan :). 
I was done some analysis and got the solution, In your tutorial / example you are passing two parameters in upload function:
`$media1 = $connection->upload('media/upload', ['media' => '/path/to/file/kitten1.jpg']);`
1- 'media/upload
2- /path/to/file/kitten1.jpg (local path) not the url

the 1st parameter isn't working and replace it with this url:
https://upload.twitter.com/1.1/media/upload.json

the code will be like that:
`$post_media = $connection->upload('https://upload.twitter.com/1.1/media/upload.json', ['media' => $data_image]);`

I am pasting my code here and its 100% working
`$connection = new TwitterOAuth(CONSUMER_KEY,CONSUMER_SECRET,$result['tw_oauth_token'],$result['tw_oauth_token_secret']);`
`$data_image = file_get_contents($media);`
`$post_media = $connection->upload('https://upload.twitter.com/1.1/media/upload.json', ['media' => $data_image]);`
`$newurl = $compress_obj->get_tiny_url("http://www.myurl.com/file.php");`
`$parameters = [
                            'status' => "$image_heading ".$newurl,
                            'media_ids' => implode(',', [$post_media->media_id_string])
                        ];`
`$result_post = $connection->post('statuses/update', $parameters);`

Screen shot of status with media

![testr](https://cloud.githubusercontent.com/assets/22678502/25165900/196ebac2-24f2-11e7-91fb-b48d90ed8462.png)

**Comment by abraham** [comment]
Glad to hear you got it working. It's weird that this isn't working, it should since the library expands the path to include a full URL.

```
$connection->upload('media/upload', ['media' => $data_image]);
```

**Comment by coderbhaai** [comment]
@abraham is there a way we can upload images from live server and not the local system?

This will be really helpful as we can then schedule our tweets accordingly.
