### ISSUE TITLE
Redirection back to Application in Callback is Not working any more

### ISSUE THREAD

**Issue by Aravind-WMG** [abraham/twitteroauth#563]
Hi ,

I made a Twitter App for posting tweets from my website.It was working fine up to yesterday. Today suddenly After authorizing the app, its not redirecting  back to the application.Finally it's going to 504 bad gateway time out.

Refer : http://prntscr.com/f0wk6l + http://prntscr.com/f0wkko

I am using this functionality in many website and in  all websites we are facing the issue now.

Could some help me on this

Thanks in Advance!!!

**Comment by abraham** [comment]
The 504 is happening on twitter.com or on your server?

**Comment by Aravind-WMG** [comment]
It's coming from Our server...

Thanks !!!

**Comment by abraham** [comment]
I have no insight into the running of your server, you will have to do some debugging and look at error logs.
