### ISSUE TITLE
cURL/SSL error

### ISSUE THREAD

**Issue by ArthurCoimbra** [abraham/twitteroauth#566]
Hello,
I'm trying to use your library to post an image on Twitter but I keep getting the following error message:
`Fatal error: Uncaught Abraham\TwitterOAuth\TwitterOAuthException: SSL read: error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac, errno 0 in C:\Users\Arthur\Desktop\twitter\src\TwitterOAuth.php:408 Stack trace: #0 C:\Users\Arthur\Desktop\twitter\src\TwitterOAuth.php(334): Abraham\TwitterOAuth\TwitterOAuth->request('https://upload....', 'POST', 'Authorization: ...', Array) #1 C:\Users\Arthur\Desktop\twitter\src\TwitterOAuth.php(305): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://upload....', 'POST', Array) #2 C:\Users\Arthur\Desktop\twitter\src\TwitterOAuth.php(252): Abraham\TwitterOAuth\TwitterOAuth->http('POST', 'https://upload....', 'media/upload', Array) #3 C:\Users\Arthur\Desktop\twitter\src\TwitterOAuth.php(235): Abraham\TwitterOAuth\TwitterOAuth->uploadMediaNotChunked('media/upload', Array) #4 C:\Users\Arthur\Desktop\twitter\index.php(29): Abraham\TwitterOAuth\TwitterOAuth->upload('media/upload', Array) #5 {main} thrown in C:\Users\Arthur\Desktop\twitter\src\TwitterOAuth.php on line 408`
Do you have any idea what it could be? Seems to be a cURL error but I really don't know how to fix it.
Thanks in advance.

**Comment by abraham** [comment]
I'm unfamiliar with that error. A quick Google shows a couple of related SO questions that might have some solutions.

https://stackoverflow.com/questions/4496941/curl-php-request-executes-50-of-the-time
https://stackoverflow.com/questions/37427688/bitbucket-cannot-push-fatal-the-remote-end-hung-up-unexpectedly
