### ISSUE TITLE
I cant upload mp4 video filesize 650k but whit other file work

### ISSUE THREAD

**Issue by spyritu** [abraham/twitteroauth#567]
this script work with the test file video.mp4, but when i use my video file no work, sorry for my english. filesize 660k.

Regards Abraham.

```
<?php
require "autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;
echo 'prueba';

$CONSUMER_KEY="xxxx";
$CONSUMER_SECRET="xxxx";
$access_token="xxxx";
$access_token_secret="xxxxx";

$connection = new TwitterOAuth($CONSUMER_KEY, $CONSUMER_SECRET, $access_token, $access_token_secret);
$connection->setTimeouts(120,60);
$media1 = $connection->upload('media/upload', ['media' => 'pj2.mp4','media_type' => 'video/mp4'],true);
print_r($media1);

$parameters = [
    'status' => 'Buenisimo jsjjssj',
    'media_ids' => $media1->media_id_string,
];
$result = $connection->post('statuses/update', $parameters);

?>
```

[tweetvideo.txt](https://github.com/abraham/twitteroauth/files/1014326/tweetvideo.txt)

**Comment by abraham** [comment]
What's not working? What errors are you getting?

**Comment by spyritu** [comment]
connection->upload

show=
pruebastdClass Object ( [media_id] => 867573008742920192 [media_id_string] => 867573008742920192 [size] => 633508 [expires_after_secs] => 86400 [video] => stdClass Object ( [video_type] => video/mp4 ) ) 
400

and connection->httpLastHttpCode()

show 400

this code i use with other mp4 file and work.

**Comment by abraham** [comment]
If other mp4s work it sounds like it's not an issue with this library. Make sure the file is compatible with [Twitter's requirements](https://dev.twitter.com/rest/media/uploading-media.html). If you think the file should be valid you should file a bug on https://twittercommunity.com/

**Comment by spyritu** [comment]
thanks a lot.
Regards Abraham.
