### ISSUE TITLE
Facing an issue after enable twitter social login option

### ISSUE THREAD

**Issue by sup077** [abraham/twitteroauth#568]
Hello Guys, I am facing 
"Ooophs, we got an error: Notice: Undefined index: oauth_token in /home/jkbinfot/public_html/jindeal.com/lib/internal/Mageplaza/SocialLogin/Hybrid/thirdparty/OAuth/OAuth1Client.php on line 85" 
this issue after enable twitter social login in magento 2.1.6 .
Somebody please help me to resolve this issue as soon as possible.
Thanks & Regards 
Supriti Kashyap

**Comment by abraham** [comment]
Make sure you have the correct Twitter Application consumer key and secret configured.

**Comment by sup077** [comment]
Yeah, I put the correct keys in Consumer Key and Consumer Secret options. Can you please explain me another options briefly?

**Comment by abraham** [comment]
Make sure the clock on the server is accurate and that there are no firewalls blocking requests to api.twitter.com
