### ISSUE TITLE
could not find package vendor/autoload.php?

### ISSUE THREAD

**Issue by drunkfever** [abraham/twitteroauth#569]
this is the first time ive ever gotten into coding so im guessing this is something simple that ive just overlooked or misunderstood but while trying to install twitteroauth i keep getting this error message 
![c795a5b054fe0a943177bdc2bc1d3630](https://cloud.githubusercontent.com/assets/29165898/26755933/4f3c028e-485d-11e7-82ac-2950a2ff4631.png)

**Comment by abraham** [comment]
In your command line you  run `composer require abraham/twitteroauth` to require the library as a dependency.

**Comment by drunkfever** [comment]
i tried that and im still getting the same message

**Comment by abraham** [comment]
You have to remove the invalid package `vendor/autoload.php` require from the `composer.json` file.

Composer will load packages of code from https://packagist.org/. `vendor/autoload.php` is not a published package, it's a local file used by composer to autoload downloaded packages.

**Comment by drunkfever** [comment]
oh okay that makes sense.. how do i uh do that exactly

**Comment by abraham** [comment]
You literally open the `composer.json` file in an editor and remove any line that mentions  `vendor/autoload.php`

**Comment by drunkfever** [comment]
just to be clear you mean this line right? its the only thing i see relating to vendor/autoload.php
![a88e1757145ca17ec7f858c2bf493c22](https://cloud.githubusercontent.com/assets/29165898/26785769/a9db6870-49c9-11e7-8a48-c0317b56e2de.png)
because when i take that out i still get the same error

**Comment by abraham** [comment]
You should not be putting `composer require "vendor/autoload.php"; ` in the command line at all. If `vendor/autoload.php` isn't listed in `composer.json` then you don't need to remove it.

The only command line you need to run to get TwitterOAuth is `composer require abraham/twitteroauth`. That is the only command you need to run from a CLI.

In your **PHP** file you would then use `require "vendor/autoload.php";` to make the package available. That is in your PHP file, not the command line.

**Comment by drunkfever** [comment]
OH.. okay i was so confused about that thank you so much for all your help i really appreciate it!!!
