### ISSUE TITLE
Demo Site

### ISSUE THREAD

**Issue by random-robbie** [abraham/twitteroauth#571]
Sorry had to put something here as the demo site repo did not appear to have an issues part.

So i've downloaded the demo site removed http.php as i dont need it removed it's requirement from bootstrap.

Changed the define for the usual bits to the actual values.

Now when i go to sign in the redirect takes me back to the main page there appears to be no php error to say there was an API error.

removing from callback.php

```
/* If the oauth_token is not what we expect, bail. */
if (isset($_REQUEST['oauth_token']) && $request_token['oauth_token'] !== $_REQUEST['oauth_token']) {
    $_SESSION['oauth_status'] = 'oldtoken';
    header('Location: ./clearsessions.php');
    exit;
}

```

returns this in php error.

```
[08-Jun-2017 08:20:29 UTC] PHP Fatal error:  Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Error processing your OAuth request: Invalid oauth_verifier parameter' in /home/whmcs/public_html/social/vendor/abraham/twitteroauth/src/TwitterOAuth.php:138
Stack trace:
#0 /home/whmcs/public_html/social/callback.php(27): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/access_to...', Array)
#1 {main}
  thrown in /home/whmcs/public_html/social/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 138
```

The app has read and write permissions and i've tried changing regenerating the auth tokens and updating them and still the same.

any suggestions at all please i am at a loss to why it does not work.

**Comment by abraham** [comment]
Make sure the domain is the same at the beginning and at the end. E.g. If you start at `http://www.example.com/redirect.php` are you ending up at `http://example.com/callback.php` instead of `http://www.example.com/callback.php`.

**Comment by txt3rob** [comment]
Hi Abraham,

I have it on a subdomain so it is https://social.mydomain.com/callback.php the callback url in the twitter app is also the same link.

This is why i thought it was a weird error as everything i can see is set correctly. 

if you want i can DM you the link so you can see it in action?

**Comment by abraham** [comment]
You can email me a link at abraham@abrah.am if you want.
