### ISSUE TITLE
increase or allow to change UPLOAD_CHUNK (upload media chunk size)

### ISSUE THREAD

**Issue by apizzini** [abraham/twitteroauth#574]
Hi Abraham.

I had issues caused by the chunk size being too small and hardcoded in the library (it's just 0,04 Megabyte, so a 30mb video requires 750+2 upload requests).

I'd like to propose to either increase it (I'm using 4Megabyte now) or to add a method or property to allow any dev to set it (overriding the default value).

I'm available to code this, just tell me if you agree and if you have preferences.

Thanks!

**Comment by abraham** [comment]
👍  Adding a config method similar to [`setTimeout`](https://github.com/abraham/twitteroauth/blob/master/src/Config.php#L38) sounds good. Maybe something like `setUploadChunkSize`. Increasing the default chunk size sounds like a good idea too. Maybe default to 0.25 mb/request.

**Comment by apizzini** [comment]
Created pull request #575 ;)

**Comment by abraham** [comment]
Thanks!
