### ISSUE TITLE
Error getting images

### ISSUE THREAD

**Issue by sgiraldo** [abraham/twitteroauth#576]
Hello there,

I am doing some tiny app for getting latest tweets about some hashtags, but I am having some issues getting the images of these tweets (which I was previously getting). 

I am using that code:
`$toa = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);

$query = array(
  "q" => "#XXX -RT OR #XXX -RT OR #XXX -RT",
  "result_type" => "mixed",
  "include_entities" => true,
  "include_rts" => false,
  "lang" => "en",
  "count" => 30,
);

$results = $toa->get('search/tweets', $query);`

I have prompted the result of the **foreach** but there is no information about any media url, whether I look into "entities->media" or "$result->retweeted_status". If I take a look to the tweet's url, a picture is attached to that tweet. I remember getting the images the first time I made the code, but that changed recently. 

Thanks!

**Comment by abraham** [comment]
My guess is the results you got before had images, and the results you are getting now don't have images.

**Comment by abraham** [comment]
I just did a test search for "kitten" and the first result had a media entity of type photo. If you only want tweets with images you will have to filter out the others.
