### ISSUE TITLE
Return descriptive error codes

### ISSUE THREAD

**Issue by leeppolis** [abraham/twitteroauth#578]
I noticed that after a call to the APIs the response object contains an "errors" array with error codes and descriptions.
It would be great to provide a method ( maybe `$connection->getErrors():_array_` ) to access that array.
The current error-handling method (checking the http response code) isn't really useful, because it does not allow you to understand the reason why a call failed.

**Comment by abraham** [comment]
Error responses are already available.

```
$content = $connection->get("statuses/show", ['id' => '1']);
if ($connection->getLastHttpCode() == 200) {
  // $content is a status object
} else {
  // $content is a errors object
}
```
