### ISSUE TITLE
Is this library allow to upload video on twitter

### ISSUE THREAD

**Issue by kiranbulley** [abraham/twitteroauth#582]

**Comment by abraham** [comment]
Yes, it should work just fine to upload video. See the "media" section of https://twitteroauth.com/. You will have to include a third parameter of `true` to enable chunked uploading.

```
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$media = $connection->upload('media/upload', ['media' => '/path/to/file/kitten1.mp4'], true);
$parameters = [
    'status' => 'Meow Meow Meow',
    'media_ids' => $media->media_id_string
];
$result = $connection->post('statuses/update', $parameters);
```

**Comment by kiranbulley** [comment]
i am getting following response

object(stdClass)#2 (23) { ["created_at"]=> string(30) "Thu Aug 10 13:01:04 +0000 2017" ["id"]=> int(895631081298382848) ["id_str"]=> string(18) "895631081298382848" ["text"]=> string(14) "Meow Meow Meow" ["truncated"]=> bool(false) ["entities"]=> object(stdClass)#6 (4) { ["hashtags"]=> array(0) { } ["symbols"]=> array(0) { } ["user_mentions"]=> array(0) { } ["urls"]=> array(0) { } } ["source"]=> string(83) "VidViral" ["in_reply_to_status_id"]=> NULL ["in_reply_to_status_id_str"]=> NULL ["in_reply_to_user_id"]=> NULL ["in_reply_to_user_id_str"]=> NULL ["in_reply_to_screen_name"]=> NULL ["user"]=> object(stdClass)#5 (41) { ["id"]=> int(895516280257523713) ["id_str"]=> string(18) "895516280257523713" ["name"]=> string(4) "rack" ["screen_name"]=> string(12) "rackinfo1234" ["location"]=> string(0) "" ["description"]=> string(0) "" ["url"]=> NULL ["entities"]=> object(stdClass)#7 (1) { ["description"]=> object(stdClass)#15 (1) { ["urls"]=> array(0) { } } } ["protected"]=> bool(false) ["followers_count"]=> int(0) ["friends_count"]=> int(0) ["listed_count"]=> int(0) ["created_at"]=> string(30) "Thu Aug 10 05:24:53 +0000 2017" ["favourites_count"]=> int(0) ["utc_offset"]=> NULL ["time_zone"]=> NULL ["geo_enabled"]=> bool(false) ["verified"]=> bool(false) ["statuses_count"]=> int(1) ["lang"]=> string(2) "en" ["contributors_enabled"]=> bool(false) ["is_translator"]=> bool(false) ["is_translation_enabled"]=> bool(false) ["profile_background_color"]=> string(6) "F5F8FA" ["profile_background_image_url"]=> NULL ["profile_background_image_url_https"]=> NULL ["profile_background_tile"]=> bool(false) ["profile_image_url"]=> string(77) "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png" ["profile_image_url_https"]=> string(78) "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png" ["profile_link_color"]=> string(6) "1DA1F2" ["profile_sidebar_border_color"]=> string(6) "C0DEED" ["profile_sidebar_fill_color"]=> string(6) "DDEEF6" ["profile_text_color"]=> string(6) "333333" ["profile_use_background_image"]=> bool(true) ["has_extended_profile"]=> bool(false) ["default_profile"]=> bool(true) ["default_profile_image"]=> bool(true) ["following"]=> bool(false) ["follow_request_sent"]=> bool(false) ["notifications"]=> bool(false) ["translator_type"]=> string(4) "none" } ["geo"]=> NULL ["coordinates"]=> NULL ["place"]=> NULL ["contributors"]=> NULL ["is_quote_status"]=> bool(false) ["retweet_count"]=> int(0) ["favorite_count"]=> int(0) ["favorited"]=> bool(false) ["retweeted"]=> bool(false) ["lang"]=> string(2) "en" } 


its creating post on twitter but it doesn't contain video

**Comment by kiranbulley** [comment]
help me to sort out this issue.thanks in advance

**Comment by abraham** [comment]
What is the value of `$media`?

**Comment by kiranbulley** [comment]
$media = $connection->upload('media/upload', ['media' => __DIR__.'/samplevideo.mp4','media_type' => 'video/mp4'], true);

the above code returning following result

{ ["request"]=> string(22) "/1.1/media/upload.json" ["error"]=> string(15) "InvalidContent." }

**Comment by abraham** [comment]
Twitter doesn't like your video. Maybe upload a different one?

**Comment by kiranbulley** [comment]
hey its working with another video but video size is specific.  how can i upload large size videos.?

**Comment by abraham** [comment]
These are the video requirements https://dev.twitter.com/rest/media/uploading-media.html

If your videos don't conform you might be able to convert them to a different quality.
