### ISSUE TITLE
Direct messages with image

### ISSUE THREAD

**Issue by mnguye08** [abraham/twitteroauth#583]
Hi,

Is there a way to send a direct message with an image using twitteroauth?
For the moment, I send DM with but without attachment
```
$connection->post('direct_messages/new', array(
    'screen_name' => 'recipientname',
    'text' => 'Foo Bar'
));
```

Thanks a lot for your help.

**Comment by abraham** [comment]
It looks like Twitter only supports attaching media to DMs in the [new DM API](https://dev.twitter.com/rest/direct-messages/attaching-media) that was just [launched](https://blog.twitter.com/developer/en_us/topics/tools/2017/new-apis-to-power-the-future-of-customer-engagement-in-direct-me.html).

Once #581 is complete that new API will be supported.
