### ISSUE TITLE
Fatal error: Class 'Abraham\TwitterOAuth\Config' not found in …

### ISSUE THREAD

**Issue by petebarr** [abraham/twitteroauth#586]
Hi,

I've been going through loads of previous issues here to try and see if they could help with trying to get this to work for me, but I'm stumped. Sorry, I'm not a php dev, so I'm using the manual method as described :-(

`require "twitteroauth/autoload.php";`
`use Abraham\TwitterOAuth\TwitterOAuth;`

The full error is:

**Fatal error: Class 'Abraham\TwitterOAuth\Config' not found in /var/www/vhosts/stagingtesting.com/subdomains/redtree.stagingtesting.com/wp-content/themes/redtree/includes/twitter/twitteroauth/src/TwitterOAuth.php on line 17**

So I'm guessing I'm having paths issues.

It's a Wordpress site, so in footer.php I've got this:

`<?php get_template_part('includes/twitter/get-tweets'); ?>`

And it's in this get-tweets.php file that I'm requiring Twitteroauth as above. My twitteroauth directory is at the same level as this php file and the files are extracted as you described. I did a print_r on $base_dir in autoload.php and it returns this which I presume is not correct:

**/var/www/vhosts/stagingtesting.com/subdomains/redtree.stagingtesting.com/wp-content/themes/redtree/includes/twitter/twitteroauth/src//var/www/vhosts/stagingtesting.com/subdomains/redtree.stagingtesting.com/wp-content/themes/redtree/includes/twitter/twitteroauth/src/**

The path is double stacked.

One other thing to note is that it works on my local MAMP using php 7.1.0 but not on the live site with Shared hosting PHP 7.1 CGI (7.1.6). 

Any thoughts on what's happening here? Sorry, I know you've been queried about this issue many times.

Thanks!

**Comment by abraham** [comment]
What is the value of `__DIR__` and `$relative_class` in autoload.php?

**Comment by petebarr** [comment]
I'm getting them both printing out twice as:

DIR = /var/www/vhosts/stagingtesting.com/subdomains/redtree.stagingtesting.com/wp-content/themes/redtree/includes/twitter/twitteroauth

REALTIVE CLASS = TwitterOAuth

DIR = /var/www/vhosts/stagingtesting.com/subdomains/redtree.stagingtesting.com/wp-content/themes/redtree/includes/twitter/twitteroauth

REALTIVE CLASS = Config

**Comment by abraham** [comment]
`$base_dir = __DIR__ . '/src/';` so I'm not sure how that would get the path twice as you originally mentioned.

**Comment by petebarr** [comment]
Yeah, there's nothing in a loop etc.

**Comment by petebarr** [comment]
I assume it shouldn't print out 2 relative classes either?

**Comment by abraham** [comment]
I think having things print twice isn't a problem. It's not ideal to have the same code run twice but requiring a file multiple times won't break things. If the value printed once is a single string with the path twice than that is an issue.

**Comment by abraham** [comment]
Try adding `use Abraham\TwitterOAuth\Config as Config;` after `namespace Abraham\TwitterOAuth;` in `src/TwitterOAuth.php`

**Comment by petebarr** [comment]
Unfortunately that gives the error:

Fatal error: Class 'Abraham\TwitterOAuth\Config' not found in /var/www/vhosts/stagingtesting.com/subdomains/redtree.stagingtesting.com/wp-content/themes/redtree/includes/twitter/twitteroauth/src/TwitterOAuth.php on line 18

**Comment by abraham** [comment]
What version of PHP are you running?

**Comment by pjethaliya** [comment]
I have the same issue. Let us know if there is a solution to this problem.

**Comment by pjethaliya** [comment]
I made the new object as \Abraham\TwitterOAuth\TwitterOAuth.
Before I use to make it like $connection = new TwitterOAuth and now changed it to 
$connection = new \Abraham\TwitterOAuth\TwitterOAuth.

This solved my problem. It was because of the namespaces thing.

**Comment by abraham** [comment]
If you have `use Abraham\TwitterOAuth\TwitterOAuth;` this shouldn't be an issue. You might have a different issue from @petebarr.

What version of PHP are you using?

**Comment by dtaylorsam** [comment]
I'm also having this problem.

PHP 7.0.17

**Comment by petebarr** [comment]
7.1.8

**Comment by MazettePatacaisse** [comment]
Hello! Me too i have this prolem.....
I have trying all as i can found in the web.....i think!  
I have trying via composer...... or manually. pffff...
Once is .........TwitterOAuth not found, once is config not found....
it becomes a real fight for a simple authentification.
One thing is certain is that it does not work as the library is provided by following the installation guide
I think the "namespace" are not correct (and / or) there are missing "use" in the files ...
Please help us

**Comment by petebarr** [comment]
Sorry abraham, my fault. I didn't realise that a prev developer had a gitignore on the Config file so it was missing. I hate my life! lol. Cheers for your help anyway, much appreciated!

**Comment by WillJW** [comment]
Similar issue here. I had a rule in Transmit to skip files named "config.php". Apparently it isn't case-sensitive. All sorted now.

**Comment by jrmgx** [comment]
same here

**Comment by RobinPeter1090** [comment]
![image](https://user-images.githubusercontent.com/34569841/34036052-0b151000-e1aa-11e7-8e6c-ed201c2d0b67.png)
![image](https://user-images.githubusercontent.com/34569841/34036103-36403160-e1aa-11e7-9af4-2c7fde7982eb.png)
![image](https://user-images.githubusercontent.com/34569841/34036150-4f7abe98-e1aa-11e7-81fc-43b1b412d4ef.png)
Whats the issue for this error?

**Comment by abraham** [comment]
You're not following the installation instructions on https://twitteroauth.com/.

You should either use composer to install and load TwitterOAuth like this:

```
require "vendor/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;
```

or download the files manually and load TwitterOAuth like this:

```
require "twitteroauth/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;
```

**Comment by Napsterxp4** [comment]
Hi Abraham
For me the problem is quite different 
am getting 
`PHP Fatal error:  Uncaught Abraham\TwitterOAuth\TwitterOAuthException: {"errors":[{"code":32,"message":"Could not authenticate you."}]}`

from
src/TwitterOAuth.php on line 168 
Please advise

**Comment by griffind2009** [comment]
@abraham in what file do you use:

`require "twitteroauth/autoload.php";`
`use Abraham\TwitterOAuth\TwitterOAuth;`

**Comment by abraham** [comment]
Anywhere you want to use the `TwitterOAuth` class.

**Comment by griffind2009** [comment]
@abraham Thanks!

**Comment by Ppikrides** [comment]
Is there ant error with the server ?
Before two days was working fine.  Now i get an error 

HP Fatal error:  Uncaught Error: Class 'Abraham\TwitterOAuth\TwitterOAuth' not found in C:\inetpub\wwwroot\twiapp\index.php:17
Stack trace:
#0 {main}

and 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

can anyone help me

**Comment by thE-iNviNciblE** [comment]
Fatal error: Uncaught Error: Class "Abraham\TwitterOAuth\Config" not found in


require "vendor/autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;
use Abraham\TwitterOAuth\Config; 

Installed with Composer. It's not working.
