### ISSUE TITLE
Error processing your OAuth request: Invalid oauth_verifier parameter

### ISSUE THREAD

**Issue by hrvojebrkasic** [abraham/twitteroauth#587]
Hi, Abraham, I would really appreciate your help with this one. I want to auth user and get his info, but I can't fetch accessToken.

This is my code 

        $consumerKey = $this->container->getParameter('hwi_oauth.twitter.client_id');
        $consumerSecret = $this->container->getParameter('hwi_oauth.twitter.client_secret');
        $twitter = new TwitterOAuth($consumerKey, $consumerSecret);
        $request_token = $twitter->oauth('oauth/request_token', array('oauth_callback' => 'OAUTH_CALLBACK'));
        $url = $twitter->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
        header('Location: ' . $url);
        $twitter = new TwitterOAuth($consumerKey, $consumerSecret, $request_token['oauth_token'], $request_token['oauth_token_secret']);
        $access_token = $twitter->oauth("oauth/access_token", array('oauth_verifier' => $_REQUEST['oauth_verifier']));

and error I get is invalid oauth_verifier parameter. I don't know what I'm missing :/
I'm working on symfony 2.8, thank you.

**Comment by abraham** [comment]
Are you executing this code all at once in one block? Or did you combine multiple steps for the code snippet in this issue?

**Comment by hrvojebrkasic** [comment]
No, everything is in one block. `header('Location: ' . $url);` this line can be removed

**Comment by abraham** [comment]
That's not how Oauth works. The code has to be split into multiple steps. See https://twitteroauth.com/redirect.php for a live example.

You have to break it into several steps. First get a request_token.

        $twitter = new TwitterOAuth($consumerKey, $consumerSecret);
        $request_token = $twitter->oauth('oauth/request_token', array('oauth_callback' => 'OAUTH_CALLBACK'));

Then send the user to twitter.com where they will authorize access. This needs to be done in a web browser.

        $url = $twitter->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
        header('Location: ' . $url);

Now you can get an access token for the user that lets you make authenticated requests to the API.

        $twitter = new TwitterOAuth($consumerKey, $consumerSecret, $request_token['oauth_token'], $request_token['oauth_token_secret']);
        $access_token = $twitter->oauth("oauth/access_token", array('oauth_verifier' => $_REQUEST['oauth_verifier']));

**Comment by rajeshvavadiya** [comment]
Hello abraham,
                   I have set same as you tell but still giving same error.
