### ISSUE TITLE
Video Upload on Twitter 

### ISSUE THREAD

**Issue by sagartpandit** [abraham/twitteroauth#590]
hi, 
I have try to upload video on twitter using by twitteroauth , i have following all step on twitter document but post status test upload on twitter but video not show there 
$filename = 'http://app.socialwithease.com/video/test3.mp4';
$status = "Uploading a video with Twitter API";
					$media1 = $connection->upload('media/upload', array('media' => $filename, 'media_type' => 'video/mp4'), true);
              $result =  $connection->post('statuses/update', array(
					'status' => $status,
					'media_ids' => implode(',', array($media1->media_id_string))
				));
				print_r($result);
Can any body help me what the problem here

**Comment by abraham** [comment]
The video file has to be local on your server. It can't be a URL to a remote hosted file.

**Comment by sagartpandit** [comment]
Thanks Abraham by replay I have upload successfully video but i have one question about it's not work on url path of video so every time it not possible all video store on sever , we need third party store server so how can manage upload process & another issue i found when i am trying to upload long file I got status as  upload media status pending , can you please tell me how to check media status of in get method in twitteroauth? 

Thank you,
Sagartpandit

**Comment by abraham** [comment]
Twitter will not handle fetching media files so they have to be uploaded to the API. You will either have to get the media files onto your server and upload or get the Twitter credentials onto the server with the media files and upload them there.

I'm reopening this issue as a reminder to support [GET media/upload](https://dev.twitter.com/rest/reference/get/media/upload-status). Currently TwitterOAuth only supports POST methods on the uploads subdomain.

**Comment by abraham** [comment]
Actually there is already an issue to support that #554

**Comment by sumedh9495** [comment]
$twitter = new TwitterOAuth('services.twitter.client_id', 'services.twitter.client_secret', 'ACCESS_TOKEN', 
                                                 'ACCESS_SECRET');
// verify user
$user = $twitter->get("account/verify_credentials");

echo 'Welcome ' . $user->screen_name ;


$tweetWM = $twitter->upload('media/upload',['media' => 'path/to/video/a.mp4' , 'media_type' => 'video/mp4'],true);


$tweet = $twitter->post('statuses/update',['media_ids' => $tweetWM->media_id , 'status' => 'tweeting with video file']);

this is working
