### ISSUE TITLE
How do i get more that 200 user timelime tweets in php ?

### ISSUE THREAD

**Issue by DhiralKaniya** [abraham/twitteroauth#591]
I was integrate twitter-oauth abraham api in my php script and implementing certain task. But now i am try to get home's tweets. I am implement following function to do

function getTweets(){
        $access_token = $_SESSION['access_token']; 
        $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token['oauth_token'], $access_token['oauth_token_secret']);
        $data = $_SESSION['data'];
        $count = 10000;
        $params = array("screen_name"=>$data->screen_name,"count"=>$count);
        $tweets = $connection->get('statuses/home_timeline',$params);
        $tweet_result = array();
        $index = 0;
        foreach($tweets as $tweet){
            $tweet_result[$index]['id'] = $tweet->id_str;
            $tweet_result[$index]['createdAt'] = $tweet->created_at;
            $tweet_result[$index]['text'] = $tweet->text;
            $tweet_result[$index]['name'] = $tweet->user->name;
            $tweet_result[$index]['screen_name'] = $tweet->user->screen_name;
            $tweet_result[$index]['profileImageurl'] = $tweet->user->profile_image_url;
            $index++;
        }
        return $tweet_result;
    }
Using above code i am getting just 200 tweets of user's timeline. Now i want to get more that 200 user's timeline tweet.

is there any other way to do or where i need to improve ?

**Comment by abraham** [comment]
[GET statuses/home_timeline](https://dev.twitter.com/rest/reference/get/statuses/home_timeline) supports `since_id` and `max_id` parameters. After you have the lowest ID of the processed tweets you will want to call `GET statuses/home_timeline` with modified `$params`.

    $params = array(
        "screen_name" => $data->screen_name,
        "count" => $count
        "max_id" => $oldest_tweet_id
    );
