### ISSUE TITLE
twitter post not posting video 

### ISSUE THREAD

**Issue by kiranbulley** [abraham/twitteroauth#594]
hello ,

I am trying to upload video on twitter . post is generating there but it does not contain video.

         require "twitteroauth/autoload.php";
         use Abraham\TwitterOAuth\TwitterOAuth;

         // code to post video to tweeter

          define("CONSUMER_KEY","*********");
          define('CONSUMER_SECRET',"*****************");
         define('ACCESS_TOKEN',"******************");
         define('ACCESS_SECRET',"****************");

         $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_SECRET);
         $content = $connection->get("account/verify_credentials");
         $connection->setTimeouts(60, 30);
        $file=file_get_contents('samplevideo.mp4',true);
         $data = base64_encode($file);
         $media1 = $connection->upload('media/upload', ['media' =>'samplevideo.mp4']);

         $parameters = [
         'status' => 'test video',
        'media_ids' => implode(',', [$media1->media_id_string]),
         'media_type' => 'video/mp4',
         'media_category'=>'tweet_video'
         ];
        $result = $connection->post('statuses/update', $parameters);
        
          var_dump($result);

**Comment by abraham** [comment]
These lines are unnecessary. The upload method takes the path the the file and will get it from the filesystem.
```
$file=file_get_contents('samplevideo.mp4',true);
$data = base64_encode($file);
```

Is there a value in `$media1->media_id_string`? Are you sure the video is getting uploaded?

**Comment by huglester** [comment]
there are few steps, to upload video:
1. INIT upload
2. APPEND (I think 1 part of file can be up to 5MB) so this upload must be chunked into parts, if file is bigger than 5mb.)
3. FINALIZE upload

like described here: https://developer.twitter.com/en/docs/media/upload-media/uploading-media/chunked-media-upload

is uploading of videos possible?

**Comment by abraham** [comment]
@kiranbulley You are not using the chunked media upload API. Try uploading like this instead. Note the `true` at the end.

```
$media1 = $connection->upload('media/upload', ['media' =>'samplevideo.mp4'], true);
```

@huglester yes, uploading video is supported in in the `upload` method that wraps [uploadMediaChunked](https://github.com/abraham/twitteroauth/blob/master/src/TwitterOAuth.php#L286).

**Comment by huglester** [comment]
thanks @abraham  - solved :)

**Comment by huglester** [comment]
@kiranbulley 

```php
        $uploadedMedia = $this->getConnection()
            ->upload('media/upload', [
                'media' => $media->getPath(),
                'media_type' => 'video/mp4',
                'media_category' => 'tweet_video',
            ], true);
```
I think you need media_category - and it will work
