### ISSUE TITLE
'Undefined index: oauth_token' error in callback.php

### ISSUE THREAD

**Issue by ronakvachhani** [abraham/twitteroauth#597]
I can successfully get my _user_timeline_ and/or my _home_timeline_ as per your documentation & examples _using the static access token and access token secret_ 

...but...

I have been trying to make a dynamic app where users can sign in, authorize the app and they would get their own timelines & data.

I have copied **ONLY** the src folder and autoload.php from the master zip (as instructed by many tutorials available online.)

Below are the two files index.php and callback.php:

## **1. index.php**

```
<!DOCTYPE html>
<html>
<body>

<?php

require "autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;
	
define('CONSUMER_KEY', 'MY_KEY_HERE'); // Consumer key 
define('CONSUMER_SECRET', 'MY_SECRET_KEY_HERE'); // Consumer secret key 
define('OAUTH_CALLBACK', 'https://127.0.0.1/TweeTen/callback.php'); // App callback URL

if (!isset($_SESSION['access_token'])) {
	
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
	$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
	$_SESSION['oauth_token'] = $request_token['oauth_token'];
	$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
	$url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
	echo $url;
	
} else {
	
	$access_token = $_SESSION['access_token'];
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token['oauth_token'], $access_token['oauth_token_secret']);
	$user = $connection->get("account/verify_credentials");

 	$tweets = $connection->get('statuses/user_timeline', ['count' => 200, 'exclude_replies' => true, 'include_rts' => false]);
	
	print_r($tweets);
}
?>

</body>
</html>
```

**_This would generate the callback URL which users would then copy and paste into URL bar and they will be redirected to the app authorization page._** 

## **2. callback.php**

```
<?php

session_start();

require 'autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;

if (isset($_REQUEST['oauth_verifier'], $_REQUEST['oauth_token']) && $_REQUEST['oauth_token'] == $_SESSION['oauth_token']) {
	$request_token = [];
	$request_token['oauth_token'] = $_SESSION['oauth_token'];
	$request_token['oauth_token_secret'] = $_SESSION['oauth_token_secret'];
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $request_token['oauth_token'], $request_token['oauth_token_secret']);
	$access_token = $connection->oauth("oauth/access_token", array("oauth_verifier" => $_REQUEST['oauth_verifier']));
	$_SESSION['access_token'] = $access_token;
	
	// redirect user back to index page
	header('Location: ./');
}

?>
```

After allowing the app it prompts the error **_'Notice: Undefined index: oauth_token in C:\xampp\htdocs\TweeTen\callback.php on line 8'_** i.e. the if condition in callback.php!

I have also set my call URL (in twitter app settings ) as https://127.0.0.1/TweeTen/callback.php.

Where am I going wrong?

**_Edit: Every once in a while (totally random) when it doesn't prompt the error, it doesn't return any data. Just a blank screen._**

P. S. Why does it ask for authorizing the app every time? Is there no workaround for that?

**Comment by abraham** [comment]
You don't have `session_start();` in `index.php` so the `$_SESSION` values are not actually set.

If you don't want users to authorize every time use `$connection->url('oauth/authenticate' ...);`

**Comment by ronakvachhani** [comment]
@abraham - Thanks. Don't know how I missed that! _PHEW!_

**Comment by ronakvachhani** [comment]
Thanks! Don't know how I missed that.

And super helpful about the `$connection->url('oauth/authenticate' ...);`

**Comment by ronakvachhani** [comment]
Thanks! Don't know how I missed that. :)

**Comment by shahrukh9272** [comment]
undefined index oauth_token in twitteroauth.php

**Comment by abuyasin82** [comment]
I'm having the same problem I did add the session_start(); in the index file but still getting the same error my code is exactly like above

**Comment by danish-manzoor** [comment]
I got the same error.please someone help me

**Comment by danish-manzoor** [comment]
I have the same error like abuyasin82 .Someone help me

**Comment by abraham** [comment]
Following up on #717
