### ISSUE TITLE
Timeout Exceptions?

### ISSUE THREAD

**Issue by StyxOfDynamite** [abraham/twitteroauth#598]
Hoping I'm not the only one to see a massive increase in timeout exceptions being thrown? - I realise it's not the issue with the Project per say, but if anyone else has seen a spike I guess they might do similar to me and check known issues for the Project?

By spike, it's not happened once in ~4 weeks, and seen >40 already today....

**Comment by StyxOfDynamite** [comment]
Nothing of note on their API status.

https://dev.twitter.com/overview/status

**Comment by kinoute** [comment]
What kind of exceptions do you get? I'm getting exceptions with 0 ms timeout directly, even if I set the Timeouts to a higher number. But it's rare:

> Uncaught Abraham\TwitterOAuth\TwitterOAuthException: Operation timed out after 0 milliseconds with 0 out of 0 bytes received..

**Comment by StyxOfDynamite** [comment]
It's stopped happening, went from regularly having 0 occurrences to about
120 on that day alone. I'll close this ticket as I doubt it was the library
that was at fault.
