### ISSUE TITLE
pin based authentiation

### ISSUE THREAD

**Issue by rupesh1910** [abraham/twitteroauth#599]
HI i cant find any solution for pin based authentication

**Comment by abraham** [comment]
[PIN based authentication](https://developer.twitter.com/en/docs/basics/authentication/overview/pin-based-oauth) is the same as the [standard flow](https://developer.twitter.com/en/docs/basics/authentication/guides/authorizing-a-request) with two changes.

During [POST oauth/request_token](https://developer.twitter.com/en/docs/basics/authentication/api-reference/request_token) the value of `oauth_callback` should be set to `oob`.
During [POST oauth/access_token](https://developer.twitter.com/en/docs/basics/authentication/api-reference/access_token) the value of `oauth_verifier ` should be set to the PIN twitter.com gives your user.

You can see a live example of the standard OAuth flow on https://twitteroauth.com/redirect.php
