### ISSUE TITLE
Not able to get the right number of requested tweets from a specific Twitter account

### ISSUE THREAD

**Issue by pduthoit** [abraham/twitteroauth#600]
Hello,
I am having some trouble getting the right number of requested tweets from the [@SNCF](https://twitter.com/SNCF) Twitter account. It only retrieves me 1 or 2 tweets, even if i request for a large number of tweets.
I have tested this with a large number of Twitter accounts, and the @SNCF one, is the only one showing me that  bug.

Do you know where it would come from and how to resolve this problem ?

Here is what I specify to call the Twitter Service and to retrieve my requested number of tweets.

``` php
$tweets = $twitter->get('statuses/user_timeline', [
    'screen_name' => $screenName,
    'exclude_replies' => true,
    'include_rts' => 1,
    'count' => 200
]);

if ($twitter->getLastHttpCode() == 200) {
    $tweets = array_splice($tweets, 0, 50);
}
```

Thank you for your help

**Comment by abraham** [comment]
That account has lots of replies. So Twitter gets 200 tweets, removes the replies and then returns what's left to you. If you want more tweets that are not replies you will have to make additional requests using pagination.
