### ISSUE TITLE
How can I use the POST direct_messages/events/new API ?

### ISSUE THREAD

**Issue by Nicolapps** [abraham/twitteroauth#601]
Hello !

I have to use the `POST direct_messages/events/new` API. I have to supply a JSON POST body (the `Content-Type` header must be set to `application/json` as well), but with this API I can only provide an array. Is there a way I could send JSON content ?

Thanks,
Nicolas

**Comment by abraham** [comment]
This is coming in #581

**Comment by michaeldprice** [comment]
What is the status of this?
