### ISSUE TITLE
Direct Message Media downloading

### ISSUE THREAD

**Issue by derikb** [abraham/twitteroauth#603]
According to Twitter docs (https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object1.html):

> Unlike media shared in Tweets, media shared in Direct Messages requires authorization to view. This authorization can be presented via an authenticated twitter.com session or by signing a request with the User’s access token using OAuth 1.0A.

As far as I can tell, since the media urls are not API endpoints, I can't use this library to access them. But it would be great if I could, as I'm not sure how to sign the request with OAuth myself.

**Comment by abraham** [comment]
There is some initial work adding support for this in #463. I expect that supporting this will not land until v2 when a more extensible HTTP interface is introduced.
