### ISSUE TITLE
Uploading files to some endpoints doesn't work

### ISSUE THREAD

**Issue by TeRMiNaTe** [abraham/twitteroauth#604]
I've been trying to use the ``account/update_profile_banner`` endpoint, which only accepts base64 or image files as input, hence why I can't use the ``media/upload`` endpoint to upload the file before the post request.  
None of these methods work:
```
$base64data = '...';
$connection->post('account/update_profile_banner', [
	// 'banner'		=> $base64data
	// 'banner'		=> file_get_contents('http://via.placeholder.com/1500x500')
	// 'banner'		=> fopen('local/path/to/file.png', 'r')
]);
// Response: media type unrecognized.
```
I even tried using the ->upload method, but that seems to be reserved exclusively for the ``media/upload`` endpoint.

**Comment by abraham** [comment]
Profile images are not currently supported. Support for it is being tracked in #361
