### ISSUE TITLE
Not all tweets with favorites/list

### ISSUE THREAD

**Issue by theBear** [abraham/twitteroauth#606]
Is it known that it's not possible to get all tweets by using [favorites/list](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-favorites-list)?

Or is it just a bug by this script or by twitter?

My current fav-list starts at 4th tweets in comparison to its [webview](https://twitter.com/i/likes).

**Comment by abraham** [comment]
Are the missing tweets older than the tweets returned from the API? I don't think they web and API sort them the same way.

**Comment by theBear** [comment]
Hi Abraham, thanks for the reply! Weird, but you are right. The fav-list by the api contains – so far I could see – every favorited tweet, but it's ordered not equal like in the webview.

**https://twitter.com/i/likes** > sorts by the time you liked a tweet.

**[favorites/list](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-favorites-list)** >sorts by the time the tweet was created.
