### ISSUE TITLE
Sorry, that page does not exist.

### ISSUE THREAD

**Issue by AndiHamolli** [abraham/twitteroauth#608]
This is part of the json that shows up when I try to get user suggestions, together with message 34, via `$connection->get("users/suggestions/:slug", ["slug"=>"sports"]);`.

How to fix it?

**Comment by abraham** [comment]
`:slug` is a placeholder of where to put the value. You want one of the following:

    $connection->get("users/suggestions", ["slug"=>"sports"]);
    $connection->get("users/suggestions/sports");

**Comment by AndiHamolli** [comment]
YeahNow i get itThank you so much for your helpYou've built a great libraryI'm gonna try your suggestionAbraham Williams <notifications@github.com> wrote:>`:slug` is a placeholder of where to put the value. You want one of the following:>>    $connection->get("users/suggestions", ["slug"=>"sports"]);>    $connection->get("users/suggestions/sports");>>-- >You are receiving this because you authored the thread.>Reply to this email directly or view it on GitHub:>https://github.com/abraham/twitteroauth/issues/608#issuecomment-336561983

**Comment by hiranipradeep** [comment]
I am trying to get reach count of particular posts using 
Request:
$parameters = [
               ‘engagement_types’ => [‘impressions’, ‘engagements’, ‘favorites’],
               ‘tweet_ids’ => [“1014115961996054535”],
           ];
$result = $connection->post(‘insights/engagement/totals’, $parameters);

Response:
{#647
     +“message”: “Sorry, that page does not exist”
     +“code”: 34
}

Please help me on that issues.
Thanks.

**Comment by abraham** [comment]
That API endpoint is not currently supported. See #622
