### ISSUE TITLE
Automatically get new posts

### ISSUE THREAD

**Issue by Dennise89** [abraham/twitteroauth#609]
Hello,

Thanks for this library! It works great.
One question tho:

I am searching tweets with a specific hashtag, how can I automatically update the list?

Hope to hear from you.

**Comment by abraham** [comment]
Got get realtime update of tweets matching a hashtag you'll want to use the Streaming API, Specifically [POST statuses/filter](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter.html). Note that TwitterOAuth does not currently support the Streaming API. I've heard good things about [Phirehose](https://github.com/fennb/phirehose) though.

**Comment by Sentireport** [comment]
Gday, Abraham.

Mate, I am getting not expected response when attempting POST statuses/filter.  Is this Oct 17, 2017 post still valid?  (i.e., TwitterOAuth does not currently support the Streaming API -- aka: https://stream.twitter.com/1.1/statuses/filter.json...) ?

Thank you for a great platform -- using it for all other aspects of our Twitter interface.

Cheers to you and yours,

Sentireport.
