### ISSUE TITLE
I have a this error TwitterOAuthException in TwitterOAuth.php line 137:

### ISSUE THREAD

**Issue by Hugolopez2** [abraham/twitteroauth#613]
I can only use once the tokens
I get this error
TwitterOAuthException in TwitterOAuth.php line 137: Esta funcionalidad no está disponible temporalmente

    in TwitterOAuth.php line 137
    at TwitterOAuth->oauth('oauth/access_token', array('oauth_verifier' => 'JQ5O0Cp26MKi5Q3ZGLCoVRD0tn84zanC')) in TwitterController.php line 55
    at TwitterController->publicar_twitter()
    at call_user_func_array(array(object(TwitterController), 'publicar_twitter'), array()) in Controller.php line 55
Can someone support me?

**Comment by Hugolopez2** [comment]
i have this error "Invalid or expired token"

**Comment by abraham** [comment]
`oauth/access_token` can only be called once. You then have perform `oauth/request_token` and send the user to twitter.com to authorize before making another request to `oauth/access_token`.

**Comment by Hugolopez2** [comment]
this is my code
$twitterOAuth = new \Abraham\TwitterOAuth\TwitterOAuth($this->twitter_consumer_key, 
                            $this->twitter_secret);    
	$request_token = $twitterOAuth->oauth('oauth/request_token', array('oauth_callback' => $this->callback_url));
	$output->writeln(print_r($request_token));

    $token_acceso=response()->json(['oauth_token'=>$request_token['oauth_token']]);

    $token_acceso_secret=response()->json(['oauth_token_secret'=>$request_token['oauth_token_secret']]);
	$url="https://api.twitter.com/oauth/authorize?oauth_token=".$request_token['oauth_token'];

**Comment by Hugolopez2** [comment]
$connection = new \Abraham\TwitterOAuth\TwitterOAuth(
                            $this->twitter_consumer_key, 
                            $this->twitter_secret, 
                            $access_token, 
                            $access_token_secret// twitter secret from DB
                            );
        $twitterUser=$connection->get("account/verify_credentials");
        // get acces token
            $access_token = $connection->oauth("oauth/access_token", ["oauth_verifier" => "oUalUJtgZadAOUIFv5wggyMZKUWhAOvK"]);

**Comment by abraham** [comment]
Please review the authentication flow as documented https://twitteroauth.com/redirect.php

You appear to be calling `oauth/access_token` after having an access token for the user.

**Comment by Hugolopez2** [comment]
I can´t resolve the error..
this is my code where i get login
public function index(){
    $twitterOAuth = new \Abraham\TwitterOAuth\TwitterOAuth($this->twitter_consumer_key, 
                            $this->twitter_secret);
    $request_token = $twitterOAuth->oauth('oauth/request_token', array('oauth_callback' => $this->callback_url));
    $tokens = TwitterTokens::create($request_token);
    $tokens = "https://api.twitter.com/oauth/authorize?oauth_token=".$tokens;
	return view('twitter.index')->with('connection',$tokens)->with("secret",$tokens);
}
The next code, is where i want use the token
public function publicar_twitter(){
    $toke_acceso="iKpZ2gAAAAAA2qY2AAABX5LZiy4";
    $token = TwitterTokens::where('oauth_token', $toke_acceso)->first(); 
    $connection = new \Abraham\TwitterOAuth\TwitterOAuth(
                            $this->twitter_consumer_key, 
                            $this->twitter_secret, 
                            $toke_acceso, 
                            $token->oauth_token_secret
                            );
    // get acces token
    $access_token = $connection->oauth("oauth/access_token", ["oauth_verifier" => $toke_acceso]); 
    $twitterOAuth = new \Abraham\TwitterOAuth\TwitterOAuth( $this->twitter_consumer_key, $this->twitter_secret, $access_token['oauth_token'], $access_token['oauth_token_secret'] );

    // Let's get the user's info with email
    $twitterUser = $twitterOAuth->get('account/verify_credentials', ['include_entities' => 'false','include_email'=>'true','skip_status'=>'true',]);
    return view('twitter.publicar')->with('statuses',$twitterUser);

    }
but i have the error oauth/access_token can only be called once. You then have perform oauth/request_token and send the user to twitter.com to authorize before making another request to oauth/access_token.

Help!!

**Comment by abraham** [comment]
As I said before, follow along with the documented authentication flow here: https://twitteroauth.com/redirect.php. It tells you exactly what API methods to call when when.

You should not be hardcoding `$toke_acceso="iKpZ2gAAAAAA2qY2AAABX5LZiy4";` that shold be dynamic and change every single time someone goes through the OAuth flow.

**Comment by Hugolopez2** [comment]
I would like it not to be dynamic, I want to make automatic publications, is it possible to do that?

**Comment by abraham** [comment]
The response from `$twitterOAuth->oauth('oauth/request_token', ...)` is only valid once and is not useful stored any longer than five minutes.

The response from `$connection->oauth("oauth/access_token", ...)` is the valid credentials for the user and should be stored long term for automated publications.

**Comment by harendrasay** [comment]
Dear Abraham,

Thanks for all the valuable comments, I am also stuck and getting the following error:
_# [27-Jan-2018 20:30:31 UTC] PHP Fatal error:  Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Invalid request token.' in /home/growuptraffic/public_html/tweetapp/src/TwitterOAuth.php:171
Stack trace:
#0 /home/growuptraffic/public_html/tweetapp/callback.php(27): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/access_to...', Array)
#1 {main}
  thrown in /home/growuptraffic/public_html/tweetapp/src/TwitterOAuth.php on line 171_

Here is the Inex.php code:
<?php 
session_start();
require "autoload.php"; 
use Abraham\TwitterOAuth\TwitterOAuth;


define('CONSUMER_KEY','XXXXXXXXXXXXXXX');
define('CONSUMER_SECRET','XXXXXXXXXXXXXXXXXXXXXX');
define('OAUTH_CALLBACK','http://growuptraffic.com/tweetapp/callback.php');

if(!isset($_SESSION['acces_token'])){
 $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET); 
 $request_token = $connection->oauth("oauth/request_token", array('oauth_callback' => OAUTH_CALLBACK )); 
 $_SESSION['oauth_token']=  $request_token['oauth_token']; 
 $_SESSION['oauth_token_secret'] =  $request_token['oauth_token_secret'];
 
 //print_r($request_token);
 
 //$url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
 
 $url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
 
 echo $url; 
 //echo "KKKddddd";
 //die;
 
} else  {
	
$access_token = $_SESSION['access_token'];

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token['oauth_token'],$access_token['oauth_token_secret']);

$user = $connection -> get("account/verify_credentials");

echo $user ->status->text;

}




?>
and below is the callback.php:
<?php
session_start();
require "autoload.php"; 
use Abraham\TwitterOAuth\TwitterOAuth;
if(isset($_REQUEST['oauth_verifier'],$_REQUEST['oauth_token']) && $_REQUEST['oauth_token']==$_SESSION['oauth_token']){
	
	
	
//define('CONSUMER_KEY','XXXXXXXXXXXXXXXXXX');
//define('CONSUMER_SECRET','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
//define('OAUTH_CALLBACK','http://growuptraffic.com/tweetapp/callback.php');

	//echo CONSUMER_KEY; die; 

	$request_token = [];
	$request_token['oauth_token'] = $_SESSION['oauth_token'];
	$request_token['oauth_token_secret'] = $_SESSION['oauth_token_secret'];	
	
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET,$request_token['oauth_token'] ,$request_token['oauth_token_secret']);
	
	
//get authentication tokens from twitter
//$access_token = $connection->oauth("oauth_token", array("oauth_verifier" => $_REQUEST['oauth_verifier']));

	
		
$access_token = $connection->oauth("oauth/access_token", array("oauth_verifier" =>$_REQUEST['oauth_verifier']));
	
	
	$_SESSION['access_token'] = $access_token;
	
	
	echo $_REQUEST['oauth_verifier']; 
	echo "<pre>";
	print_r($access_token);
	die;
	
	
	
	
	header("Locatio: ./");

}



?>

Please look into the error and let me know the update

Regards,
Harendra
