### ISSUE TITLE
I have a this error TwitterOAuthException in TwitterOAuth.php line 440

### ISSUE THREAD

**Issue by kntrknm** [abraham/twitteroauth#615]
I definitely post it because I do not know how to solve it.

When executing this code with shared server, the following error occurred.

```
<?php
    define( 'CONSUMER_KEY', 'hogehoge' );
    define( 'CONSUMER_SECRET', 'hogehoge' );
    define( 'OAUTH_CALLBACK', 'https://example.com/callback/' );
    use Abraham\TwitterOAuth\TwitterOAuth;
    session_start();
    require_once( 'twitteroauth/autoload.php' );
    $connection = new TwitterOAuth( CONSUMER_KEY, CONSUMER_SECRET );
    $request_token = $connection->oauth( 'oauth/request_token', [ 'oauth_callback' => OAUTH_CALLBACK ] 
```

> Fatal error: Uncaught Abraham\TwitterOAuth\TwitterOAuthException in /home/user/html/DocumentRoot/twitteroauth/src/TwitterOAuth.php:440 Stack trace: #0 /home/user/html/DocumentRoot/twitteroauth/src/TwitterOAuth.php(357): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array) #1 /home/user/html/DocumentRoot/twitteroauth/src/TwitterOAuth.php(134): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array) #2 /home/user/html/DocumentRoot/twitter.php(9): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array) #3 {main} thrown in /home/user/html/DocumentRoot/twitteroauth/src/TwitterOAuth.php on line 440

This problem has never occurred in another environment.
Please tell me how to solve.

**Comment by abraham** [comment]
If you catch the error, what is the message accompanying it?

**Comment by kntrknm** [comment]
Thank you for your a comment!
But, This is the only message output on the browser...

> Fatal error: Uncaught Abraham\TwitterOAuth\TwitterOAuthException in /home/user/html/DocumentRoot/twitteroauth/src/TwitterOAuth.php:440 Stack trace: #0 /home/user/html/DocumentRoot/twitteroauth/src/TwitterOAuth.php(357): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array) #1 /home/user/html/DocumentRoot/twitteroauth/src/TwitterOAuth.php(134): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array) #2 /home/user/html/DocumentRoot/twitter.php(9): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array) #3 {main} thrown in /home/user/html/DocumentRoot/twitteroauth/src/TwitterOAuth.php on line 440

Please tell me if there are other views.

**Comment by abraham** [comment]
This has been open for a while. Please comment if you still need help.
