### ISSUE TITLE
Twitter connect errors (using proxy)

### ISSUE THREAD

**Issue by nikolasr200** [abraham/twitteroauth#616]
Hi i have an application on the 0.6.2 version.
The application integrates with 4 social networks through proxy (facebook, twitter, linkedin, google+) however we notice high rate of failures over twitter.

```
        $connection = new Abraham\TwitterOAuth\TwitterOAuth(
            $twitter_CONSUMER_KEY, 
            $CONSUMER_SECRET);
            $connection->setProxy(array(
                'CURLOPT_PROXYUSERPWD' => '',
                'CURLOPT_PROXY' => $proxy,
                'CURLOPT_PROXYPORT' => $proxy_port, //8080
            ));
            $connection->setTimeouts(60, 60);

        try {
            $request_token = $connection->oauth(
                'oauth/request_token',
                ['oauth_callback' => $OAUTH_CALLBACK]
            ]);
            //received token info from twitter
            $tw_token          = $request_token['oauth_token'];
            $tw_token_secret   = $request_token['oauth_token_secret'];
            $url = $connection->url('oauth/authorize', array('oauth_token' =>
$request_token['oauth_token']));
            }catch (Exception $e) {
            $e->getMessage()
            }
```

in a period of three months

| count | error
| 10520 | couldn't connect to host // the most common error which is not clear if it is a proxy issue, or twitter issue
| 644 |  Received HTTP code 503 from proxy after CONNECT // this seems as a service unavailable from twitter
| 600 |  // no returned message
| 505  | Empty reply from server
| 405  | SSL connect error
| 140  | Proxy CONNECT aborted

Any help would be much appreciated

**Comment by abraham** [comment]
"couldn't connect to host" is typically not an issue with Twitter. Sometimes it's DNS, sometimes it's service providers between your machines and Twitter, sometimes it's a proxy issues. Ultimately I don't think the errors are very related to this library but to network infrastructure.
