### ISSUE TITLE
Can't get insights

### ISSUE THREAD

**Issue by digitak** [abraham/twitteroauth#622]
hi
when i run this code : 
`$insight = $connection->post('insights/engagement/totals' , array('tweet_ids' => $tweet_id , 'engagement_types' => 'impressions' ));`

get this error :
`object(stdClass)#277 (1) { ["errors"]=> array(1) { [0]=> object(stdClass)#336 (2) { ["message"]=> string(31) "Sorry, that page does not exist" ["code"]=> int(34) } } } Finished`

how to get impression of tweet?

tanks.

**Comment by abraham** [comment]
That API endpoint lives under the `data-api.twitter.com` domain which this library doesn't yet support.

**Comment by seanmangar** [comment]
That's a shame, I have the same problem. Could I submit a PR with a method to change the API host? This would do the trick I reckon.

**Comment by abraham** [comment]
Moving to #684
