### ISSUE TITLE
Twitter Image Upload Changed? Media Type Unrecognized.

### ISSUE THREAD

**Issue by michaeldprice** [abraham/twitteroauth#623]
Hello Guys,

All of a sudden my twitter posts for image uploads started failing.
In my code I was using ...

$Twitter->upload('media/upload', ['media' => $rawBinary]);

On a whim, I decided to try sending it using the  file location, instead of the binary, and they started working again.

Any Idea's about why this happened?

**Comment by CristianGno** [comment]
It turns out that the library in the upload method converts the image to the binary, so you are not sending a valid file to decode

**Comment by abraham** [comment]
As documented on https://twitteroauth.com, the current API requires a path to a file.

    $connection->upload('media/upload', ['media' => '/path/to/file/kitten1.jpg']);

**Comment by coderbhaai** [comment]
@abraham If you can highlight on how does buffer.com posts images through URL, it will be helpful.

**Comment by abraham** [comment]
I'd assume that buffer is downloading to their servers first.
