### ISSUE TITLE
How can I integrate the library correctly in Laravel 5.5?

### ISSUE THREAD

**Issue by CristianGno** [abraham/twitteroauth#629]
Hello! I have tried for several days to integrate the library in Laravel 5.5 and I can not ... Maybe this kind of questions can not be asked here but I have not found a way to use it and I have exhausted my possibilities. If they could help me it would be fantastic. Thank you.

**Comment by maggz69** [comment]
# If you have access to composer and ssh
Run composer in laravel  and let it install this repository.
`Composer require abraham/twitteroauth`
Add `use Abraham\TwitterOAuth\TwitterOAuth;` in the header of your routes or controller or model
Access the library as per the tutorials on [TwitterOauth.com](url)
# Without composer
Copy this project and paste it somewhere in your directory
Load autoload in your php file by getting the correct directory link to the vendor/autoload.php

**Comment by abraham** [comment]
Composer makes it easy to get TwitterOAuth. I have no experience with Laravel however so I can't provide any specific advice.
