### ISSUE TITLE
Change CURL parameters that are predefined

### ISSUE THREAD

**Issue by nikolasr200** [abraham/twitteroauth#630]
Hi,

is it possible without changing library default parameters for obvious reasons, to be able (perhaps in a future version) to override them?

for instance

            CURLOPT_SSL_VERIFYHOST => 2,
            CURLOPT_SSL_VERIFYPEER => true,

we still haven't spotted the issue over here https://github.com/abraham/twitteroauth/issues/616#issuecomment-350571292 which is definately not a twitter / library issue, but being able to handle some further options which might affect may be a good starting point.

**Comment by abraham** [comment]
I'll put it on the list to explore. I try to avoid surfacing options to make code less secure as developers having issues are likely to just disable the security measures instead of trying to fix the root cause.

**Comment by nikolasr200** [comment]
You are right, imo you could have them predefined in the core code, as long as this is not great hassle to you, but still be able through the api call for someone to override them at their own risk. I understand your concerns, but as i had stated in the previous ticket there is still some underlying issue through the proxy call, probably with an internal certificate, and everytime i have to remember to alter library options just to bypass ssl verifications.
Thank you for adding it to the explore list :)

**Comment by abraham** [comment]
The library is going to migrate to Guzzle which will support modifying more of the configuration.
