### ISSUE TITLE
Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException'

### ISSUE THREAD

**Issue by asifnaveed28** [abraham/twitteroauth#635]
i am trying to generate the URL to make request to authorize my application. i find when $twitteroauth->oauth( method call it generate the fatal error as follow.
  
Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message '{"errors":[{"code":32,"message":"Could not authenticate you."}]}' in C:\xampp\htdocs\promo\app\twitteroauth\src\TwitterOAuth.php:138 Stack trace: #0 C:\xampp\htdocs\promo\twitter.php(26): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array) #1 {main} thrown in C:\xampp\htdocs\promo\app\twitteroauth\src\TwitterOAuth.php on line 138

my code is as below 
`
$twitteroauth = new TwitterOAuth($config['consumer_key'], $config['consumer_secret']);

$request_token = $twitteroauth->oauth(
        'oauth/request_token', [
    'oauth_callback' => $config['url_callback']
        ]
);

if ($twitteroauth->getLastHttpCode() != 200) {
    throw new \Exception('There was a problem performing this request');
}

$url = $twitteroauth->url(
        'oauth/authorize', [
    'oauth_token' => $request_token['oauth_token']
        ]
);
// and redirect
header('Location: ' . $url);
`

**Comment by rocketsan** [comment]
Try to "Regenerate Consumer Key and Secret" at apps.twitter.com. It helped me.

**Comment by asifnaveed28** [comment]
i set redirect url and it start working
