### ISSUE TITLE
expires oauth_verifier

### ISSUE THREAD

**Issue by NotherOne** [abraham/twitteroauth#636]
Good evening,
I have a problem with the oauth_verifier since I want to use it in more than one page, my query is, it can be used in more than one page. And if you can, could you provide me with an example, I would greatly appreciate it.

Greetings.

**Comment by abraham** [comment]
`oauth_verifier` can be used once and only once. The access token you get when you use the `oauth_verifier` can be stored and used on multiple pages though.
