### ISSUE TITLE
timed out before SSL handshake

### ISSUE THREAD

**Issue by aoxiang594** [abraham/twitteroauth#639]
Hello Abraham
Thanks for you build twitteroatuh,this is a amazing project.

when i use twitteroauth,i am getting this error

PHP Fatal error:  Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'timed out before SSL handshake' in /root/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php:440
Stack trace:
#0 /root/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(357): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array)
#1 /root/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(323): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array)
#2 /root/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(178): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'account/verify_...', Array)
#3 /root/twitter/index.php(7): Abraham\TwitterOAuth\TwitterOAuth->get('account/verify_...')
#4 {main}

and i don't know why.

**Comment by abraham** [comment]
You could try extending the timeout settings as described on https://twitteroauth.com/. You might also try checking if there are proxies causing issues.
