### ISSUE TITLE
Manage exception timeout

### ISSUE THREAD

**Issue by LiveXenon** [abraham/twitteroauth#645]
Is there a way to handle the timeout exception using the try catch method?

try{
$request_token = $twitteroauth->oauth(......)
}catch (?){
}

The error I receive is: PHP Fatal error:  Uncaught exception 'Abraham\\TwitterOAuth\\TwitterOAuthException' with message 'Connection timed out after 10001 milliseconds' in /twitteroauth/src/TwitterOAuth.php:503\nStack trace:\n#0 /twitteroauth/src/TwitterOAuth.php(420): Abraham\\TwitterOAuth\\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array)\n#1 /twitteroauth/src/TwitterOAuth.php(372): Abraham\\TwitterOAuth\\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array)\n#2 /twitteroauth/src/TwitterOAuth.php(354): Abraham\\TwitterOAuth\\TwitterOAuth->makeRequests('https://api.twi...', 'GET', Array)\n#3 /twitteroauth/src/TwitterOAuth.php(209): Abraham\\TwitterOAuth\\TwitterOAuth->http('GET', 'https://api.twi...', 'friends/ids', Array)\n#4 /twitteroauth/src/TwitterOAuth.php on line 503

**Comment by abraham** [comment]
There isn't currently a specific timeout exception. You'd have to catch the TwitterOAuthException and match against the message. Something like the following.

```php
try {
  $request_token = $twitteroauth->oauth(......)
} catch (TwitterOAuthException $e) {
  $isTimeout = str_contains($e-getMessage(), 'Connection timed out');
  if ($isTimeout) {
    // something
  }
}
```
