### ISSUE TITLE
Could not authenticate you.

### ISSUE THREAD

**Issue by gurjanjua** [abraham/twitteroauth#650]
Hlo sir,
I am unable to authenticate and authorize the access of twitter. It was working fine few days ago but suddenly it start throwing below error.
  
`Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message '{"errors":[{"code":32,"message":"Could not authenticate you."}]}' in /var/www/html/user/vendor/abraham/twitteroauth/src/TwitterOAuth.php:168 Stack trace: #0 /var/www/html/user/givePermissions.php(52): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array) #1 {main} thrown in /var/www/html/user/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 168`

My code is :- 
   $callback_url = $config['url_callback'];
   $twitteroauth = new TwitterOAuth($config['customerKey'], $config['customerSecret']);
   $request_token = $twitteroauth->oauth(
        'oauth/request_token', [
            'oauth_callback' =>$callback_url
        ]
    );
    print_r($request_token); die;

    if($twitteroauth->getLastHttpCode() != 200) {
        throw new \Exception('There was a problem performing this request');
    }

It seems $request_token is not generating because when i am printing variable it throwing above error. Please help me asap. Thankyou

**Comment by RyuMaster** [comment]
Stopped working for me too. Did Twitter change their API? Was not it supposed to be in August?

**Comment by bytehead** [comment]
Same here.

**Comment by willymena** [comment]
You try sending all 4 keys (Consumer Key, Consumer Secret , Access Token and Access Token Secret?

**Comment by bytehead** [comment]
Yes, it stopped working without any change...

**Comment by getflourish** [comment]
Same here. Suddenly stopped working. Somewhere in that line:

```
$connection = new TwitterOAuth($consumer_key, $consumer_secret);
```

**Comment by abraham** [comment]
You have to change how you handle callback URLs. Check out Twitter's announcement.

https://twittercommunity.com/t/action-required-sign-in-with-twitter-users-must-whitelist-callback-urls/105342/3

**Comment by getflourish** [comment]
Thank you!

**Comment by augustinejenin** [comment]
Hello Sir,

I am getting an error when connecting with abraham twitter sdk.

Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message '{"errors":[{"code":32,"message":"Could not authenticate you."}]}' in /home/tieit/domains/alpha.tieit.io/public_html/application/third_party/twitter-oauth/src/TwitterOAuth.php:138 Stack trace: #0 /home/tieit/domains/alpha.tieit.io/public_html/application/modules/smm/controllers/social_media.php(1387): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array) #1 [internal function]: Social_media->twitterLogin('index') #2 /home/tieit/domains/alpha.tieit.io/public_html/system/core/CodeIgniter.php(359): call_user_func_array(Array, Array) #3 /home/tieit/domains/alpha.tieit.io/public_html/index.php(210): require_once('/home/tieit/dom...') #4 {main} thrown in /home/tieit/domains/alpha.tieit.io/public_html/application/third_party/twitter-oauth/src/TwitterOAuth.php on line 138.

I have two servers with two different twitter applications with different callback urls. In production server, its working but I got this error in my staging sever. Code is same in both server. In staging, php version upgraded from 5.4 to 5.6. Will that cause any issues or I need to create developer account.

Thank you,
