### ISSUE TITLE
App suddenly throwing error: Could not resolve host: api.twitter.com;

### ISSUE THREAD

**Issue by sarahk** [abraham/twitteroauth#652]
My app has been trucking along for a week or so, doing what it should. Today it stopped.

I've checked in my app settings and my page's notifications but there are no messages warning that I'm blocked, no code has changed. 

What could be stopping my the app from connecting?

`Fatal error: Uncaught Abraham\TwitterOAuth\TwitterOAuthException: Could not resolve host: api.twitter.com; Name or service not known in /var/www/vhosts/mysite.net/httpdocs/includes/abraham/twitteroauth/TwitterOAuth.php:503 Stack trace: #0 /var/www/vhosts/mysite.net/httpdocs/includes/abraham/twitteroauth/TwitterOAuth.php(420): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array) #1 /var/www/vhosts/mysite.net/httpdocs/includes/abraham/twitteroauth/TwitterOAuth.php(165): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array) #2 /var/www/vhosts/mysite.net/httpdocs/includes/config.php(48): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...') #3 /var/www/vhosts/mysite.net/httpdocs/cronjob.php(88): getNewTwitterObject() #4 /var/www/vhosts/mysite.net/httpdocs/cronjob.php(347): flagTweeter->postTweet(1) #5 {main} thrown in /var/www/vhosts/mysite.net/httpdocs/includes/abraham/twitteroauth/TwitterOAuth.php on line 503`

**Comment by abraham** [comment]
> Could not resolve host: api.twitter.com; Name or service not known

This is a problem with your server or hosting provider and the DNS they provide. I would contact them or change your DNS service.
