### ISSUE TITLE
 certificate error with newly installed apache server with php 7.2.5 

### ISSUE THREAD

**Issue by StepanyanAlbert** [abraham/twitteroauth#653]
Fresh installed apache with php throws an error when trying to get statuses . 
```
PHP Fatal error:  Uncaught Abraham\TwitterOAuth\TwitterOAuthException: error setting certificate verify locations:
  CAfile: F:\twitterApi\src\
  CApath: none in F:\twitterApi\src\TwitterOAuth.php:440
Stack trace:
#0 F:\twitterApi\src\TwitterOAuth.php(357): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array)
#1 F:\twitterApi\src\TwitterOAuth.php(323): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array)
#2 F:\twitterApi\src\TwitterOAuth.php(178): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'search/tweets', Array)
#3 F:\twitterApi\index.php(14): Abraham\TwitterOAuth\TwitterOAuth->get('search/tweets', Array)
#4 {main}
  thrown in F:\twitterApi\src\TwitterOAuth.php on line 440

Fatal error: Uncaught Abraham\TwitterOAuth\TwitterOAuthException: error setting certificate verify locations:
  CAfile: F:\twitterApi\src\
  CApath: none in F:\twitterApi\src\TwitterOAuth.php:440
Stack trace:
#0 F:\twitterApi\src\TwitterOAuth.php(357): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array)
#1 F:\twitterApi\src\TwitterOAuth.php(323): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array)
#2 F:\twitterApi\src\TwitterOAuth.php(178): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'search/tweets', Array)
#3 F:\twitterApi\index.php(14): Abraham\TwitterOAuth\TwitterOAuth->get('search/tweets', Array)
#4 {main}
  thrown in F:\twitterApi\src\TwitterOAuth.php on line 440
```

**Comment by djpetenice** [comment]
I'm getting exactly the same error - running on gcloud app engine.

**Comment by StepanyanAlbert** [comment]
The horrible part is there is not any decent lib to act with twitter

**Comment by djpetenice** [comment]
#524 this worked for me.

**Comment by StepanyanAlbert** [comment]
I can't find that line in TwitterOAuth.php

**Comment by StepanyanAlbert** [comment]
@djpetenice  can you put the line where you changed it ?

**Comment by abraham** [comment]
ssl_verfy => false is not a recommended solution. SSL verification is necessary to prevent malicious actors from intercepting your requests to the Twitter API and spying or modifying them. You should make sure the environment you are using is up to date and can correctly verify SSL certificates.

**Comment by StepanyanAlbert** [comment]
@abraham  for local servers are there other solutions ?

**Comment by abraham** [comment]
The OS or the server probably need to be updated. Maybe openssl.

**Comment by StepanyanAlbert** [comment]
Windows 10 and xampp latest version as this is for testing only . But I think we can close as @djpetenice  said problem is solved setting ssl to false .

**Comment by djpetenice** [comment]
I'm getting this error on Google Cloud App Engine - any idea what the solution would be?

**Comment by StepanyanAlbert** [comment]
it seems to worked but  - 
 ```
$connection->get("statuses/home_timeline", ["count" => 25, "exclude_replies" => true]);
``` 
returns empty array , Does the twitter have any kind of limit for old tweets ? for instance you can't get tweets older then 3 years ?

**Comment by abraham** [comment]
App Engine should be automatically updated and current. I wouldn't expect any issues from them.
