### ISSUE TITLE
Missing method to Post media/metadata/create

### ISSUE THREAD

**Issue by davaxi** [abraham/twitteroauth#655]
Hi,

I want to use https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-metadata-create api but not exist upload method without media.

Two choice, i think : 
- Create new method for this case
- Update upload method for case without media but with alt_text / media_id
- Update post method for pass UPLOAD_HOST

**Comment by abraham** [comment]
Planning on addressing this in #685
