### ISSUE TITLE
post a direct message using 1.1/direct_messages/events/new.json

### ISSUE THREAD

**Issue by gentjana** [abraham/twitteroauth#657]
Hello i'm using your api to post direct using the new entitiy but does not work for me. My code as below. Please help is very important. Thank You.

$parameters = array(
    'event' => array(
        'type' => 'message_create',
        'message_create' => array(
            'target' => array(
                "recipient_id" => "id of receipent"
            ),
            'message_data' => array(
                'text' => "Hello World!"
            )
        )
    )
);

$connection = new TwitterOAuth(CONS_KEY, CONS_SECRET, ACC_TOKEN, ACC_TOKEN_SECRET);
$direct = $connection->post("direct_messages/events/new.json", $parameters);

**Comment by pklosko** [comment]
Hi, see https://github.com/abraham/twitteroauth/issues/651
P.
