### ISSUE TITLE
Twitter welcome message

### ISSUE THREAD

**Issue by Ashwin-Kapes** [abraham/twitteroauth#661]
`$parameters = array (
  'welcome_message' => 
  array (
    'name' => 'simple_welcome-message 01',
    'message_data' => 
    array (
      'text' => 'Welcome!',
    ),
  ),
);
$content = $connection->post("direct_messages/welcome_messages/new", array(json_encode($parameters)));`

I tried above code to generate welcome message for all users as soon they open Direct message window. But in response I'm getting "null".

**Comment by abraham** [comment]
This will be fixed with https://github.com/abraham/twitteroauth/pull/581
