### ISSUE TITLE
Should throw a decent error when request refused by Twitter

### ISSUE THREAD

**Issue by teo1978** [abraham/twitteroauth#665]
I'm forced to file a new issue because #115 was not only wrongly closed, but locked to comments, so I can't comment on that to ask for it to be reopened.

I'm facing the exact same problem as the OP there, for the exact same reason: my server clock being off by more than 5 minutes.

However, in this situation, you should get a meaningful exception with a clear error message, not a PHP error message caused by accessing a non-existing index. This is a BUG in the library.

By definition, whenever you see an error that says "PHP error/warning/notice" that points to a line of code that is within the library code, that's a bug in the library. If *I* am doing something wrong, then the library should throw an exception pointing to what *I* am doing wrong.

**Comment by abraham** [comment]
`getRequestToken` is not a method in the codebase anymore. If you are using that method you should update your version of TwitterOAuth.

Looking at the current [`oauth`](https://github.com/abraham/twitteroauth/blob/70d8fe1ab49d1fd6801cb18fcf7517e2e990aa38/src/TwitterOAuth.php#L167:L169) method in the codebase it includes error handling if something other than a 200 response is returned from the server.

If you get similar errors with the current version please create a new issue.
