### ISSUE TITLE
Switching to guzzle

### ISSUE THREAD

**Issue by abraham** [abraham/twitteroauth#680]

**Comment by sp4ceb4r** [comment]
Hello abraham,

In #686 you ask if anyone is interested on working one of the v2 features to comment on the particular issue. I'd be interested in helping implement this one.

It would, in my opinion, make sense to also work on #682 in conjunction with updating the transport layer.

**Comment by RoHodson** [comment]
Please do not. Adding more prerequisits is bad/inconvenient/to be avoided.

**Comment by abraham** [comment]
TwitterOAuth is in maintenance mode and major improvements are no longer planned. https://github.com/abraham/twitteroauth/issues/1188
