### ISSUE TITLE
Add File class

### ISSUE THREAD

**Issue by abraham** [abraham/twitteroauth#681]
Add a `File` class that handles getting file data for media uploads. The `File` class will handle getting the file data from a variety of sources (disk, URL, base64, etc) and make sure it's in the needed format for upload.

**Comment by jeanlucc** [comment]
Hi,

First a great THANK YOU for this lib!!!

I encountered the problem when I used it for file upload but in my case it could have been solved by not performing the is_readable check here:
https://github.com/abraham/twitteroauth/blob/master/src/TwitterOAuth.php#L295-L296

My use case is I use a URL as path and file_get_contents works fine but the is_readable check make it fail before this.

I'm curious, why is this check needed?

Best,

J-L

**Comment by abraham** [comment]
TwitterOAuth is in maintenance mode and major improvements are no longer planned. https://github.com/abraham/twitteroauth/issues/1188
