### ISSUE TITLE
Throw exceptions for non-2XX HTTP responses

### ISSUE THREAD

**Issue by abraham** [abraham/twitteroauth#682]
Users shouldn't have to check if the response code is a HTTP 2XX.

**Comment by KevinHN** [comment]
@abraham I think it'd be better if it has an option for this.

Because some of API, status is non-2xx doesn't mean it's error, such as 'account_activity/all/:env_name/subscriptions' for the case user's already subscribed.

**Comment by abraham** [comment]
TwitterOAuth is in maintenance mode and major improvements are no longer planned. https://github.com/abraham/twitteroauth/issues/1188
