### ISSUE TITLE
Using Library failed

### ISSUE THREAD

**Issue by Justinsss** [abraham/twitteroauth#688]
Hey Abraham,
I would like to program a twitter app.
I have a Linux (Debian 9 used) VServer and would like to run my script on that. (XAMPP installed)
Details:
path for script = opt/lampp/htdocs - there is my script tweet.php
library path = opt/lampp/htdocs/twitteroauth - there is the folder with src folder and all files
Problem is: 
It can't find you TwitterOAuth.php file
Error message: 
Fatal error: Uncaught Error: Class 'opt\lampp\twitteroauth\src\TwitterOAuth' not found in /opt/lampp/htdocs/tweet.php:10 Stack trace: #0 {main} thrown in /opt/lampp/htdocs/tweet.php on line 10

CODE to line 10:

```
<?php

set_time_limit(999999);
if( ob_get_level() > 0 ) ob_end_flush();
ob_implicit_flush(true);

require_once 'autoload.php';
 use \opt\lampp\htdocs;
 
$connection = new opt\lampp\twitteroauth\src\TwitterOAuth.php("", "","","");
```

(my keys was removed for this post. they are putted in the fields in my normal code-file.)

So, what can I do?
Best regards
Justin

**Comment by abraham** [comment]
You say your code is in `opt/lampp/htdocs/twitteroauth` and then you are trying to use the class in `opt\lampp\twitteroauth`.

**Comment by Justinsss** [comment]
Now it says:

Parse error: syntax error, unexpected '/', expecting ',' or ';' in /opt/lampp/htdocs/tweet.php on line 8

Best regards

**Comment by Justinsss** [comment]
Path's btw. changed.

Code now:

<?php

set_time_limit(999999);
if( ob_get_level() > 0 ) ob_end_flush();
ob_implicit_flush(true);

require_once 'autoload.php';
 use Abraham/TwitterOAuth;
 
$connection = new Abraham/TwitterOAuth/src/TwitterOAuth.php("", "","","");

**Comment by abraham** [comment]
I would recommend reading more about[ how to use](https://www.sitepoint.com/php-53-namespaces-basics/) PHP Namespaces and the [installation instructions for TwitterOAuth](https://twitteroauth.com/).

What you probably are trying to do should look more like this.

```
require_once 'autoload.php';
use Abraham/TwitterOAuth/TwitterOAuth;
 
$connection = new TwitterOAuth.php("", "", "", "");
```

**Comment by Justinsss** [comment]
Hey,
I'm very desperate with this now :(
Can I contact you otherwise (private) and give you my VServer datas, so you can make it quick for me?
Or isn't it possible?
I would trust you

Best regards,
Justin :)

**Comment by Justinsss** [comment]
If it's possible (maybe as private message or something like this, or Twitter DM) 
I will give you my server datas and you can make it. Cause you're a expert and can make it easy and quick I think :)

**Comment by Justinsss** [comment]
It would be very nice

**Comment by abraham** [comment]
I'm not going to fix your code for you. I recommend you read the document I linked to earlier and check out the [working example of using TwitterOAuth](https://github.com/abraham/twitteroauth-demo).

**Comment by Justinsss** [comment]
Hey Abraham,
My script should post tweets automatically
It runs now BUT if I close the website it stops..
Should i keep open the website (I remember I work with Xampp on a virtual Server) numericIP/tweets.php that it works?
Or why it ONLY posts 3 tweets if I close the site and works fine if I keep it open??
Cause I can't keep my PC running for days.. or months...
What can I do? Can I keep the site open as a Screen with my server? (Running on Linux (Debian 9) btw) or what can I do? :(
Please help..
Best regards:
Justin

**Comment by abraham** [comment]
That's going to be very specific to your use case. I would recommend looking at some resources like https://coderexample.com/how-to-run-a-php-script-in-background/

**Comment by tanya882** [comment]
hello sir this error came please help me !!
Fatal error: Uncaught Error: Class 'abraham\twitteroauth\TwitterOAuth' not found in C:\xampp\htdocs\tan_login\index.php:13 Stack trace: #0 {main} thrown in C:\xampp\htdocs\tan_login\index.php on line 13
