### ISSUE TITLE
require(): Failed opening required 'twitteroauth/autoload.php'

### ISSUE THREAD

**Issue by macm7** [abraham/twitteroauth#689]
Hey, im getting this error
Fatal error: require(): Failed opening required 'twitteroauth/autoload.php'
The autoload file is in the twitteroauth folder but idk whats happening  : / 

```
namespace xxxxxxxxx
require(__DIR__.'/twitteroauth/autoload.php');
use Abraham\TwitterOAuth\TwitterOAuth;

class xxxxxxxxx {
  public static function xxxxxxxxxxx($a, $b) {
  $config = \Drupal::config('xxxxxxxxxxxx');
  $CONSUMER_KEY = $config->get('xxxxxxxxxxxxxxx');
  $CONSUMER_SECRET = $config->get('xxxxxxxxxxxxxxx');
  $ACCESS_TOKEN = $config->get('xxxxxxxxxxxxxxx');
  $ACCESS_TOKEN_SECRET = $config->get('xxxxxxxxxxxxxxx');
  $connection = new TwitterOAuth($CONSUMER_KEY, $CONSUMER_SECRET, $ACCESS_TOKEN, $ACCESS_TOKEN_SECRET);
  $link_message = $a . ' ' . $b;
  $response = $connection->post('statuses/update', ['status' => $link_message]);
  }
}
```

**Comment by abraham** [comment]
What file is this code in and where is it in relation to the `twitteroauth` directory?

**Comment by macm7** [comment]
@abraham that file is Twitter.php and is on same folder as twitteroauth folder.
Above this folder are 6 Folders more.
SomeFolder
|-- Twitter.php
|-- twitteroath
|    |-- autoload.php
|    |-- src
|    |-- etc...

**Comment by abraham** [comment]
That looks like it should work. Maybe there is some weird server config so within `Twitter.php` it doesn't think it's in `SomeFolder`.

**Comment by macm7** [comment]
Yeah i know, but i fixed it by just using composer to install it i had no choice, composer wasnt working idk why but its working now anyway thanks for ur help have a nice day :100:
