### ISSUE TITLE
Suddenly getting 403 after years of working flawlessly

### ISSUE THREAD

**Issue by inorganik** [abraham/twitteroauth#690]
Hi, I've enjoyed this library for quite a long time; I started using it around 2013. I have a login page where the login link goes to twitter-redirect.php:

```php
<?php

/* Start session and load library. */
session_start();
require_once('twitteroauth.php');

/* Build TwitterOAuth object with client credentials. */
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
 
/* Get temporary credentials. */
$request_token = $connection->getRequestToken(OAUTH_CALLBACK);

/* Save temporary credentials to session. */
$_SESSION['oauth_token'] = $token = $request_token['oauth_token'];
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
 
/* If last connection failed don't display authorization link. */
switch ($connection->http_code) {
  case 200:
    /* Build authorize URL and redirect user to Twitter. */
    $url = $connection->getAuthorizeURL($token);
    header('Location: ' . $url); 
    break;
  default:
    /* Show notification if something went wrong. */
    // header('Location: ../500');
    echo "Error: ".$connection->http_code;
}
```
I haven't touched this code in literally years, and now $connection->http_code is returning a 403. I double checked my CONSUMER_KEY and CONSUMER_SECRET, they are still current with what I see on apps.twitter.com for application settings. App permissions haven't changed from "read and write".

I just tried regenerating my keys in case there was a hiccup on twitter's end, but that didn't fix the problem. Any thing else I could check?

php version: 5.6.30
twitter api version: 1.1

**Comment by abraham** [comment]
Sounds like you are running into this: https://twittercommunity.com/t/action-required-sign-in-with-twitter-users-must-whitelist-callback-urls/105342/3

The value of `OAUTH_CALLBACK` has to be added as a callback URL on apps.twitter.com

**Comment by inorganik** [comment]
Wow, they did a horrible job of communicating that. Thanks!
