### ISSUE TITLE
 Reverse auth credentials are invalid thrown on oauth/access_token call

### ISSUE THREAD

**Issue by krupjanski** [abraham/twitteroauth#691]
Converting the request token via oauth/access_token endpoint causes **HTTP/1.1 401 Authorization Required** with message: **Reverse auth credentials are invalid**

Method call
`$access_token = $connection->oauth("oauth/access_token", ["oauth_verifier" => "5EMzHJRHV3DyHGoCuoiNOzgitN03nnXl"]);`

Generated authorization header:
`
Authorization: OAuth oauth_version="1.0", oauth_nonce="7c300ecc81c9c9248eb5ea91dca9bbce", oauth_timestamp="1531527606", oauth_consumer_key="27oeUj7tbBmWQBLn38lfACP5i", oauth_verifier="5EMzHJRHV3DyHGoCuoiNOzgitN03nnXl", oauth_signature_method="HMAC-SHA1", oauth_signature="DzPfCjZlKDt4o3T9oSQncALohOU%3D"`

**Comment by abraham** [comment]
I'd reverse auth something you expect would work? Last I checked Twitter had removed the documentation.

**Comment by jasonsarino** [comment]
Hello I got this error in:
$access_token = $connection->oauth("oauth/access_token", ["oauth_verifier" => trim($oauth_verifier)]);

Error message:

Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Reverse auth credentials are invalid' in X:\xampp\htdocs\globalsportsfeed\vendor\abraham\twitteroauth\src\TwitterOAuth.php:168 Stack trace: #0 X:\xampp\htdocs\globalsportsfeed\callback.php(16): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/access_to...', Array) #1 {main} thrown in X:\xampp\htdocs\globalsportsfeed\vendor\abraham\twitteroauth\src\TwitterOAuth.php on line 168

PLEASE HELP!!!

**Comment by abraham** [comment]
Are you trying to use reverse auth? Or are you trying to use standard three-legged oauth and mistakenly getting this error?

Maybe something in here well help: https://twittercommunity.com/t/reverse-auth-credentials-are-invalid-3-legged-authorization/110970/8
