### ISSUE TITLE
How to like/favorite?

### ISSUE THREAD

**Issue by Neeath** [abraham/twitteroauth#693]
Retweet:
$connection->post("statuses/retweet/$id");

How is it Fav/Like?

Thanks!

**Comment by abraham** [comment]
[POST favorites/create](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-favorites-create.html) is basically the same format.

$connection->post("statuses/retweet/", ["id" => $id]);

**Comment by Neeath** [comment]
It worked, thanks!!
