### ISSUE TITLE
"null" on DELETE request

### ISSUE THREAD

**Issue by EnderRaider** [abraham/twitteroauth#695]
Hello,
I'm getting a null return with this request:
```
$connection = new TwitterOAuth($consumerkey, $consumersecret, $accesstoken, $accesstokensecret);

$statuses = $connection->DELETE("direct_messages/welcome_messages/rules/destroy", ["id" => "XXXXXXXXXXXXXXXX"]);

echo json_encode($statuses);
```

What am I doing wrong?

**Comment by abraham** [comment]
You should be using `delete` not `DELETE`. The PHP API is lowercase.

According to the docs that request returns HTTP 204 No Content so your `$statuses` variable wouldn't have a value.

You should be checking that `$connection->getLastHttpCode()` is 204.
