### ISSUE TITLE
You must supply a readable file

### ISSUE THREAD

**Issue by saqlain-syed** [abraham/twitteroauth#697]
I am trying to upload media files using API . but when I try to check it says 

you must supply a readable file. I have added the source of PNG file which is on live server.

**ERROR :** 

An uncaught Exception was encountered Type: InvalidArgumentException

Message: You must supply a readable file

Filename: D:\xampp\htdocs\socialmediascheduling\application\controllers\twitteroauth-master\src\TwitterOAuth.php

Line Number: 297

**MY CODE** 

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, OAUTH_TOKEN, OAUTH_SECRET);
$content = $connection->get('account/verify_credentials');

$tweetWM = $connection->upload('media/upload', ['media' => 'https://i0.wp.com/androidbash.com/wp-content/uploads/2016/12/Screenshot-109.png']);

print_r($tweetWM);
    die();

$tweet = $connection->post('statuses/update', ['media_ids' => $tweetWM->media_id]);

**Comment by mrbellek** [comment]
The upload() function requires a local file. An URL will not work, you must download it first.

**Comment by abraham** [comment]
In v2 downloading hosted files automatically might be supported with #681. All files will have to be downloaded to the local server somehow though.
