### ISSUE TITLE
Twitter - How to check if user is already authentiacetd your app 

### ISSUE THREAD

**Issue by saqlain-syed** [abraham/twitteroauth#698]
Dear @abraham  I have used your API to work with twitter accounts.. Users come will to my webiste and will authenticate my app in order to publish posts to their profiles. Everything is just working fine..

I need to ask that, API is asking users to authenticate each time they submit request .. Is there any way that script should auto check that user is already authenticated and just redirect him/her back to the application.

waiting for your kind response :)

**Comment by abraham** [comment]
It sounds like you want to use [oauth/authenticate](https://developer.twitter.com/en/docs/basics/authentication/api-reference/authenticate.html) instead of oauth/authorize.
