### ISSUE TITLE
POST 'direct_messages/events/new' returning HTTP 415

### ISSUE THREAD

**Issue by ericwoolard** [abraham/twitteroauth#699]
Attempting to reply to DM's but am running into issues. Using version 0.9.2.

    $connection = new TwitterOAuth(env('TWITTER_CONS_KEY'), 
				       env('TWITTER_CONS_SECRET'), 
				       env('TWITTER_ACCESS_TOKEN'), 
				       env('TWITTER_ACCESS_SECRET'));
    $params = [
        'event' => [
            'type' => "message_create",
            'message_create' => [
                'target' => [
                    'recipient_id' => $userId
                ],
                'message_data' => [
                    'text' => $msg
                ]
            ]
        ]
    ];
    $sendResult = $connection->post('direct_messages/events/new', array(json_encode($params)));

According to Twitter, HTTP 415's are given if the callback URL is not approved for this client application, but I don't have one saved for my app at all. 

Without passing `$params` to `json_encode()`, I get an error in Util.php line 105: Array to string conversion.

Am I being dumb and missing something simple in my app options or is there actually something going on?

**Comment by abraham** [comment]
`'direct_messages/events/new'` requires a different payload format than all the other API endpoints so you have to pass a third parameter to `post`

    $sendResult = $connection->post('direct_messages/events/new', $params, true);
