### ISSUE TITLE
OAuth broken after upgrade from 0.7.4 to 0.9.2

### ISSUE THREAD

**Issue by peterver** [abraham/twitteroauth#700]
The `oauth` function was working properly in v0.7.4, but after upgrading to v0.9.2 I receive the following error everytime I try to make a request.

The output is the following

```
{"errors":[{"code":215,"message":"Bad Authentication data."}]} in /app/vendor/abraham/twitteroauth/src/TwitterOauth.php:168
```

The request is using the following code on our side, where $this->client is an instance of `Abraham\TwitterOauth\TwitterOauth` : 

```
$this->client->oauth("oauth/request_token, [
    'oauth_callback' => "..."
]);
```

**Comment by peterver** [comment]
I also checked, callback urls are whitelisted, so there's nothing wrong in regards to that

**Comment by peterver** [comment]
Sorry my bad, I forgot I had config caching enabled >.< ! ( using laravel ). On a sidenote, love the library, continue with the great work :D

**Comment by abraham** [comment]
Glad to hear you got it working!
