### ISSUE TITLE
CKeditor content want to post but it post html along with it.

### ISSUE THREAD

**Issue by DhirajBelure** [abraham/twitteroauth#701]
Hello,

I am using ckeditor for twitter posting. I have content "text + video"  want to post in twitter. but how to post without html tag with youtube video using in php rest api. My below code to post.
`$twitter = new Twitter($consumerKey, $consumerSecret, $twitter_list['toauth_token'], $twitter_list['toauth_token_secret']);
$twitterbody = "ckeditor content 'text + youtube video'";
$tweet = $twitter->send($twitterbody); `

**Comment by abraham** [comment]
TwitterOAuth is going to post whatever you tell it to post. You'll have to strip out the HTML before you post it. Also it looks like you're actually using a different library.
