### ISSUE TITLE
Register Webhook Error

### ISSUE THREAD

**Issue by BhupendraKumar** [abraham/twitteroauth#702]
Hi,

We are using TwitterOAuth to register webhook. But we are getting an error. Could you please help us to resolve this?

Error: "Webhook URL does not meet the requirements. Please consult: https://dev.twitter.com/webhooks/securing"

We do have 'access_token' in $_SESSION and we have below codes to register webhook.

![image](https://user-images.githubusercontent.com/497683/43639034-7b85384e-9738-11e8-8a88-cf83437a4c5f.png)

And we are getting below error.

![image](https://user-images.githubusercontent.com/497683/43639065-9648f968-9738-11e8-8b49-7c4f999a4e22.png)

Could you please let us know if anything wrong with code?

Your prompt response will be highly appreciated.

Thanks..

**Comment by abraham** [comment]
This doesn't look like an issue with TwitterOAuth but an issue with the page that is receiving the webhook. Make sure it meets all of Twitter's requirements.
