### ISSUE TITLE
Could not authenticate you : only with access token

### ISSUE THREAD

**Issue by KrankerApfel** [abraham/twitteroauth#704]
Hello !

I try to post a simple tweet, I can have access token without any problem (in another page and I stocked it in $_SESSION, when I print it, it's correct) but when I try to make a new TwitterOAuth witd them I got this error : **stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => 32 [message] => Could not authenticate you. ) ) )**

I don't understand why because it's work with request token, it's just when I use access token.  My code below : 

**_NOTE : I have already whitelist my callback URL
NOTE2 : I have tested my app with an old version of twitteroauth (the one which use getAccessToken() and getRequestToken()) and it's work, so it's not a problem with my apps parameters (I think)_**

`<?php
require_once '../vendor/abraham/twitteroauth/autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;

session_start();

define('CONSUMER_KEY', 'xxxxxxxxxxxxxxx');
define('CONSUMER_SECRET', 'xxxxxxxxxxxxxxxxxxxxxx');
define('OAUTH_CALLBACK', ''); // it's blank

$connection = new TwitterOAuth('CONSUMER_KEY', 'CONSUMER_SECRET', $_SESSION['access_oauth_token'], $_SESSION['access_oauth_token_secret']); // doesn't work

$usr = $connection->get("account/verify_credentials");

$tweetName = "@Name";
$siteURL = "https://My-Website.com/";

$tweet = [
    'status' => $_POST['textarea']." via ".$tweetName." ".$siteURL ,
];

$result = $connection->post("statuses/update", $tweet);
print_r($result);
?>
`

**Comment by abraham** [comment]
You are using the literal strings `'CONSUMER_KEY'` and `'CONSUMER_SECRET'` when you should be using the defined constants `CONSUMER_KEY` and `CONSUMER_SECRET`. Remove the wrapping `'`.

**Comment by KrankerApfel** [comment]
It's work, thank you !!
