### ISSUE TITLE
How to create token

### ISSUE THREAD

**Issue by VirendraArekar** [abraham/twitteroauth#708]
How to create user_token without redirect for login and also how to post on another user wall using php. Because i tried more than 100 time but i failure please anyone guide me.

**Comment by abraham** [comment]
There are two ways to get a user's access_token. For your own account you can [create an app](https://developer.twitter.com/en/apps) an generate a token through the app configuration. For other accounts you have to use [Sign in with Twitter](https://developer.twitter.com/en/docs/twitter-for-websites/log-in-with-twitter/login-in-with-twitter.html).

https://twitteroauth.com/redirect.php is a live guide that tells you what code you need to call and when to get someone's access_token.
