### ISSUE TITLE
Add link to status attachment_url usage

### ISSUE THREAD

**Issue by knnguler** [abraham/twitteroauth#709]
Hi 

I want to add a link but I can not add it
**attachment_url parameter is invalid.**

`
                    $parameters     = [
                        'status'    => mb_substr(rawurldecode($caption), 0, $length) . $url,
                        'attachment_url' => $url
                    ];
                    $return         = $connection->post('statuses/update', $parameters); `

I do not want to add link status to preview, how can I use it

thanks in advance

**Comment by abraham** [comment]
What value are you using for `attachment_url`?
