### ISSUE TITLE
Capture tweets from an account

### ISSUE THREAD

**Issue by Neeath** [abraham/twitteroauth#712]
Is it possible with this library to do some of these two things?

Send an update whenever an account tweets something;
Get link from the last tweet of an account.

Preferably the first, the second would be an alternative.

**Comment by abraham** [comment]
There are two ways to get tweets from an account. In realtime using the [streaming API](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter.html) or fetching a list of users[ recent tweets](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline.html). The streaming API is not currently supported by this library, using the timeline APIs is what this library was made for. With the timeline API you have to setup a cron job or something similar to periodically check for new tweets.

Using the timeline API you will get links included in tweets in the [entities object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object.html#urls).

**Comment by Neeath** [comment]
// options
	    $number = 5;
	    $exclude_replies = 'false';
	    $screenname = '&screen_name=ronynth';

	    // connect
		$connection = getConnectionWithAccessToken($consumer_key, $consumer_secret, $accessToken, $secretToken);
	    $tweets = $connection->get('https://api.twitter.com/1.1/statuses/user_timeline.json?count='.$number.$screenname.'&exclude_replies='.$exclude_replies);

nothing happens, is something wrong?

**Comment by Neeath** [comment]
I was able to rescue json, but I am not able to rescue the ids inside a foreach, could you help me? Thanks!
