### ISSUE TITLE
Add like or hastag from twitter to my website ?

### ISSUE THREAD

**Issue by ZerooCool** [abraham/twitteroauth#713]
I search how i can add the content from a hashtag from twitter to my website.

I search how i can add the content from like from my accound twitter to my website.

twitter.com/settings/widgets work not good for that.

**Comment by abraham** [comment]
Your options are basically to use the [Twitter for websites](https://developer.twitter.com/en/docs/twitter-for-websites/overview.html) plugins or use community projects like this project and the [`<twitter-status>`](https://github.com/abraham/twitter-status) web component.

**Comment by ZerooCool** [comment]
Ok, thank you.
