### ISSUE TITLE
Direct message new API returning NULL

### ISSUE THREAD

**Issue by hlashish** [abraham/twitteroauth#714]
Hi Sir

I am using the following code and library functions to use twitter API's 

```
require "vendor/autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;

$globalProjectName 				= "TweekSocial";
$consumerKey 					= 'vT********************RQy';
$consumerSecret 				= 'hdJqg*****************o************************MF0';
$accessToken 					= "8**********************************************a6I";
$accessSecret 					= "zYJ********************************************dRH";
$baseUrl 						=  "http://******************/";
$redirectURL 					= 'http://******************/';


$connection = new TwitterOAuth($consumerKey, $consumerSecret, $accessToken, $accessSecret);
$content = $connection->get("account/verify_credentials");
$connection->setTimeouts(10, 15);
echo "<pre>"; print_r($content);echo "</pre>"; 
$userId = "1027************96 ";

 $userDtaRes = $connection->get('users/lookup ', array('screen_name' => "Easemymarketing")); 
 print_r("<br/> user lookup API <br/>");
var_dump("<br/>".$connection->getLastHttpCode());
var_dump("<br/>".$connection->getLastApiPath());
var_dump("<br/>".$userDtaRes);



$data = [
    'event' => [
        'type' => 'message_create',
        'message_create' => [
            'target' => [
                'recipient_id' => $userId
            ],
            'message_data' => [
                'text' => "hi new dm messg to ashsi "
            ]
        ]
    ]
];

$result = $connection->post('direct_messages/events/new ', $data, true); // Note the true
print_r("<br/> USER send direct mesage api <br/>");
var_dump("<br/>".$connection->getLastHttpCode());

var_dump("<br/>".$result);
```

Always it returns NULL for each library, please guide me how to run the to fetch various API result and send the direct message event new.

**Comment by hlashish** [comment]
I am attaching the  #screen-shot of app permissions and browser result for further refrence -::

![app-permisions](https://user-images.githubusercontent.com/19687204/45598111-04e3d900-b9f4-11e8-9584-abe09cd6513a.png)
![browser-result](https://user-images.githubusercontent.com/19687204/45598113-0dd4aa80-b9f4-11e8-921e-83b4a7cf013d.png)

**Comment by abraham** [comment]
Try `var_dump($userDtaRes);` and `var_dump("<br/>".$result);` without the `"<br/>".` because is going to try and concatenate the complex object with the string which is going to be a bad time.

**Comment by hlashish** [comment]
> Try `var_dump($userDtaRes);` and `var_dump("<br/>".$result);` without the `"<br/>".` because is going to try and concatenate the complex object with the string which is going to be a bad time.

Hi
I tried  var_dump($userDtbaRes); but it is still returning null, can you please help me out also what about the deirect new messsage create event api it is aso not working even after app permiisions

**Comment by abraham** [comment]
I don't see any obvious reasons why this wouldn't work. Two things that to check is that you are using the latest version of TwitterOAuth and that the person you are sending the DM to has authorized the sender to contact them.

**Comment by ozgurky** [comment]
There is a space end of new message endpoint, checking actual code for this space can be helpful maybe. Also this space exists in the JSON data part of https://twitteroauth.com/ main page doc.

> $result = $connection->post('direct_messages/events/new ', $data, true); // Note the true

**Comment by abraham** [comment]
Ya, the extra space at the end of the path will likely cause issues.

**Comment by abraham** [comment]
I just copied the code you have and there are multiple places with with trailing spaces. After fixing them sending direct messages worked fine.

`$userDtaRes = $connection->get('users/lookup ', array('screen_name' => "Easemymarketing"));`

`$userId = "1027************96 ";`

`$result = $connection->post('direct_messages/events/new ', $data, true);`

**Comment by CesarNatic** [comment]
> 
> 
> I have removed the extra space still the same issue exists, do anyone is still facing the null return value issue (-1

Im facing the same issue. 

`require_once(APP.'Vendor/twitteroauth/twitteroauth/twitteroauth.php');
      $tweet = new TwitterOAuth('b********************************t',
        'M***********************************************g',
        $tokenTwitter['Socialtoken']['access_token'],
        $tokenTwitter['Socialtoken']['access_token_secret']);     
      $mensaje = '123';
      $userDtaRes = $tweet->get('users/lookup', array('screen_name' => $nombreUsuario)); 
      $idusr = $userDtaRes[0]->id_str;     
      $text = 'DM ' . $nombreUsuario . ' ' . $mensaje;
 
      $data = [
          'event' => [
              'type' => 'message_create',
              'message_create' => [
                  'target' => [
                      'recipient_id' => $idusr
                  ],
                  'message_data' => [
                      'text' => $text
                  ]
              ]
          ]
      ];

     // var_dump($data);die;
    
      $tw = $tweet->post('direct_messages/events/new', $data, true);  
      if(isset($tw->sender)){
        CakeLog::write('twitterDM', "Twit enviado a " . $nombreUsuario, 'twitterDM');
      }
      if(isset($tw->errors)){
         CakeLog::write('twitterDM', "Error al enviar a " . $nombreUsuario . " por CODE: {$tw->errors[0]->code} mensaje: {$tw->errors[0]->message}", 'twitterDM');
      }
      
      debug($tw);die;`

$data is correct, but $tw returns null, if i put the old endpoint i get a response from the twitter api but if i put the new endpoint i get a null and this error:

Array to string conversion [APP/Vendor/twitteroauth/twitteroauth/twitteroauth.php, line 223]

**Comment by hlashish** [comment]
HI @abraham 

Thanks for all the help and time you invested for my code debugging. It started working now.

Again thanks a lot for all y

**Comment by CesarNatic** [comment]
> 
> 
> HI @abraham
> 
> Thanks for all the help and time you invested for my code debugging. It started working now.
> 
> Again thanks a lot for all your help and cooperation :)

What you did to solve it?

**Comment by abraham** [comment]
@CesarNatic this API is only supported in version 0.9 and later.

**Comment by CesarNatic** [comment]
Thanks so much @abraham, updated to last version and worked like butter. :) Nice library btw.

**Comment by awadhajj** [comment]
Am using 0.9.2, and still receiving NULL response!
`
$tw_con = $this->twConnect();
        //$twt = $this->getTweet('AppBundle:Tweet', $id);
        $statues = $tw_con->post("statuses/update", array("status" => '.......'));
        echo $tw_con->getLastHttpCode();
        print_r($statues);
        
        $data = [
                'event' => [
                    'type' => 'message_create',
                    'message_create' => [
                        'target' => [
                            'recipient_id' => '872***********304' //$y->id
                        ],
                        'message_data' => [
                            'text' => 'Hi am just testing some service'
                        ]
                    ]
                ]
            ];
        
        
            $result = $tw_con->post('direct_messages/events/new ', $data, true); 
            echo $tw_con->getLastHttpCode();
            var_dump($result);
`
the "post status" in the second line works well

am sending to a user that following me, and i always contact him through Direct Meassage :(

**Comment by abraham** [comment]
@awadhajj Your API path string has a space in it `'direct_messages/events/new '`

**Comment by ijazraja** [comment]
How to know which API level we are using?

**Comment by ijazraja** [comment]
I am having an issue it returns with the parse error

$data = [
            'event' => [
                'type' => 'message_create',
                'message_create' => [
                    'target' => [
                        'recipient_id' => $account_id
                    ],
                    'message_data' => [
                        'text' => $msg
                    ]
                ]
            ]
        ];

        //echo '<pre>'; print_r($data);die;

       $result =  $connection->post('direct_messages/events/new', $data, true);

        var_dump($result);

//$result is null

**Comment by ijazraja** [comment]
I am having an issue it returns with the parse error

    $data = [
'event' => [
'type' => 'message_create',
'message_create' => [
'target' => [
'recipient_id' => $account_id
],
'message_data' => [
'text' => $msg
]
]
]
];

    //echo '<pre>'; print_r($data);die;

   $result =  $connection->post('direct_messages/events/new', $data, true);

    var_dump($result);
//$result is `null`

**Comment by ijazraja** [comment]
I am having same Issue it return null in result and display parse error on ajax response

`
$data = [
'event' => [
'type' => 'message_create',
'message_create' => [
'target' => [
'recipient_id' => $account_id
],
'message_data' => [
'text' => $msg
]
]
]
];

    //echo '<pre>'; print_r($data);die;

   $result =  $connection->post('direct_messages/events/new', $data, true);

    var_dump($result);
//$result is `null`
`

**Comment by ijazraja** [comment]
`$data = [
                            "event" => [
                                "type" => "message_create",
                                "message_create" => [
                                    "target" => [
                                        "recipient_id" => trim($account_id)
                                    ],
                        "message_data" => [
                            "text" => $msg
                        ]
                    ]
                ]
            ];


       $result =  $connection->post('direct_messages/events/new',array($data), true);`

**Comment by ijazraja** [comment]
It comes with a 415 error ('Media format not supported'), although I only need to send text, not with the Image, Any solution?

I had checked the app permissions these are alright
