### ISSUE TITLE
problem with upload image 

### ISSUE THREAD

**Issue by shabayekdes** [abraham/twitteroauth#715]
when upload image saying errors "You must supply a readable file"
my code 
```
        $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $account_tw->account_oauth_token, $account_tw->account_oauth_secret);
                $media1 = $connection->upload('media/upload', ['media' => 'https://d.top4top.net/p_9928rqkf1.jpg', 'media_type' => 'image/jpg'], true);
                dd($media1);
                $parameters = [
                    'status' => 'Meow Meow Meow',
                    'media_ids' => implode(',', [$media1->media_id]),
                ];

                $result = $connection->post('statuses/update', $parameters);

```

**Comment by abraham** [comment]
You must use the path a file local the the server. Remote hosted files are not supported.

**Comment by chinanderm** [comment]
Ever since `uploadMediaNotChunked` had the guard of `if (! is_readable($parameters['media']) ||
            ($file = file_get_contents($parameters['media'])) === false) {
            throw new \InvalidArgumentException('You must supply a readable file');
        }` added, supplying a URL for the media does not work. In a previous version where that guard wasn't present, simply supplying a URL worked.

**Comment by abraham** [comment]
Yes, if you have a remote file, you'll have to download it to the local disk first. Previously it was too easy for developers to pass a URL and not realize their server was first downloading the file and then uploading it to Twitter. You now have to intentionally download the file first.
