### ISSUE TITLE
Can we examine the authorize the user through twitter api by using localhost??

### ISSUE THREAD

**Issue by danish-manzoor** [abraham/twitteroauth#716]
In the app callback url is defined
Fatal error: Uncaught Abraham\TwitterOAuth\TwitterOAuthException: {"errors":[{"code":415,"message":"Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings"}]} in C:\xampp\htdocs\twitterapi\src\TwitterOAuth.php:168 Stack trace: #0 C:\xampp\htdocs\twitterapi\index.php(25): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array) #1 {main} thrown in C:\xampp\htdocs\twitterapi\src\TwitterOAuth.php on line 168

**Comment by abraham** [comment]
I've got some test apps that use `localhost` as the callback URL. Make sure the registered callback URL on https://developer.twitter.com/apps matches exactly the URL you are using locally without an params or fragments.

For example if you are using `http://localhost:8000/callback.php?param=thing#fragment`, you would register `http://localhost:8000/callback.php`.

**Comment by danish-manzoor** [comment]
Sir this problem is solved 
Now i have to face a new problem that is 
Notice: Undefined index: oauth_token in C:\xampp\htdocs\twitterapi\callback.php on line 5
Here is my all code
**index.php**
<?php
session_start();
require_once 'autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;
define('CONSUMER_KEY', 'Vn3Q6iF0N5CTelifVP7VP6cgq'); // add your app consumer key between single quotes
define('CONSUMER_SECRET', '5rt9AWrmJeV3UtGfU1cSS8G1tPg4GGNSYY6kSHsTMgvcMsTQDW'); // add your app consumer secret key between single quotes
define('OAUTH_CALLBACK', 'https://127.0.0.1/twitterapi/callback.php'); // your app callback URL
if (!isset($_SESSION['access_token'])) {
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
	$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
	$_SESSION['oauth_token'] = $request_token['oauth_token'];
	$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
	$url = $connection->url('oauth/authenticate', array('oauth_token' => $request_token['oauth_token']));
	echo $url;
	echo '<a href="'.$url.'">Login to Twitter</a>';
} else {
	$access_token = $_SESSION['access_token'];
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token['oauth_token'], $access_token['oauth_token_secret']);
	$user = $connection->get("account/verify_credentials");
	echo $user->screen_name;
}



Here is my **callback.php**
<?php
session_start();
require 'autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;
if(isset($_REQUEST['oauth_verifier'],$_REQUEST['oauth_token']) && $_REQUEST['oauth_token']=== $_SESSION['oauth_token']){
	$request_token = [];
	$request_token['oauth_token'] = $_SESSION['oauth_token'];
	$request_token['oauth_token_secret'] = $_SESSION['oauth_token_secret'];
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $request_token['oauth_token'], $request_token['oauth_token_secret']);
	$access_token = $connection->oauth("oauth/access_token", array("oauth_verifier" => $_REQUEST['oauth_verifier']));
	$_SESSION['access_token'] = $access_token;
	// redirect user back to index page
	header('Location: ./');
}


The error is occur in callback.php.
