### ISSUE TITLE
Cannot see [unwound] of entities->urls

### ISSUE THREAD

**Issue by JonasGaldikas** [abraham/twitteroauth#718]
@abraham Cannot access to [unwound] from entities->urls. ( https://developer.twitter.com - 'metadata such as the fully unwound URL and the webpage’s title and description' - described on twitter).

<pre>
`object(stdClass)#7 (25) {
  ["created_at"]=>
  string(30) "Mon Sep 24 13:42:10 +0000 2018"
  ["id"]=>
  int(1044220450367320064)
  ["id_str"]=>
  string(19) "1044220450367320064"
  ["full_text"]=>
  string(69) "Something interesting to start the week with!
https://t.co/onD1dqMJcf"
  ["truncated"]=>
  bool(false)
  ["display_text_range"]=>
  array(2) {
    [0]=>
    int(0)
    [1]=>
    int(69)
  }
  ["entities"]=>
  object(stdClass)#16 (4) {
    ["hashtags"]=>
    array(0) {
    }
    ["symbols"]=>
    array(0) {
    }
    ["user_mentions"]=>
    array(0) {
    }
    ["urls"]=>
    array(1) {
      [0]=>
      object(stdClass)#17 (4) {
        ["url"]=>
        string(23) "https://t.co/onD1dqMJcf"
        ["expanded_url"]=>
        string(73) "https://www.invisionapp.com/blog/7-ted-talks-every-designer-should-watch/"
        ["display_url"]=>
        string(33) "invisionapp.com/blog/7-ted-tal…"
        ["indices"]=>
        array(2) {
          [0]=>
          int(46)
          [1]=>
          int(69)
        }
      }
    }
  }
  ["source"]=>
  string(66) "Twitter Web Client"
  ["in_reply_to_status_id"]=>
  NULL
  ["in_reply_to_status_id_str"]=>
  NULL
  ["in_reply_to_user_id"]=>
  NULL
  ["in_reply_to_user_id_str"]=>
  NULL
  ["in_reply_to_screen_name"]=>
  NULL
  ["user"]=>
  object(stdClass)#18 (41) {
    ["id"]=>
    int(923505096113184769)
    ["id_str"]=>
    string(18) "923505096113184769"
    ["name"]=>
    string(13) "AAAAA AAAAAA"
    ["screen_name"]=>
    string(14) "AAAAAA"
    ["location"]=>
    string(7) "AAAAAA"
    ["description"]=>
    string(107) "AAAAAAAAAAAAAAAA"
    ["url"]=>
    string(23) "https://t.co/AAAAAAAAAAA"
    ["entities"]=>
    object(stdClass)#21 (2) {
      ["url"]=>
      object(stdClass)#20 (1) {
        ["urls"]=>
        array(1) {
          [0]=>
          object(stdClass)#19 (4) {
            ["url"]=>
            string(23) "https://t.co/AAAAAA"
            ["expanded_url"]=>
            string(26) "http://www.AAAAAAAA.co"
            ["display_url"]=>
            string(15) "AAAAAAAA.co"
            ["indices"]=>
            array(2) {
              [0]=>
              int(0)
              [1]=>
              int(23)
            }
          }
        }
      }
      ["description"]=>
      object(stdClass)#22 (1) {
        ["urls"]=>
        array(0) {
        }
      }
    }
    ["protected"]=>
    bool(false)
    ["followers_count"]=>
    int(407)
    ["friends_count"]=>
    int(596)
    ["listed_count"]=>
    int(2)
    ["created_at"]=>
    string(30) "Thu Oct 26 11:02:27 +0000 2017"
    ["favourites_count"]=>
    int(983)
    ["utc_offset"]=>
    NULL
    ["time_zone"]=>
    NULL
    ["geo_enabled"]=>
    bool(false)
    ["verified"]=>
    bool(false)
    ["statuses_count"]=>
    int(29)
    ["lang"]=>
    string(2) "en"
    ["contributors_enabled"]=>
    bool(false)
    ["is_translator"]=>
    bool(false)
    ["is_translation_enabled"]=>
    bool(false)
    ["profile_background_color"]=>
    string(6) "000000"
    ["profile_background_image_url"]=>
    string(48) "http://abs.twimg.com/images/themes/theme1/bg.png"
    ["profile_background_image_url_https"]=>
    string(49) "https://abs.twimg.com/images/themes/theme1/bg.png"
    ["profile_background_tile"]=>
    bool(false)
    ["profile_image_url"]=>
    string(74) "http://pbs.twimg.com/profile_images/999999999999999999999/AAAAAA_normal.jpg"
    ["profile_image_url_https"]=>
    string(75) "https://pbs.twimg.com/profile_images/999999999999999999999/AAAAAAA_normal.jpg"
    ["profile_link_color"]=>
    string(6) "7953F8"
    ["profile_sidebar_border_color"]=>
    string(6) "000000"
    ["profile_sidebar_fill_color"]=>
    string(6) "000000"
    ["profile_text_color"]=>
    string(6) "000000"
    ["profile_use_background_image"]=>
    bool(false)
    ["has_extended_profile"]=>
    bool(false)
    ["default_profile"]=>
    bool(false)
    ["default_profile_image"]=>
    bool(false)
    ["following"]=>
    bool(false)
    ["follow_request_sent"]=>
    bool(false)
    ["notifications"]=>
    bool(false)
    ["translator_type"]=>
    string(4) "none"
  }
  ["geo"]=>
  NULL
  ["coordinates"]=>
  NULL
  ["place"]=>
  NULL
  ["contributors"]=>
  NULL
  ["is_quote_status"]=>
  bool(false)
  ["retweet_count"]=>
  int(1)
  ["favorite_count"]=>
  int(5)
  ["favorited"]=>
  bool(false)
  ["retweeted"]=>
  bool(false)
  ["possibly_sensitive"]=>
  bool(false)
  ["lang"]=>
  string(2) "en"
}`
</pre>

So the problem is:
When i share link on my twitter -

![image](https://user-images.githubusercontent.com/36409833/46156461-37a69080-c282-11e8-98c7-28dec54da4fd.png)

I see beautifull box.

But when i try to get same thing on website, cannot see any properties to achieve same box. Maybe someone have similar experience.

**Comment by abraham** [comment]
`unwound` is only available to [premium Twitter API](https://twittercommunity.com/t/embedded-tweet-shows-video-but-nothing-in-json-references-it/100611/3) users.
