### ISSUE TITLE
How to handle error if connection fails?

### ISSUE THREAD

**Issue by praveend06** [abraham/twitteroauth#720]
How to handle error if we profide wrong credentials. I am getting fatal error. I want to send false if oAuth faills.

$connection = new TwitterOAuth($RS["consumerkey"], $RS["consumersecret"]);
         if ($connection
        ) {
            return true;
        }
        return false;

**Comment by abraham** [comment]
Check out error handling on https://twitteroauth.com/. You have to check for errors per request.

```php
$statues = $connection->post("statuses/update", ["status" => "hello world"]);
if ($connection->getLastHttpCode() == 200) {
    // Tweet posted succesfully
} else {
    // Handle error case
}
```
