### ISSUE TITLE
Returning 'state pending' during Uploading a video on twitter.

### ISSUE THREAD

**Issue by KrishnaVishwakarma1595** [abraham/twitteroauth#723]
Hey,

Could anyone help me with this issue? I am uploading a video on Twitter but every time after the request sent it returns the data which is showing video state pending and don't upload a video on my twitter profile. The video I'm using if of length 20 seconds only.

Here is the code I wrote: 

$path -: is the path of the media file

$connection = new TwitterOAuth(TW_CONSUMER_KEY, TW_CONSUMER_SECRET, $accessToken,$accessSecret);
$connection->setTimeouts(10, 2000);
$media1 = $connection->upload('media/upload', ['media' =>$path,'media_type' => 'video/mp4','media_category' => 'tweet_video'],true);
		$parameters = [
			'status' => 'Video Test',
			'media_ids' => $media1->media_id_string
		];
					
$connection->post('statuses/update', $parameters);

Here is the data I got after the request sent-:
{
     "media_id":1049213484272144384,
     "media_id_string":"1049213484272144384",
     "media_key":"13_1049213484272144384",
     "size":1802240,
     "expires_after_secs":86400,
     "processing_info":{
             "state":"pending",
             "check_after_secs":1
       }
}

Please do help If I'm doing anything wrong.
Thanks in advance!🙏

**Comment by abraham** [comment]
You have to check `$connection->mediaStatus($media1->media_id_string)` until Twitter has finished processing the video.

**Comment by CpHeat** [comment]
> You have to check `$connection->mediaStatus($media1->media_id_string)` until Twitter has finished processing the video.

Where should I have looked to find this info ? I had a hard time finding this and was stuck, but didn't want to come here asking a simple question that I should have been able to figure out by myself, I think I don't read docs the right way because I always struggle to find this kind of info (I don't have an academic past I learned alone so I guess I miss some good practices)
