### ISSUE TITLE
Not able to fetch records with 'result_type' => 'popular'

### ISSUE THREAD

**Issue by rana07i** [abraham/twitteroauth#727]
my sample code is:
```
$parameters = array(
		'q' => $search_keyword,
	       'lang' => 'en',
	       'count' => '75',
	        'result_type' => 'popular',
	`    
	);`
```
need help, and how we can get error message.

**Comment by abraham** [comment]
What do you mean by "not able to fetch"? What are you trying to do, what do you expect to happen, and what is actually happening? Please include specific API endpoints you are calling.
