### ISSUE TITLE
PHP Fatal error: Uncaught path/to/library Reverse auth credentials are invalid 

### ISSUE THREAD

**Issue by UVLabs** [abraham/twitteroauth#729]
This error comes up in php error_log after entering the consumer key and secret:

`PHP Fatal error: Uncaught Abraham\TwitterOAuth\TwitterOAuthException: Reverse auth credentials are invalid `

Any idea what might be causing this issue? @abraham

**Comment by drastik** [comment]
Same issue lately

**Comment by abraham** [comment]
I've seen this error pop up a few times on twittercommunity.com forum but I've yet to see a concrete solution.

What Twitter API requests does this error happen for?

Does it always happen for those API requests? If not are there any patterns you see of when they do and don't have the error?

**Comment by drastik** [comment]
We're getting it on the first leg of token authorization. 

I can give you specifics tomorrow, but right after the Twitter username/password screen, the user submits credentials, then when redirecting to callback URL it throws this error.

**Comment by brianzzzasd** [comment]
I am using 3-legged authentication. When I try to use `oauth/access_token`, this error happens also.

**Comment by abraham** [comment]
I don't know what causes this error. According to [this comment](https://twittercommunity.com/t/reverse-auth-credentials-are-invalid/113799/3?u=abraham) it might be caused by using incorrect tokens or a typo in your code. 

Please provide exact code and APIs you are using that results in this error. Does the error always happen? If it's only sometimes are there any patterns to when it does or doesn't happen? Remember to exclude any consumer secrets and access token secrets from your replies.

**Comment by extsalt** [comment]
` /**
     * Obtain request token and redirect user to authenticate
     *
     * @throws \Abraham\TwitterOAuth\TwitterOAuthException
     */
    public function obtainRequestToken()
    {
        $oauth = new TwitterOAuth($this->consumerKey, $this->consumerSecret);

        $response = $oauth->oauth('oauth/request_token', ['oauth_callback' => $this->callback]);

        if (!array_key_exists('oauth_token', $response)) {
            return abort(404);
        }

        return redirect()->to($oauth->url("oauth/authorize", ["oauth_token" => $response['oauth_token']]));
    }

    /**
     * Manage callback
     *
     * @param Request $request
     * @throws \Abraham\TwitterOAuth\TwitterOAuthException
     */
    public function manageCallback(Request $request)
    {
        if (!$request->has('oauth_verifier')) {
            abort(404);
        }

        $oauth = new TwitterOAuth($this->consumerKey, $this->consumerSecret);

        $accessToken = $oauth->oauth('oauth/access_token', $request->only('oauth_verifier'));

        var_dump($accessToken);
`
