### ISSUE TITLE
Plugins in WordPress using this library .

### ISSUE THREAD

**Issue by mondyfy** [abraham/twitteroauth#732]
Is there any plugins in wordpress,basically made by using this library ? If yes please feel free to share.And can I make the plugin just like featuring the functionality of publicize of jetpack using this library ?

**Comment by abraham** [comment]
I know there are some WordPress plugins using this library but I don't know specifically which ones. I am unsure what outcome you desire from this issue resolution.

**Comment by abraham** [comment]
Maybe the resolution of this issue should be adding a section to the documentation that lists developers tools leveraging this library.

**Comment by developer-sandip** [comment]
Sure @abraham !

**Comment by isaajibola** [comment]
Hello hubbers,
I am new here and also have less knowledge about programming. I having an issue deleting my twitter auto-direct message. can anyone help me on how I can delete/remove the auto Direct Message?
Thanks in advance.

**Comment by abraham** [comment]
@isaajibola please open a new issue.

**Comment by isaajibola** [comment]
issue opened

**Comment by abraham** [comment]
It's probably better that WordPress users search for the plugin that bests supports their Twitter needs regardless of the underlying implementation. https://wordpress.org/plugins/
