### ISSUE TITLE
Does you library support permanent token for logged user?

### ISSUE THREAD

**Issue by Mohamm6d** [abraham/twitteroauth#734]
I need to know if user one time logged with this API. for next time or even when he is offline, can we send posts via saved tokens? when i want to do this with my own account after one call, it says invalid token

Actually I must simple ask that does this API support permanent token for user with unlimited times use?

**Comment by abraham** [comment]
Yes, a users access token is long lived and will not expire (although may be revoked). You can store them in your database and use them as needed.

**Comment by Mohamm6d** [comment]
Hey, Thank you for your support but when I want to use token twice it says 'invalid or expired token'
