### ISSUE TITLE
Since any weeks we have Twitter limit errors

### ISSUE THREAD

**Issue by tomswinkels** [abraham/twitteroauth#737]
Hi,

Since any weeks we have very mutch limit errors 'User is over daily status update limit'.

But are the limits per app key or user key? 

And is there some work arround?

**Comment by abraham** [comment]
Twitter posted an announcement about rate limit changes: https://twittercommunity.com/t/upcoming-post-endpoint-rate-limit-enforcement-on-october-22nd/114900
