### ISSUE TITLE
Mentioning a User with @

### ISSUE THREAD

**Issue by acpadhi** [abraham/twitteroauth#738]
Is there a way to mention a user while creating/posting a new status update?
I tried with the following : @username and also urlencoded %40username within the status text
In either of the cases, it shows @username or %40username in the resulting tweet instead of a real mention link like in manual tweet. 
I am using the following code : 
$parameters = array('status' => $message, 'media_ids' => $media_id); 
/* media id is for a video uploaded in previous step */
$result = $twitter->post('statuses/update', $parameters);

**Comment by abraham** [comment]
What do you mean by "real mention"? Including @username in the text is all you need to do to mention someone.

**Comment by acpadhi** [comment]
Hi Abraham, my apologies, I was not sending the @ sign correctly, and read through some forum messages that they need to be URL encoded. It worked perfectly fine. Thanks a ton for your reply and for writing this excellent library. Please close this issue. Sorry once again for misreporting.
