### ISSUE TITLE
URL normalization essentials

### ISSUE THREAD

**Issue by das-pro** [abraham/twitteroauth#740]
Notice: Undefined index: scheme in /opt/lampp/htdocs/pesa/OAuth.php on line 333

Notice: Undefined index: host in /opt/lampp/htdocs/pesa/OAuth.php on line 334

**Comment by abraham** [comment]
It looks like you are using a very old version. Please update and if you are still getting errors open an issue describing what you are trying to do, what you expect to happen and what is actually happening.
