### ISSUE TITLE
can you share twitter pin entry ?

### ISSUE THREAD

**Issue by twioauth** [abraham/twitteroauth#747]
if you help me I will be happy
**callbackurl=oob**  how do i do it for php ?

**Comment by abraham** [comment]
the `oauth_callback` parameter is needed when [getting a request token](https://twitteroauth.com/redirect.php). You would do something like the following:

~~~php
$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => 'oob'));
~~~
