### ISSUE TITLE
Inbox system for sending and receiving messages from followers

### ISSUE THREAD

**Issue by ijazraja** [abraham/twitteroauth#748]
I want to know if it is possible to create inbox system for twitter messages using Twitter OAuth API, in which all followers should be displayed on the left side of the screen and on clicking each user remaining screen display all previous messages and with the option to send new, just like Skype as an example

**Comment by abraham** [comment]
That should be possible.

APIs for dealing with friends: https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/overview
APIs for direct messages: https://developer.twitter.com/en/docs/direct-messages/api-features
