### ISSUE TITLE
twitter media upload API

### ISSUE THREAD

**Issue by abhishekpwebdev** [abraham/twitteroauth#766]
Hello everyone,
i am trying to post a tweet on twitter through twitter post API i am able to tweet the text successfully but i am facing an issue in posting media is that i am using the google cloud storage for storing object and will be reading the uploaded object through URL but i have read that twitter does not allow URL to upload media or access media it needs a raw file path

the URL of reading object from cloud storage is https://storage.googleapis.com/social27949.appspot.com/1.png

but what i think twitter needs is .home/social/assets/img/1.png
please help me to find the solution

**Comment by abraham** [comment]
Twitter requires that image data be included in the upload request itself. I would suggest you download the images, put them in the systems temp directory and use that temporary location to perform the upload. There are a [number of methods for downloading images](https://stackoverflow.com/a/724449/26406) from a URL.
