### ISSUE TITLE
Download media/upload image from external source

### ISSUE THREAD

**Issue by UVLabs** [abraham/twitteroauth#768]
I'm trying to download an image for upload from an external website but the upload is failing with error:

` {"request":"/1.1/media/upload.json","error":"Invalid media_id: Some()."}`

When I set the `'media'` parameter with the link of the external image it doesn't work. So I tried to upload the base64 image by downloading it from the url using file_get_contents then converting it:

```
$img = file_get_contents($url);
$data = base64_encode($img);
$upload_args  = [ 'media_data' => $data ];
$media_response = $api->upload( 'media/upload', $upload_args, true );
```

This fails. I saw the issue here: https://github.com/abraham/twitteroauth/issues/487 and it doesn't seem to have been resolved

I also saw your comment here: https://github.com/abraham/twitteroauth/pull/595 

Are you saying at this point images need to be on the same server where the tweet is being constructed? In the use case I have tweet images are coming from an external site.

Looking forward to your reply

**Comment by abraham** [comment]
[POST media/upload](https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-upload.html) requires that the raw binary file be included with the request so Twitter will not fetch the image from an URL and use that. Until #681 is implemented this libraries API requires a path to file on the servers storage. I recommend writing the file to the servers tmp directory while.
