### ISSUE TITLE
upload multiple images to twitter media api and post to twitter

### ISSUE THREAD

**Issue by abhishekpwebdev** [abraham/twitteroauth#773]
hey, I am able to post a tweet with a message and single image. Now I want to post a tweet with multiple images .i.e. I want to upload multiple images to tweet media API.Any help

**Comment by abraham** [comment]
The media section on https://twitteroauth.com/ is an example of posting multiple images at once.

```php
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$media1 = $connection->upload('media/upload', ['media' => '/path/to/file/kitten1.jpg']);
$media2 = $connection->upload('media/upload', ['media' => '/path/to/file/kitten2.jpg']);
$parameters = [
    'status' => 'Meow Meow Meow',
    'media_ids' => implode(',', [$media1->media_id_string, $media2->media_id_string])
];
$result = $connection->post('statuses/update', $parameters);
```

**Comment by shreya-14-may** [comment]
This is not working
and gi
<img width="1436" alt="Screenshot 2020-10-20 at 4 53 03 PM" src="https://user-images.githubusercontent.com/69234158/96579599-ba309b80-12f4-11eb-88ee-0ae8b62b0264.png">
ving this error

**Comment by maggz69** [comment]
@shreya-14-may Did you copy the code word for word?

**Comment by abraham** [comment]
Check "Changing timeout settings" on https://twitteroauth.com/. Sometimes for media you have to increase the default timeouts.
