### ISSUE TITLE
 Igot error like This feature is temporarily unavailable

### ISSUE THREAD

**Issue by ALtarTech** [abraham/twitteroauth#775]
url: https://example.com/project/index.php/user_authentication/twpro?oauth_token=YdrEaAAAAAAA94IVAAABai9WlAo&oauth_verifier=YRoJ4aRp4cxPasOC9HnAEueYHQzicSg3
An uncaught Exception was encountered
Type: Abraham\TwitterOAuth\TwitterOAuthException

Message: This feature is temporarily unavailable

Filename: /home/systqkqp/public_html/project/application/libraries/twvendor/abraham/twitteroauth/src/TwitterOAuth.php

**Comment by abraham** [comment]
That's an error on Twitter's side. If the error continues I would post to https://twittercommunity.com
