### ISSUE TITLE
POST direct_messages/events/new issue in the last version

### ISSUE THREAD

**Issue by tuyennguyen2906** [abraham/twitteroauth#777]
Hello

I am using the following code and library functions to use twitter API's: 

![dm message issue2](https://user-images.githubusercontent.com/24350137/57062719-34c5bf80-6ceb-11e9-8b5b-9513ed20c835.png)

But there was a issue with the last API. I alway get **Array to string conversion** in src/Util.php 103

You can see the attach image for more detail:
http://prntscr.com/nje8fu
![dm message issue](https://user-images.githubusercontent.com/24350137/57062551-b9640e00-6cea-11e9-9b39-4615a36be065.png)

Can you check it out again?

Thanks

**Comment by abraham** [comment]
I think you are running an old version of TwitterOAuth and upgrading to the latest version will fix it.

**Comment by tuyennguyen2906** [comment]
Thank you for your answer.

But can you tell me the link to get the last version?

I shall check it out again

Thanks

**Comment by tuyennguyen2906** [comment]
HI @abraham 

I just download the last version through composer and now it works.

Thank you for your help let me close this issue

Thanks
