### ISSUE TITLE
cant get tweet by hashtag

### ISSUE THREAD

**Issue by srhtylmz19** [abraham/twitteroauth#778]
I want to get all tweets from all user (not private) by my function is like ;
        
        $conn = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
        $statuses = $conn->get("search/tweets", ["q" => "@sinelist"]);

        dd($statuses);

but it's not returning the correct data.. could you please help me  @abraham

**Comment by abraham** [comment]
Can you be more specific about what tweets you would like the search results to include.
