### ISSUE TITLE
Receiving 'non-object' error

### ISSUE THREAD

**Issue by benyates1** [abraham/twitteroauth#779]
I receive the following notice in PHP: "Trying to get property of non-object" when try to retreive tweets via the api.

I'm certain my credentials are correct.

The full error notice (covering multiple varaibles) is copied below:

`Notice: Trying to get property of non-object in C:\xampp\htdocs\cheshire-elite\includes\include.tweets.php on line 123

Notice: Trying to get property of non-object in C:\xampp\htdocs\cheshire-elite\includes\include.tweets.php on line 131

Notice: Trying to get property of non-object in C:\xampp\htdocs\cheshire-elite\includes\include.tweets.php on line 135

Notice: Trying to get property of non-object in C:\xampp\htdocs\cheshire-elite\includes\include.tweets.php on line 135

Notice: Trying to get property of non-object in C:\xampp\htdocs\cheshire-elite\includes\include.tweets.php on line 143

Notice: Trying to get property of non-object in C:\xampp\htdocs\cheshire-elite\includes\include.tweets.php on line 146`

I also get a timestamp of 01:00AM Jan 1st.

**Comment by abraham** [comment]
What APIs are you calling and how are you calling them?

**Comment by benyates1** [comment]
I am using the TwitterOAuth.php to show just latest tweet using the `display_latest_tweets` function.

The code that the error references is copied below:

`if($connection){
				// Get the latest tweets from Twitter
 				$get_tweets = $connection->get("https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=".$twitter_user_id."&count=".$tweets_to_display."&include_rts=".$include_rts."&exclude_replies=".$ignore_replies);
				
				// Error check: Make sure there is at least one item.
				if (count($get_tweets)) {
 					
					// Define tweet_count as zero
					$tweet_count = 0;
 
					// Start output buffering.
					ob_start();
 
					// Open the twitter wrapping element.
					$twitter_html = $twitter_wrap_open;
 
					// Iterate over tweets.
					foreach($get_tweets as $tweet) {
						
							$tweet_found = true;
							$tweet_count++;
 							$tweet_desc = $tweet->text;
							// Add hyperlink html tags to any urls, twitter ids or hashtags in the tweet.
							$tweet_desc = preg_replace("/((http)+(s)?:\/\/[^<>\s]+)/i", "<a href=\"\\0\" target=\"_blank\">\\0</a>", $tweet_desc );
							$tweet_desc = preg_replace("/[@]+([A-Za-z0-9-_]+)/", "<a href=\"http://twitter.com/\\1\" target=\"_blank\">\\0</a>", $tweet_desc );
							$tweet_desc = preg_replace("/[#]+([A-Za-z0-9-_]+)/", "<a href=\"http://twitter.com/search?q=%23\\1\" target=\"_blank\">\\0</a>", $tweet_desc );
 
 
              // replace t.co links with expanded link, if present
              $entities = $tweet->entities;
              if(!empty($entities->urls[0]->expanded_url)) {
              $tweet_desc = str_replace($entities->urls[0]->url, $entities->urls[0]->expanded_url, $tweet_desc);
              }
                 $media_url = $entities->media[0]->media_url;
		 if($media_url) {
 		 $img = "<img src='".$media_url."'>";
 		 $twitter_html .= $img;
 		}
 
 
 							// Convert Tweet display time to a UNIX timestamp. Twitter timestamps are in UTC/GMT time.
							$tweet_time = strtotime($tweet->created_at);
							
							// Get Tweet ID
							$tweet_id   = $tweet->id_str;`

**Comment by abraham** [comment]
What line of that code is triggering the error? Has the code worked before and recently started throwing the error?

Make sure you are running the latest version of TwitterOAuth. The format of your `get` request is not supported by the library. You should try:

```php
$connection->get(
        "statuses/user_timeline.json",
        [
            "screen_name" => $twitter_user_id,
            "count" => $tweets_to_display,
           ...
        ]
    );
```

**Comment by benyates1** [comment]
Thanks, I will try the updated code although I thought I was using the latest release (1.0.1) as downloaded from https://github.com/abraham/twitteroauth/releases (link found in the manual istallation tab of the documentation at https://twitteroauth.com/.

There are several lines triggering errors, i have copied in each below:
`$tweet_desc = $tweet->text;` (#123)
`$entities = $tweet->entities;` (#131)
`$media_url = $entities->media[0]->media_url;` (#135)
`$tweet_time = strtotime($tweet->created_at);` (#143)
`$tweet_id   = $tweet->id_str;` (#146)

**Comment by abraham** [comment]
what does the following methods return when called after making the `get` request?

```php
$connection->getLastHttpCode();
$connection->getLastBody();
```
