### ISSUE TITLE
can I only print to the ID screen

### ISSUE THREAD

**Issue by trphp** [abraham/twitteroauth#780]
screen
`

  | array(1) {
-- | --
  | [0]=>
  | object(stdClass)#11 (26) {
  | ["created_at"]=>
  | string(30) "Wed May 22 18:32:38 +0000 2019"
  | ["id"]=>
  | int(1131266637280288768)
  | ["id_str"]=>
  | string(19) "1131266637280288768"
  | ["text"]=>
  | string(74) "RT @nocontextavrupa: Dünyanın en güzel kavgası https://t.co/ds3CCQXns6"
  | ["truncated"]=>
  | bool(false)
  | ["entities"]=>
  | object(stdClass)#12 (5) {
  | ["hashtags"]=>
  | array(0) {
  | }
  | ["symbols"]=>
  | array(0) {
  | }
  | ["user_mentions"]=>
  | array(1) {
  | [0]=>
  | object(stdClass)#13 (5) {
  | ["screen_name"]=>
  | string(15) "nocontextavrupa"
  | ["name"]=>
  | string(25) "no context avrupa yakası"
  | ["id"]=>
  | int(734705953472446467)
  | ["id_str"]=>
  | string(18) "734705953472446467"
  | ["indices"]=>
  | array(2) {
  | [0]=>
  | int(3)
  | [1]=>
  | int(19)
  | }
  | }
  | }

`
just want to print the screen to tweet id.

**Comment by abraham** [comment]
If you only want the ID you should be able to do something like `$tweet->id` or `$tweet-id_str`.
