### ISSUE TITLE
account/verify_credentials This feature is temporarily unavailable

### ISSUE THREAD

**Issue by Abdulmanan0315** [abraham/twitteroauth#781]
I am using this Oauth library to authenticate user into my app and it works very smooth until a point:

        $id = 'xxxxx';
        $secret = 'xxxxxxxxxx';
        $oauth_verifier = $_GET['oauth_verifier'];

        // connect with application token
        $connection = new TwitterOAuth(
            $id,
            $secret,
            $this->session->userdata('oauth_token'),
            $this->session->userdata('oauth_token_secret')
        );
         
        // request user token
        $token = $connection->oauth(
            'oauth/access_token', [
                'oauth_verifier' => $oauth_verifier
            ]
        );

 **Untill the above point where i request user token this is working great and returns the following as it should 👍 **

> Array ( [oauth_token] => xxxxxx [oauth_token_secret] => xxxx [user_id] => xxxx [screen_name] => xxxxx )

**But when doing something like tweet or getting user details using the following  i am getting error 👎 **

        $userInfo = $connection->get("account/verify_credentials", ['include_email' => 'true']);

        print_r($userInfo);

**The Error**

> An uncaught Exception was encountered
> Type: Abraham\TwitterOAuth\TwitterOAuthException
> 
> Message: This feature is temporarily unavailable
> 
> Filename: C:\MAMP\htdocs\application\third_party\twitteroauth\abraham\twitteroauth\src\TwitterOAuth.php
> 
> Line Number: 168
> 
> Backtrace:
> 
> File: C:\MAMP\htdocs\application\controllers\account.php
> Line: 292
> Function: oauth
> 
> File: C:\MAMP\htdocs\index.php
> Line: 315
> Function: require_once

**Comment by abraham** [comment]
I would guess it's one of a couple things.

1. The API is temporarily down and it'll start randomly working again.
1. You're not storing the correct API tokens or they are getting modified somehow.
1. Something is wrong with the account/app.

If the issue persists and you triple check that all four token values are correct you might check out similar posts on [twittercommunity.com](https://twittercommunity.com/search?q=%22This%20feature%20is%20temporarily%20unavailable%22) for possible solutions.

**Comment by Abdulmanan0315** [comment]
Can you provide me full working example to retireve user details ? so that i can also confirm that

**Comment by Abdulmanan0315** [comment]
and one more question i am testing this on localhost with **https://** , thus what should i put in website its not accepting as follows:

<img width="531" alt="Capture" src="https://user-images.githubusercontent.com/20532497/59204366-e8a74e00-8bb9-11e9-82b5-8c09841dad79.PNG">

**Comment by abraham** [comment]
Website URL must be a valid domain and can't be localhost. Note that it's what's used on Tweet attribution and is different from callback URLs which are used when authenticating.

**Comment by abraham** [comment]
https://twitteroauth.com/ is a live example of the OAuth flow. you can click "Sign in with Twitter" in the upper right to walk through the example and see the code used.

**Comment by Abdulmanan0315** [comment]
hmm it looks like the error is due to the wrong website while my callback url is good.I ll test on a live site and get back asap.Thanks for such a beautiful plugin.
