### ISSUE TITLE
Regarding Twitter requiring TLS 1.2 as of July 15 2019

### ISSUE THREAD

**Issue by kittybangtango** [abraham/twitteroauth#782]
Does the current code support TLS 1.2?
Any tips on how to confirm that my current app is using 1.2?

Here's a link to the announcement:
https://twittercommunity.com/t/removing-support-for-legacy-tls-versions-1-0-1-1-on-twitter/126648

TIA

**Comment by abraham** [comment]
It looks like TLS is [supported since OpenSSL 1.0.1](https://stackoverflow.com/a/30145222/26406). So as long as you are on that you should be good.

**Comment by kittybangtango** [comment]
Excellent, thanks very much for the info!
