### ISSUE TITLE
How to shoot logged-in user's tweets    [oauth / authorize ]

### ISSUE THREAD

**Issue by HaciKandemir** [abraham/twitteroauth#786]
```php
<?php 
require "twitteroauth/autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;

define('CONSUMER_KEY', 'KEY');
define('CONSUMER_SECRET', 'KEY');
define('OAUTH_CALLBACK', 'http://localhost/twitter_bot/index2.php');

$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);

$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));

$_SESSION['oauth_token'] = $request_token['oauth_token'];
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];

$url = $connection->url('oauth/authorize',['oauth_token' => $request_token['oauth_token']]);

if (isset($_GET['oauth_token'])) {
	$oauth_token=$_GET['oauth_token'];
	$oauth_verifier=$_GET['oauth_verifier'];
	
$baglan = new TwitterOAuth(CONSUMER_KEY,CONSUMER_SECRET,$oauth_token,$oauth_verifier);
	
	$statues = $connection->post("statuses/update", ["status" => "hello world"]);
	if ($connection->getLastHttpCode() == 200) {
		echo "Tweet posted succesfully";
	} else {
		echo "Handle error case";
	}
}

 ?>
 <a href="<?php echo $url ?>">Enter</a>
```

With the code above, the user successfully logs in. What I don't know is how do I pull the tweets of the user who logged in after the user logged in,

**Comment by abraham** [comment]
Once you have the users credentials you can get the users own tweets similar to how you are posting a tweet except with the [GET statuses/user_timeline](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline.html) API method.

```php
$statuses = $baglan->get("statuses/user_timeline");
```

**Comment by HaciKandemir** [comment]
not working error message;

`
  |Abraham\TwitterOAuth\TwitterOAuth Object
  |--
  | (
  | [response:Abraham\TwitterOAuth\TwitterOAuth:private] => Abraham\TwitterOAuth\Response Object
  | (
  | [apiPath:Abraham\TwitterOAuth\Response:private] =>
  | [httpCode:Abraham\TwitterOAuth\Response:private] => 0
  | [headers:Abraham\TwitterOAuth\Response:private] => Array
  | (
  | )
  |  
  | [body:Abraham\TwitterOAuth\Response:private] => Array
  | (
  | )
  |  
  | [xHeaders:Abraham\TwitterOAuth\Response:private] => Array
  | (
  | )
  |  
  | )
  |  
  | [bearer:Abraham\TwitterOAuth\TwitterOAuth:private] =>
  | [consumer:Abraham\TwitterOAuth\TwitterOAuth:private] => Abraham\TwitterOAuth\Consumer Object
  | (
  | [key] => 'key'
  | [secret] => 'key'
  | [callbackUrl] =>
  | )
  |  
  | [token:Abraham\TwitterOAuth\TwitterOAuth:private] => Abraham\TwitterOAuth\Token Object
  | (
  | [key] => 'key'
  | [secret] => 'key'
  | )
  |  
  | [signatureMethod:Abraham\TwitterOAuth\TwitterOAuth:private] => Abraham\TwitterOAuth\HmacSha1 Object
  | (
  | )
  |  
  | [attempts:Abraham\TwitterOAuth\TwitterOAuth:private] => 0
  | [timeout:protected] => 5
  | [connectionTimeout:protected] => 5
  | [maxRetries:protected] => 0
  | [retriesDelay:protected] => 1
  | [decodeJsonAsArray:protected] =>
  | [userAgent:protected] => TwitterOAuth (+https://twitteroauth.com)
  | [proxy:protected] => Array
  | (
  | )
  |  
  | [gzipEncoding:protected] => 1
  | [chunkSize:protected] => 250000
  | )
  | stdClass Object
  | (
  | [errors] => Array
  | (
  | [0] => stdClass Object
  | (
  | [code] => 89
  | [message] => Invalid or expired token.
  | )
  |  
  | )
  |  
  | )
`
my code ;
`
| require "twitteroauth/autoload.php";
| 
| use Abraham\TwitterOAuth\TwitterOAuth;
| 
| define('CONSUMER_KEY', 'sqIBb2kNJdkKMW1DpemXguEy8');
| define('CONSUMER_SECRET', 'kerI8LaVJtYHEfCcpBtgrewHBxihFQeS7PEQVHRdrFGYLTYT8Q');
| define('OAUTH_CALLBACK', 'http://localhost/twitter_bot/index2.php');
| 
| $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
| $oauth_token=null;
| $oauth_verifier=null;
| 
| if (empty($oauth_token) && empty($_GET['oauth_verifier'])) {
| 	$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
| 
| 	$_SESSION['oauth_token'] = $request_token['oauth_token'];
| 	$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
| 	$url = $connection->url('oauth/authorize',['oauth_token' => $request_token['oauth_token']]);
| 	echo "<a href='$url'>Link</a>";
| }
| 
| 
| else if(isset($_GET['oauth_verifier'])) {
| 	$oauth_token=$_GET['oauth_token'];
| 
| 	$oauth_verifier=$_GET['oauth_verifier'];
| 	$baglan = new 
|  TwitterOAuth(CONSUMER_KEY,CONSUMER_SECRET,$oauth_token,$oauth_verifier);
| 	print_r($baglan);
| 	$statuses = $baglan->get("statuses/user_timeline");
| 	print_r($statuses);
| }
`

**Comment by abraham** [comment]
```php
$baglan = new TwitterOAuth(CONSUMER_KEY,CONSUMER_SECRET,$oauth_token,$oauth_verifier);
print_r($baglan);
$statuses = $baglan->get("statuses/user_timeline");
```

You can't use `oauth_verifier` to make actual API requests. You have to first use it to get an access token which then can be used on the Twitter APIs.

1. Get request token
2. Send user to Twitter to authorize access
3. Exchange request token and verifier for access token
4. Use access token to get Twitter data.

You can see an example of getting an access token here: https://github.com/abraham/twitteroauth-demo/blob/master/callback.php
You ca see an example of using the access token here: https://github.com/abraham/twitteroauth-demo/blob/master/profile.php

**Comment by HaciKandemir** [comment]
I'm already using 'oauth_verifier ' right now.   [imgur](https://imgur.com/a/NuUJZpj)

**Comment by abraham** [comment]
In your sample code you are skipping step 3. You need to get an access token to to use any of the Twitter APIs.
