### ISSUE TITLE
Twitteroauth stopped working 2 days ago

### ISSUE THREAD

**Issue by navbugtom** [abraham/twitteroauth#787]
Everything was working for 2 years, and two days ago, July 30th, I started getting this error:
I didn't change anything.
Please help :)

Fatal error: Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'SSL connect error' in /var/www/html/accidentin/navbug-twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php:409 Stack trace: #0 /var/www/html/accidentin/navbug-twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(334): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array) #1 /var/www/html/accidentin/navbug-twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(305): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array) #2 /var/www/html/accidentin/navbug-twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(179): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'statuses/user_t...', Array) #3 /var/www/html/accidentin/navbug-twitter/twitter.class.php(129): Abraham\TwitterOAuth\TwitterOAuth->get('statuses/user_t...', Array) #4 /var/www/html/accidentin/navbug-twitter/test.php(51): Twitter->collect_tweets(Array) #5 {main} thrown in /var/www/html/accidentin/navbug-twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 409

**Comment by abraham** [comment]
I would guess this is related to the [TLS changes](https://twittercommunity.com/t/removing-support-for-legacy-tls-versions-1-0-1-1-on-twitter/126648). Make try updating PHP, cURL, and OpenSSL.

**Comment by navbugtom** [comment]
Hi Abraham, Thank you for taking the time to help me!!
It is indeed the TLS changes. I'm unable to update cURL on my server. when I try to cURL the twitter API in SSH I get this error: 'SSL connect error'.
However, if I force TLSv1.2 when I cURL ( curl --tlsv1.2 ), it seems to be working.

My question is, can I change something in the twitterOAuth.php or twitter.class.php to force tlsv1.2 ? It should be an easy fix, but I don't know where the cURL line is called...

Again, thank you so much for your time.

Kevin

**Comment by navbugtom** [comment]
I managed to fix this issue by adding the following line:
CURLOPT_SSLVERSION => 6,
in the $options field, in TwitterOAuth.php. 
This forces TLSV1.2 on cURL.

**Comment by jlukic** [comment]
Also see https://github.com/abraham/twitteroauth/issues/790
