### ISSUE TITLE
Remote File path Fails

### ISSUE THREAD

**Issue by emmanuelr20** [abraham/twitteroauth#789]
The Media upload fun the adding a remote path fails due to the is_readable function which works only on local files. You should remove that check or check and upload for remote files.

private function uploadMediaNotChunked($path, array $parameters)
    {
        if (($file = file_get_contents($parameters['media'])) === false) {
            throw new \InvalidArgumentException('You must supply a readable file');
        }
        $parameters['media'] = base64_encode($file);
        return $this->http('POST', self::UPLOAD_HOST, $path, $parameters, false);
    }

**Comment by abraham** [comment]
Why should the check be removed? Twitter doesn't support remote files.
