### ISSUE TITLE
Support POST requests to the UPLOAD

### ISSUE THREAD

**Issue by Hato6502** [abraham/twitteroauth#792]
When upload media already encodied to base64, temporary files are needed to use upload method. 
(ex. )
`
$twitterOAuth->upload('media/upload', ['media' => '/tmp/media.png']);
`

Uploading base64 strings directly is may be more useful than through temporary files. 
But the following is doesn't supported. 
(ex. )
`
$twitterOAuth->post('media/upload', ['media_data' => $base64Image]);
`. 

So I've sent a pull request: https://github.com/abraham/twitteroauth/pull/791

This issue may be similar from https://github.com/abraham/twitteroauth/issues/487 .

**Comment by abraham** [comment]
Thanks for bringing this up. I would like the problem to be solved with #681 though.
