### ISSUE TITLE
Prevent twitter from converting a URL into link

### ISSUE THREAD

**Issue by leem32** [abraham/twitteroauth#798]
I need to post tweets that may contain a URL e.g asp.net, example.com. The problem is I don't want these URL's to be converted into anchor tags/links.

How can I do this?

I've tried:

      $status = str_replace('.', '.&#8203;', $url); // Zero Width Space 
      $status = str_replace('.', '&#046;', $url) ; // dot entity

      $post_tweets = $connection->post("statuses/update", ["status" => $status]);

But the entities are not converting and just teated as strings like www.&#8203;nhs.&#8203;uk
I want the tweet to be like: www.nhs.uk, but for it not to be a link.

**Comment by abraham** [comment]
You can try posting about this on https://twittercommunity.com/ but I don't think anything can be done. That's a feature of Twitter in general and I doubt they'd change it.
