### ISSUE TITLE
Issue Video Upload 

### ISSUE THREAD

**Issue by himanshupatel95** [abraham/twitteroauth#800]
Not show video ?
-------------------------------------------------------------------------------------------------
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, OAUTH_TOKEN, OAUTH_SECRET);
$content = $connection->get("account/verify_credentials");

    $connection->setTimeouts(60, 30);
    $file=file_get_contents('tests/video.mp4',true);
    $data = base64_encode($file);
    $media1 = $connection->upload('media/upload', ['media' =>'tests/video.mp4']);

     $parameters = [
     'status' => 'test video',
    'media_ids' => $media1->media_id_string ,
     'media_type' => 'video/mp4',
     'media_category'=>'tweet_video'
     ];
    $result = $connection->post('statuses/update', $parameters);
    
    var_dump($result);
---------------------------------------------------------------------------------------------

**Comment by mrbellek** [comment]
Are you missing a line that writes `$data` to disc? Because you're fetching the video, but the var never gets used.

**Comment by himanshupatel95** [comment]
twitter video post exteali right code  send ?

**Comment by himanshupatel95** [comment]
> Are you missing a line that writes `$data` to disc? Because you're fetching the video, but the var never gets used.

without use $data  video  error show : 
object(stdClass)#25 (2) { ["request"]=> string(22) "/1.1/media/upload.json" ["error"]=> string(24) "media type unrecognized." }

**Comment by mrbellek** [comment]
Your video file is invalid.

**Comment by acondura** [comment]
I have uploaded the same mp4 video through Twitter UI and it works but it does NOT work through this library, I get the same error: "media type unrecognized".

**Comment by acondura** [comment]
The path to the file is "/var/www/docroot/sites/default/files/2019-11/file_example_MP4_480_1_5MG_5.mp4" and it's 1.6MB. It should upload nicely since Twitter UI accepts it and publishes the tweet with that mp4.

**Comment by acondura** [comment]
So, the call is:

`$twCon->upload('media/upload',` ['media' => $imgPaths], TRUE);

and then in the logs I get:

> Notice: Undefined index: media_type in Abraham\TwitterOAuth\TwitterOAuth->mediaInitParameters() (line 346 of /var/www/vendor/abraham/twitteroauth/src/TwitterOAuth.php).

**Comment by acondura** [comment]
That error got resolved with:

`$twCon->upload('media/upload', ['media' => $imgPaths**, 'media_type' => 'video/mp4'**], TRUE);`

Now, no error and no video uploaded to the tweet.

**Comment by acondura** [comment]
Strange, a different video than before worked well but both videos worked through Twitter UI.

So, if anyone has this issue, the 'media_type' parameter solves it.
