### ISSUE TITLE
Redirect delivers 2 pairs of Oauth tokens

### ISSUE THREAD

**Issue by dachan** [abraham/twitteroauth#804]
I am following the example from twitteroauth ( https://twitteroauth.com/redirect.php ) but when I request for an Oauth token / secret, I get 2 different pairs and I think this is causing issues when trying to finalize my authorization.

My app was working fine before October. Can someone help me understand?

Below is my code:

```
session_start();

require "vendor/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;
require "env.php";

$connection = new TwitterOAuth($consumer_key, $consumer_secret);
$request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => $oauth_callback));

$_SESSION['oauth_token'] = $request_token['oauth_token'];
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];

$url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));

echo "<pre>";
print_r('consumer_key: ' . $consumer_key);
echo "<br>";
print_r('consumer_secret: ' . $consumer_secret);
echo "<br>";
print_r('_SESSION: ');
echo "<br>";
print_r($_SESSION);
echo "<br>";
print_r('url: ' . $url);
echo "</pre>";
```

**Comment by abraham** [comment]
The OAuth 1.0 flow will generate two token pairs. One from `oauth/request_token` that is temporary and will only be used for `oauth/authorize` and `oauth/access_token` which will result in the long term token pair that you should keep.

**Comment by dachan** [comment]
👌
