### ISSUE TITLE
Register Webhook Error Code 369: Invalid JSON Syntax

### ISSUE THREAD

**Issue by putrapurba** [abraham/twitteroauth#814]
Hi, Abraham,
Thank you so much for this library, I find it helped me a lot. But I got an issue when I register webhook, I don't know what was wrong because I found two sources success registering webhooks with this library:

- https://github.com/sadaimudiNaadhar/php-twitter-webhook-account-activity-api

- https://www.twilio.com/blog/create-twitter-sms-notifications-tweets-retweets-mentions-php

But when I try, it give me Error Code 369. I modify a bit of TwitterOAuth.php to download media from DM. Could you help me?

```
private function http($method, $host, $path, array $parameters, $json) {
        $this->resetLastResponse();
        $this->resetAttemptsNumber();
        $url = $this->buildUrl($host, $path);
        $this->response->setApiPath($path);
        if (!$json) {
            $parameters = $this->cleanUpParameters($parameters);
        }
        return $this->makeRequests($url, $method, $parameters, $json);
    }
```

```
private function buildUrl($host, $path)
    {
        if(is_null($host)) {
            return $path;
        }
        return sprintf('%s/%s/%s.json', $host, self::API_VERSION, $path);
    }`
```

```
private function makeRequests($url, $method, array $parameters, $json)
    {
        do {
            $this->sleepIfNeeded();
//            $result = $this->oAuthRequest($url, $method, $parameters, $json);
//            $response = JsonDecoder::decode($result, $this->decodeJsonAsArray);
            $response = $this->oAuthRequest($url, $method, $parameters, $json);
            try {
                // Decode response only if decoding required (if string is json encoded)
                $response = $this->decodeJsonResponseIfRequired($response);
            } catch (\RuntimeException $exception) {
                // If we catched RuntimeException, it means, response cannot be decoded
                // This may be any attachment or binary string
                // Do nothing for while
            }
            $this->response->setBody($response);
            $this->attempts++;
            // Retry up to our $maxRetries number if we get errors greater than 500 (over capacity etc)
        } while ($this->requestsAvailable());
        return $response;
    }
```

```
private function decodeJsonResponseIfRequired($response)
    {
        $response = JsonDecoder::decode($response, $this->decodeJsonAsArray);
        $jsonLastError = json_last_error();
        if ($jsonLastError === JSON_ERROR_NONE) {
            return $response;
        }
        // Throws RuntimeException for compatibility with PHP 5
        throw new \RuntimeException(json_last_error_msg(), $jsonLastError);
    }
```

**Comment by abraham** [comment]
I'm unsure what exactly you're trying to do. Please include what Twitter API you're trying to call and how you are calling it.

**Comment by putrapurba** [comment]
I want to register webhooks, and already:
1. Make webhook environment on Twitter Dashboard
2. Put my webhook URL on Twitter App settings

Then I code like this:

`/* Create a TwitterOauth object with consumer/user tokens. */
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token['oauth_token'], $access_token['oauth_token_secret']);
$url = "example.com/webhook";
$content = $connection->post("account_activity/all/{myEnvironmentName}/webhooks", ["url" => $url]);`

I always got response Invalid JSON syntax.

**Comment by sanket007** [comment]
Hi @putrapurba, You have to supply encoded webhook url in request body against url parameter as written in official twitter doc.
[(https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/aaa-premium#post-account-activity-all-env-name-webhooks)]

and make sure webhook url is HTTPS.

**Comment by abraham** [comment]
It looks like you've modified the TwitterOAuth code? That shouldn't be needed for interacting with this API and might be causing weird issues.
