### ISSUE TITLE
TwitterOAuth::getLastBody() undocumented 

### ISSUE THREAD

**Issue by Chealer** [abraham/twitteroauth#816]
As can be seen in https://github.com/abraham/twitteroauth/blob/master/src/TwitterOAuth.php TwitterOAuth contains an important getLastBody() method which returns the body of the response. Unfortunately it appears to be completely undocumented.

**Comment by abraham** [comment]
I don't expect developers to use that API all that often. Typically I expect a usage pattern like this:

```php
$content = $connection->get("account/verify_credentials")
```

Eventually documentation will be generated from the source code and then this will API will be more explicitly listed.

**Comment by Chealer** [comment]
Why was this ticket closed?

**Comment by abraham** [comment]
As I said I don't expect developers to need this API method very often. I don't plan on manually documenting it so there isn't an action item from this issue.

**Comment by Chealer** [comment]
> As I said I don't expect developers to need this API method very often. I don't plan on manually documenting it so there isn't an action item from this issue.

There isn't an action item? How about **adding documentation**?
