### ISSUE TITLE
using oAuth to authenticate twittergas error 

### ISSUE THREAD

**Issue by Ppikrides** [abraham/twitteroauth#817]
Is there any error with the server ?
Before two days i do AUTHENTICATION using my keys and  was working fine. Now i get an error

HP Fatal error: Uncaught Error: Class 'Abraham\TwitterOAuth\TwitterOAuth' not found in C:\inetpub\wwwroot\twiapp\index.php:17
Stack trace:
#0 {main}

and
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

can anyone help me

**Comment by abraham** [comment]
That sounds like you don't have the TwitterOAuth library installed correctly.

**Comment by Ppikrides** [comment]
I just downloaded it and twitteroauth  folder and in my program using :


<?php
require_once "twitteroauth-master/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;
 
define('CONSUMER_KEY', 'xxxxx');
define('CONSUMER_SECRET', 'xxx');
define('ACCESS_TOKEN', 'xxx');
define('ACCESS_TOKEN_SECRET', 'xxx');

$conn = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
//$conn = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET );

**Comment by Ppikrides** [comment]
Can you give me any instructions for installing correctly?

**Comment by abraham** [comment]
It's recommend that you follow the composer directions on https://twitteroauth.com/

**Comment by Ppikrides** [comment]
Abraham thank a lot for your rely.
The problem with with twitter starts when i change my key . Before it was
worked k fine until i changed the keys. With the new keys in twitter it
does not authenticate me!!!.

i run 2 scripts that were worked fine before and now i get error
connection 0
and

PHP Warning:  file_get_contents(https://api.twitter.com/oauth2/token):
failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden
 in C:\inetpub\wwwroot\KF6013_Assignment\testauth2.php on line 20


I do not know what to do...

I will appreciate it if you response to me. I do not know what else to do????


thanks Abraham

**Comment by mrbellek** [comment]
Last time this happened to me, I had a trailing space in one of the keys.

**Comment by abraham** [comment]
> The problem with with twitter starts when i change my key

Then there is something wrong with they key. Check for whitespace or zero-width characters like @mrbellek suggests.
