### ISSUE TITLE
The TwitterOAuth could not Inheritable 

### ISSUE THREAD

**Issue by KevinHN** [abraham/twitteroauth#819]
Because the TwitterOAuth doesn't support for Ads API, so I want to inherit it to support Ads but it doesn't have a good design for inheritance. 

I think that the properties of this class and private method should be protected.
$url = sprintf('%s/%s', self::API_HOST, $path); should be place on a protected method.

Hope that you help for this!

**Comment by abraham** [comment]
It's not officially supported but you can override `apiUrl` in 3.1.0.
