### ISSUE TITLE
Post tweets to another account

### ISSUE THREAD

**Issue by jinming88** [abraham/twitteroauth#823]
HI.
I am currently using your code.
This is really useful.
I have one question.
Now,I can only post to my account which create api key but I want to post tweets to another account.
I know another user email address and password.
Is this possible ?
If yes,Please let me know how can I solve this problem.
Thanks.

**Comment by abraham** [comment]
Using your application keys you have to perform the oauth flow with the other user and get their access token. I would recommend using a tool like [twurl](https://github.com/twitter/twurl) although you can also try using the [twitteroauth.com source code](https://github.com/abraham/twitteroauth-demo).

**Comment by jinming88** [comment]
Hi abraham!
Thanks for your help.
It's working well!
