### ISSUE TITLE
Upload image from Server

### ISSUE THREAD

**Issue by coderbhaai** [abraham/twitteroauth#824]
Hi,

Is there a way we can upload images from the live server instead of the local system. 
Buffer seems to do this easily. 

It works well with the local system but I would like to automate it and hence need to upload the server images and not local system.

Amit

**Comment by abraham** [comment]
The media has to be uploaded from the system that has the TwitterOAuth library and the user's Twitter credentials. This is a requirement of the [Twitter API](https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-upload).
