### ISSUE TITLE
Sorry for this, 'Your credentials do not allow access to this resource', 'code' => 220

### ISSUE THREAD

**Issue by theApprentice** [abraham/twitteroauth#825]
Hello Abraham,
thank you so much for your work and your code.

I'm deeply sorry to ask again help for the 220 issue, i came up with the code below, it has been checked and rechecked, i verified the tokens, all seems ok, but i get stuck on this.

My app has only read and email permissions, since i would like to perform Twitter login in a couple of different situations with different callbacks, i have putted the two main functions in two wrapper, but i do not think this is the problem. 

Thank you again,
G.

Here is the code:
```php
  session_start();
  require_once( 'twitteroauth/autoload.php' );
  use Abraham\TwitterOAuth\TwitterOAuth;

  function _callTwitt(){
    define( 'CONSUMER_KEY', 'xxxxxxxxxxxxxxxxxxxxxxx' );
    define( 'CONSUMER_SECRET', 'xxxxxxxxxxxxxxxxxxxxxxxx' );
    define( 'OAUTH_CALLBACK', 'https://twim.community/it/welcomet' );
    if ( !isset ( $_SESSION['access_token'])) {
      $connection = new TwitterOAuth( CONSUMER_KEY, CONSUMER_SECRET );
      $request_token = $connection->oauth( 'oauth/request_token', array( 'oauth_callback' => OAUTH_CALLBACK ) );
      $_SESSION['oauth_token'] = $request_token['oauth_token'];
      $_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
      $url = $connection->url( 'oauth/authorize', array( 'oauth_token' => $request_token['oauth_token'] ) );
      header( 'Location: ' . $url );
    } else {
      $access_token = $_SESSION['access_token'];
      $connection = new TwitterOAuth( CONSUMER_KEY, CONSUMER_SECRET, $access_token['oauth_token'], $acces_token['oauth_token_secret'] );
      $params = array( 'include_email' => 'true', 'include_entities' => 'false', 'skip_status' => 'true' );
      $user = $connection->get( 'account/verify_credentials', $params );
    }
  }


  function _getTwittCred(){
    define( 'CONSUMER_KEY2', 'xxxxxxxxxxxx' );
    define( 'CONSUMER_SECRET2', 'xxxxxxxxxxxxxxxxx' );
    if ( isset( $_REQUEST['oauth_verifier'], $_REQUEST['oauth_token'] ) &&  $_REQUEST['oauth_token'] == $_SESSION['oauth_token'] ) {
      $connection = new TwitterOAuth( CONSUMER_KEY2, CONSUMER_SECRET2, $_SESSION['oauth_token'], $_SESSION['oauth_token_secret'] );
      $access_token = $connection->oauth( 'oauth/access_token', ['oauth_verifier' => $_REQUEST['oauth_verifier']] );
      $_SESSION['access_token'] = $access_token;
      header( 'Location: ./test' );
    }
  }
```

**Comment by abraham** [comment]
Which specific call to the Twitter API is returning that error?

**Comment by theApprentice** [comment]
Hello Abraham, sorry i did not get the notification of your response!

The error is given in the last step of the procedure in _callTwitt() function, printing the $user variable gives the error.

Thank you!

`else {
      $access_token = $_SESSION['access_token'];
      $connection = new TwitterOAuth( CONSUMER_KEY, CONSUMER_SECRET, $access_token['oauth_token'], $acces_token['oauth_token_secret'] );
      $params = array( 'include_email' => 'true', 'include_entities' => 'false', 'skip_status' => 'true' );
      $user = $connection->get( 'account/verify_credentials', $params );
    }`

**Comment by theApprentice** [comment]
Hello Abraham,
hope all for the best with this Covid thing.
Could i do something else to help you help me out solving the issue?

Thank you

**Comment by abraham** [comment]
If you are getting "Your credentials do not allow access to this resource" on `account/verify_credentials` you should double check you are correctly converting request token to an access token. The request tokens are temporary and don't provide access to any resources other than getting access token.
