### ISSUE TITLE
Missing Function getAuthorizeURL()

### ISSUE THREAD

**Issue by zckyachmd** [abraham/twitteroauth#827]
I like the get Authorize URL () function because my web users don't need to approve when logging in, can you re-create this function? With a script like the one I included

/* Build TwitterOAuth object with client credentials. */
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
 
/* Get temporary credentials. */
$request_token = $connection->getRequestToken(OAUTH_CALLBACK);

/* Save temporary credentials to session. */
$_SESSION['oauth_token'] = $token = $request_token['oauth_token'];
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
 
/* If last connection failed don't display authorization link. */
switch ($connection->http_code) {
  case 200:
    /* Build authorize URL and redirect user to Twitter. */
    $url = $connection->getAuthorizeURL($token);
    header('Location: ' . $url); 
    break;
  default:
    /* Show notification if something went wrong. */
    echo 'Could not connect to Twitter. Refresh the page or try again later.';
}

**Comment by abraham** [comment]
It sounds like you're looking for 

```php
$url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
```

**Comment by zckyachmd** [comment]
Not. My point is if the user has logged in for the first time, then the user does not need to do the Authorize App again. The code seems like this, but in the current file this code doesn't exist

> function getAuthorizeURL($token, $sign_in_with_twitter = TRUE) {
>     if (is_array($token)) {
>       $token = $token['oauth_token'];
>     }
>     if (empty($sign_in_with_twitter)) {
>       return $this->authorizeURL() . "?oauth_token={$token}";
>     } else {
>        return $this->authenticateURL() . "?oauth_token={$token}";
>     }
>   }

**Comment by abraham** [comment]
I'm not planning on adding `getAuthorizeURL` back to the codebase. It's easy for you to replace it with the `url` function though.
