### ISSUE TITLE
Poll is not added to tweet

### ISSUE THREAD

**Issue by smokeyzap** [abraham/twitteroauth#837]
I'm trying to add a poll to a tweet and because there is no such example (no offence) I tried to combine the Twitter dev documentation and the provided examples for status update, media and JSON data.

On the Twitter dev docs I've found the following tweet structure:
{
  "id": 411031503817039874,
  "id_str": "411031503817039874",
  "text": "test $TWTR @twitterapi #hashtag http:\/\/t.co\/p5dOtmnZyu https:\/\/t.co\/ZSvIEMOPb8",
  "created_at": "Thu Dec 12 07:15:21 +0000 2013",
  "entities":{  
      "polls":[  
         {  
            "options":[  
               {  
                  "position":1,
                  "text":"The better answer"
               },
               {  
                  "position":2,
                  "text":"The best answer"
               }
            ],
            "end_datetime":"Sat Feb 04 15:33:11 +0000 2017",
            "duration_minutes":1440
         }
      ]
   }
}

I've converted this JSON example to the following code:

$data = [
	'status' => 'Hello world, which answer do you like?',
    'entities' => [
        'polls' => [
            'options' => [
				[
					'position' => '1',
					'text' => 'The better answer'
				],
				[
					'position' => '2',
					'text' => 'The best answer'
				]
			],
			'duration_minutes' => 1440
        ]
    ]
];
$post = $connection->post('statuses/update', $data);

The result was that the status was updated but the poll was not added. What could I improve to get this sorted or is this an known issue?

**Comment by andypiper** [comment]
Polls are not currently supported for posting in the Twitter API (this is a known request, see https://twitterdevfeedback.uservoice.com) so no API libraries can support this either.

Poll results can be retrieved in the Twitter Developer Labs API (the next version of the Twitter API in incubation) but posting is not available yet.
