### ISSUE TITLE
How to get DM Media atchachment

### ISSUE THREAD

**Issue by MetinSAYGIN** [abraham/twitteroauth#838]
Hello, 

I have a problem to get twitter DM Image, is it possible by using twitteroauth ?
I found this https://stackoverflow.com/questions/43971476/php-fetch-image-from-dm-twitter-using-rest-api/43982817#43982817 and I understand it but I dont know how to do it with your app

I tried to put the img url in " $connectioin -> get" but it doesnt work

also this https://developer.twitter.com/en/docs/direct-messages/message-attachments/guides/retrieving-media

thank you

**Comment by xJoeyv** [comment]
There is pull request open for it but not merged yet. https://github.com/abraham/twitteroauth/pull/769

**Comment by mirabdolbaghi** [comment]
why ???
whyyyyyyyyyyyy ???
why it has not been merge yet ??

**Comment by abraham** [comment]
TwitterOAuth is in maintenance mode and major improvements are no longer planned. https://github.com/abraham/twitteroauth/issues/1188
