### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by aparna-github157** [abraham/twitteroauth#839]
Its showing an error that 
This page isn’t workingapsecoglobalwarming-com.stackstaging.com is currently unable to handle this request.
HTTP ERROR 500

How to solve this error
![twitterOauth error](https://user-images.githubusercontent.com/64718125/80897696-40dac780-8d19-11ea-9bfa-a43843f8b54d.png)

**Comment by abraham** [comment]
How is this related to the TwitterOAuth library?

**Comment by aparna-github157** [comment]
I have downloaded the code Twitter OAuth Master from github and after adding code, the page is showing the error "HTTP ERROR 500".

How to solve this issue

**Comment by abraham** [comment]
Look at your server logs for what's causing the error.

**Comment by abraham** [comment]
Also You should not be using master. Install the latest stable with composer. https://packagist.org/packages/abraham/twitteroauth

**Comment by aparna-github157** [comment]
Hello Abraham,

Still it's not working. I just want to ask that is it required to be served
over a secured context such as HTTPS. Because still it's showing the error
"HTTP ERROR 500".


Thanks

**Comment by abraham** [comment]
You need to look at your server logs and see what the errors are.

**Comment by aparna-github157** [comment]
Hello Abraham,

I don't run it on my local system. I do it on an ecowebhosting site in
which my hosting package is apsecoglobalwarming.com hosting package. I
checked the error log where it's showing:

"apsecoglobalwarming-com.stackstaging.com [Sun May 10 04:41:50 2020]
[error] [client 223.186.145.189:0] PHP Parse error:  syntax error,
unexpected '?', expecting variable (T_VARIABLE) in
/home/sites/9a/7/7e999c6e5b/public_html/Api/tewitterApi/twitteroauth/src/Request.php
on line 23"

When I am checking the Request.php file. I don't see anything wrong over
there. I am unable to understand what's wrong with the code.

Thanks

**Comment by abraham** [comment]
I'd guess you are running into the [`?array` type](https://github.com/abraham/twitteroauth/blob/master/src/Request.php#L30) which was [added to PHP 7.1](https://wiki.php.net/rfc/nullable_types). What version of PHP are you using?

**Comment by aparna-github157** [comment]
Hello Abraham,

I am currently using PHP version 7.0 in Eco Web Hosting. Do I need to
change it ?

Thanks & Regards,
Aparna Banerjee

**Comment by aparna-github157** [comment]
Hello Abraham,

I am currently using PHP version 7.0 in Eco Web Hosting and here is my
code:

<?php

require "twitteroauth/autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;

$consumerkey = "HRVhbEngTk2G63iFogf3CSCB4";
$consumersecretkey = "53HoG3OA3iaNbSLRIxSL3ZSQRANqQIR5NEAC2oX2awlGQGQMpf";
$accesstoken = "1247326401402785793-iI37CUvCetSa96hs3h9p5IABLD4R1h";
$accesstokensecret = "4FgANtxHYk0rZl7zwGTMgtVBfZVw0Wz8hZlr5r3wIXCj3";

$connection = new TwitterOAuth($consumerkey, $consumersecretkey,
$accesstoken, $accesstokensecret);
$content = $connection->get("account/verify_credentials");

print_r ($content);
?>

Thanks & Regards,
Aparna Banerjee

**Comment by abraham** [comment]
TwitterOAuth requires PHP 7.1 or later. 

Do not post Twitter credentials publicly. You will want to go to https://developer.twitter.com/en/apps and regenerate the consumer API key.

**Comment by aparna-github157** [comment]
Thanks Abraham,

It's working now. Sorry, I will egenerate the consumer API key.

Thanks & Regards,
Aparna Banerjee
