### ISSUE TITLE
Subscribing a user to a Webhook after 3 legged OAuth

### ISSUE THREAD

**Issue by kishanhansjee9** [abraham/twitteroauth#840]
Hi, Abraham!

Thanks for the library, I've successfully and easily gone through the 3 legged OAuth process with it and generated an access token for my user. The web app I'm building requires the user to subscribe to an accounts activity webhook. I've registered my webhook, but can't seem to find the correct method of subscribing a user to it.

This is the endpoint I'm trying to hit: https://api.twitter.com/1.1/account_activity/all/:env_name/subscriptions.json

https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/aaa-premium#post-account-activity-all-env-name-subscriptions

Is there a method to achieve this in the library?

Thanks!

**Comment by abraham** [comment]
That looks like it would just be the `post` method?

```php
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$statues = $connection->post("account_activity/all/:env_name/subscriptions.json");
```

**Comment by kishanhansjee9** [comment]
Of course... thank you.
