### ISSUE TITLE
How to handle / know errors

### ISSUE THREAD

**Issue by akshayshrivastav866** [abraham/twitteroauth#841]
Hi,

The library is super awesome, but still i have one doubt.

The error handling part you've mentioned is more like manual error handling, what if the content length was long / account is locked / some other error, how to determine these errors?

**Comment by abraham** [comment]
You can check to see if the request was successful if there is a 200 HTTP status code. (some API endpoints may use other success codes like 201) If it falls into the error case you can check the error message from the response value from Twitter.

```php
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
$result = $connection->post('statuses/update', ['status' => str_repeat('a', 512)]);

if ($connection->getLastHttpCode() == 200) {
  print('success');
} else {
  print('error: ' . $result->errors[0]->message);
}
```

**Comment by akshayshrivastav866** [comment]
@abraham that works like charm 👍 i'm able to catch the error message and customise it now for a smooth transition.
