### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Abraham\TwitterOAuth\Test\PHPUnit_Framework_TestCase' not found 

### ISSUE THREAD

**Issue by nthanfp** [abraham/twitteroauth#845]
PHP Fatal error:  Uncaught Error: Class 'Abraham\TwitterOAuth\Test\PHPUnit_Framework_TestCase' not found in /root/workspace/twitteroauth/tests/TwitterOAuthTest.php:14
why i get this error?

**Comment by abraham** [comment]
What are you trying to do? What leads up to this error?
