### ISSUE TITLE
"Sorry, that page does not exist" on trying to upload a img

### ISSUE THREAD

**Issue by Guuri11** [abraham/twitteroauth#846]
**I can post tweets without media, but when I try upload media I've got a 404 error and the _"Sorry, that page does not exist"_ message**

The code is like this one:
`$tw_img = $this->upload('media/upload', ['media' => $image]);`
`$params = ['status' => $text, 'media_ids'=>[$tw_img->media_id_string]];`
`$this->post('status/update', $params);`

Note: **$this** is the TwitterService obj that I created extending from Twitter Api Class

**Comment by abraham** [comment]
What API request is returning the 404 error? `$this->upload('media/upload', ['media' => $image])`?

**Comment by Guuri11** [comment]
No, `$this->post('status/update', $params);`

**Comment by abraham** [comment]
It should be `statuses/update`.

**Comment by Guuri11** [comment]
omg... hahahahha true, thank you
