### ISSUE TITLE
Is this working with Twitter Labs?

### ISSUE THREAD

**Issue by tunkusalim** [abraham/twitteroauth#848]
i was looking for api library that works with Twitter Labs (https://developer.twitter.com/en/account/labs) 
does this one works with that?

**Comment by abraham** [comment]
I haven't explicitly tested but I think it should work.

**Comment by tunkusalim** [comment]
i tried to change some and tried with [PUT /labs/2/tweets/:id/hidden](https://developer.twitter.com/en/docs/labs/hide-replies/api-reference/put-hidden)
and use ``$connection->put("tweets/[statusid]/hidden", ["hidden" => 'true']);``
but the response was
```
{
    "errors":
    [ 
        {
            "parameters":{"hidden":["true"]},
            "message":"[hidden] is not one of [tweet_id,expansions,tweet.fields,media.fields,poll.fields,place.fields,user.fields]"
        },
        {
        "parameters":{"hidden":[]},
        "message":"Field hidden can not be empty"
        }
    ],
    "title":"Invalid Request",
    "detail":"One or more parameters to your request was invalid.",
    "type":"https:\/\/api.twitter.com\/labs\/2\/problems\/invalid-request"
}
```
i dont really know how to use it properly for the endpoint url
```
Endpoint URL
https://api.twitter.com/labs/2/tweets/:id/hidden
```
hope anyone can help xx

**Comment by maggz69** [comment]
What does you full PUT request look like?

**Comment by abraham** [comment]
v2 API support has been added in release [3.0.0](https://github.com/abraham/twitteroauth/releases/tag/3.0.0).
