### ISSUE TITLE
Can't get rate limits when hitting endpoint

### ISSUE THREAD

**Issue by JSebastianOspina** [abraham/twitteroauth#859]
Hello everybody, first of all want to say thank you for the amazing work developing this library.

I'm triying to get my current rate limits hitting https://developer.twitter.com/en/docs/developer-utilities/rate-limit-status/api-reference/get-application-rate_limit_status

I instance like this 

        $aux = Deck::where('nombre', str_replace('_',' ', $id))->first();

        $consumer_key = $aux->crearkey;
        $consumer_secret = $aux->crearsecret;
        
       
            $connection = new TwitterOAuth($consumer_key, $consumer_secret);
            
            $statues = $connection->get("application/rate_limit_status", ["resources" => "statuses"]);
            var_dump($statues);    `
I get null.

I try hitting another endpoints like this and it works fine.

Thank you

**Comment by abraham** [comment]
It looks like you should be using `["resources" => "statuses"]`.

**Comment by JSebastianOspina** [comment]
> It looks like you should be using `["resources" => "statuses"]`.

Still getting null :(

**Comment by abraham** [comment]
If you check the HTTP status code it returns a 401 authentication error.

```php
$statues = $connection->get("application/rate_limit_status");
var_dump($connection->getLastHttpCode());
```

If you add a user token and secret to the request it returns data as expected so it looks like that API endpoint doesn't work with application only auth.
