### ISSUE TITLE
Connection time out after 5000 miliseconds

### ISSUE THREAD

**Issue by demoseed** [abraham/twitteroauth#860]
I have used "abraham twitteroauth" library for retrieve tweet from twitter timeline. Everything working good like authorization, retrieved tweet Json and so on..

Recently i have faced issue with connection timeout but every time this issue not occurred. Sometime this error occurred in the my website. I do not know why this error happens.

Please let me know how to solve this issue.
I have attached error log with below screenshot:
>>https://nimb.ws/l7wRW3
  
Thanks

**Comment by abraham** [comment]
If you need to increase the timeout you can do that with

```php
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$connection->setTimeouts(10, 15);
```

> The first parameter corresponds to the timeout for the connect phase and the second to the maximum time the request is allowed to take.

Generally it shouldn't be needed to increase the timeouts. Check for network latency between your server and Twitter's servers.
