### ISSUE TITLE
Test old db perms

### ISSUE THREAD

**Issue by Neeath** [abraham/twitteroauth#863]
Would there be any code for me to test if old perms are still working?

**Comment by abraham** [comment]
If you have user credentials and you want to validate they are active you can make a request to the [GET account/verify_credentials](https://developer.twitter.com/en/docs/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials) endpoint.

**Comment by Neeath** [comment]
Ok, thanks!
