### ISSUE TITLE
How can I create a scheduled tweet?

### ISSUE THREAD

**Issue by theharunuysal** [abraham/twitteroauth#870]
Hello, how can I create a scheduled tweet using your library? Thank you.

**Comment by abraham** [comment]
The [POST statuses/update](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-update) endpoint does not support scheduled tweets. You would have to use something like a cron job and job queue to manage the schedules yourself.
