### ISSUE TITLE
DM (Direct Message) fails

### ISSUE THREAD

**Issue by smokeyzap** [abraham/twitteroauth#871]
I created a data variable as discribed in the manual but no message was sent.
```php
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$data = [
    'event' => [
        'type' => 'message_create',
        'message_create' => [
            'target' => [
                'recipient_id' => $userId
            ],
            'message_data' => [
                'text' => 'Hello World!'
            ]
        ]
    ]
];
$result = $connection->post('direct_messages/events/new', $data, true); // Note the true
```

Initially this was caused by the Twitter permissions. After changing this (and keys and tokens) it failed again.

var_dump of $result: NULL

**Comment by abraham** [comment]
What does `$connection->getLastBody();` show after you make the request?

**Comment by smokeyzap** [comment]
After enabling error reporting is see the following messages:

Notice:  Array to string conversion in /var/www/domains/twit.iturion.nl/vendor/abraham/twitteroauth/src/Util.php on line 103



Notice:  Array to string conversion in /var/www/domains/twit.iturion.nl/vendor/abraham/twitteroauth/src/Util.php on line 105



Notice:  Array to string conversion in /var/www/domains/twit.iturion.nl/vendor/abraham/twitteroauth/src/Util.php on line 103



Notice:  Array to string conversion in /var/www/domains/twit.iturion.nl/vendor/abraham/twitteroauth/src/Util.php on line 105

**Comment by smokeyzap** [comment]
After enabling error reporting is see the following messages:

Notice: Array to string conversion in /var/www/domains/vendor/abraham/twitteroauth/src/Util.php on line 103

Notice: Array to string conversion in /var/www/domains/vendor/abraham/twitteroauth/src/Util.php on line 105

Notice: Array to string conversion in /var/www/domains/vendor/abraham/twitteroauth/src/Util.php on line 103

Notice: Array to string conversion in /var/www/domains/vendor/abraham/twitteroauth/src/Util.php on line 105

**Comment by abraham** [comment]
What version of TwitterOAuth are you using?

**Comment by smokeyzap** [comment]
Sorry, where can I find that?

**Comment by abraham** [comment]
Look in `composer.json`.

**Comment by smokeyzap** [comment]
{
    "name": "abraham/twitteroauth",
    "type": "library",
    "description": "The most popular PHP library for use with the Twitter OAuth REST API.",
    "keywords": ["twitter", "api", "oauth", "rest", "social", "twitter api", "twitter oauth"],
    "license": "MIT",
    "homepage": "https://twitteroauth.com",
    "authors": [
        {
            "name": "Abraham Williams",
            "email": "abraham@abrah.am",
            "homepage": "https://abrah.am",
            "role": "Developer"
        }
    ],
    "support": {
        "source": "https://github.com/abraham/twitteroauth",
        "issues": "https://github.com/abraham/twitteroauth/issues"
    },
    "require": {
        "php": "^5.6 || ^7.0",
        "ext-curl": "*"
    },
    "require-dev": {
        "phpunit/phpunit": "~5.6",
        "squizlabs/php_codesniffer": "~2.7",
        "phpmd/phpmd": "~2.4"
    },
    "autoload": {
        "psr-4": {
            "Abraham\\TwitterOAuth\\": "src"
        }
    }
}

**Comment by abraham** [comment]
That's the composer.json for the TwitterOAuth library. You would find the version in your applications composer.json. Looking at `"php": "^5.6 || ^7.0"` though that's a very old version of TwitterOAuth that does not support sending the new version of DMs. You will need to update.

**Comment by smokeyzap** [comment]
Ah, I see. My appologies. It looks like I'm not using the latest version. 0.7.3.
