### ISSUE TITLE
Does this support v2 of the twitter API?

### ISSUE THREAD

**Issue by davehowson** [abraham/twitteroauth#874]
Twitter recently release v2 of their API and I was wondering if it was possible to get data from an endpoint in v2 since the API defaults to v1 when a request is made.

**Comment by mattmcdonald-uk** [comment]
I've created a fork for use myself with v2 (https://github.com/mattmcdonald-uk/twitteroauth)

I've only tested it with my own requirements, so your mileage may vary!

It defaults to API v1.1, but you can switch to v2 by calling `useNewApi()`

**Comment by albertleao** [comment]
@mattmcdonald-uk Any chance you can make a PR for that?

**Comment by mattmcdonald-uk** [comment]
> @mattmcdonald-uk Any chance you can make a PR for that?

Yes 🙂

**Comment by jonathantullett** [comment]
@abraham @albertleao any chance of getting v2 support merged?

Thank you!

**Comment by abraham** [comment]
v2 API support has been added in release [3.0.0](https://github.com/abraham/twitteroauth/releases/tag/3.0.0).
