### ISSUE TITLE
Encoding issue(s) when posting with certain characters

### ISSUE THREAD

**Issue by Valid** [abraham/twitteroauth#891]
When posting with at the very least '’' (which is the stylized version of the single tick) and '–' (which is an emdash instead of an endash/hyphen like '-') the tweet comes out with HTML encoding, but not rendered as the character, so the tweet is just garbled.

```
$string = "This’ll – look weird.";
$connection->post('statuses/update', array('status' => $string));

// Result on twitter: 'This&#8217;ll &#8211; look weird.'
```

**Comment by Valid** [comment]
Any chance I can get a response on this? It's been 20 days since I submitted it.

**Comment by abraham** [comment]
It seems to be working for me.

https://twitter.com/devbraham/status/1325590509239328775

Are you sure you're not doing some encoding first?
