### ISSUE TITLE
What does this error mean? Fatal error: Uncaught Error: Class 'Composer\CaBundle\CaBundle' not found 

### ISSUE THREAD

**Issue by TheConceptBoy** [abraham/twitteroauth#892]
Hey, everyone.
What does this error mean? Fatal error: Uncaught Error: Class 'Composer\CaBundle\CaBundle' not found.
I followed the Manual installation guide on this page https://twitteroauth.com that does not require Composer to be installed. I can't have composer because I'm on shared hosting. Any idea what this error is caused by and how I could possibly fix it?

**Comment by JosephShenton** [comment]
I have this as well

**Comment by dnsbtchr** [comment]
I have the same problem. Looking forward to an answer.

**Comment by abraham** [comment]
I strongly recommend you use composer for installing PHP packages and dependencies.

If you really must install manually you should be able to manually install https://github.com/composer/ca-bundle as well.

**Comment by JosephShenton** [comment]
Normally I do, however my client only has shared hosting. Therefore cannot
run composer.

**Comment by abraham** [comment]
What host doesn't support composer? You could probably also use composer on another machine and include the vendor folder in your source repo or as part of deploying the app to the shared host.

**Comment by robico** [comment]
I've got the same issue.  I contacted my host and they said they have composer on the server but the code it looks like it's trying to load it's own account specific version of composer within the host.  I'm guessing something has to change on TwitterOAuth.php as thats the file that uses it.  Any advice how to get it working?

**Comment by mfn** [comment]
The problem: everyone complaining here is using this library _without installing via composer_

Basically: not supported after the recent changes in https://github.com/abraham/twitteroauth/pull/885

How do I know? Because this is the first time this library starting to have a real dependency on another _package_, prior to this it was self-contained => https://github.com/abraham/twitteroauth/blob/45924a0c3a6fc0d64bac4df4b45036267a652f99/composer.json#L41

Unless someone proposes to revert this or the maintainer does, your options are:
- switch back to an older version (i.e. before `1.2.0` AFAICS)
- install it properly via https://getcomposer.org/

**Comment by abraham** [comment]
@robico As far as I'm aware TwitterOAuth is standard Composer compliant. If you having issues with installing through composer please open a new issue with details.

**Comment by robico** [comment]
@abraham I'm liaising with the hosting's tech support as they said its on the server but I can't see where composer is installed as its only cpanel.  They aren't very technical so I'm waiting seeing what namespace their version is using so I can replace your line (use Composer\CaBundle\CaBundle;) with their one.

**Comment by seal-git** [comment]
The same error occurred and I have solved it. The reason for the error may be not autoloading composer. 
1. make "composer.json" as follows.

```
{
    "require": {
        "abraham/twitteroauth": "^2.0",
        "composer/ca-bundle": "^1.2"
    }
}
```

2. Then execute "composer install"
3. When using, you have to execute "autoload.php" in "vendor" directory, not in "twitteroauth" directory.

**Comment by abraham** [comment]
Composer is the only supported method of installing TwitterOAuth. If a host doesn't support it I recommend you use composer on a different computer to get the vendor files and manually copy them to the final host.

**Comment by rinshankolayil** [comment]
The following steps solve my problem
- Install a new laravel application in the localhost
- Open the new laravel application in the code editor (My preference - VS code)
- Install the package by `composer` require composer/ca-bundle`
- Search for `ca-bundle` in visual studio code by pressing **ctrl+shift+f**(VS code shortcut)
- Locate all the files and select the lines with ca-bundle and paste those lines into live shared hosting files

**Comment by ngothoai** [comment]
> 2\. composer install

composer install
and add require_once "vendor/autoload.php";
