### ISSUE TITLE
error with the callback url

### ISSUE THREAD

**Issue by RzWisemar** [abraham/twitteroauth#896]

**Comment by RzWisemar** [comment]
Hello, I have a problem when I connect with twitter it redirects me to the twitter page to authorize the application but after that redirects me to this link: localhost / callback.php? Oauth_token = *** MYOAUTHTOKEN *** auth_verifier = *** MYOAUTHVERIFIER ***

**Comment by maggz69** [comment]
Did you register a valid callbacl url? You can view this link for more information https://developer.twitter.com/en/docs/apps/callback-urls

**Comment by RzWisemar** [comment]
yes I registered a valid callback because it works perfectly in localhost but once I modify all the links etc when I upload to my server this bug ...

**Comment by abraham** [comment]
You can set the callback to whatever you want. There is an example on https://twitteroauth.com/redirect.php

**Comment by RzWisemar** [comment]
there is something that i do not understand why locally it works and not on my server?

**Comment by abraham** [comment]
Debug the value you are using on the server. I would guess the value being passed to `$connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));` and the value you think you are using are differnt.

**Comment by RzWisemar** [comment]
I'm already using his ...

**Comment by RzWisemar** [comment]
My callback.php : 

<?php
session_start();
require 'autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;

if (isset($_REQUEST['oauth_verifier'], $_REQUEST['oauth_token']) && $_REQUEST['oauth_token'] == $_SESSION['oauth_token']) {
	$request_token = [];
	$request_token['oauth_token'] = $_SESSION['oauth_token'];
	$request_token['oauth_token_secret'] = $_SESSION['oauth_token_secret'];
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $request_token['oauth_token'], $request_token['oauth_token_secret']);
	$access_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
	$_SESSION['access_token'] = $access_token;
	// redirect user back to index page
	header('Location: /dashboard/');
}

I have this error : 

Notice: Undefined index: oauth_token in \www\app\callback.php on line 6

**Comment by RzWisemar** [comment]
My callback.php : 

<?php
session_start();
require 'autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;

if (isset($_REQUEST['oauth_verifier'], $_REQUEST['oauth_token']) && $_REQUEST['oauth_token'] == $_SESSION['oauth_token']) {
	$request_token = [];
	$request_token['oauth_token'] = $_SESSION['oauth_token'];
	$request_token['oauth_token_secret'] = $_SESSION['oauth_token_secret'];
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $request_token['oauth_token'], $request_token['oauth_token_secret']);
	$access_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
	$_SESSION['access_token'] = $access_token;

	header('Location: /dashboard/');
}
?>

**Comment by RzWisemar** [comment]
My callback.php : 

`<?php
session_start();
require 'autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;

if (isset($_REQUEST['oauth_verifier'], $_REQUEST['oauth_token']) && $_REQUEST['oauth_token'] == $_SESSION['oauth_token']) {
	$request_token = [];
	$request_token['oauth_token'] = $_SESSION['oauth_token'];
	$request_token['oauth_token_secret'] = $_SESSION['oauth_token_secret'];
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $request_token['oauth_token'], $request_token['oauth_token_secret']);
	$access_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));
	$_SESSION['access_token'] = $access_token;

header('Location: /dashboard/');
}
?>`

**Comment by RzWisemar** [comment]
can someone help me ?? plz

**Comment by RzWisemar** [comment]
active extension of php in my server : https://www.hebergeur-image.fr/uploads/20201027/e77713ff61dc10830f888ebf13fce0d549525b75.png

**Comment by abraham** [comment]
Twitter is going to return users to the URL you set in `$connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));`. If Twitter is not returning users to the URL you expect you need to update your code to set the correct URL.

**Comment by RzWisemar** [comment]
the url is good sight that it works locally ...

**Comment by RzWisemar** [comment]
New callback.php : 
`<?php
session_start();
require "vendor/autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;

if (isset($_REQUEST['oauth_verifier'], $_REQUEST['oauth_token']) && $_REQUEST['oauth_token'] == $_SESSION['oauth_token']) {			   //In project use this session to change login header after successful login 
	$request_token = [];
	$request_token['oauth_token'] = $_SESSION['oauth_token'];
	$request_token['oauth_token_secret'] = $_SESSION['oauth_token_secret'];
	$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $request_token['oauth_token'], $request_token['oauth_token_secret']);
	$access_token = $connection->oauth("oauth/access_token", array("oauth_verifier" => $_REQUEST['oauth_verifier']));
	$_SESSION['access_token'] = $access_token;
	// redirect user back to index page
	header("location:index.php");
}`

**Comment by abraham** [comment]
That looks like the code that should get called after a user has been already returned from Twitter. The callback URL should be getting set before the user gets sent to Twitter.
