### ISSUE TITLE
Connect other user from his access_token ?

### ISSUE THREAD

**Issue by bastien70** [abraham/twitteroauth#898]
I am trying to create an app that allows my users to login with Twitter and perform some tasks on their account right from my app, with Symfony (PHP).

For this I generated my API keys.

To get the access_token of my users' twitter account, I used **HWIOAuthBundle** (https://github.com/hwi/HWIOAuthBundle).

Now to log into the API I am using **twitteroauth**

In the doc, they say to do like this:

```php
$connection = new TwitterOAuth($consumer_key, $consumer_secret_key, $access_token, $access_token_secret);
$content = $connection->get("account/verify_credentials");
```
So I first tried with my consumer API and access token keys generated by Twitter-Developer-API. It worked, I have the account information.

Now I would like to connect to the API the account of one of my users who previously authenticated using Twitter. So I have its "**access_token**".

I then stupidly tried the same command but replacing the "access_token" provided by the API, with my user's twitter "**acess_token**", which I retrieve from the database.

```php
$user_access_token = $this->getUser()->getTwitterAccessToken();
$connection = new TwitterOAuth($consumer_key, $consumer_secret_key, $user_access_token , $access_token_secret);
$content = $connection->get("account/verify_credentials");
```
But as I expected it sends me back to an error saying the keys are wrong.

How could I do it?

**Comment by abraham** [comment]
To perform actions as a user you need the users access token and access token secret, the 3rd and 4th value passed to `TwitterOAuth`. They have to be paired with the consumer key and consumer secret that was used when that user authorized access.

How did you generate the access token and secret for the user?

**Comment by bastien70** [comment]
I am using hwioauthbundle to retrieve information from a user logging in with Twitter. Thanks to that, I get this kind of response:

![token](https://user-images.githubusercontent.com/53140475/98526869-9967c000-227a-11eb-9550-5b51f8762dbb.PNG)

But suddenly from this response, I can't see where I can get the access_token and access_secret_token twitter from this user?
