### ISSUE TITLE
EventSubscriber on twitteroauth requests ?

### ISSUE THREAD

**Issue by bastien70** [abraham/twitteroauth#899]
Hello ! I have created several functions using twitteroauth, but each time I have to verify that I am properly logged into the API. Would there be a way to automatically verify with each request from twitteroauth that a connection has been initiated, and if not, initiate an authentication?

It would therefore be necessary to initialize an event to twitteroauth, which would be called on each request. Thus, in my role, I will no longer have to carry out the verification myself. But how to do it ?

**Comment by abraham** [comment]
Please clarify what problem you are trying to solve and how you would like to see it solved. An example of how you would like to interact with the TwitterOAuth code would be helpful.
