### ISSUE TITLE
add Support for PHP8

### ISSUE THREAD

**Issue by boredom2** [abraham/twitteroauth#911]
First of all - thank you for this brillant Library.
We are migrating our Dev Servers to PHP8 at the Moment and although the Lib is working, technically, it cant be installed, as the requirements are only given until 7.4. Can this be changed to include PHP8 too?

Thanks!

**Comment by abraham** [comment]
This is being worked on in #869 but needs an dependency to be updated.

**Comment by boredom2** [comment]
I saw that already. Sorry for opening this and thanks a lot for your Reply!
