### ISSUE TITLE
Checkpoint Login

### ISSUE THREAD

**Issue by canyesilyurtx** [abraham/twitteroauth#916]
Hello Abraham, With this system, there are accounts entering checkpoints when logging into Twitter. How do I answer Checkpoint questions and get tokens?

**Comment by abraham** [comment]
What are checkpoints?

**Comment by canyesilyurtx** [comment]
Enter your email address to verify after login Xauth

**Comment by abraham** [comment]
Isn't xauth [removed](https://twittercommunity.com/t/retirement-of-xauth/88022)? Please link to some documentation describing what your talking about.

**Comment by canyesilyurtx** [comment]
I learned that the system needs to be done with curl. Thank you so much abraham ❤️
