### ISSUE TITLE
cacert.pem and v1.0.x

### ISSUE THREAD

**Issue by smares** [abraham/twitteroauth#920]
Is it possible to backport the changes related to the cacert.pem to the 1.0.x branch? I am still using PHP 7.0 for a project and cannot update to a newer version.

The current idea if this is a no-go from you would be writing a post-deployment script for my project that replaces the file with either a concatenated /etc/ssl/certs/*.pem or the one from composer/ca-bundle.

**Comment by abraham** [comment]
There are not cacert.pem changes in v2 that are not in v1. Is this the change you are talking about? https://github.com/abraham/twitteroauth/releases/tag/1.2.0

**Comment by smares** [comment]
Yes, but that is in 1.2 which no longer supports PHP 7.0. The last version to support PHP 7.0 is 1.0.1. But I guess I can close this since I ended up forking the current version, changing the code to support PHP 7.0 again and also did some changes to the media handling that was not according to the Twitter documentation (wrong field used, no multipart/formdata used).

**Comment by abraham** [comment]
Ah, 7.0. There are no plans to backport features for versions of PHP that no longer get security updates.
