### ISSUE TITLE
having trouble installing

### ISSUE THREAD

**Issue by NathanTech7713** [abraham/twitteroauth#922]
Hi folks.
I'm having a little trouble installing and I wonder if someone could help.
I'm a bit of a dur when it comes to composer, but I've tried my best.
First, I ran the command:
composer require abraham/twitteroauth
But then when running my php script, I get the following:

Warning: Use of undefined constant CURLOPT_CONNECTTIMEOUT - assumed 'CURLOPT_CONNECTTIMEOUT' (this will throw an Error in a future version of PHP) in /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 575

Warning: Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' (this will throw an Error in a future version of PHP) in /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 576

Warning: Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' (this will throw an Error in a future version of PHP) in /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 577

Warning: Use of undefined constant CURLOPT_SSL_VERIFYHOST - assumed 'CURLOPT_SSL_VERIFYHOST' (this will throw an Error in a future version of PHP) in /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 578

Warning: Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER' (this will throw an Error in a future version of PHP) in /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 579

Warning: Use of undefined constant CURLOPT_TIMEOUT - assumed 'CURLOPT_TIMEOUT' (this will throw an Error in a future version of PHP) in /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 580

Warning: Use of undefined constant CURLOPT_USERAGENT - assumed 'CURLOPT_USERAGENT' (this will throw an Error in a future version of PHP) in /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 581

Warning: Use of undefined constant CURLOPT_CAINFO - assumed 'CURLOPT_CAINFO' (this will throw an Error in a future version of PHP) in /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 725

Fatal error: Uncaught TypeError: Return value of Abraham\TwitterOAuth\TwitterOAuth::curlCaOpt() must be of the type int, string returned in /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php:725 Stack trace: #0 /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php(582): Abraham\TwitterOAuth\TwitterOAuth->curlCaOpt() #1 /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php(620): Abraham\TwitterOAuth\TwitterOAuth->curlOptions() #2 /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php(557): Abraham\TwitterOAuth\TwitterOAuth->request() #3 /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php(490): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest() #4 /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php(467): Abraham\TwitterOAuth\TwitterOAuth->makeRequests() #5 /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php(249): Abraham\TwitterOAuth\TwitterOAuth->http() #6 /home/html/crtweet/m009tu66.php(14): Abraham\TwitterOAuth\Twitte in /home/html/crtweet/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 725

Any helps is appreciated on what I did wrong here.

**Comment by abraham** [comment]
It sounds like you don't have curl installed. https://stackoverflow.com/questions/12282779/use-of-undefined-constant

**Comment by NathanTech7713** [comment]
LEgend. thanks for your help
