### ISSUE TITLE
Issue with "Undefined index: media"

### ISSUE THREAD

**Issue by pirmax** [abraham/twitteroauth#946]
Hi,

I've an error when I try to upload base64 encode PNG image.

With chunked, or not.

    $upload = $connection->upload('media/upload', [
        'media_data' => $base64Encoded,
        'media_type' => 'image/png',
    ], true);

    dd($upload);

Here, the error I have:

![image](https://user-images.githubusercontent.com/1739235/116472687-84a5d580-a876-11eb-846a-1a6cbbc17dc0.png)

**Comment by pirmax** [comment]
I think, in https://github.com/abraham/twitteroauth/blob/main/src/TwitterOAuth.php#L367, the parameters variable use **media** instead **media_data**.

**Comment by abraham** [comment]
TwitterOAuth currently only supports paths to images that are on the filesystem. #681 should support additional sources when implemented.
