### ISSUE TITLE
Can I get trends list? 

### ISSUE THREAD

**Issue by WeTruck** [abraham/twitteroauth#947]
Can I get trends list? 
As described here: https://developer.twitter.com/en/docs/twitter-api/v1/trends/trends-for-location/api-reference/get-trends-place

**Comment by abraham** [comment]
It should work something like this:

```php
$statuses = $connection->get("trends/place", ["id" => 1]);

```

**Comment by bugbaal** [comment]
> It should work something like this:
> 
> ```
> $statuses = $connection->get("trends/place", ["id" => 1]);
> ```

Hi, this doesn't work for me. 
Can you help me?
Thanks
