### ISSUE TITLE
"uploadMediaChunked" takes long time to upload large media file

### ISSUE THREAD

**Issue by szhalf** [abraham/twitteroauth#955]
Since fread function cannot read more than 8192 bytes, "$this->chunkSize" ignored and maximum chunk size of each "APPEND" request is limited to 8192B.

This causes long time upload.

Couldn't you consider to use "stream_get_contents" instead of "fread"?

https://www.php.net/manual/en/function.fread.php
https://www.php.net/manual/en/function.stream-get-contents.php

Thank you.

**Comment by abraham** [comment]
@PINHOf please create a new issues.

**Comment by abraham** [comment]
I wouldn't expect there to be much performance improvement from switching how media is read from disk. Network requests are usually much much slower.

**Comment by abraham** [comment]
Closing in favor of #681
