### ISSUE TITLE
Issue on oauth access token

### ISSUE THREAD

**Issue by leosarturi** [abraham/twitteroauth#956]
![image](https://user-images.githubusercontent.com/57293190/119247580-0c72bd00-bb61-11eb-8bd8-2d5c8fc9e316.png)

getting this error using oauth("oauth/access_token") on line 20
![image](https://user-images.githubusercontent.com/57293190/119247597-45129680-bb61-11eb-8bcd-ccb9dda1eab4.png)

**Comment by abraham** [comment]
Please open a new issue and include the code. Screenshots are really hard to read.
