### ISSUE TITLE
Issue on oauth access token

### ISSUE THREAD

**Issue by leosarturi** [abraham/twitteroauth#957]
Getting this error using oauth/access_token
Fatal error: Uncaught Abraham \ TwitterOAuth \ TwitterOAuthException: This feature is temporarily unavailable in E: \ xampp \ htdocs \ curiousDog \ Twitter-API-Login-PHP-master \ src \ TwitterOAuth.php: 138 Stack trace: # 0 E: \ xampp \ htdocs \ curiousDog \ callback.php (20): Abraham \ TwitterOAuth \ TwitterOAuth-> oauth ('oauth / access_to ...', Array) # 1 {main} thrown in E: \ xampp \ htdocs \ curiousDog \ Twitter -API-Login-PHP-master \ src \ TwitterOAuth.php on line 138

 in this line: $access_token = $twitter->oauth("oauth/access_token", ["oauth_verifier" => $_REQUEST['oauth_verifier']]);

**Comment by abraham** [comment]
This error suggests you are trying to convert a single request token to an access token more than once. Each request token is one time use.

https://stackoverflow.com/q/32095556/26406

**Comment by leosarturi** [comment]
Thank you, issue solved
