### ISSUE TITLE
Dropping PHP 7.2 support in a patch release (2.0.1) ?

### ISSUE THREAD

**Issue by dregad** [abraham/twitteroauth#961]
Hello,

On a web server running PHP 7.2, I had `"abraham/twitteroauth": "~1.0",` in composer.json, so `composer outdated` gave me 2.0.0 which came as a surprise. 

Based on SemVer, I would have expected the PHP 7.2 drop to happen in 2.0.0.

For the record, I'm not challenging dropping 7.2 support at all :wink:

**Comment by abraham** [comment]
2.0.0 was mistakenly released without dropping 7.2 support so 2.0.1 was immediately released afterwards.
