### ISSUE TITLE
How to get mentions since  ....

### ISSUE THREAD

**Issue by blackbulldogzz** [abraham/twitteroauth#968]
Hi,
Loving the code.
Got a question though. I'm using this code:

`  		$content = $twit->get('statuses/mentions_timeline');    	`

and it works great. How do I only get mentions since a certain tweetid?

Thanks.

p.s. also, how would I use the 'in_reply_to_status_id' parameter when I post a status?

**Comment by abraham** [comment]
Pass whatever parameters you want as the second argument like this:

    $statuses = $connection->get("statuses/home_timeline", ["count" => 25, "exclude_replies" => true]);
