### ISSUE TITLE
How can I use twitteroauth without composer

### ISSUE THREAD

**Issue by glosnick** [abraham/twitteroauth#982]
Hi, I am at present following an online course about building a Twitter app but have failed to get my code to authorise my Twitter credentials.  In the course I am following when the instructor outlines how to use TwitterOAuth to vailidate credentials there is a section on twitterouth.com concerning the old fashioned method or manual method which I suppose means without using composer.  So I followed this method but it doesn't appear to work and it no longer appears on twitteroauth.com.  I'm not entirely sure if composer is installed or I can use it on the server where my website is hosted so I was wondering what I could do so that my fledgling app could use my Twitter credentials to get authorised.

I'm not sure if this is the place to ask this question or if you would be willing to help.  But I live in hope and have found no support elsewhere.

Regards

Nick

**Comment by abraham** [comment]
1. On your local system install composer and run `composer require abraham/twitteroauth` in an empty directory or the root of you project source code. This will create a `vendor` folder with all the needed dependencies.
1. Copy the entire `vendor` folder to the root of your apps source and commit it to version control. Deploy the `vendor` folder contents with the rest of your app source code.
