### ISSUE TITLE
Invalid function calls

### ISSUE THREAD

**Issue by EzequielHPP** [abraham/twitteroauth#987]
**System info:**
PHP 7.3.24
Ubuntu 18.04.3
Apache 2.4.29

**Error**
```
 PHP Parse error:  syntax error, unexpected ')' in /var/www/websitelocation/vendor/abraham/twitteroauth/src/Request.php on line 35
```

**Issue**
Prettier adding commas on multi-line function calls:
https://github.com/abraham/twitteroauth/blob/d0689e4ca00f2dec9fba8be5e09b4812193a6965/.prettierrc.json#L4

For instance:
https://github.com/abraham/twitteroauth/blob/d0689e4ca00f2dec9fba8be5e09b4812193a6965/src/Request.php#L34
```
$parameters = array_merge(
    Util::parseParameters(parse_url($httpUrl, PHP_URL_QUERY)),
    $parameters,
);
```
Two more instances on this file:
https://github.com/abraham/twitteroauth/blob/d0689e4ca00f2dec9fba8be5e09b4812193a6965/src/Request.php#L227
https://github.com/abraham/twitteroauth/blob/d0689e4ca00f2dec9fba8be5e09b4812193a6965/src/Request.php#L261

---
Also on:
https://github.com/abraham/twitteroauth/blob/d0689e4ca00f2dec9fba8be5e09b4812193a6965/src/Util.php#L25
```
$output = array_map(
    [__NAMESPACE__ . '\Util', 'urlencodeRfc3986'],
    $input,
);
```

**Comment by abraham** [comment]
Trailing commas in function calls was implemented in [PHP 7.3](https://wiki.php.net/rfc/trailing-comma-function-calls)  and this code is running without issue on CI with [PHP 7.3](https://github.com/abraham/twitteroauth/runs/3316879809).
